### ISSUE TITLE
Got some issues with new UC version (3.4)

### ISSUE THREAD

**Issue by ben-elbert** [ultrafunkamsterdam/undetected-chromedriver#1035]
First issue:
`Traceback (most recent call last):
  File "/infrastructure/goldenmoth/goldenmoth/command_runner.py", line 213, in run_command
    result, error, fragment_id = run_function(command)
  File "/infrastructure/goldenmoth/goldenmoth/worker.py", line 8, in wrapper
    return_value = f(*args, **kwargs)
  File "/worker/browser_module.py", line 119, in run
    with _get_browser(url, config["browser"]) as browser:
  File "/worker/browser_module.py", line 20, in _get_browser
    return ChromeBrowser(url)
  File "/worker/browsers.py", line 109, in __init__
    super(ChromeBrowser, self).__init__(url, **config)
  File "/worker/browsers.py", line 39, in __init__
    self._driver = self.get_driver()
  File "/worker/browsers.py", line 117, in get_driver
    driver = undetected_chrome.Chrome(options=chrome_options, desired_capabilities=caps)
  File "/usr/local/lib/python3.8/site-packages/undetected_chromedriver/__init__.py", line 246, in __init__
    patcher.auto()
  File "/usr/local/lib/python3.8/site-packages/undetected_chromedriver/patcher.py", line 135, in auto
    return self.patch()
  File "/usr/local/lib/python3.8/site-packages/undetected_chromedriver/patcher.py", line 139, in patch
    return self.is_binary_patched()
  File "/usr/local/lib/python3.8/site-packages/undetected_chromedriver/patcher.py", line 220, in is_binary_patched
    with io.open(executable_path, "rb") as fh:
FileNotFoundError: [Errno 2] No such file or directory: '/root/.local/share/undetected_chromedriver/undetected_chromedriver'`

Second issue:
`Traceback (most recent call last):
  File "/worker/browser_module.py", line 96, in _run_submodules
    new_detections = submodule.analyze_page(html=html,
  File "/worker/submodules/sso.py", line 151, in analyze_page
    sso_detector = self.detect_sso_product()
  File "/worker/submodules/sso.py", line 143, in detect_sso_product
    if sso_detector(self._browser):
  File "/worker/submodules/sso_detectors/base.py", line 55, in bool_method
    return any(self.__checks__) and all(getattr(self, check)()
  File "/worker/submodules/sso_detectors/base.py", line 55, in <genexpr>
    return any(self.__checks__) and all(getattr(self, check)()
  File "/worker/submodules/sso_detectors/base.py", line 13, in wrapper
    return_value = method(self)
  File "/worker/submodules/sso_detectors/duo_detector.py", line 22, in has_noscript
    return self.fullmatch_pattern(pattern, 'noscript', re.I)
  File "/worker/submodules/sso_detectors/common.py", line 82, in fullmatch_pattern
    element = self.browser.query_selector(css_selector)
  File "/worker/browsers.py", line 70, in query_selector
    return self._driver.find_element(By.CSS_SELECTOR, selector)
  File "/usr/local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 830, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
  File "/usr/local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 440, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 245, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Runtime.evaluate threw exception: SyntaxError: missing ) after argument list
  (Session info: headless chrome=109.0.5414.119)`

**Comment by PashaM999** [comment]
Having the second issue as well. For me  that happens when trying to execute `driver.find_elements(By.ID, 'someid')`. This works fine using `webdriver.chrome` leaving everything else untouched.

**Comment by ultrafunkamsterdam** [comment]
update to 3.4.1 :) 
just tested on linux and ok here

**Comment by ben-elbert** [comment]
Can you paste pip freeze plz?

**Comment by ultrafunkamsterdam** [comment]
sorry, update to 3.4.2 .. you might need to `pip install -U undetected-chromedriver`. and you even might do it twice (at least it took me 2 runs before the actual version was installed.

**Comment by ben-elbert** [comment]
Im running with 3.4.2 and selenium 4.8.0 and still seeing this error.

**Comment by ultrafunkamsterdam** [comment]
do you even have chrome on your linux machine? otherwise this error also pops up.

**Comment by ben-elbert** [comment]
Im running it in docker. based on python:3.8-buster

**Comment by ben-elbert** [comment]
im not getting this error with older versions (<3.4.0)

**Comment by ultrafunkamsterdam** [comment]
please try by installing this branch and let me know how that goes.
```
pip install git+https://github.com/ultrafunkamsterdam/undetected-chromedriver#fix-linux-find-elements
```

**Comment by Lyapsus** [comment]
> please try by installing this branch and let me know how that goes.
> 
> ```
> pip uninstall undetected-chromedriver
> pip install git+https://github.com/ultrafunkamsterdam/undetected-chromedriver@fix-linux-find-elements
> ```

Doesn't work sadly

**Comment by zunjae** [comment]
I am unsure if this is related to uc, as I get the same error with it uninstalled

**Comment by zunjae** [comment]
I fixed "selenium.common.exceptions.WebDriverException: Message: unknown error: Runtime.evaluate threw exception: SyntaxError: missing ) after argument list" by updating my chromedriver.

**Comment by ultrafunkamsterdam** [comment]
Manually uninstall . Remove your chromedriver binary , and pip install https://github.com/ultrafunkamsterdam/undetected-chromedriver@fix-linux-find-elements

**Comment by ultrafunkamsterdam** [comment]
Sorry for inconvenience I'll try to merge some things later today

**Comment by emanodame** [comment]
> Im running it in docker. based on python:3.8-buster

Running successfully ?

**Comment by soft-top-notch** [comment]
So, is it resolved? I'm also getting the same issue.

**Comment by soft-top-notch** [comment]
> please try by installing this branch and let me know how that goes.
> 
> ```
> pip uninstall undetected-chromedriver
> pip install git+https://github.com/ultrafunkamsterdam/undetected-chromedriver@fix-linux-find-elements
> ```

I'm getting this error when try to run the second line:
```
error: pathspec 'fix-linux-find-elements' did not match any file(s) known to git.
```
