### ISSUE TITLE
selenium.common.exceptions.WebDriverException: Message: unknown error: Runtime.evaluate threw exception: SyntaxError: missing ) after argument list

### ISSUE THREAD

**Issue by kevinl1210** [ultrafunkamsterdam/undetected-chromedriver#1039]
Problem description:
Encountered the error ```selenium.common.exceptions.WebDriverException: Message: unknown error: Runtime.evaluate threw exception: SyntaxError: missing ) after argument list``` while using headless mode in ubuntu linux.

OS version:
ubuntu 20.04.5 LTS

Python version:
Python 3.8.10
undetected-chromedriver 3.4.2

 Python script:
```
>>> import undetected_chromedriver as uc
>>> options = uc.ChromeOptions()
>>> options.add_argument('--headless')
>>> driver = uc.Chrome(use_subprocess=True, options=options)
>>> from selenium.webdriver.common.by import By
>>> driver.get('https://hk.cruworldwine.com/france')
>>> driver.find_elements(by=By.XPATH, value='//table[@class="products-list data dutypaid"]/tbody/tr[@class="product-shop item"]')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/wwx/backup/venv/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 860, in find_elements
    return self.execute(Command.FIND_ELEMENTS, {"using": by, "value": value})["value"] or []
  File "/wwx/backup/venv/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 440, in execute
    self.error_handler.check_response(response)
  File "/wwx/backup/venv/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 245, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Runtime.evaluate threw exception: SyntaxError: missing ) after argument list
  (Session info: headless chrome=109.0.5414.119)
Stacktrace:
#0 0x560d9aba3303 <unknown>
#1 0x560d9a977d37 <unknown>
#2 0x560d9a9838df <unknown>
#3 0x560d9a97adf1 <unknown>
#4 0x560d9a97a931 <unknown>
#5 0x560d9a97b351 <unknown>
#6 0x560d9a97b6dc <unknown>
#7 0x560d9a9b4188 <unknown>
#8 0x560d9a9b46c1 <unknown>
#9 0x560d9a9eeb71 <unknown>
#10 0x560d9a9d49ad <unknown>
#11 0x560d9a9ec88c <unknown>
#12 0x560d9a9d4753 <unknown>
#13 0x560d9a9a7a14 <unknown>
#14 0x560d9a9a8b7e <unknown>
#15 0x560d9abf232e <unknown>
#16 0x560d9abf5c0e <unknown>
#17 0x560d9abd8610 <unknown>
#18 0x560d9abf6c23 <unknown>
#19 0x560d9abca545 <unknown>
#20 0x560d9ac176a8 <unknown>
#21 0x560d9ac17836 <unknown>
#22 0x560d9ac32d13 <unknown>
#23 0x7f433a8a8609 start_thread


```

**Comment by ultrafunkamsterdam** [comment]
Please see the other issues before raising a new one. Thanks

**Comment by thanhnd1o2** [comment]
Same to me
But only on Linux with version 3.4.0
File "/app/api.py", line 248, in get_chapter_content
2023-02-07 23:30:13     mx_auto = driver.find_elements(By.CLASS_NAME, 'mx-auto')
2023-02-07 23:30:13   File "/opt/venv/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 860, in find_elements
2023-02-07 23:30:13     return self.execute(Command.FIND_ELEMENTS, {"using": by, "value": value})["value"] or []
2023-02-07 23:30:13   File "/opt/venv/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 440, in execute
2023-02-07 23:30:13     self.error_handler.check_response(response)
2023-02-07 23:30:13   File "/opt/venv/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py", line 245, in check_response
2023-02-07 23:30:13     raise exception_class(message, screen, stacktrace)
2023-02-07 23:30:13 selenium.common.exceptions.WebDriverException: Message: unknown error: Runtime.evaluate threw exception: SyntaxError: missing ) after argument list
