### ISSUE TITLE
Unable tu run multiple instances since 3.4

### ISSUE THREAD

**Issue by labodj** [ultrafunkamsterdam/undetected-chromedriver#1041]
Hi,
Since 3.4 I'm unable to launch multiple instances at the same time of a python script that uses undetected chromedriver.

I need start the script like so

start.bat:

```bat
start "" /high cmd /k python script.py --parameter_a 1 --parameter_b 2
start "" /high cmd /k python script.py --parameter_a 2 --parameter_b 3
start "" /high cmd /k python script.py --parameter_a 4 --parameter_b 5
start "" /high cmd /k python script.py --parameter_a 6 --parameter_b 7
start "" /high cmd /k python script.py --parameter_a 8 --parameter_b 9
pause
```

The problem is due to the fact that 3.4 changed this

> rewritten the file naming, to prevent ending up with 1000 of {randomstring}_chromedriver.exe 's instead it is just called undetected_chromedriver.exe

So the current behavior is that the first instance runs fine, every other instance errors out because undetected_chromedriver.exe is already in use (by the fastest instance)

```
DEBUG:undetected_chromedriver.patcher:getting release number from /LATEST_RELEASE
DEBUG:undetected_chromedriver.patcher:downloading from https://chromedriver.storage.googleapis.com/109.0.5414.74/chromedriver_win32.zip
DEBUG:undetected_chromedriver.patcher:unzipping C:\Users\user\AppData\Local\Temp\tmpfjgf1q30
Traceback (most recent call last):
  File "redacted.py", line 358, in <module>
    driver = uc.Chrome()
             ^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\undetected_chromedriver\__init__.py", line 246, in __init__
    self.patcher.auto()
  File "C:\Python311\Lib\site-packages\undetected_chromedriver\patcher.py", line 134, in auto
    self.unzip_package(self.fetch_package())
  File "C:\Python311\Lib\site-packages\undetected_chromedriver\patcher.py", line 187, in unzip_package
    os.rename(os.path.join(self.zip_path, self.exe_name), self.executable_path)
PermissionError: [WinError 32] Impossibile accedere al file. Il file è utilizzato da un altro processo: 'C:\\Users\\user\\appdata\\roaming\\undetected_chromedriver\\undetected\\chromedriver.exe' -> 'C:\\Users\\user\\appdata\\roaming\\undetected_chromedriver\\undetected_chromedriver.exe'
DEBUG:undetected_chromedriver.patcher:successfully unlinked C:\Users\user\appdata\roaming\undetected_chromedriver\undetected_chromedriver.exe
```

or

```
DEBUG:undetected_chromedriver.patcher:getting release number from /LATEST_RELEASE
DEBUG:undetected_chromedriver.patcher:downloading from https://chromedriver.storage.googleapis.com/109.0.5414.74/chromedriver_win32.zip
DEBUG:undetected_chromedriver.patcher:unzipping C:\Users\user\AppData\Local\Temp\tmp04ydh7g5
Traceback (most recent call last):
  File "redacted.py", line 358, in <module>
    driver = uc.Chrome()
             ^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\undetected_chromedriver\__init__.py", line 246, in __init__
    self.patcher.auto()
  File "C:\Python311\Lib\site-packages\undetected_chromedriver\patcher.py", line 134, in auto
    self.unzip_package(self.fetch_package())
  File "C:\Python311\Lib\site-packages\undetected_chromedriver\patcher.py", line 187, in unzip_package
    os.rename(os.path.join(self.zip_path, self.exe_name), self.executable_path)
FileExistsError: [WinError 183] Impossibile creare un file, se il file esiste già: 'C:\\Users\\user\\appdata\\roaming\\undetected_chromedriver\\undetected\\chromedriver.exe' -> 'C:\\Users\\user\\appdata\\roaming\\undetected_chromedriver\\undetected_chromedriver.exe'
Exception ignored in: <function Patcher.__del__ at 0x000002AA0372C180>
Traceback (most recent call last):
  File "C:\Python311\Lib\site-packages\undetected_chromedriver\patcher.py", line 292, in __del__
    time.sleep(0.1)
OSError: [WinError 6] Handle non valido
```

**Comment by ultrafunkamsterdam** [comment]
really shouldnt be doing this....
here we go:

```
pip install -U https://github.com/ultrafunkamsterdam/undetected-chromedriver@fix-multiple-instance
```
please check if it is really installed, or just run this twice.

report back appreciated..

**Comment by ultrafunkamsterdam** [comment]
and your code may look like
```
import undetected_chromedriver as uc
num_drivers= 10

drivers = [uc.Chrome() for _ in range(num_drivers) ]

[d.get('https://pornhub.com') for d in drivers ] 

# etc etc

```

**Comment by labodj** [comment]
> really shouldnt be doing this.... here we go:
> 
> ```
> pip install -U https://github.com/ultrafunkamsterdam/undetected-chromedriver@fix-multiple-instance
> ```
> 
> please check if it is really installed, or just run this twice.
> 
> report back appreciated..

Hi, thanks for the fast reply, I just tested it with no code changes on my side, it doesn't work

The first instance is ok

```
DEBUG:undetected_chromedriver.patcher:getting release number from /LATEST_RELEASE
DEBUG:undetected_chromedriver.patcher:downloading from https://chromedriver.storage.googleapis.com/110.0.5481.77/chromedriver_win32.zip
DEBUG:undetected_chromedriver.patcher:unzipping C:\Users\user\AppData\Local\Temp\tmpikhzp3si
INFO:undetected_chromedriver.patcher:patching driver executable C:\Users\user\appdata\roaming\undetected_chromedriver\undetected_chromedriver.exe
DEBUG:undetected_chromedriver.patcher:found block:
b'{window.cdc_adoQpoasnfa76pfcZLmcfl_Array = window.Array;window.cdc_adoQpoasnfa76pfcZLmcfl_Promise = window.Promise;window.cdc_adoQpoasnfa76pfcZLmcfl_Symbol = window.Symbol;}'
replacing with:
b'{console.log("undetected chromedriver 1337!")}                                                                                                                               '
DEBUG:undetected_chromedriver.patcher:patching took us 0.28 seconds
DEBUG:selenium.webdriver.common.service:Started executable: `C:\Users\user\appdata\roaming\undetected_chromedriver\undetected_chromedriver.exe` in a child process with pid: 9252
DEBUG:selenium.webdriver.remote.remote_connection:POST http://localhost:52485/session {"capabilities": {"firstMatch": [{}], "alwaysMatch": {"browserName": "chrome", "pageLoadStrategy": "normal", "goog:chromeOptions": {"extensions": [], "binary": "C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe", "args": ["--remote-debugging-host=127.0.0.1", "--remote-debugging-port=52484", "--user-data-dir=C:\\Users\\user\\AppData\\Local\\Temp\\tmpiztl69ko", "--lang=it-IT", "--no-default-browser-check", "--no-first-run", "--no-sandbox", "--test-type", "--window-size=1920,1080", "--start-maximized", "--no-sandbox", "--log-level=0"], "debuggerAddress": "127.0.0.1:52484"}}}}
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost:52485
DEBUG:urllib3.connectionpool:http://localhost:52485 "POST /session HTTP/1.1" 200 668
DEBUG:selenium.webdriver.remote.remote_connection:Remote response: status=200 | data={"value":{"capabilities":{"acceptInsecureCerts":false,"browserName":"chrome","browserVersion":"110.0.5481.78","chrome":{"chromedriverVersion":"110.0.5481.77 (65ed616c6e8ee3fe0ad64fe83796c020644d42af-refs/branch-heads/5481@{#839})"},"goog:chromeOptions":{"debuggerAddress":"127.0.0.1:52484"},"pageLoadStrategy":"normal","platformName":"","proxy":{},"setWindowRect":false,"strictFileInteractability":false,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000},"unhandledPromptBehavior":"dismiss and notify","webauthn:extension:credBlob":true,"webauthn:extension:largeBlob":true,"webauthn:virtualAuthenticators":true},"sessionId":"329e88df86303c913bef0e66a242dd01"}} | headers=HTTPHeaderDict({'Content-Length': '668', 'Content-Type': 'application/json; charset=utf-8', 'cache-control': 'no-cache'})
```

Every other one fails:

```
DEBUG:undetected_chromedriver.patcher:getting release number from /LATEST_RELEASE
DEBUG:undetected_chromedriver.patcher:downloading from https://chromedriver.storage.googleapis.com/110.0.5481.77/chromedriver_win32.zip
DEBUG:undetected_chromedriver.patcher:unzipping C:\Users\user\AppData\Local\Temp\tmpsi2wjj8y
Traceback (most recent call last):
  File "C:\Users\user\script.py", line 358, in <module>
    driver = uc.Chrome()
             ^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\undetected_chromedriver\__init__.py", line 246, in __init__
    self.patcher.auto()
  File "C:\Python311\Lib\site-packages\undetected_chromedriver\patcher.py", line 127, in auto
    self.unzip_package(self.fetch_package())
  File "C:\Python311\Lib\site-packages\undetected_chromedriver\patcher.py", line 181, in unzip_package
    os.rename(os.path.join(self.zip_path, self.exe_name), self.executable_path)
FileExistsError: [WinError 183] Impossibile creare un file, se il file esiste già: 'C:\\Users\\user\\appdata\\roaming\\undetected_chromedriver\\undetected\\chromedriver.exe' -> 'C:\\Users\\user\\appdata\\roaming\\undetected_chromedriver\\undetected_chromedriver.exe'
Exception ignored in: <function Patcher.__del__ at 0x0000022DE45AC180>
Traceback (most recent call last):
  File "C:\Python311\Lib\site-packages\undetected_chromedriver\patcher.py", line 283, in __del__
    time.sleep(0.1)
OSError: [WinError 6] Handle non valido
```

**Comment by labodj** [comment]
> and your code may look like
> 
> ```
> import undetected_chromedriver as uc
> num_drivers= 10
> 
> drivers = [uc.Chrome() for _ in range(num_drivers) ]
> 
> [d.get('https://pornhub.com') for d in drivers ] 
> 
> # etc etc
> ```

I see your point, and I kinda agree, but it's not that easy.
Running multiple instances of the same script with different args is just way more flexible in some cases.

EG: in my case I need to contact the very same website many (variable each time) times at the sime time and send same requests with different arguments

**Comment by labodj** [comment]
@ultrafunkamsterdam 

I just retested the code updated to 57a2bd3f436832ffe8b127efa1d358a64f32be6f and it seems to be working again using chrome 110, I noted that selenium must be >=4.8.0 to work with Chrome 110

**Comment by estromenko** [comment]
Facing similar issue with following message: `selenium.common.exceptions.WebDriverException: Message: 'undetected_chromedriver' executable needs to be in PATH`.

**Comment by nullANzero** [comment]
The new version 3.4.7 came out today.
Here's the test code I tested, and it works.
If it doesn't work for someone else, check the 3.4.7 documentation on githab / or in __init__.py code, you may not have UNDETECTED_CHROMEDRIVER BINARY in your ROAMING DATA FOLDER (roaming appdata/undetected_chromedriver)

<------------------------code------------------------>

import time
from multiprocessing import Pool
import undetected_chromedriver as uc

url_list = ["https://bot.sannysoft.com/"]*3

def check(url):
    try:
        driver = uc.Chrome(user_multi_procs=True)

        driver.get(url=url)
        
        #Waiting time to check if multiple browsers are open
        time.sleep(1)
    except Exception:
        print("ex")
    finally:
        driver.close()
        driver.quit()

if __name__ == '__main__':
    p = Pool(processes=3)
    p.map(check, url_list)
    
<------------------------code------------------------>
