### ISSUE TITLE
Timed out receiving message from renderer

### ISSUE THREAD

**Issue by ben-elbert** [ultrafunkamsterdam/undetected-chromedriver#1043]
Hello, 
for some reason I keep getting this error:
'''
Traceback (most recent call last):
  File "/worker/browser_module.py", line 129, in run
    output = _get_output(browser, flags)
  File "/worker/browser_module.py", line 53, in _get_output
    screenshot = browser._driver.get_screenshot_as_base64()
  File "/usr/local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 937, in get_screenshot_as_base64
    return self.execute(Command.SCREENSHOT)["value"]
  File "/usr/local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 440, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 245, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 10.000
  (Session info: headless chrome=109.0.5414.119)
'''

Even though I added those lines:
'''
        driver = undetected_chrome.Chrome(options=chrome_options, desired_capabilities=caps)
        driver.set_page_load_timeout(60)
        driver.set_script_timeout(60)
'''

What should I do?

thanks in advance

**Comment by stevenhubhub** [comment]
I also encountered the same problem, after many tests, setting the same timeout parameter as you can not solve.

**Comment by stevenhubhub** [comment]
> I also encountered the same problem, after many tests, setting the same timeout parameter as you can not solve.

selenium.common.exceptions.WebDriverException: Message: unknown error: cannot connect to chrome at 127.0.0.1:38447

**Comment by papplication** [comment]
I had a similar error, it was only solved by downgrading to version 3.1.2.
