### ISSUE TITLE
Ver 3.4.5 - FileNotFoundError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by ben-elbert** [ultrafunkamsterdam/undetected-chromedriver#1057]
Hello, tried to upgrade to 3.4.5, but I encounter an issue
```
Traceback (most recent call last):
  File "/infrastructure/goldenmoth/goldenmoth/command_runner.py", line 213, in run_command
    result, error, fragment_id = run_function(command)
  File "/infrastructure/goldenmoth/goldenmoth/worker.py", line 8, in wrapper
    return_value = f(*args, **kwargs)
  File "/worker/browser_module.py", line 119, in run
    with _get_browser(url, config["browser"]) as browser:
  File "/worker/browser_module.py", line 20, in _get_browser
    return ChromeBrowser(url)
  File "/worker/browsers.py", line 112, in __init__
    super(ChromeBrowser, self).__init__(url, **config)
  File "/worker/browsers.py", line 39, in __init__
    self._driver = self.get_driver()
  File "/worker/browsers.py", line 120, in get_driver
    driver = undetected_chrome.Chrome(options=chrome_options, desired_capabilities=caps, version_main=109,
  File "/usr/local/lib/python3.8/site-packages/undetected_chromedriver/__init__.py", line 246, in __init__
    self.patcher.auto()
  File "/usr/local/lib/python3.8/site-packages/undetected_chromedriver/patcher.py", line 127, in auto
    self.unzip_package(self.fetch_package())
  File "/usr/local/lib/python3.8/site-packages/undetected_chromedriver/patcher.py", line 180, in unzip_package
    os.rename(os.path.join(self.zip_path, self.exe_name), self.executable_path)
FileNotFoundError: [Errno 2] No such file or directory: '/root/.local/share/undetected_chromedriver/undetected/chromedriver' -> '/root/.local/share/undetected_chromedriver/undetected_chromedriver'
```

chrome version - 109 latest
undetecte version - 3.4.5
running in docker - so no need to upgrade twice

**Comment by ben-elbert** [comment]
This line
```
os.rename(os.path.join(self.zip_path, self.exe_name), self.executable_path)
```

fails when the second thread is trying to initialize the driver. we need to find a workaround for a multi-threaded environment

**Comment by Arsh1219** [comment]
same issue here

**Comment by FHOFHAWK** [comment]
Same issue with multithreading

**Comment by Arsh1219** [comment]
So after researching, the solution is to mention executable path to downloaded chromedriver file.

**Comment by FHOFHAWK** [comment]
@Arsh1219 , could you please specify where is it located?
As far as I understood, it's part of docker image.

**Comment by Arsh1219** [comment]
we can do it like this:

driver = Chrome(options=chrome_options, version_main=111,
                        driver_executable_path="/home/chromedriver")

**Comment by FHOFHAWK** [comment]
Yeah, but I guess there is difference between expected "undetected_chromedriver" and usual "chromedriver" in your example (assuming it was downloaded from official webpage)?

**Comment by Arsh1219** [comment]
I downloaded it from the official website; it's working fine for the website I am scraping.

**Comment by FHOFHAWK** [comment]
Thank you, let me try.

Will update soon.

**Comment by FHOFHAWK** [comment]
Hi @Arsh1219 ,
Nothing helped.

Still same issue, but now it's related to path I provided.

**Comment by Arsh1219** [comment]
Try to move chromedriver file in same folder where script exists and fix permissions with
`chmod +x chromedriver`

**Comment by FHOFHAWK** [comment]
Oh, cool, I provided following configuration according your suggestions and it worked.
Thank you very much!

`FROM ultrafunk/undetected-chromedriver

RUN DEBIAN_FRONTEND=noninteractive 
RUN wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub > /usr/share/keyrings/chrome.pub 
RUN echo 'deb [arch=amd64 signed-by=/usr/share/keyrings/chrome.pub] http://dl.google.com/linux/chrome/deb/ stable main' > /etc/apt/sources.list.d/google-chrome.list
RUN apt update -y 
RUN apt install -y google-chrome-stable

RUN apt install xvfb -y 
RUN export DISPLAY=:1 
RUN Xvfb $DISPLAY -screen $DISPLAY 1280x1024x16 &
RUN apt-get update
RUN apt-get install -y chromium-driver
RUN wget https://chromedriver.storage.googleapis.com/111.0.5563.64/chromedriver_linux64.zip \
    && unzip chromedriver_linux64.zip \
    && chmod +x chromedriver \
    && mv chromedriver /usr/local/bin/`

and also downgraded version for undetected-chromedriver==3.2.0

and also provided `driver_executable_path="/usr/local/bin/chromedriver"`.

But now I am facing with another issue, maybe you @Arsh1219 know how to resolve it:
I see thousands of zombie processes due to opened chromes in threads during program execution.

Same happens in GUI, it's endless chromes (probably, something's wrong in my code, but I use close() and quit() for driver everywhere, where it's possible, including error handling.)
So, I really wonder, why it's happening. 
<img width="239" alt="image" src="https://user-images.githubusercontent.com/50171653/227601421-ebd07738-80fc-475b-ac93-2e69dda24cb9.png">

Will be very grateful, if you can suggest something.

**Comment by ngMinhDan** [comment]
yes it true, i try use specific chrome like this

**Comment by jdholtz** [comment]
@FHOFHAWK you can kill those zombie processes (assuming you are using a *nix system) by waiting for the PIDs after you do `quit()`. Here is an example:

```
driver.quit()
os.waitpid(driver.browser_pid, 0)
os.waitpid(driver.service.process.pid, 0)
```

I added a PR (#1391) to fix this issue.
