### ISSUE TITLE
[🐛 Bug]: Python unexpected driver behavior after closing a new tab and switching back to initial tab when using chrome profiles

### ISSUE THREAD

**Issue by danielrzad** [ultrafunkamsterdam/undetected-chromedriver#1059]
Hi!
I've encountered a very strange bug while I was working with multiple tabs. Basically what I do is:
1) I'm opening a new tab with a click on element.
2) I'm switching to the new tab.
3) I'm closing the new tab and switching back to the initial tab.
4) And now we get to the unexpected part. After switching to the initial tab any action with driver is producing the error: `selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found` (I'm attaching full error code under my code) I've added some sites to visit show that the error happens after closing the tab and it's not caused by the rest of my code. **HOWEVER** if I will add `time.sleep(10)` before visiting those sites everything works fine. What is more weird to me - **it has to be 10 seconds or more** (9 seconds won't work and will produce same error as without time.sleep() added). I think the problem here are chrome profiles. Without them everything works fine. 

I will appreciate any feedback. 
Best regards, 
Daniel.

[tab_switche_error.zip](https://github.com/ultrafunkamsterdam/undetected-chromedriver/files/10697787/tab_switche_error.zip)
Above I'm attaching .py file with minimal code to reproduce the error and console output, but if someone doesn't want to download that, here's the code and below that will be the console output:

```
from selenium.webdriver.common.by import By
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver import ActionChains
from selenium import webdriver


import undetected_chromedriver as uc
import time


def hover_over_element_and_click_it_presence(
    driver, enter_to_iframe, iframe_location, element_location,
):
    print(f'Trying to hover and click: {element_location}')
    # moving mouse to given location
    wait = WebDriverWait(driver, 100)
    actions = ActionChains(driver)
    if enter_to_iframe:
        wait.until(EC.frame_to_be_available_and_switch_to_it(iframe_location))
        print(f'Switched to iframe: {iframe_location}')
    element = wait.until(EC.presence_of_element_located(element_location))
    actions.move_to_element(element).click(element).perform()
    print(f'Mouse moved and clicked into: {element_location}')
    return driver


def initialize_web_driver():
    # set up a webdriver instance
    print('Setting up new webdriver instance')
    options = webdriver.ChromeOptions()
    # use the user profile
    options.add_argument(r'--user-data-dir=C:\Users\user_name\AppData\Local\Google\Chrome\User Data')
    options.add_argument('--profile-directory=Profile 8')
    options.set_capability("detach", True)
    # lunch webdriver
    driver = uc.Chrome(use_subprocess=True, options=options)
    print('~Driver initialized')
    return driver


def mp_process_extraction(driver):
    wait = WebDriverWait(driver, 10)
    initial_tab = driver.current_window_handle
    print(f'initial_tab: {initial_tab}')
    # hover over and click initial <Download> button
    driver.get('https://multiup.org/42201a945d5306a8832548f02e0840b9')
    hover_over_element_and_click_it_presence(
        driver=driver, enter_to_iframe=False, iframe_location=None,
        element_location=(By.XPATH, '//div/button[@type="submit"]')
    )
    wait.until(EC.number_of_windows_to_be(2))
    all_tabs = driver.window_handles
    new_tab = [tab for tab in all_tabs if tab != initial_tab][0]
    driver.switch_to.window(new_tab)
    wait.until(EC.title_contains('Mirror list '))
    driver.close()
    driver.switch_to.window(initial_tab)
    wait.until(EC.title_contains('Download '))
    tab_after_switch = driver.current_window_handle
    print(f'tab_after_switch: {tab_after_switch}')
    sites_to_visit = (
        'https://www.google.com/', 'https://www.wikipedia.org/', 'https://www.bing.com/news'
    )
    # time.sleep(10) # with this wait program work fine
    for url in sites_to_visit:
        print(f'Trying to get: {url}')
        driver.get(url)
        print(f'Site {url} reached.')
        print(f'Drivers current url: {driver.current_url}')
    return True


initialized_driver = initialize_web_driver()
mp_process_extraction(initialized_driver)
```

Here's the error log:

```
C:\Users\user_name\Desktop>python tab_switch_error.py
Setting up new webdriver instance
~Driver initialized
initial_tab: CDwindow-D2C9339780405C2A12E5884EE80D6662
Trying to hover and click: ('xpath', '//div/button[@type="submit"]')
Mouse moved and clicked into: ('xpath', '//div/button[@type="submit"]')
tab_after_switch: CDwindow-D2C9339780405C2A12E5884EE80D6662
Trying to get: https://www.google.com/
Site https://www.google.com/ reached.
Drivers current url: https://multiup.org/42201a945d5306a8832548f02e0840b9
Trying to get: https://www.wikipedia.org/
Site https://www.wikipedia.org/ reached.
Traceback (most recent call last):
  File "C:\Users\user_name\Desktop\tab_switch_error.py", line 76, in <module>
    mp_process_extraction(initialized_driver)
  File "C:\Users\user_name\Desktop\tab_switch_error.py", line 71, in mp_process_extraction
    print(f'Drivers current url: {driver.current_url}')
  File "C:\Users\user_name\AppData\Local\Programs\Python\Python310\lib\site-packages\undetected_chromedriver\__init__.py", line 740, in __getattribute__
    return super().__getattribute__(item)
  File "C:\Users\user_name\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 538, in current_url
    return self.execute(Command.GET_CURRENT_URL)["value"]
  File "C:\Users\user_name\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 444, in execute
    self.error_handler.check_response(response)
  File "C:\Users\user_name\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 249, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=110.0.5481.78)
Stacktrace:
Backtrace:
        (No symbol) [0x00E337D3]
        (No symbol) [0x00DC8B81]
        (No symbol) [0x00CCB36D]
        (No symbol) [0x00CAE5DA]
        (No symbol) [0x00D1F0CB]
        (No symbol) [0x00D30A56]
        (No symbol) [0x00D1B216]
        (No symbol) [0x00CF0D97]
        (No symbol) [0x00CF253D]
        GetHandleVerifier [0x010AABF2+2510930]
        GetHandleVerifier [0x010D8EC1+2700065]
        GetHandleVerifier [0x010DC86C+2714828]
        GetHandleVerifier [0x00EE3480+645344]
        (No symbol) [0x00DD0FD2]
        (No symbol) [0x00DD6C68]
        (No symbol) [0x00DD6D4B]
        (No symbol) [0x00DE0D6B]
        BaseThreadInitThunk [0x766700F9+25]
        RtlGetAppContainerNamedObjectPath [0x77CC7BBE+286]
        RtlGetAppContainerNamedObjectPath [0x77CC7B8E+238]
```

**Comment by ultrafunkamsterdam** [comment]
there is soo much wrong with this. 

most important . you cannot run multiple processes with the same profile
