### ISSUE TITLE
TypeError when initiating multiple ChromeOptions

### ISSUE THREAD

**Issue by bharatbots** [ultrafunkamsterdam/undetected-chromedriver#1096]
I'm running two uc chromedrivers at the same time with two different ChromeOptions. The same ChromeOption can't be resused to i had to create two but I got this type error whenever I tried running two instances of it:

`Traceback (most recent call last):
  File "C:\Users\asusr\Desktop\chatGPT prog\Stake.com Notification\sel\tabs.py", line 26, in <module>
    driver2 = uc.Chrome(user_data_dir=user_dir2, options=options2)
  File "C:\Users\asusr\AppData\Local\Programs\Python\Python310\lib\site-packages\undetected_chromedriver\__init__.py", line 374, in __init__        
    if self.patcher.version_main < 108:
TypeError: '<' not supported between instances of 'NoneType' and 'int'`

Any way to define chromedriver options globally without using ChromeOptions? I just want both my drivers to be headless

**Comment by Simatwa** [comment]
I'm experiencing the same issue when even running a single instance in headless mode.

**Comment by bharatbots** [comment]
Passing `main_version` to UC webdriver fixed it for me.

I ran the same script on Linux and it worked fine.

For me this bug is windows only and i was about to fix it by passing
main_version=110

**Comment by Jobine23** [comment]
I am having the same issue. I had to specify main_version=110 to fix.

**Comment by niksingla** [comment]
> ```python
> version and version
> ```

It really worked, thanks!
