### ISSUE TITLE
Similar error to this issue. Cant connect to chromedriver port

### ISSUE THREAD

**Issue by neomachiney** [ultrafunkamsterdam/undetected-chromedriver#1128]
https://github.com/ultrafunkamsterdam/undetected-chromedriver/issues/1046
```
Traceback (most recent call last):
  File "/root/My-Computer/My-Working/Money/Youtube/YoutubeProfiles/machineaaaaa/test.py", line 4, in <module>
    driver = uc.Chrome(headless = True, user_data_dir="chromium/", options=options, version_main=110)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/undetected_chromedriver/__init__.py", line 441, in __init__
    super(Chrome, self).__init__(
  File "/usr/local/lib/python3.12/site-packages/selenium/webdriver/chrome/webdriver.py", line 81, in __init__
    super().__init__(
  File "/usr/local/lib/python3.12/site-packages/selenium/webdriver/chromium/webdriver.py", line 106, in __init__
    super().__init__(
  File "/usr/local/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 288, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python3.12/site-packages/undetected_chromedriver/__init__.py", line 704, in start_session
    super(selenium.webdriver.chrome.webdriver.WebDriver, self).start_session(
  File "/usr/local/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 381, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 444, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py", line 249, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot connect to chrome at 127.0.0.1:46383
from chrome not reachable
Stacktrace:
#0 0x556ae5750d93 <unknown>
#1 0x556ae551f15d <unknown>
#2 0x556ae550da2b <unknown>
#3 0x556ae554bc63 <unknown>
#4 0x556ae55432fc <unknown>
#5 0x556ae55884f4 <unknown>
#6 0x556ae557f353 <unknown>
#7 0x556ae554ee40 <unknown>
#8 0x556ae5550038 <unknown>
#9 0x556ae57a48be <unknown>
#10 0x556ae57a88f0 <unknown>
#11 0x556ae5788f90 <unknown>
#12 0x556ae57a9b7d <unknown>
#13 0x556ae577a578 <unknown>
#14 0x556ae57ce348 <unknown>
#15 0x556ae57ce4d6 <unknown>
#16 0x556ae57e8341 <unknown>
#17 0x7f3fae295fd4 <unknown>

```

**Comment by neomachiney** [comment]
I figured out --headless with user_data_dir was culprit.
![image](https://user-images.githubusercontent.com/118899053/225063305-a75db161-2c38-450b-821f-3c50252e0891.png)

**Comment by neomachiney** [comment]
So user_data_dir folder was corrupted.

**Comment by neomachiney** [comment]
It wasnt. There's something else going on

**Comment by neomachiney** [comment]
I'll try to figure out and report back

**Comment by neomachiney** [comment]
[21100:21100:0314/215909.099576:ERROR:process_singleton_posix.cc(334)] Failed to create chromium/SingletonLock: File exists (17)

**Comment by neomachiney** [comment]
This error is there when --user-data-dir + --headless=new is used but not when --headless=new is removed but --user-data-dir is there. Also for some reason I also had a chromium process opened that was non killable. Not sure how but this issue got fixed automatically?

**Comment by neomachiney** [comment]
Anyways I am closing it for now

**Comment by Zai-Kun** [comment]
I'm getting the same error when using `--headless` with `options.add_argument('--user-data-dir=./bin/testprofile2')`

any updates on the matter?

**Comment by neomachiney** [comment]
@Zai-Kun try running pkill chromium and delete SingletonLock file in user data dir folder and try again
