### ISSUE TITLE
Issue at driver.quit()

### ISSUE THREAD

**Issue by epsilonr** [ultrafunkamsterdam/undetected-chromedriver#1172]
```
Exception ignored in: <function Chrome.__del__ at 0x0000024C9B35610>
Traceback (most recent call last):
  File "C:\Python311\Lib\site-packages\undetected_chromedriver\__init__.py", line 788, in __del__
    self.quit()
  File "C:\Python311\Lib\site-packages\undetected_chromedriver\__init__.py", line 743, in quit
    time.sleep(0.1)
OSError: [WinError 6] The handle is invalid
```

I am running chrome in headless mode with 5 threads at the same time this error occurs. I think driver doesn't quit properly and it fills up my temp storage.

**Comment by ggnetoo** [comment]
Same here. Does anyone know how to avoid this so as not to accumulate or something?

**Comment by koctalha** [comment]
Same here in macos

**Comment by yousuobuxue** [comment]
I have the same problem
System: windows 10
undetected-chromedriver: 3.4.6
I commented out the code at line 743 in the file Lib\site-packages\undetected_chromedriver\__init__.py: `time.sleep(0.1)` There is no prompt: OSError: [WinError 6] The handle is invalid

**Comment by benethor** [comment]
@ggnetoo I've already noticed the problem in early March, one socket isn't being closed correctly - fix is available at #1124
