### ISSUE TITLE
I am trying to make it run but it fails

### ISSUE THREAD

**Issue by deriklogov** [ultrafunkamsterdam/undetected-chromedriver#118]
### I am trying to run it on Centos7 VPS.

**I installed everything it needs:**

```

sudo yum install wget
wget https://dl.google.com/linux/direct/google-chrome-stable_current_x86_64.rpm
sudo yum install google-chrome-stable_current_x86_64.rpm
sudo yum install python3-pip
sudo yum install xorg-x11-server-Xvfb
curl "https://bootstrap.pypa.io/get-pip.py" -o "get-pip.py"
python3 get-pip.py
```

Google Chrome 89.0.4389.82

**Test file:**
```
import undetected_chromedriver as uc
#driver = uc.Chrome()
driver = uc.Chrome()
driver.get('https://distilnetworks.com')
```

**and I am getting error:**

```
Traceback (most recent call last):
  File "test1.py", line 3, in <module>
    driver = uc.Chrome()
  File "/home/centos/.local/lib/python3.6/site-packages/undetected_chromedriver/__init__.py", line 53, in __new__
    instance.__init__(*args, **kwargs)
  File "/home/centos/.local/lib/python3.6/site-packages/selenium/webdriver/chrome/webdriver.py", line 81, in __init__
    desired_capabilities=desired_capabilities)
  File "/home/centos/.local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/home/centos/.local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/centos/.local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/centos/.local/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally.
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)

```

**Comment by deriklogov** [comment]
I would really appreciate if you could explain what i am doing wrong.

**Comment by ultrafunkamsterdam** [comment]
My educated guess would be an issue with (not having) a physical display. 

try 

```shell
pip install pyvirtualdisplay
```
and in your code, before any chromedriver initialization:
```python
from pyvirtualdisplay import Display
disp = Display(visible=0, size=(1920, 1080)).start()

# your actual code 
```

note: untested

**Comment by deriklogov** [comment]
Its working, Thank You
