### ISSUE TITLE
when i try run recaptcha demo ,but it have error

### ISSUE THREAD

**Issue by CodeTrainerMan** [ultrafunkamsterdam/undetected-chromedriver#1180]
Traceback (most recent call last):
  File "D:\python\workspace\web3Robot\venv\lib\site-packages\urllib3\connectionpool.py", line 700, in urlopen
    self._prepare_proxy(conn)
  File "D:\python\workspace\web3Robot\venv\lib\site-packages\urllib3\connectionpool.py", line 996, in _prepare_proxy
    conn.connect()
  File "D:\python\workspace\web3Robot\venv\lib\site-packages\urllib3\connection.py", line 369, in connect
    self.sock = conn = self._connect_tls_proxy(hostname, conn)
  File "D:\python\workspace\web3Robot\venv\lib\site-packages\urllib3\connection.py", line 510, in _connect_tls_proxy
    ssl_context=ssl_context,
  File "D:\python\workspace\web3Robot\venv\lib\site-packages\urllib3\util\ssl_.py", line 453, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls)
  File "D:\python\workspace\web3Robot\venv\lib\site-packages\urllib3\util\ssl_.py", line 495, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock)
  File "D:\python\Python\Python37\lib\ssl.py", line 423, in wrap_socket
    session=session
  File "D:\python\Python\Python37\lib\ssl.py", line 870, in _create
    self.do_handshake()
  File "D:\python\Python\Python37\lib\ssl.py", line 1139, in do_handshake
    self._sslobj.do_handshake()
OSError: [Errno 0] Error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\python\workspace\web3Robot\venv\lib\site-packages\requests\adapters.py", line 499, in send
    timeout=timeout,
  File "D:\python\workspace\web3Robot\venv\lib\site-packages\urllib3\connectionpool.py", line 788, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "D:\python\workspace\web3Robot\venv\lib\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: /recaptcha/api2/payload/audio.mp3?p=06AKH6MRHGipkBZlHUeg06eJTKgvRN59XK26GscKH8whUOX3sdtjEOSazHNyAjVKdvD1GbTUhgjdOIQVrg2LNPdNq4GVXq04IRF_syh1oiKKex1LE9fhnEC8fzXYbKf8qFql4xhnfpxwb8bDvVzioRgK6CcJIR6lBHCrjsxUHyh_uca7HVOTy-kj50zVdxM6OrJiwNoiR6hTfQ53oHsOHeMmAcuo5v1XLv_A&k=6Le-wvkSAAAAAPBMRTvw0Q4Muexq9bi0DJwx_mJ- (Caused by ProxyError('Cannot connect to proxy.', OSError(0, 'Error')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:/python/workspace/web3Robot/get_goerli/test_recaptcha.py", line 33, in <module>
    solver.click_recaptcha_v2(iframe=recaptcha_iframe)
  File "D:\python\workspace\web3Robot\venv\lib\site-packages\selenium_recaptcha_solver\solver.py", line 83, in click_recaptcha_v2
    self.solve_recaptcha_v2_challenge(iframe=captcha_challenge)
  File "D:\python\workspace\web3Robot\venv\lib\site-packages\selenium_recaptcha_solver\solver.py", line 123, in solve_recaptcha_v2_challenge
    self._solve_audio_challenge()
  File "D:\python\workspace\web3Robot\venv\lib\site-packages\selenium_recaptcha_solver\solver.py", line 193, in _solve_audio_challenge
    audio_download = requests.get(url=link, allow_redirects=True)
  File "D:\python\workspace\web3Robot\venv\lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "D:\python\workspace\web3Robot\venv\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "D:\python\workspace\web3Robot\venv\lib\site-packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\python\workspace\web3Robot\venv\lib\site-packages\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "D:\python\workspace\web3Robot\venv\lib\site-packages\requests\adapters.py", line 559, in send
    raise ProxyError(e, request=request)
requests.exceptions.ProxyError: HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: /recaptcha/api2/payload/audio.mp3?p=06AKH6MRHGipkBZlHUeg06eJTKgvRN59XK26GscKH8whUOX3sdtjEOSazHNyAjVKdvD1GbTUhgjdOIQVrg2LNPdNq4GVXq04IRF_syh1oiKKex1LE9fhnEC8fzXYbKf8qFql4xhnfpxwb8bDvVzioRgK6CcJIR6lBHCrjsxUHyh_uca7HVOTy-kj50zVdxM6OrJiwNoiR6hTfQ53oHsOHeMmAcuo5v1XLv_A&k=6Le-wvkSAAAAAPBMRTvw0Q4Muexq9bi0DJwx_mJ- (Caused by ProxyError('Cannot connect to proxy.', OSError(0, 'Error')))

**Comment by CodeTrainerMan** [comment]
???
