### ISSUE TITLE
SSL: CERTIFICATE_VERIFY_FAILED when calling function from other file

### ISSUE THREAD

**Issue by ashold7** [ultrafunkamsterdam/undetected-chromedriver#122]
I have two files: test5.py and test4.py. The content of test5.py is:
```
import undetected_chromedriver as uc
import time
from bs4 import BeautifulSoup

def a():
    options = uc.ChromeOptions()
    options.headless = True
    options.add_argument('--headless')
    options.add_argument('ignore-certificate-errors')
    driver = uc.Chrome(options=options)
    driver.get("https://www.bstn.com")
    time.sleep(10)
    page = BeautifulSoup(driver.page_source, 'html.parser')
    print(page)
a()
```
This works without any error, however if I call it within test4.py:
```
import test5
test5.a()
```
I get the following error:
```
Traceback (most recent call last):
  File "/usr/lib/python3.8/urllib/request.py", line 1350, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/usr/lib/python3.8/http/client.py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1301, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1250, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1010, in _send_output
    self.send(msg)
  File "/usr/lib/python3.8/http/client.py", line 950, in send
    self.connect()
  File "/usr/lib/python3.8/http/client.py", line 1424, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "/usr/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/usr/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1123)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ashold7/PycharmProjects/sneaker_scraper/test4.py", line 7, in <module>
    import bstn_releases
  File "/home/ashold7/PycharmProjects/sneaker_scraper/bstn_releases.py", line 82, in <module>
    bstn_releases()
  File "/home/ashold7/PycharmProjects/sneaker_scraper/bstn_releases.py", line 50, in bstn_releases
    api_key = get_bstn_api()
  File "/home/ashold7/PycharmProjects/sneaker_scraper/bstn_releases.py", line 22, in get_bstn_api
    options = uc.ChromeOptions()
  File "/home/ashold7/PycharmProjects/sneaker_scraper/venv/lib/python3.8/site-packages/undetected_chromedriver/__init__.py", line 110, in __new__
    ChromeDriverManager(*args, **kwargs).install()
  File "/home/ashold7/PycharmProjects/sneaker_scraper/venv/lib/python3.8/site-packages/undetected_chromedriver/__init__.py", line 144, in __init__
    self.target_version = self.get_release_version_number().version[
  File "/home/ashold7/PycharmProjects/sneaker_scraper/venv/lib/python3.8/site-packages/undetected_chromedriver/__init__.py", line 209, in get_release_version_number
    return LooseVersion(urlopen(self.__class__.DL_BASE + path).read().decode())
  File "/usr/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/usr/lib/python3.8/urllib/request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 1393, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/usr/lib/python3.8/urllib/request.py", line 1353, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1123)>
```
Thank you in advance, any help is appreciated.

**Comment by ultrafunkamsterdam** [comment]
this is not an issue caused by this package. you probably need to setup:
```sh
sudo apt install -y python3.8-dev
sudo apt install -y build-essential checkinstall libreadline-gplv2-dev ibncursesw5-dev libssl-dev libsqlite3-dev tk-dev libgdbm-dev libc6-dev libbz2-dev
```

good chance your ssl implementation of python will work like a charm.

**Comment by ashold7** [comment]
Thank you it really worked like a charm
