### ISSUE TITLE
Message: unknown error: DevToolsActivePort file doesn't exist

### ISSUE THREAD

**Issue by pablocool** [ultrafunkamsterdam/undetected-chromedriver#123]
Hi

I successfully installed undetected-chromedriver and I am trying your simple example:
```
import undetected_chromedriver as uc
driver = uc.Chrome()
driver.get('https://distilnetworks.com')
```
Chromium opens and is just displaying "data:," for some time and crashes afterwards:
```
Traceback (most recent call last):
  File "./undetected-chrome.py", line 14, in <module>
    driver = uc.Chrome()
  File "/home/pablocool/.local/lib/python3.8/site-packages/undetected_chromedriver/__init__.py", line 53, in __new__
    instance.__init__(*args, **kwargs)
  File "/home/pablocool/.local/lib/python3.8/site-packages/selenium/webdriver/chrome/webdriver.py", line 76, in __init__
    RemoteWebDriver.__init__(
  File "/home/pablocool/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/home/pablocool/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/pablocool/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/pablocool/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: DevToolsActivePort file doesn't exist
```

I have met similar error before with vanilla selenium. Even ~/bin was exported to PATH variable, I had to add chromedriver path argument to solve issue:
`driver = webdriver.Chrome("~/bin/chromedriver", options=options)`

Now I cannot use this workaround because your undetected-chromedriver downloads and patches chromedriver binary on its own (if I understood correctly of course).

I noticed v2 is not facing this issue, but it opens Chromium not maximized so I assume it is not fed with all arguments hiding it from bot detectors?

Do you know what can I do with standard recommended version?
Install Chrome instead of Chromium?
or?

I use latest ubuntu distribution.

Thanks for your work!

**Comment by pablocool** [comment]
Using Chrome instead of Chromium solved issue
