### ISSUE TITLE
unable to find element 

### ISSUE THREAD

**Issue by 007-JB** [ultrafunkamsterdam/undetected-chromedriver#1237]
Hi - amazing contribution - thank you.

some feedback/errors I'm encountering - not sure if there's something I should be doing differently - but when I run your most recent [example code]([undetected-chromedriver](https://github.com/ultrafunkamsterdam/undetected-chromedriver/tree/master)/[example](https://github.com/ultrafunkamsterdam/undetected-chromedriver/tree/master/example)
/example.py) I get this error off the bat:

```
Traceback (most recent call last):
  File "C:\\\..\\\\", line 177, in <module>
    main(a)
  File "C:\\\..\\\\", line 34, in main
    inp_search = driver.find_element(By.XPATH, '//input[@title="Search"]')
  File "C:\\\..\\\\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 855, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\\\..\\\\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 428, in execute
    self.error_handler.check_response(response)
  File "C:\\\..\\\\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 243, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//input[@title="Search"]"}
  (Session info: chrome=113.0.5672.64)
Stacktrace:
Backtrace:
	GetHandleVerifier [0x01088893+48451]
	(No symbol) [0x0101B8A1]
        etc. etc.
```

Pls advise (I'm having trouble launching to begin with - I remember using this cool library/resource previously without same issues - may be something RE: the way I have configured chrome/chromedriver?  Your code provides for chromedriver I think - I've downloaded the latest chrome (113.xx) to be compatible with the chromdriver - so that's not actually an issue any longer - was hoping my personal implementation issues would be resolved by just running some stock / from the source / code - i.e your examples - but no such luck I'm afraid.

Version Python:  PyCharm 2022.3.1 (Community Edition)
chrome/chrome: as above:
Pycharm IDE

Machine (not that it matters) - i19 13th 64GB - ran on some slower machines lying around - same story - will try on one more machine I have - hopefully that will indicate configuration or something... (I can open an ordinary webdriver.Chrome instance no sweat otherwise )...

**Comment by 007-JB** [comment]
Any luck?
