### ISSUE TITLE
cant connect to chromedriver for some reason

### ISSUE THREAD

**Issue by GariPog** [ultrafunkamsterdam/undetected-chromedriver#1259]
root@ubuntu-python-3:~/fs0# python src/flaresolverr.py 8195
2023-05-13 13:42:21 INFO     FlareSolverr 3.1.2
Testing web browser installation...
Platform: Linux-5.4.0-148-generic-x86_64-with-glibc2.31
Chrome / Chromium path: /root/fs0/src/chrome/chrome
Chrome / Chromium major version: 111
Launching web browser...

Traceback (most recent call last):
  File "/root/fs0/src/utils.py", line 194, in get_user_agent
    driver = get_webdriver()
             ^^^^^^^^^^^^^^^
  File "/root/fs0/src/utils.py", line 83, in get_webdriver
    driver = uc.Chrome(options=options, browser_executable_path=browser_executable_path,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/fs0/src/undetected_chromedriver/__init__.py", line 453, in __init__
    super(Chrome, self).__init__(
  File "/root/.pyenv/versions/3.11.1/lib/python3.11/site-packages/selenium/webdriver/chrome/webdriver.py", line 80, in __init__
    super().__init__(
  File "/root/.pyenv/versions/3.11.1/lib/python3.11/site-packages/selenium/webdriver/chromium/webdriver.py", line 104, in __init__
    super().__init__(
  File "/root/.pyenv/versions/3.11.1/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 286, in __init__
    self.start_session(capabilities, browser_profile)
  File "/root/fs0/src/undetected_chromedriver/__init__.py", line 716, in start_session
    super(selenium.webdriver.chrome.webdriver.WebDriver, self).start_session(
  File "/root/.pyenv/versions/3.11.1/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 378, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.pyenv/versions/3.11.1/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 440, in execute
    self.error_handler.check_response(response)
  File "/root/.pyenv/versions/3.11.1/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py", line 245, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot connect to chrome at 127.0.0.1:51909
from chrome not reachable
Stacktrace:
#0 0x5609658ac243 <unknown>
#1 0x560965670631 <unknown>
#2 0x56096565ef06 <unknown>
#3 0x56096569d7d0 <unknown>
#4 0x560965694d52 <unknown>
#5 0x5609656d72a7 <unknown>
#6 0x5609656d68cf <unknown>
#7 0x5609656cde53 <unknown>
#8 0x5609656a09ea <unknown>
#9 0x5609656a1b2e <unknown>
#10 0x560965900d5e <unknown>
#11 0x560965904a80 <unknown>
#12 0x5609658e68b0 <unknown>
#13 0x560965905b63 <unknown>
#14 0x5609658d7f75 <unknown>
#15 0x560965928998 <unknown>
#16 0x560965928b27 <unknown>
#17 0x560965943c23 <unknown>
#18 0x7ff4774f0609 start_thread

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/fs0/src/flaresolverr.py", line 105, in <module>
    flaresolverr_service.test_browser_installation()
  File "/root/fs0/src/flaresolverr_service.py", line 78, in test_browser_installation
    user_agent = utils.get_user_agent()
                 ^^^^^^^^^^^^^^^^^^^^^^
  File "/root/fs0/src/utils.py", line 198, in get_user_agent
    raise Exception("Error getting browser User-Agent. " + str(e))
Exception: Error getting browser User-Agent. Message: unknown error: cannot connect to chrome at 127.0.0.1:51909
from chrome not reachable
Stacktrace:
#0 0x5609658ac243 <unknown>
#1 0x560965670631 <unknown>
#2 0x56096565ef06 <unknown>
#3 0x56096569d7d0 <unknown>
#4 0x560965694d52 <unknown>
#5 0x5609656d72a7 <unknown>
#6 0x5609656d68cf <unknown>
#7 0x5609656cde53 <unknown>
#8 0x5609656a09ea <unknown>
#9 0x5609656a1b2e <unknown>
#10 0x560965900d5e <unknown>
#11 0x560965904a80 <unknown>
#12 0x5609658e68b0 <unknown>
#13 0x560965905b63 <unknown>
#14 0x5609658d7f75 <unknown>
#15 0x560965928998 <unknown>
#16 0x560965928b27 <unknown>
#17 0x560965943c23 <unknown>
#18 0x7ff4774f0609 start_thread

only works with standard version of chromedriver that comes with flaresolver, when i put custom chromedriver by google or chromium, it doesnt work. I have even tried to use patcher.py from last update and use that but still same.

**Comment by zax2002** [comment]
Try with version 3.4.6. In the current version, driver_executable_path is broken

**Comment by henzycuong1** [comment]
I got same problem

**Comment by GariPog** [comment]
3.4.6 doesnt exits bruh?

**Comment by GariPog** [comment]
Nah, same with 3.4.6

**Comment by ontisme** [comment]
I got same problem

**Comment by GariPog** [comment]
can you add me on discord so we can test stuff together and etc?
Velja Nevolja#7142

**Comment by GariPog** [comment]
```
2023-05-13 19:35:00 INFO     FlareSolverr 3.1.2
Testing web browser installation...
Platform: Linux-5.4.0-148-generic-x86_64-with-glibc2.31
Chrome / Chromium path: /root/fs0/src/chrome/chrome
Chrome / Chromium major version: 113
Launching web browser...
*FREEZES HERE*
```

still doesnt work with 3.4.5 version of undetected-chromedriver and 113 version of chromium, but with 115 (Chromium 115.0.5769.0) version i get this error:

```
2023-05-13 19:33:24 INFO     FlareSolverr 3.1.2
Testing web browser installation...
Platform: Linux-5.4.0-148-generic-x86_64-with-glibc2.31
Chrome / Chromium path: /root/fs0/src/chrome/chrome
Chrome / Chromium major version: 115
Launching web browser...
Traceback (most recent call last):
  File "/root/fs0/src/utils.py", line 188, in get_user_agent
    driver = get_webdriver("/")
             ^^^^^^^^^^^^^^^^^^
  File "/root/fs0/src/utils.py", line 83, in get_webdriver
    driver = uc.Chrome(options=options, browser_executable_path=browser_executable_path,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/fs0/src/undetected_chromedriver/__init__.py", line 246, in __init__
    self.patcher.auto()
  File "/root/fs0/src/undetected_chromedriver/patcher.py", line 124, in auto
    release = self.fetch_release_number()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/fs0/src/undetected_chromedriver/patcher.py", line 145, in fetch_release_number
    return LooseVersion(urlopen(self.url_repo + path).read().decode())
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.pyenv/versions/3.11.1/lib/python3.11/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.pyenv/versions/3.11.1/lib/python3.11/urllib/request.py", line 525, in open
    response = meth(req, response)
               ^^^^^^^^^^^^^^^^^^^
  File "/root/.pyenv/versions/3.11.1/lib/python3.11/urllib/request.py", line 634, in http_response
    response = self.parent.error(
               ^^^^^^^^^^^^^^^^^^
  File "/root/.pyenv/versions/3.11.1/lib/python3.11/urllib/request.py", line 563, in error
    return self._call_chain(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.pyenv/versions/3.11.1/lib/python3.11/urllib/request.py", line 496, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/root/.pyenv/versions/3.11.1/lib/python3.11/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/fs0/src/flaresolverr.py", line 105, in <module>
    flaresolverr_service.test_browser_installation()
  File "/root/fs0/src/flaresolverr_service.py", line 78, in test_browser_installation
    user_agent = utils.get_user_agent()
                 ^^^^^^^^^^^^^^^^^^^^^^
  File "/root/fs0/src/utils.py", line 192, in get_user_agent
    raise Exception("Error getting browser User-Agent. " + str(e))
Exception: Error getting browser User-Agent. HTTP Error 404: Not Found
```

Someone knows fixed?

**Comment by cuppjj** [comment]
> ```
> 2023-05-13 19:35:00 INFO     FlareSolverr 3.1.2
> Testing web browser installation...
> Platform: Linux-5.4.0-148-generic-x86_64-with-glibc2.31
> Chrome / Chromium path: /root/fs0/src/chrome/chrome
> Chrome / Chromium major version: 113
> Launching web browser...
> *FREEZES HERE*
> ```
> 
> still doesnt work with 3.4.5 version of undetected-chromedriver and 113 version of chromium, but with 115 (Chromium 115.0.5769.0) version i get this error:
> 
> ```
> 2023-05-13 19:33:24 INFO     FlareSolverr 3.1.2
> Testing web browser installation...
> Platform: Linux-5.4.0-148-generic-x86_64-with-glibc2.31
> Chrome / Chromium path: /root/fs0/src/chrome/chrome
> Chrome / Chromium major version: 115
> Launching web browser...
> Traceback (most recent call last):
>   File "/root/fs0/src/utils.py", line 188, in get_user_agent
>     driver = get_webdriver("/")
>              ^^^^^^^^^^^^^^^^^^
>   File "/root/fs0/src/utils.py", line 83, in get_webdriver
>     driver = uc.Chrome(options=options, browser_executable_path=browser_executable_path,
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/root/fs0/src/undetected_chromedriver/__init__.py", line 246, in __init__
>     self.patcher.auto()
>   File "/root/fs0/src/undetected_chromedriver/patcher.py", line 124, in auto
>     release = self.fetch_release_number()
>               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/root/fs0/src/undetected_chromedriver/patcher.py", line 145, in fetch_release_number
>     return LooseVersion(urlopen(self.url_repo + path).read().decode())
>                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/root/.pyenv/versions/3.11.1/lib/python3.11/urllib/request.py", line 216, in urlopen
>     return opener.open(url, data, timeout)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/root/.pyenv/versions/3.11.1/lib/python3.11/urllib/request.py", line 525, in open
>     response = meth(req, response)
>                ^^^^^^^^^^^^^^^^^^^
>   File "/root/.pyenv/versions/3.11.1/lib/python3.11/urllib/request.py", line 634, in http_response
>     response = self.parent.error(
>                ^^^^^^^^^^^^^^^^^^
>   File "/root/.pyenv/versions/3.11.1/lib/python3.11/urllib/request.py", line 563, in error
>     return self._call_chain(*args)
>            ^^^^^^^^^^^^^^^^^^^^^^^
>   File "/root/.pyenv/versions/3.11.1/lib/python3.11/urllib/request.py", line 496, in _call_chain
>     result = func(*args)
>              ^^^^^^^^^^^
>   File "/root/.pyenv/versions/3.11.1/lib/python3.11/urllib/request.py", line 643, in http_error_default
>     raise HTTPError(req.full_url, code, msg, hdrs, fp)
> urllib.error.HTTPError: HTTP Error 404: Not Found
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/root/fs0/src/flaresolverr.py", line 105, in <module>
>     flaresolverr_service.test_browser_installation()
>   File "/root/fs0/src/flaresolverr_service.py", line 78, in test_browser_installation
>     user_agent = utils.get_user_agent()
>                  ^^^^^^^^^^^^^^^^^^^^^^
>   File "/root/fs0/src/utils.py", line 192, in get_user_agent
>     raise Exception("Error getting browser User-Agent. " + str(e))
> Exception: Error getting browser User-Agent. HTTP Error 404: Not Found
> ```
> 
> Someone knows fixed?

whats ur code?

**Comment by henzycuong1** [comment]
> I got same problem with 3.4.7
> 
> but 3.4.5 is working

I tried, but not working

**Comment by henzycuong1** [comment]
I tried uninstall and install GoogleChrome and it's working

**Comment by GariPog** [comment]
Can you add me on discord henzy? Velja Nevolja#7142

**Comment by henzycuong1** [comment]
> Can you add me on discord henzy? Velja Nevolja#7142

sorrry, i don't use Discord. You can following the step below:
- 1. Delete all Google folder in C:\Users\...\AppData\Local
- 2. Install GoogleChrome.
- 3. Try undetected_chromedriver.
I did it and working now.

**Comment by GariPog** [comment]
im using ubuntu brother. on windows everything works fine.

**Comment by GariPog** [comment]
UPDATE:
its slow and bad only at CF, on ddos guard it works fine and solves in 3-4 seconds like on cf like 5 days ago.
```

2023-05-14 11:18:57 INFO     1.1.1.1 POST http://1.1.1.1:8191/v1 200 OK
2023-05-14 11:19:08 INFO     Incoming request => POST /v1 body: {'cmd': 'request.get', 'url': 'https://anidex.info/', 'maxTimeout': 30000}
2023-05-14 11:19:09 INFO     Challenge detected. Title found: DDoS-Guard

2023-05-14 11:19:12 INFO     Challenge solved!
2023-05-14 11:19:12 INFO     Response in 3.652 s
2023-05-14 11:19:12 INFO     1.1.1.1 POST http://1.1.1.1:8191/v1 200 OK
2023-05-14 11:19:13 INFO     Incoming request => POST /v1 body: {'cmd': 'request.get', 'url': 'https://anidex.info/', 'maxTimeout': 30000}
2023-05-14 11:19:14 INFO     Challenge detected. Title found: DDoS-Guard
2023-05-14 11:19:16 INFO     Challenge solved!
2023-05-14 11:19:16 INFO     Response in 3.604 s
2023-05-14 11:19:16 INFO     1.1.1.1 POST http://1.1.1.1:8191/v1 200 OK
2023-05-14 11:19:17 INFO     Incoming request => POST /v1 body: {'cmd': 'request.get', 'url': 'https://anidex.info/', 'maxTimeout': 30000}
2023-05-14 11:19:18 INFO     Challenge detected. Title found: DDoS-Guard
2023-05-14 11:19:20 INFO     Challenge solved!
2023-05-14 11:19:21 INFO     Response in 3.516 s
2023-05-14 11:19:21 INFO     1.1.1.1POST http://1.1.1.1:8191/v1 200 OK
```
