### ISSUE TITLE
Headless not working?

### ISSUE THREAD

**Issue by bigredcardinal** [ultrafunkamsterdam/undetected-chromedriver#1282]
Hi. 

driver = uc.Chrome(headless=True) has been working fine for me for a long time,
suddenly i get:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\Python\.venv\Lib\site-packages\undetected_chromedriver\__init__.py", line 386, in __init__
    if self.patcher.version_main < 108:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: '<' not supported between instances of 'NoneType' and 'int'

I have tried making an instance of patcher and getting release.version[0], which correctly returns "113", and that is why I cannot understand that self.patcher.version_main would be 'NoneType'.

Versions:
chrome, Version 113.0.5672.127 (Official Build) (64-bit)
ChromeDriver 113.0.5672.63

Thank you in advance. 
P.S. if you want some help with working around the detection on Bet365 let me know. I have some tips and tricks for making it work despite the detection happening when you navigate the site :)

**Comment by borgben** [comment]
I have the same issue re: Headless mode.

Also I would be interested in hearing what you have to say about avoid Bet365 detection.

Feel free to drop me a message via Github.

**Comment by borgben** [comment]
Just a note @bigredcardinal, a work around I have found to work is

driver = uc.Chrome(headless=True, version_main=113)

I said this in my last message but I would love to hear what you have to say about bet365 :)

**Comment by bigredcardinal** [comment]
> Just a note @bigredcardinal, a work around I have found to work is
> 
> 
> 
> driver = uc.Chrome(headless=True, version_main=113)
> 
> 
> 
> I said this in my last message but I would love to hear what you have to say about bet365 :)

Hey, 
Thanks, I eventually found a work around in another thread. 

I do not seem to be able to message you directly on GitHub. You can drop your e-mail if you like. Then I will reach out and you can delete comment here after.

**Comment by borgben** [comment]
benjaminborg9@gmail.com

**Comment by scatcove** [comment]
Hey @bigredcardinal, I would also love to hear what you have working for bet 365 :). If you are happy to share then that would be legendary! My email is sam.richards2103@gmail.com

**Comment by daniherculano84** [comment]
@bigredcardinal I would like to know about that bet365 fix, please! Thank you so much!

daniherculano84@gmail.com
