### ISSUE TITLE
class undetected_chromedriver fails to initialize while using WSL

### ISSUE THREAD

**Issue by pulpocaminante** [ultrafunkamsterdam/undetected-chromedriver#1284]
```
Traceback (most recent call last):
  File "/mnt/c/Users/amnesia/test.py", line 60, in __init__
    self.driver = uc.Chrome(enable_cdp_events=True) 
  File "/home/amnesia/.local/lib/python3.10/site-packages/undetected_chromedriver/__init__.py", line 433, in __init__
    browser = subprocess.Popen(
  File "/usr/lib/python3.10/subprocess.py", line 969, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1720, in _execute_child
    and os.path.dirname(executable)
  File "/usr/lib/python3.10/posixpath.py", line 152, in dirname
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

**Comment by Po4e4ka** [comment]
I have so when i use IDE "run"

When I run from console, it's OK

**Comment by jdholtz** [comment]
@pulpocaminante do you have Chrome installed in your WSL environment? This error happens when it can’t find the Chrome browser executable
