### ISSUE TITLE
I keep getting a memory error after my script loops thru about 10 iterations, any idea what causes this error? 

### ISSUE THREAD

**Issue by disposablecarcass** [ultrafunkamsterdam/undetected-chromedriver#1305]
I am using extensions so perhaps that's part of the issue? Since uc has has an issue with driver.quit() at the moment, I'm using OS.kill to ensure all chrome windows get killed in memory. 

After it iterates thru the loop about ten times, it throws a memory error on this line : 
    driver = uc.Chrome(version_main=112, options=options )

```
 

Traceback (most recent call last):

  File "C:/Users/user/PycharmProjects/bot_2023/p_uc.py", line 1171, in <module>

    driver = uc.Chrome(version_main=112, options=options )

  File "C:\Users\user\PycharmProjects\CleanDvenv\lib\site-packages\undetected_chromedriver\__init__.py", line 419, in __init__

    desired_capabilities = options.to_capabilities()

  File "C:\Users\user\PycharmProjects\CleanD\venv\lib\site-packages\selenium\webdriver\chromium\options.py", line 166, in to_capabilities

    chrome_options["extensions"] = self.extensions

  File "C:\Users\user\PycharmProjects\CleanD\venv\lib\site-packages\selenium\webdriver\chromium\options.py", line 83, in extensions

    encoded_extensions.append(base64.b64encode(file_.read()).decode('UTF-8'))

MemoryError
```

**Comment by ggforces** [comment]
Does the "os.kill" method effectively reduce the increasing CPU/RAM usage over time when used for a long period?
