### ISSUE TITLE
error

### ISSUE THREAD

**Issue by ghost** [ultrafunkamsterdam/undetected-chromedriver#1326]
driver = uc.Chrome()
             ^^^^^^^^^^^
  File "C:\pythonProjects\api_regger\venv\Lib\site-packages\undetected_chromedriver\__init__.py", line 453, in __init__
    super(Chrome, self).__init__(
TypeError: WebDriver.__init__() got an unexpected keyword argument 'executable_path'
Exception ignored in: <function Chrome.__del__ at 0x0000019644A14900>
Traceback (most recent call last):
  File "C:\pythonProjects\api_regger\venv\Lib\site-packages\undetected_chromedriver\__init__.py", line 800, in __del__
  File "C:\pythonProjects\api_regger\venv\Lib\site-packages\undetected_chromedriver\__init__.py", line 755, in quit
OSError: [WinError 6] Неверный дескриптор

**Comment by mdmintz** [comment]
This is due to changes in ``selenium`` ``4.10.0``. More info: https://stackoverflow.com/a/76432386/7058266

There's already a duplicate ``undetected-chromedriver`` issue thread here: https://github.com/ultrafunkamsterdam/undetected-chromedriver/issues/1318

**Comment by KittyMurphy** [comment]
Thank you for the speedy response @mdmintz !

**Comment by SKnight79** [comment]
lets keep in moving...money on the table.

pip uninstall selenium
pip install selenium=4.9.1

**Comment by Maxhem2** [comment]
> lets keep in moving...money on the table.
> 
> pip uninstall selenium pip install selenium==4.9.1

I get this issue:
`raceback (most recent call last):
  File "c:\Users\JanK\Downloads\test\test.py", line 3, in <module>
    driver = uc.Chrome()
             ^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\undetected_chromedriver\__init__.py", line 453, in __init__
    super(Chrome, self).__init__(
  File "C:\Python311\Lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 84, in __init__
    super().__init__(
  File "C:\Python311\Lib\site-packages\selenium\webdriver\chromium\webdriver.py", line 101, in __init__
    self.service.start()
  File "C:\Python311\Lib\site-packages\selenium\webdriver\common\service.py", line 96, in start
    self._start_process(self._path)
  File "C:\Python311\Lib\site-packages\selenium\webdriver\common\service.py", line 197, in _start_process
    self.process = subprocess.Popen(
                   ^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\subprocess.py", line 1024, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Python311\Lib\subprocess.py", line 1509, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [WinError 216] Die Version von %1 ist mit der ausgeführten Windows-Version nicht kompatibel. Überprüfen Sie die Systeminformationen des Computers, und wenden Sie sich anschließend an den Herausgeber der Software`

**Comment by enesgorkemgenc** [comment]
https://github.com/ultrafunkamsterdam/undetected-chromedriver/pull/1339
