### ISSUE TITLE
Windows11 - cannot connect to chrome at 127.0.0.1:51957

### ISSUE THREAD

**Issue by Romhast** [ultrafunkamsterdam/undetected-chromedriver#1381]
I am using windows 11, I have deleted chrome many times, I have reinstalled the packages, but it does not work. Undetected chromedriver for windows 11 does not work, when I try the same in a different windows version, it is fine.

Error output:
```
`C:\Users\fatih\AppData\Local\Programs\Python\Python38-32\python.exe "C:\Users\fatih\OneDrive\Masaüstü\Python\discord reklam-project\main.py" 
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Users\fatih\OneDrive\Masaüstü\Python\discord reklam-project\main.py", line 1886, in openbrowser
    self.browser = uc.Chrome(options=options, user_data_dir="")
  File "C:\Users\fatih\AppData\Local\Programs\Python\Python38-32\lib\site-packages\undetected_chromedriver\__init__.py", line 443, in __init__
    super(Chrome, self).__init__(
  File "C:\Users\fatih\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 49, in __init__
    super().__init__(
  File "C:\Users\fatih\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\chromium\webdriver.py", line 54, in __init__
    super().__init__(
  File "C:\Users\fatih\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 206, in __init__
    self.start_session(capabilities)
  File "C:\Users\fatih\AppData\Local\Programs\Python\Python38-32\lib\site-packages\undetected_chromedriver\__init__.py", line 674, in start_session
    super(selenium.webdriver.chrome.webdriver.WebDriver, self).start_session(
  File "C:\Users\fatih\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 291, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
  File "C:\Users\fatih\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 346, in execute
    self.error_handler.check_response(response)
  File "C:\Users\fatih\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 245, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot connect to chrome at 127.0.0.1:51957
from session not created: This version of ChromeDriver only supports Chrome version 112
Current browser version is 114.0.5735.199
Stacktrace:
Backtrace:
	GetHandleVerifier [0x00AADCE3+50899]
	(No symbol) [0x00A3E111]
	(No symbol) [0x00945588]
	(No symbol) [0x0096570C]
	(No symbol) [0x0095F5B1]
	(No symbol) [0x0095F391]
	(No symbol) [0x00991FFE]
	(No symbol) [0x00991CEC]
	(No symbol) [0x0098B6F6]
	(No symbol) [0x00967708]
	(No symbol) [0x0096886D]
	GetHandleVerifier [0x00D13EAE+2566302]
	GetHandleVerifier [0x00D492B1+2784417]
	GetHandleVerifier [0x00D4327C+2759788]
	GetHandleVerifier [0x00B45740+672048]
	(No symbol) [0x00A48872]
	(No symbol) [0x00A441C8]
	(No symbol) [0x00A442AB]
	(No symbol) [0x00A371B7]
	BaseThreadInitThunk [0x76797D59+25]
	RtlInitializeExceptionChain [0x775AB74B+107]
	RtlClearBits [0x775AB6CF+191]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\fatih\AppData\Local\Programs\Python\Python38-32\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "C:\Users\fatih\AppData\Local\Programs\Python\Python38-32\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\fatih\OneDrive\Masaüstü\Python\discord reklam-project\main.py", line 1920, in openbrowser
    if "discord" in self.browser.current_url and "login" not in self.browser.current_url:
AttributeError: 'bool' object has no attribute 'current_url'
`
```

**Comment by montovaneli** [comment]
The error says:
This version of ChromeDriver only supports Chrome version 112 - Current browser version is 114.0.5735.199

Try to delete the folder %USERPROFILE%\AppData\Roaming\undetected_chromedriver and run the code again.

**Comment by mikehaydon** [comment]
You're a superstar @montovaneli. I spent the last 5 hours trying to figure out the problem and that solved it.

**Comment by montovaneli** [comment]
> You're a superstar @montovaneli. I spent the last 5 hours trying to figure out the problem and that solved it.

Glad to help! Believe me, I was stuck in this error for days. 😬

**Comment by ovciina** [comment]
Must say I've been using UC for last three years and never had this issue. I always have that UC has "newer" version and I simply update my chrome/chromium and it solves the issue, but this was something new. Thanks alot!

**Comment by PLFR23456** [comment]
thanks you sm @montovaneli
