### ISSUE TITLE
Can not use undetected-chromedriver with aws lambda. OSError: [Errno 38] Function not implemented

### ISSUE THREAD

**Issue by dajiangqingzhou** [ultrafunkamsterdam/undetected-chromedriver#1382]
Hello guys, I'm trying to use undetected_chromedriver on aws lambda, but some error happened.
the error:
[ERROR] OSError: [Errno 38] Function not implemented
Traceback (most recent call last):
File "/var/task/lambda_function.py", line 42, in lambda_handler
driver = create_undetected_driver()
File "/var/task/lambda_function.py", line 23, in create_undetected_driver
import undetected_chromedriver as uc
File "/opt/python/lib/python3.7/site-packages/undetected_chromedriver/init.py", line 43, in
from .patcher import IS_POSIX
File "/opt/python/lib/python3.7/site-packages/undetected_chromedriver/patcher.py", line 25, in
class Patcher(object):
File "/opt/python/lib/python3.7/site-packages/undetected_chromedriver/patcher.py", line 26, in Patcher
lock = Lock()
File "/var/lang/lib/python3.7/multiprocessing/context.py", line 67, in Lock
return Lock(ctx=self.get_context())
File "/var/lang/lib/python3.7/multiprocessing/synchronize.py", line 162, in init
SemLock.init(self, SEMAPHORE, 1, 1, ctx=ctx)
File "/var/lang/lib/python3.7/multiprocessing/synchronize.py", line 59, in init
unlink_now)

I use python3.7
selenium==3.9.1
undetect-chromedriver=3.5.0
[chrome-driver==2.31](https://chromedriver.storage.googleapis.com/index.html?path=2.37/)
[headlesschrome==v1.0.0-41](https://github.com/adieuadieu/serverless-chrome/releases/tag/v1.0.0-41)

there is my code:
```python
from selenium import webdriver
from selenium.webdriver.chrome.options import Options

chrome_dir = '/opt/chrome'
chrome_path = chrome_dir + '/headless-chromium'
chrome_driver_path = chrome_dir + '/chromedriver'

def create_undetected_driver():
import undetected_chromedriver as uc
  from undetected_chromedriver.options import ChromeOptions
  chrome_options = ChromeOptions()
  chrome_options.add_argument('--headless')
  chrome_options.add_argument('--no-sandbox')
  chrome_options.add_argument('--single-process')
  chrome_options.add_argument('--disable-dev-shm-usage')
  chrome_options.add_argument("--disable-gpu")
  chrome_options.binary_location = chrome_path
  return uc.Chrome(driver_executable_path=chrome_driver_path,
  headless=True,
  options=chrome_options,
  use_subprocess=False,
  user_data_dir="/tmp")

def lambda_handler(event, context):
  driver = create_undetected_driver()
  try:
  url = 'https://nowsecure.nl/'
  driver.get(url)
  image = driver.get_screenshot_as_base64()
  return {
  'headers': { "Content-Type": "image/png" },
  'statusCode': 200,
  'body': image,
  'isBase64Encoded': True
  }
  finally:
  driver.quit()
  
  return {
      'statusCode': 200,
      'body': json.dumps(str(event))
  }
```

**Comment by chuanyao17** [comment]
Hi, I also had the same/similar problem while testing the aws lambda. ( The code is workable on the local testing)
the error:
{
  "errorMessage": "[Errno 38] Function not implemented",
  "errorType": "OSError",
  "requestId": "",
  "stackTrace": [
    "  File \"/usr/local/lib/python3.7/importlib/__init__.py\", line 127, in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\n",
    "  File \"<frozen importlib._bootstrap>\", line 1006, in _gcd_import\n",
    "  File \"<frozen importlib._bootstrap>\", line 983, in _find_and_load\n",
    "  File \"<frozen importlib._bootstrap>\", line 967, in _find_and_load_unlocked\n",
    "  File \"<frozen importlib._bootstrap>\", line 677, in _load_unlocked\n",
    "  File \"<frozen importlib._bootstrap_external>\", line 728, in exec_module\n",
    "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
    "  File \"/function/lambda_function.py\", line 4, in <module>\n    import undetected_chromedriver as uc\n",
    "  File \"/function/undetected_chromedriver/__init__.py\", line 43, in <module>\n    from .patcher import IS_POSIX\n",
    "  File \"/function/undetected_chromedriver/patcher.py\", line 25, in <module>\n    class Patcher(object):\n",
    "  File \"/function/undetected_chromedriver/patcher.py\", line 26, in Patcher\n    lock = Lock()\n",
    "  File \"/usr/local/lib/python3.7/multiprocessing/context.py\", line 67, in Lock\n    return Lock(ctx=self.get_context())\n",
    "  File \"/usr/local/lib/python3.7/multiprocessing/synchronize.py\", line 162, in __init__\n    SemLock.__init__(self, SEMAPHORE, 1, 1, ctx=ctx)\n",
    "  File \"/usr/local/lib/python3.7/multiprocessing/synchronize.py\", line 59, in __init__\n    unlink_now)\n"
  ]
}

my dockerfile:
```
# Define custom function directory
ARG FUNCTION_DIR="/function"

FROM python:3.7.8 as build-image

# Include global arg in this stage of the build
ARG FUNCTION_DIR

# Copy function code
RUN mkdir -p ${FUNCTION_DIR}
COPY . ${FUNCTION_DIR}

# Install the function's dependencies
RUN pip install --target ${FUNCTION_DIR} selenium==4.9.1 awslambdaric undetected-chromedriver

# Use a slim version of the base Python image to reduce the final image size
FROM python:3.7.8

# Include global arg in this stage of the build
ARG FUNCTION_DIR

# Set working directory to function root directory
WORKDIR ${FUNCTION_DIR}

# Copy in the built dependencies
COPY --from=build-image ${FUNCTION_DIR} ${FUNCTION_DIR}

# Install Chrome 
RUN apt-get update && apt-get install -y wget gnupg2 && \
    wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | apt-key add - && \
    echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list && \
    apt-get update && apt-get install -y google-chrome-stable && \
    rm -rf /var/lib/apt/lists/*

# Install Chrome driver
RUN wget -q -O /tmp/chromedriver.zip https://chromedriver.storage.googleapis.com/$(curl -sS chromedriver.storage.googleapis.com/LATEST_RELEASE)/chromedriver_linux64.zip && \
    unzip /tmp/chromedriver.zip -d /usr/local/bin/ && \
    rm /tmp/chromedriver.zip

# Set runtime interface client as default command for the container runtime
ENTRYPOINT [ "/usr/local/bin/python", "-m", "awslambdaric" ]

# Pass the name of the function handler as an argument to the runtime
CMD [ "lambda_function.handler" ]
```

my code: 
```
from selenium import webdriver
from selenium.webdriver.chrome.options import Options
import selenium
import undetected_chromedriver as uc

def handler(event, context):
    
    print("selenium",selenium.__version__)
    print("test!!!!")

```
I've not done any scrapping yet and still had error importing the undetected_chromedriver.

**Comment by arik103** [comment]
I have the same issue. Any solutions to this? Thanks!

**Comment by panterozo** [comment]
Same issue here

**Comment by grantfuhr** [comment]
Ran into the same issue. I believe this is because Lambdas can't use all features of the Python `multiprocessing` standard library. According to [this article](https://aws.amazon.com/blogs/compute/parallel-processing-in-python-with-aws-lambda/) 

> Due to the Lambda execution environment not having /dev/shm (shared memory for processes) support, you can’t use multiprocessing.Queue or multiprocessing.Pool

You're probably better off running this in your own container with Fargate.

**Comment by cimentadaj** [comment]
Same issue here

**Comment by ErikCikalleshi** [comment]
Same issue also here

**Comment by arifulislamat** [comment]
### **I had similar issue:**

```bash
[ERROR] FileNotFoundError: [Errno 2] No such file or directory
Traceback (most recent call last):
  File "/var/lang/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1026, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/var/task/scrapper.py", line 15, in <module>
    import undetected_chromedriver as uc
  File "/var/lang/lib/python3.13/site-packages/undetected_chromedriver/__init__.py", line 44, in <module>
    from .patcher import IS_POSIX
  File "/var/lang/lib/python3.13/site-packages/undetected_chromedriver/patcher.py", line 27, in <module>
    class Patcher(object):
  File "/var/lang/lib/python3.13/site-packages/undetected_chromedriver/patcher.py", line 28, in Patcher
    lock = Lock()
  File "/var/lang/lib/python3.13/multiprocessing/context.py", line 68, in Lock
    return Lock(ctx=self.get_context())
  File "/var/lang/lib/python3.13/multiprocessing/synchronize.py", line 169, in __init__
    SemLock.__init__(self, SEMAPHORE, 1, 1, ctx=ctx)
  File "/var/lang/lib/python3.13/multiprocessing/synchronize.py", line 57, in __init__
    sl = self._semlock = _multiprocessing.SemLock(
```

### The Reason: 
undetected_chromedriver is try to use multiprocessing locks, which require shared memory (/dev/shm) that isn't available in the AWS Lambda environment.

### The Solution

```python
# Patch for AWS Lambda - must be done before importing undetected_chromedriver
if os.environ.get('AWS_LAMBDA_FUNCTION_NAME'):
    import multiprocessing
    # Replace the Lock with a dummy lock that doesn't use shared memory
    class DummyLock:
        def __enter__(self):
            return self
        def __exit__(self, *args):
            pass
        def acquire(self, blocking=True):
            return True
        def release(self):
            pass
    
    # Monkey patch before importing undetected_chromedriver
    multiprocessing.Lock = lambda: DummyLock()
```
