### ISSUE TITLE
Unable to fetch last version

### ISSUE THREAD

**Issue by kWAYTV** [ultrafunkamsterdam/undetected-chromedriver#1419]
Traceback (most recent call last):
  File "<dist\obf\b.py>", line 3, in <module>
  File "<frozen b>", line 298, in <module>
  File "<frozen b>", line 186, in main
  File "<frozen b>", line 141, in login
  File "<frozen src.tools.app>", line 295, in app
  File "undetected_chromedriver__init.py", line 233, in init__
  File "undetected_chromedriver\patcher.py", line 127, in auto
  File "undetected_chromedriver\patcher.py", line 148, in fetch_release_number
  File "urllib\request.py", line 216, in urlopen
  File "urllib\request.py", line 525, in open
  File "urllib\request.py", line 634, in http_response
  File "urllib\request.py", line 563, in error
  File "urllib\request.py", line 496, in _call_chain
  File "urllib\request.py", line 643, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found
[1236] Failed to execute script 'b' due to unhandled exception!

**Comment by rawandahmad698** [comment]
https://github.com/ultrafunkamsterdam/undetected-chromedriver/pull/1427 

Fixed. hope the author merges

**Comment by sSuHao** [comment]
So Chrome 115 is unable to work with UC right now? Cause my scripts will force close immediately

**Comment by rawandahmad698** [comment]
Yes. The PR fixes that issue
