### ISSUE TITLE
Error when running undetected_chromedriver on google colab

### ISSUE THREAD

**Issue by MartinMashalov** [ultrafunkamsterdam/undetected-chromedriver#1446]
Hi, 

I am attempting to run my web scraper in google colab using undetected_chromedriver. Here is my code below: 

`options = webdriver.ChromeOptions()
options.add_argument('--headless')
options.add_argument('--no-sandbox')
options.add_argument('--disable-dev-shm-usage')
options.add_argument('--disable-gpu')
driver = webdriver.Chrome(options=options)`

The error I have is this: 
AttributeError: 'Patcher' object has no attribute 'user_multiprocs'

Can anyone please direct me on how to run undetected chromedriver in google colab?

Thank you. 

Martin

**Comment by Krylanc3lo** [comment]
install from git directly : pip install git+https://www.github.com/ultrafunkamsterdam/undetected-chromedriver@master

**Comment by javakam** [comment]
The same error appears in Github Actions ...

**Comment by 0xtahaeth** [comment]
me too

**Comment by srdgtr** [comment]
For me to, have freshly installed it, also if installed from git. Only when i correct   
# self.patcher.auto(user_multiprocess = user_multi_num_procs)  to   
# self.patcher.auto(user_multi_procs = user_multi_num_procs)  in the  __init__.py  file i get it to work.

>>> driver = uc.Chrome(headless=True,use_subprocess=False)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/dongen/.local/lib/python3.11/site-packages/undetected_chromedriver/__init__.py", line 257, in __init__
    self.patcher.auto()
  File "/home/dongen/.local/lib/python3.11/site-packages/undetected_chromedriver/patcher.py", line 119, in auto
    if self.user_multi_procs:
       ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Patcher' object has no attribute 'user_multiprocs'. Did you mean: 'user_multi_procs'?

**Comment by devbrian** [comment]
> Has anyone managed to find a solution to this yet, without changing the files?

There is no solution without changing the file.. there is an error with the file.  Impossible without fixing it.

**Comment by srdgtr** [comment]
@MartinMashalov I forked it, on https://github.com/srdgtr/undetected-chromedriver/tree/master-1 so you can do do a git to there. If you don't want to change the file. But i assume, the fix wil be quickly accepted.
