### ISSUE TITLE
Doesn't work on Debian anymore

### ISSUE THREAD

**Issue by sdfgsdfgd** [ultrafunkamsterdam/undetected-chromedriver#1458]
hi, I used to keep my UC version locked at around 3.4.2 or something.... also wasn't updating Chrome, everything was peachy for a loong time-  but recently something happened at some point in the last month or week, nothing works anymore. 

It hangs up for a solid 40 seconds, nothing opens up, then I get the following error: 

Traceback (most recent call last):
  File "/home/x/Desktop/py/gpt/a_gpt.py", line 10, in <module>
    import a_gpt_server
  File "/home/x/Desktop/py/gpt/a_gpt_server.py", line 118, in <module>
    driver = uc.Chrome(options=options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/x/.local/lib/python3.11/site-packages/undetected_chromedriver/__init__.py", line 466, in __init__
    super(Chrome, self).__init__(
  File "/usr/lib/python3/dist-packages/selenium/webdriver/chrome/webdriver.py", line 49, in __init__
    super().__init__(
  File "/usr/lib/python3/dist-packages/selenium/webdriver/chromium/webdriver.py", line 54, in __init__
    super().__init__(
  File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/webdriver.py", line 206, in __init__
    self.start_session(capabilities)
  File "/home/x/.local/lib/python3.11/site-packages/undetected_chromedriver/__init__.py", line 724, in start_session
    super(selenium.webdriver.chrome.webdriver.WebDriver, self).start_session(
  File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/webdriver.py", line 291, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/webdriver.py", line 346, in execute
    self.error_handler.check_response(response)
  File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/errorhandler.py", line 245, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot connect to chrome at [127.0.0.1:42277](http://127.0.0.1:42277/)
from chrome not reachable
Stacktrace:
#0 0x5586101ea4e3 <unknown>
#1 0x55860ff19b00 <unknown>
#2 0x55860ff07436 <unknown>
#3 0x55860ff469be <unknown>
#4 0x55860ff3e884 <unknown>
#5 0x55860ff7dccc <unknown>
#6 0x55860ff7d47f <unknown>
#7 0x55860ff74de3 <unknown>
#8 0x55860ff4a2dd <unknown>
#9 0x55860ff4b34e <unknown>
#10 0x5586101aa3e4 <unknown>
#11 0x5586101ae3d7 <unknown>
#12 0x5586101b8b20 <unknown>
#13 0x5586101af023 <unknown>
#14 0x55861017d1aa <unknown>
#15 0x5586101d36b8 <unknown>
#16 0x5586101d3847 <unknown>
#17 0x5586101e3243 <unknown>
#18 0x7ff2f86773ec <unknown>

I updated to the latet 115 chrome version, and the latest UC version, and problem seems to be the same. 

Weird ._.

edit 1: in my recent tries, the stack trace now looks like this, with symbols deleted instead of unknown, wtf, is this a binary location issue or chromedriver path ? :
edit 2: it's probably more likely this is a selenium issue, since I only had UC and Chrome versions fixed, but not selenium. Maybe latest selenium is causing this specifically on debian chromedriver ?
 
Stacktrace:
#0 0x55ce6ed0f4e3 (/home/x/.local/share/undetected_chromedriver/undetected_chromedriver (deleted)+0x6d74e2)
#1 0x55ce6ea3eb00 (/home/x/.local/share/undetected_chromedriver/undetected_chromedriver (deleted)+0x406aff)
#2 0x55ce6ea2c436 (/home/x/.local/share/undetected_chromedriver/undetected_chromedriver (deleted)+0x3f4435)
#3 0x55ce6ea6b9be (/home/x/.local/share/undetected_chromedriver/undetected_chromedriver (deleted)+0x4339bd)
#4 0x55ce6ea63884 (/home/x/.local/share/undetected_chromedriver/undetected_chromedriver (deleted)+0x42b883)
#5 0x55ce6eaa2ccc (/home/x/.local/share/undetected_chromedriver/undetected_chromedriver (deleted)+0x46accb)
#6 0x55ce6eaa247f (/home/x/.local/share/undetected_chromedriver/undetected_chromedriver (deleted)+0x46a47e)
#7 0x55ce6ea99de3 (/home/x/.local/share/undetected_chromedriver/undetected_chromedriver (deleted)+0x461de2)
#8 0x55ce6ea6f2dd (/home/x/.local/share/undetected_chromedriver/undetected_chromedriver (deleted)+0x4372dc)

**Comment by JademusSreg** [comment]
I am affected by this issue as well. In my case, testing it out on google colab (default instance config) with the following installs/updates:
```
!pip install selenium
!apt-get update # to update ubuntu to correctly run apt install
!apt install chromium-chromedriver
!cp /usr/lib/chromium-browser/chromedriver /usr/bin
!pip install undetected-chromedriver
```
In this context, ubuntu update resolves an issue with the driver path on google colab specifically. Selenium works following this setup, but the requested URL host protects against automation, thus trying UC.

If anyone knows a workaround, like a known specific version of the respective components that circumvents this issue, I'd appreciate it.

**Comment by sdfgsdfgd** [comment]
@ultrafunkamsterdam  let us know if sharing any other info will help debug this  ?  it works perfectly fine on my OSX....

**Comment by sdfgsdfgd** [comment]
@JademusSreg 

OK - I found the issue in my case, I don't think it'll help you but maybe it will. 

Here's how I use and setup the script normally: 

```

env_vars = {
    'DISPLAY': ':1.0',          # THIS IS WHAT CAUSES IT TO NOT DISPLAY AT ALL LOL
    'SHELL': '/usr/bin/zsh',
    'TERM': 'xterm-256color',
    'USER': 'x'
    ...
    ... more stuff here ... 
    }
#
# ----[ 2 ]---     Setup
#
options = uc.ChromeOptions()
if platform.system() == "Darwin":  # OSX
    options.add_argument('--user-data-dir=/Users/kaano/Desktop/xx/')
    options.add_argument('--profile-directory=Default')  # Copy of Chrore/User Data/Profile 1
    options.add_argument('--disable-popup-blocking')
    options.add_argument('--new-window')
    # options.add_argument('--disable-extensions')
    # options.add_argument('--disable-gpu')
elif platform.system() == "Linux":  # Linux
    # Set environment variables for our linux (Chrome profile reuse, startup issues, all fixed with this)
    # for var, value in env_vars.items():
    #     os.environ[var] = value
    options.user_data_dir = '/home/x/Desktop/browser_home/'
    options.add_argument('--disable-extensions')
    options.add_argument('--disable-blink-features=AutomationControlled')
    options.add_argument('--disable-popup-blocking')
    options.add_argument('--disable-gpu')
    # # TODO: start deleting these one by one, check their diffs descrs w/ GPT, minimise the code.
    # # added on 28 April
    options.add_argument('--no-sandbox')
    options.add_argument('--disable-features=IsolateOrigins,site-per-process')
    # options.add_argument('--password-store=0')
    # options.binary_location = '/usr/bin/google-chrome-stable'  # seems actually unnecessary, but anyways.
    # options.binary_location = '/etc/alternatives/google-chrome'  #xx 11 Aug 2023
    options.binary_location = '/usr/bin/google-chrome'  #xx 11 Aug 2023

    #xx 11 August 2023
    # options.binary_location = "/usr/bin/chromium"
options.log_path = 'chromedriver.log'

driver = uc.Chrome(options=options)
```

as you can see, a few months ago I've decided to also pass some environment variables to my linux - I don't remember why but this helped with something at that time. I realise this is what's causing the problem now - specifically the DISPLAY: 1.0 
Removing the environment variable forwarding resolved my issues. Maybe in your case setting them will fix your problem ? lol 

The binary locations are my fix attempts from recent days, don't let them distract you I will start removing them one by one now that I've found my fix. 

Thanks team

**Comment by sdfgsdfgd** [comment]
hmm it seems it's just not working when I'm ssh connected to the Debian - and I trigger the script from the logged in user. 

The environment (env variables) is entirely different when you're remotely connected, DISPLAY and SCREEN values, term, shell, something must be interfering with it. 


try to print out the local env when you're the local user on the machine like `env` 
then set it manually inside the script when you're remotely connected, like: 
env_vars = {
    'DISPLAY': ':1.0',
    'SHELL': '/usr/bin/zsh',
    'TERM': 'xterm-256color',
    'USER': 'x',
    'WINDOWID': '0',
    # 'COLORFGBG': '15;0',
    # 'COLORTERM': 'truecolor' 
    }
    
    then apply them in your program like: 
    for var, value in env_vars.items():
         os.environ[var] = value
    
    try this, does it work for you ?

**Comment by JademusSreg** [comment]
Didn't work in my case, but I'll continue to investigate and tinker.
