### ISSUE TITLE
This version of ChromeDriver only supports Chrome version xx ++++ HTTP Error 404: Not Found

### ISSUE THREAD

**Issue by alimp5** [ultrafunkamsterdam/undetected-chromedriver#1465]
Greetings !
UC => 3.5.2
selenium => 4.11.2
selenium-wire => 5.1.0

I defined the chrome-driver path for chrome ver115 manually and didn't work.

self.driver = uc.Chrome (use_subprocess=True,  options=self.chrome_options,  version_main=self.chrome_ver,  user_data_dir=self.profile_path,  seleniumwire_options=sw_options, executable_path=self.chrome_driver_path)

We have new changes on Chrome Driver 115 and `UC` can't fetch the release number and get new chrome driver for version 115.

https://chromedriver.chromium.org/downloads

```
Current Releases

    If you are using Chrome version 115 or newer, please consult the Chrome for Testing availability dashboard. This page provides convenient JSON endpoints for specific ChromeDriver version downloading.

    For older versions of Chrome, please see below for the version of ChromeDriver that supports it.

For more information on selecting the right version of ChromeDriver, please see the Version Selection page.

ChromeDriver 114.0.5735.90
```

## Error:
```

Traceback (most recent call last):
  File "C:\ea_env\ea_games\ea_app\models.py", line 368, in save
    resp = SeleniumLogin(bot_info).run_browser()
  File "C:\ea_env\ea_games\ea_app\all_utils\selenium_login_sw.py", line 237, in run_browser
    self.driver = uc.Chrome(use_subprocess=True,  options=self.chrome_options,  version_main=self.chrome_ver,  user_data_dir=self.profile_path,  seleniumwire_options=sw_options, executable_path=self.chrome_driver_path)
  File "C:\ea_env\lib\site-packages\seleniumwire\undetected_chromedriver\webdriver.py", line 61, in __init__
    super().__init__(*args, **kwargs)
  File "C:\ea_env\lib\site-packages\undetected_chromedriver\__init__.py", line 258, in __init__
    self.patcher.auto()
  File "C:\ea_env\lib\site-packages\undetected_chromedriver\patcher.py", line 157, in auto
    release = self.fetch_release_number()
  File "C:\ea_env\lib\site-packages\undetected_chromedriver\patcher.py", line 225, in fetch_release_number
    return LooseVersion(urlopen(self.url_repo + path).read().decode())
  File "C:\Python38\lib\urllib\request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Python38\lib\urllib\request.py", line 531, in open
    response = meth(req, response)
  File "C:\Python38\lib\urllib\request.py", line 640, in http_response
    response = self.parent.error(
  File "C:\Python38\lib\urllib\request.py", line 569, in error
    return self._call_chain(*args)
  File "C:\Python38\lib\urllib\request.py", line 502, in _call_chain
    result = func(*args)
  File "C:\Python38\lib\urllib\request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
[models.py file] error: None
Traceback (most recent call last):
  File "C:\ea_env\ea_games\ea_app\models.py", line 368, in save
    resp = SeleniumLogin(bot_info).run_browser()
  File "C:\ea_env\ea_games\ea_app\all_utils\selenium_login_sw.py", line 237, in run_browser
    self.driver = uc.Chrome(use_subprocess=True,  options=self.chrome_options,  version_main=self.chrome_ver,  user_data_dir=self.profile_path,  seleniumwire_options=sw_options, executable_path=self.chrome_driver_path)
  File "C:\ea_env\lib\site-packages\seleniumwire\undetected_chromedriver\webdriver.py", line 61, in __init__
    super().__init__(*args, **kwargs)
  File "C:\ea_env\lib\site-packages\undetected_chromedriver\__init__.py", line 258, in __init__
    self.patcher.auto()
  File "C:\ea_env\lib\site-packages\undetected_chromedriver\patcher.py", line 157, in auto
    release = self.fetch_release_number()
  File "C:\ea_env\lib\site-packages\undetected_chromedriver\patcher.py", line 225, in fetch_release_number
    return LooseVersion(urlopen(self.url_repo + path).read().decode())
  File "C:\Python38\lib\urllib\request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Python38\lib\urllib\request.py", line 531, in open
    response = meth(req, response)
  File "C:\Python38\lib\urllib\request.py", line 640, in http_response
    response = self.parent.error(
  File "C:\Python38\lib\urllib\request.py", line 569, in error
    return self._call_chain(*args)
  File "C:\Python38\lib\urllib\request.py", line 502, in _call_chain
    result = func(*args)
  File "C:\Python38\lib\urllib\request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

```

**Comment by own3mall** [comment]
Have the same issue.  :(

**Comment by max32002** [comment]
use chromedriver-autoinstaller to download chromedriver,
https://github.com/max32002/python-chromedriver-autoinstaller

and assign chrome driver file to driver_executable_path argument.
`driver = uc.Chrome(driver_executable_path=chromedriver_path)`

**Comment by alimp5** [comment]
@max32002 tnx you ;X
@own3mall  , you can download a correct chrome driver for your google chrome and call it manually by `driver_executable_path=chromedriver_path`

solvedd my issue. ;X

**Comment by alimp5** [comment]
@max32002 hi again.
your solution didn't work for new versions of chrome.


```
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot connect to chrome
at 127.0.0.1:64765
from session not created: This version of ChromeDriver only supports Chrome version 113
Current browser version is 116.0.5845.97
Stacktrace:
Backtrace:
        GetHandleVerifier [0x00418893+48451]
        (No symbol) [0x003AB8A1]
        (No symbol) [0x002B5058]
        (No symbol) [0x002D5D9C]
```

**Comment by alimp5** [comment]
Tnx you MAX

**Comment by pguardiario** [comment]
Is there a trick to setting chromedriver_path? Should it be the full path? include the filename?

**Comment by alimp5** [comment]
> Is there a trick to setting chromedriver_path? Should it be the full path? include the filename?

you need full path: **`C:\......\chromedriver_v116.exe`**
