### ISSUE TITLE
Exception ignored in: <function Chrome.__del__ at 0x0000018EFF3274C0>

### ISSUE THREAD

**Issue by ggnetoo** [ultrafunkamsterdam/undetected-chromedriver#1490]
Python 3.11

When Process which open the undetected chromedriver finishes, this error is triggered:

```
Exception ignored in: <function Chrome.__del__ at 0x0000018EFF3274C0>
Traceback (most recent call last):
  File "C:\Users\Mano\AppData\Local\Programs\Python\Python311\Lib\site-packages\undetected_chromedriver\__init__.py", line 843, in __del__
    self.quit()
  File "C:\Users\Mano\AppData\Local\Programs\Python\Python311\Lib\site-packages\undetected_chromedriver\__init__.py", line 798, in quit   
    time.sleep(0.1)
OSError: [WinError 6] Identificador inválido
```

![image](https://github.com/ultrafunkamsterdam/undetected-chromedriver/assets/64275214/7852a938-968b-40ec-abfe-75f5c0fd6775)

**Comment by richard-hurley** [comment]
For me this was fixed by surrounding it with a try block. I'm not sure why:

                try:
                    time.sleep(0.1)
                except:
                    pass

**Comment by ggnetoo** [comment]
> This has been fixed in #1339

Is this the fix or the workaround?

**Comment by jdholtz** [comment]
> Is this the fix or the workaround?

This is the fix, but it has yet to be merged into the library

**Comment by Anonymous6598** [comment]
> For me this was fixed by surrounding it with a try block. I'm not sure why:
> 
> ```
>             try:
>                 time.sleep(0.1)
>             except:
>                 pass
> ```

Thank you! It helped me a lot.

**Comment by loeclos** [comment]
Has anyone actually figured out what the issue was? After adding the try/except block, does the `time.sleep(0.1)` even run anymore?
