### ISSUE TITLE
Not supported in Chrome version 116.0.5845.111

### ISSUE THREAD

**Issue by cr941131** [ultrafunkamsterdam/undetected-chromedriver#1511]
![image](https://github.com/ultrafunkamsterdam/undetected-chromedriver/assets/55981391/14c70704-3fc6-4084-a390-9a5b26a71e18)

```
Python 3.9.13 (main, Aug 25 2022, 23:51:50) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import undetected_chromedriver as uc
>>> driver = uc.Chrome(headless=True,use_subprocess=False)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\ProgramData\Anaconda3\lib\site-packages\undetected_chromedriver\__init__.py", line 466, in __init__
    super(Chrome, self).__init__(
  File "C:\ProgramData\Anaconda3\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 45, in __init__
    super().__init__(
  File "C:\ProgramData\Anaconda3\lib\site-packages\selenium\webdriver\chromium\webdriver.py", line 56, in __init__
    super().__init__(
  File "C:\ProgramData\Anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 206, in __init__
    self.start_session(capabilities)
  File "C:\ProgramData\Anaconda3\lib\site-packages\undetected_chromedriver\__init__.py", line 724, in start_session
    super(selenium.webdriver.chrome.webdriver.WebDriver, self).start_session(
  File "C:\ProgramData\Anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 290, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
  File "C:\ProgramData\Anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 345, in execute
    self.error_handler.check_response(response)
  File "C:\ProgramData\Anaconda3\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot connect to chrome at 127.0.0.1:3598
from session not created: This version of ChromeDriver only supports Chrome version 114
Current browser version is 116.0.5845.111
Stacktrace:
Backtrace:
        GetHandleVerifier [0x0121A813+48355]
        (No symbol) [0x011AC4B1]
        (No symbol) [0x010B5358]
        (No symbol) [0x010D61AC]
        (No symbol) [0x010D06B4]
        (No symbol) [0x010D0491]
        (No symbol) [0x01100C55]
        (No symbol) [0x0110093C]
        (No symbol) [0x010FA536]
        (No symbol) [0x010D82DC]
        (No symbol) [0x010D93DD]
        GetHandleVerifier [0x0147AABD+2539405]
        GetHandleVerifier [0x014BA78F+2800735]
        GetHandleVerifier [0x014B456C+2775612]
        GetHandleVerifier [0x012A51E0+616112]
        (No symbol) [0x011B5F8C]
        (No symbol) [0x011B2328]
        (No symbol) [0x011B240B]
        (No symbol) [0x011A4FF7]
        BaseThreadInitThunk [0x76E57D59+25]
        RtlInitializeExceptionChain [0x77DEB79B+107]
        RtlClearBits [0x77DEB71F+191]
```

**Comment by kohonez** [comment]
pip install undetected-chromedriver -U

**Comment by GlitchedPanda** [comment]
that doesnt work, i have the same problem

**Comment by mynoob2** [comment]
Uninstall undetected-chromedriver and install his beta release.

pip install -e git+https://github.com/jdholtz/undetected-chromedriver.git@29551bd27954dacaf09864cf77935524db642c1b#egg=undetected_chromedriver

**Comment by Hecbi** [comment]
> 

it works for me

**Comment by jdholtz** [comment]
This should be fixed in the latest version. Make sure you have undetected-chromedriver v3.5.3 downloaded

**Comment by Sheheryarbaig** [comment]
If WebdriverManager is in use, navigate to the directory located at C:/Users/abcuser/cache/selenium/chromedriver.exe. Proceed to update the chromedriver.exe file here, and also replace it with the latest version compatible with your Chrome browser.

If you are not utilizing WebdriverManager, ensure to exclusively update the chromedriver.exe file to a version that aligns with your Chrome browser.
I.E chromebrowser 116. 
FIND IT ON: https://googlechromelabs.github.io/chrome-for-testing/#stable

**Comment by grantrosse** [comment]
Latest version doesn't work for me either- and if I try to use version_main=116 I get a 404 error.

**Comment by jdholtz** [comment]
@grantrosse can you show the output of `pip show undetected-chromedriver`? Also, try creating a new virtual environment and see if you get the same issue

**Comment by grantrosse** [comment]
@jdholtz 
![image](https://github.com/ultrafunkamsterdam/undetected-chromedriver/assets/68277405/50ce8cc4-fc09-474b-be7b-c0f6fdc0b1b5)

**Comment by jdholtz** [comment]
@grantrosse try installing it in a virtual environment and see if you get the same issue. It seems to be that something is leftover from previous installations and the new changes aren’t being applied, as the 404 error was fixed in v3.5.3.

**Comment by NazikM** [comment]
I was working on Python 3.8 and it was not working, but after upgrading to 3.10 and reinstalling all libraries it's start working.

**Comment by grantrosse** [comment]
@jdholtz doing the fresh install in a virtual environment worked- I'm on python 3.9.6

**Comment by cr941131** [comment]
I update Chrome to version 117.0.5938.63（Official Build） and also update uc, it works now.
```cmd
pip install undetected-chromedriver -U
```
