### ISSUE TITLE
No Binary Location / Binary Location Must be a String - Linux

### ISSUE THREAD

**Issue by keisanng** [ultrafunkamsterdam/undetected-chromedriver#1544]
I've tried to run undetected-chromedriver installed using pip on both GitHub Codespace and Arch Linux, but this problem still occurs:

```bash
Traceback (most recent call last):
  File "/usr/local/python/3.10.8/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/local/python/3.10.8/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/workspaces/codespaces-blank/main.py", line 32, in doTest
    self.setupWebBrowser()
  File "/workspaces/codespaces-blank/main.py", line 23, in setupWebBrowser
    self.driver = uc.Chrome(options=chrome_options)
  File "/usr/local/python/3.10.8/lib/python3.10/site-packages/undetected_chromedriver/__init__.py", line 372, in __init__
    options.binary_location = (
  File "/usr/local/python/3.10.8/lib/python3.10/site-packages/selenium/webdriver/chromium/options.py", line 53, in binary_location
    raise TypeError(self.BINARY_LOCATION_ERROR)
TypeError: Binary Location Must be a String
```

**Comment by keisanng** [comment]
Thank you sir

**Comment by draicor** [comment]
Thank you for posting this mate
