### ISSUE TITLE
ImportError: cannot import name 'InvalidArgumentException' from 'selenium.common'

### ISSUE THREAD

**Issue by rainbow-catch** [ultrafunkamsterdam/undetected-chromedriver#1576]
https://stackoverflow.com/questions/71105820/undetected-chromedriver-start-error-in-python

```
[Thu Sep 21 20:51:48.352415 2023] [wsgi:error] [pid 367060:tid 367107] [client 170.64.154.53:56370] mod_wsgi (pid=367060): Failed to exec Python script file '/var/www/eprotool/wsgi.py'.

[Thu Sep 21 20:51:48.352822 2023] [wsgi:error] [pid 367060:tid 367107] [client 170.64.154.53:56370] mod_wsgi (pid=367060): Exception occurred processing WSGI script '/var/www/eprotool/wsgi.py'.

[Thu Sep 21 20:51:48.353186 2023] [wsgi:error] [pid 367060:tid 367107] [client 170.64.154.53:56370] Traceback (most recent call last):

[Thu Sep 21 20:51:48.353279 2023] [wsgi:error] [pid 367060:tid 367107] [client 170.64.154.53:56370]   File "/var/www/eprotool/wsgi.py", line 7, in <module>

[Thu Sep 21 20:51:48.353315 2023] [wsgi:error] [pid 367060:tid 367107] [client 170.64.154.53:56370]     from eprotool import app

[Thu Sep 21 20:51:48.353347 2023] [wsgi:error] [pid 367060:tid 367107] [client 170.64.154.53:56370]   File "/var/www/eprotool/eprotool/__init__.py", line 11, in <module>

[Thu Sep 21 20:51:48.353374 2023] [wsgi:error] [pid 367060:tid 367107] [client 170.64.154.53:56370]     from eprotool.api.cronjob import cronjob_auto_relist, cronjob_update_price, cronjob_update_product

[Thu Sep 21 20:51:48.353425 2023] [wsgi:error] [pid 367060:tid 367107] [client 170.64.154.53:56370]   File "/var/www/eprotool/eprotool/api/cronjob.py", line 12, in <module>

[Thu Sep 21 20:51:48.353453 2023] [wsgi:error] [pid 367060:tid 367107] [client 170.64.154.53:56370]     import undetected_chromedriver as uc

[Thu Sep 21 20:51:48.353481 2023] [wsgi:error] [pid 367060:tid 367107] [client 170.64.154.53:56370]   File "/usr/local/lib/python3.9/site-packages/undetected_chromedriver/__init__.py", line 37, in <module>

[Thu Sep 21 20:51:48.353508 2023] [wsgi:error] [pid 367060:tid 367107] [client 170.64.154.53:56370]     import selenium.webdriver.chromium.service

[Thu Sep 21 20:51:48.353536 2023] [wsgi:error] [pid 367060:tid 367107] [client 170.64.154.53:56370]   File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/chromium/service.py", line 20, in <module>

[Thu Sep 21 20:51:48.353562 2023] [wsgi:error] [pid 367060:tid 367107] [client 170.64.154.53:56370]     from selenium.common import InvalidArgumentException

[Thu Sep 21 20:51:48.353618 2023] [wsgi:error] [pid 367060:tid 367107] [client 170.64.154.53:56370] ImportError: cannot import name 'InvalidArgumentException' from 'selenium.common' 
(/usr/local/lib/python3.9/site-packages/selenium/common/__init__.py)
```

**Comment by rainbow-catch** [comment]
I found the solution🚀🚀🚀.

I modified the following file.

    /usr/local/lib/python3.9/site-packages/selenium/common/__init__.py

The origin file has the following line

    From . import exceptions
I changed this to 

    From .exceptions import *

Then it works 👌.

Thanks.
