### ISSUE TITLE
Why I am not able to work without using headless?

### ISSUE THREAD

**Issue by mdminhaz2003** [ultrafunkamsterdam/undetected-chromedriver#1603]
### It's working

```
options = ChromeOptions()
options.add_argument("--headless")
driver = Chrome(options=options, driver_executable_path='./chrome-driver')
```

### but it's not working :(
```
options = ChromeOptions()
# options.add_argument("--headless")
driver = Chrome(options=options, driver_executable_path='./chrome-driver')
```

### This is the issue
```
Traceback (most recent call last):
  File "/home/mdminhaz/PycharmProjects/Facebook-Page-Finder/scrap_possible_facebook_pages.py", line 36, in <module>
    driver = Chrome(options=options, driver_executable_path='./chrome-driver')
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mdminhaz/PycharmProjects/Facebook-Page-Finder/venv/lib/python3.11/site-packages/undetected_chromedriver/__init__.py", line 398, in __init__
    if headless or options.headless:
                   ^^^^^^^^^^^^^^^^
AttributeError: 'ChromeOptions' object has no attribute 'headless'
```

**Comment by yangex** [comment]
options = uc.ChromeOptions()
options.headless = True

 have a try

**Comment by firaa-ol** [comment]
try this
options.add_argument('--headless=new')

**Comment by nathan30** [comment]
> options = uc.ChromeOptions() options.headless = True
> 
> have a try

He didn't wan't headless.

Try options.headless = False 
or 
options.add_argument('--headless=False')

?

**Comment by dimitar-petrov** [comment]
It is due to this commit:

https://github.com/SeleniumHQ/selenium/commit/b5cfcc4f9c51dd9df9106b62971c417a0fc9a5e4

uc has to be patched not to check for ChromeOptions.headless attribute:

 Temporary ugly hack:
```py
class Options(uc.ChromeOptions):
    def __init__(self, *args, headless, **kwargs):
        self.headless = headless
        super().__init__(*args, **kwargs)
...
options = Options(headless=headless) # pass that object down to u.Chrome
```

**Comment by Berthouille** [comment]
Downgrading to Selenium 4.12.0 made it work for me.
