### ISSUE TITLE
Chrome not opening when running uc

### ISSUE THREAD

**Issue by AXL-2020** [ultrafunkamsterdam/undetected-chromedriver#1606]
`import undetected_chromedriver as uc
from selenium import webdriver

chrome_options = uc.ChromeOptions()
chrome_options.add_argument('--no-sandbox')
chrome_options.add_argument('--headless')
chrome_options.add_argument('--enable-javascript')
chrome_options.add_argument('--disable-gpu')
driver = uc.Chrome(options=chrome_options,service_args=['--quiet'])

driver.get("https://google.com")

driver.close()`
I have tried everything, and using UC just does not open the browser. As soon as I switch to the regular chrome driver instead of UC everything works fine. I have tried uninstalling and reinstalling, specifying the executable path to UC, etc. Maybe I specified the path wrong?

**Comment by cjthor** [comment]
I have the same problem

**Comment by yangex** [comment]
options.add_argument('--headless')  replace  options.headless = False
You can check the browser version and uc version

**Comment by GivenFLY** [comment]
```
>>> import undetected_chromedriver as uc
>>> driver = uc.Chrome()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\GivenFLY\AppData\Local\Programs\Python\Python38\lib\site-packages\undetected_chromedriver\__init__.py", line 398, in __init__
    if headless or options.headless:
AttributeError: 'ChromeOptions' object has no attribute 'headless'
```

Idk it's very strange

**Comment by cjthor** [comment]
> options.add_argument('--headless') replace options.headless = False You can check the browser version and uc version

thanks, now the browser can be opened. But i still cannot pass cloudflare

**Comment by AXL-2020** [comment]
> options.add_argument('--headless') replace options.headless = False You can check the browser version and uc version

That worked, appreciate it brother!
