### ISSUE TITLE
new 119 chrome crash 

### ISSUE THREAD

**Issue by LordS-Inactive** [ultrafunkamsterdam/undetected-chromedriver#1644]
Having upgraded to 119 chrome + driver 119.
crashes at driver.excecute_script, at driver.close(), with an error that dev tools are not connected. 

How to fix it?

![image](https://github.com/ultrafunkamsterdam/undetected-chromedriver/assets/79606012/e62fb533-6cf3-4e8c-b911-c839db4a0151)

Traceback (most recent call last):
  File "C:\Users\PC\Desktop\soft\Python\Money Make\Mellstroy\files\login_account.py", line 150, in <module>
    login_account(int(input('\nВыберите номер аккаунта который открыть: ')))
  File "C:\Users\PC\Desktop\soft\Python\Money Make\Mellstroy\files\login_account.py", line 120, in login_account
    driver.close()
  File "C:\Users\PC\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 455, in close
    self.execute(Command.CLOSE)
  File "C:\Users\PC\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 344, in execute
    self.error_handler.check_response(response)
  File "C:\Users\PC\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: disconnected: not connected to DevTools
  (failed to check if window was closed: disconnected: not connected to DevTools)
  (Session info: chrome=119.0.6045.106)
Stacktrace:
        GetHandleVerifier [0x002C72A3+45731]
        (No symbol) [0x00252D51]
        (No symbol) [0x0014880D]
        (No symbol) [0x00139A6D]
        (No symbol) [0x00139FFA]
        (No symbol) [0x00148C3A]
        (No symbol) [0x0012F30D]
        (No symbol) [0x001A0DF7]
        (No symbol) [0x001A0BD1]
        (No symbol) [0x00197FA3]
        (No symbol) [0x001731F6]
        (No symbol) [0x0017439D]
        GetHandleVerifier [0x005D0716+3229462]
        GetHandleVerifier [0x006184C8+3523784]
        GetHandleVerifier [0x0061214C+3498316]
        GetHandleVerifier [0x00351680+611968]
        (No symbol) [0x0025CCCC]
        (No symbol) [0x00258DF8]
        (No symbol) [0x00258F1D]
        (No symbol) [0x0024B2C7]
        BaseThreadInitThunk [0x7620FCC9+25]
        RtlGetAppContainerNamedObjectPath [0x77507C6E+286]
        RtlGetAppContainerNamedObjectPath [0x77507C3E+238]
        (No symbol) [0x00000000]

**Comment by max32002** [comment]
downgrade selenium to 4.11.2.

**Comment by VQHieu1012** [comment]
How can you run undetected_chrome with 119 version. I got this error: Message: unknown error: cannot connect to chrome at 127.0.0.1:54646
from session not created: This version of ChromeDriver only supports Chrome version 114
Current browser version is 119.0.6045.160
