### ISSUE TITLE
Launching Undetected ChromeDriver with user_data_dir when Regular Chrome Process Exists - Is This Impossible ?

### ISSUE THREAD

**Issue by joeld1** [ultrafunkamsterdam/undetected-chromedriver#1670]
I'm unable to launch Undetected ChromeDriver with `user_data_dir` defined and while a pre-existing Chrome process exists.

I was wondering if this is normal and is expected? Is there a way to circumvent this?

Here's the code:

```python
import undetected_chromedriver as uc

user_data_dir = '/Users/jd/Library/Application Support/Google/Chrome'
options.headless = False
dr = uc.Chrome(user_data_dir=user_data_dir, use_subprocess=False, options=options, port=54805)
url = 'https://app.alpaca.markets/brokerage/banking'
dr.get(url)
```

Traceback

```
pydev debugger: bytes arguments were passed to a new process creation function. Breakpoints may not work correctly.
Traceback (most recent call last):
  File "/opt/anaconda3/envs/sandbox/lib/python3.11/site-packages/selenium/webdriver/chromium/webdriver.py", line 56, in __init__
    super().__init__(
  File "/opt/anaconda3/envs/sandbox/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 205, in __init__
    self.start_session(capabilities)
  File "/opt/anaconda3/envs/sandbox/lib/python3.11/site-packages/undetected_chromedriver/__init__.py", line 724, in start_session
    super(selenium.webdriver.chrome.webdriver.WebDriver, self).start_session(
  File "/opt/anaconda3/envs/sandbox/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 289, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/sandbox/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 344, in execute
    self.error_handler.check_response(response)
  File "/opt/anaconda3/envs/sandbox/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot connect to chrome at 127.0.0.1:54805
from chrome not reachable
Stacktrace:
0   undetected_chromedriver             0x00000001025d9d28 undetected_chromedriver + 4795688
1   undetected_chromedriver             0x00000001025d12b3 undetected_chromedriver + 4760243
2   undetected_chromedriver             0x00000001021aa6bd undetected_chromedriver + 407229
3   undetected_chromedriver             0x00000001021944ba undetected_chromedriver + 316602
4   undetected_chromedriver             0x00000001021e70b3 undetected_chromedriver + 655539
5   undetected_chromedriver             0x00000001021dddd7 undetected_chromedriver + 617943
6   undetected_chromedriver             0x000000010222aafb undetected_chromedriver + 932603
7   undetected_chromedriver             0x0000000102220a73 undetected_chromedriver + 891507
8   undetected_chromedriver             0x00000001021eb143 undetected_chromedriver + 672067
9   undetected_chromedriver             0x00000001021ec31e undetected_chromedriver + 676638
10  undetected_chromedriver             0x000000010259a795 undetected_chromedriver + 4536213
11  undetected_chromedriver             0x000000010259f853 undetected_chromedriver + 4556883
12  undetected_chromedriver             0x0000000102580001 undetected_chromedriver + 4427777
13  undetected_chromedriver             0x00000001025a059d undetected_chromedriver + 4560285
14  undetected_chromedriver             0x000000010257148c undetected_chromedriver + 4367500
15  undetected_chromedriver             0x00000001025c00e8 undetected_chromedriver + 4690152
16  undetected_chromedriver             0x00000001025c029e undetected_chromedriver + 4690590
17  undetected_chromedriver             0x00000001025d0eee undetected_chromedriver + 4759278
18  libsystem_pthread.dylib             0x00007ff809c85202 _pthread_start + 99
19  libsystem_pthread.dylib             0x00007ff809c80bab thread_start + 15
```

**Comment by kim-chung-man** [comment]
#1836 refer here
