### ISSUE TITLE
Issue: Script Deleting and Redownloading undetected-chromedriver Every Run - How to Resolve?

### ISSUE THREAD

**Issue by eem1r** [ultrafunkamsterdam/undetected-chromedriver#1683]
Every time I run my script, it deletes the already downloaded 'undetected-chromedriver' and downloads it again. How can I solve this issue?

**Comment by Noodles0x00** [comment]
How does your script run undetected-chromedriver? and do you mean it as a package or the driver itself? your script should probably not be installing or installing undetected-chromedriver to begin with and if you mean the driver the script has to download a driver matching your chrome version, you can prevent chrome from updating and this should fix itself

**Comment by lolren** [comment]
just found out myself the same thing while investigating the slow start. the file at "/home/lolren/.local/share/undetected_chromedriver" deletes itself and redownloads at every run!

**Comment by lolren** [comment]
this happens if i lock the folders permissions: Traceback (most recent call last):
  File "/home/lolren/Desktop/Files/WebScrapper/Selenium_Browser.py", line 26, in <module>
    driver = uc.Chrome(headless=False, use_subprocess=False, options=options)
  File "/home/lolren/.local/lib/python3.10/site-packages/undetected_chromedriver/__init__.py", line 258, in __init__
    self.patcher.auto()
  File "/home/lolren/.local/lib/python3.10/site-packages/undetected_chromedriver/patcher.py", line 178, in auto
    self.unzip_package(self.fetch_package())
  File "/home/lolren/.local/lib/python3.10/site-packages/undetected_chromedriver/patcher.py", line 307, in unzip_package
    os.makedirs(self.zip_path, mode=0o755, exist_ok=True)
  File "/usr/lib/python3.10/os.py", line 225, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/home/lolren/.local/share/undetected_chromedriver/undetected

**Comment by pedro-peixot0** [comment]
The only solution for that is to hard code the directory to google chrome and chromedriver. 

Here is how you can do that (just don't forget to change the paths to match the actual paths in your machine):
```
from undetected_chromedriver.options import ChromeOptions
from undetected_chromedriver import Chrome

chrome_options = ChromeOptions()
driver = Chrome(
    options = chrome_options,
    version_main=119, # I also like to set google chrome version
    browser_executable_path="/opt/google/chrome/google-chrome",
    driver_executable_path="/usr/bin/chromedriver",
)
```

**Comment by Chetan11-dev** [comment]
Hi Everyone, I recommend giving Botasaurus a try. It's an Anti Detection library that will help you bypass bot detection. It also downloads the executable once. Here's how you can use it to visit https://nowsecure.nl/:

1. **Install Botasaurus**
```bash
python -m pip install botasaurus
```

2. **Bypass https://nowsecure.nl/**
```python
from botasaurus import *
from botasaurus.create_stealth_driver import create_stealth_driver

@browser(
    create_driver=create_stealth_driver(
        start_url="https://nowsecure.nl/",
    ),
)
def scrape_heading_task(driver: AntiDetectDriver, data):
    driver.prompt()
    heading = driver.text('h1')
    return heading

scrape_heading_task()    
```

![Now Secure Bypass](https://raw.githubusercontent.com/omkarcloud/botasaurus/master/images/now-secure-bypass.gif)

I suggest learning about bypassing various Cloudflare protections [here.](https://github.com/omkarcloud/botasaurus/tree/master#can-you-bypass-cloudflareimperva-challenges)

## If this has been a lifesaver for you, I would greatly appreciate a [Star here :)](https://github.com/omkarcloud/botasaurus)
