### ISSUE TITLE
"HTTP Error 404: Not Found" Showing when driver is initialised

### ISSUE THREAD

**Issue by omkmorendha** [ultrafunkamsterdam/undetected-chromedriver#1744]
For this simple code:
```

import undetected_chromedriver as uc
import time

if __name__ == '__main__':
    driver = uc.Chrome()
    
    time.sleep(20)
```

I get this error:

```
Traceback (most recent call last):
  File "/home/omkmorendha/Desktop/Work/JSX_scraping/exp.py", line 5, in <module>
    driver = uc.Chrome()
  File "/home/omkmorendha/.local/share/virtualenvs/JSX_scraping-34LRwH2V/lib/python3.10/site-packages/undetected_chromedriver/__init__.py", line 258, in __init__
    self.patcher.auto()
  File "/home/omkmorendha/.local/share/virtualenvs/JSX_scraping-34LRwH2V/lib/python3.10/site-packages/undetected_chromedriver/patcher.py", line 178, in auto
    self.unzip_package(self.fetch_package())
  File "/home/omkmorendha/.local/share/virtualenvs/JSX_scraping-34LRwH2V/lib/python3.10/site-packages/undetected_chromedriver/patcher.py", line 287, in fetch_package
    return urlretrieve(download_url)[0]
  File "/usr/lib/python3.10/urllib/request.py", line 241, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/usr/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/usr/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
```

**Comment by opemvbs** [comment]
#1743 see here

**Comment by omkmorendha** [comment]
Thank you @opemvbs
