### ISSUE TITLE
urllib.error.HTTPError: HTTP Error 404: Not Found

### ISSUE THREAD

**Issue by mominurr** [ultrafunkamsterdam/undetected-chromedriver#1754]
My code is :

# selenium chrome driver function
def selenium_driver():
    try:
        options = uc.ChromeOptions()
        options.add_argument("--excludeSwitches=enable-automation")
        options.add_argument("--disable-extensions")
        options.add_argument("--disable-infobars")
        options.add_argument("--disable-popup-blocking")
        options.add_argument("--disable-notifications")
                # options.add_argument("--ssl-verify=0")
        # options.add_argument("--ignore-certificate-errors")
        driver = uc.Chrome(options=options)
        driver.maximize_window()
        driver.set_page_load_timeout(60)
    except:
        sys.stderr = open('error.log', 'a+', encoding='utf-8')
        traceback.print_exc()
        sys.stderr.close()
        os._exit(0)
    
    return driver
    
    
    driver=selenium_driver()
    
    ERROR:
    Traceback (most recent call last):
  File "D:\W.S-PROJECT\proxy-download\test-1.py", line 42, in selenium_driver
    driver = uc.Chrome(options=options)
  File "D:\W.S-PROJECT\proxy-download\env\lib\site-packages\undetected_chromedriver\__init__.py", line 258, in __init__
    self.patcher.auto()
  File "D:\W.S-PROJECT\proxy-download\env\lib\site-packages\undetected_chromedriver\patcher.py", line 178, in auto
    self.unzip_package(self.fetch_package())
  File "D:\W.S-PROJECT\proxy-download\env\lib\site-packages\undetected_chromedriver\patcher.py", line 287, in fetch_package
    return urlretrieve(download_url)[0]
  File "C:\Users\Mominur\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 241, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "C:\Users\Mominur\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\Mominur\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 525, in open
    response = meth(req, response)
  File "C:\Users\Mominur\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 634, in http_response
    response = self.parent.error(
  File "C:\Users\Mominur\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 563, in error
    return self._call_chain(*args)
  File "C:\Users\Mominur\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 496, in _call_chain
    result = func(*args)
  File "C:\Users\Mominur\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

   
   
   Please give me solution.

**Comment by skarwech** [comment]
i have the same issue, although my code was working 2 days ago

**Comment by skarwech** [comment]
i've found a solution, https://stackoverflow.com/questions/78009548/selenium-urllib-error-httperror-http-error-404-not-found, in the second comment it tells that you should uninstall and install again uc, and it works for me,
good luck !

**Comment by igorcodigo** [comment]
For now i just upgraded the package and it no long gives that error
The comando to upgrade: 
pip install --upgrade undetected-chromedriver

**Comment by OMarcusCastro** [comment]
it worked too, Thanks!!! @igorcodigo  @skarwech

**Comment by colbyhill21** [comment]
Updating worked for me as well, thank you @skarwech @igorcodigo
