### ISSUE TITLE
WebDriverException with new undetected-chromedriver version

### ISSUE THREAD

**Issue by SubinPradeep** [ultrafunkamsterdam/undetected-chromedriver#1755]
WebDriverException                        Traceback (most recent call last)
Cell In[5], line 28
     23 # Pass the argument 1 to allow and 2 to block
     24 options.add_experimental_option(
     25     "prefs", {"profile.default_content_setting_values.notifications": 2}
     26 )
---> 28 driver = uc.Chrome(
     29     options=options,
     30     browser_executable_path="/Applications/Google Chrome.app/Contents/MacOS/Google Chrome",
     31 )
     32 driver.get("https://google.com/")
     35 wait = WebDriverWait(driver, 5)

File ~/Downloads/personalprojects/NBA Optimizer/env/lib/python3.10/site-packages/undetected_chromedriver/__init__.py:466, in Chrome.__init__(self, options, user_data_dir, driver_executable_path, browser_executable_path, port, enable_cdp_events, desired_capabilities, advanced_elements, keep_alive, log_level, headless, version_main, patcher_force_close, suppress_welcome, use_subprocess, debug, no_sandbox, user_multi_procs, **kw)
    459     self.browser_pid = browser.pid
    462 service = selenium.webdriver.chromium.service.ChromiumService(
    463     self.patcher.executable_path
    464 )
--> 466 super(Chrome, self).__init__(
    467     service=service,
    468     options=options,
    469     keep_alive=keep_alive,
    470 )
    472 self.reactor = None
...
16  undetected_chromedriver             0x00000001052a3d37 undetected_chromedriver + 4525367
17  undetected_chromedriver             0x00000001052b4763 undetected_chromedriver + 4593507
18  libsystem_pthread.dylib             0x00007ff8048f54e1 _pthread_start + 125
19  libsystem_pthread.dylib             0x00007ff8048f0f6b thread_start + 15

<img width="1228" alt="Screen Shot 2024-02-21 at 3 33 47 AM" src="https://github.com/ultrafunkamsterdam/undetected-chromedriver/assets/90484021/19f1635f-0999-438f-9803-77d6ab6bf0a1">

**Comment by NotD4v1d** [comment]
same Issue
I have the last version

**Comment by castanhas98** [comment]
Having a similar issue:

```
>>> chrome_options = Options()                                                                                                                                                                >>> chrome_options.add_argument("--disable-popup-blocking")                                                                                                                                   >>> # chrome_options.add_argument("--auto-open-devtools-for-tabs")                                                                                                                            >>> driver = uc.Chrome(options=chrome_options, headless=False, use_subprocess=True)  
Traceback (most recent call last):                                                                                                                                                              File "<stdin>", line 1, in <module>                                                                                                                                                           File "/home/francisco/git/mkm_bot/.venv/lib/python3.11/site-packages/undetected_chromedriver/__init__.py", line 466, in __init__                                                                super(Chrome, self).__init__(                                                                                                                                                               File "/home/francisco/git/mkm_bot/.venv/lib/python3.11/site-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__                                                              super().__init__(                                                                                                                                                                           File "/home/francisco/git/mkm_bot/.venv/lib/python3.11/site-packages/selenium/webdriver/chromium/webdriver.py", line 61, in __init__
    super().__init__(command_executor=executor, options=options)
  File "/home/francisco/git/mkm_bot/.venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 208, in __init__
    self.start_session(capabilities)
  File "/home/francisco/git/mkm_bot/.venv/lib/python3.11/site-packages/undetected_chromedriver/__init__.py", line 724, in start_session
    super(selenium.webdriver.chrome.webdriver.WebDriver, self).start_session(
  File "/home/francisco/git/mkm_bot/.venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 292, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]

 File "/home/francisco/git/mkm_bot/.venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "/home/francisco/git/mkm_bot/.venv/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot connect to chrome at 127.0.0.1:52577
from session not created: This version of ChromeDriver only supports Chrome version 122
Current browser version is 121.0.6167.184
Stacktrace:
#0 0x55ff710547d3 <unknown>
...
```

Seems like it requires Chrome version 122, while the latest stable release still is 121:
![image](https://github.com/ultrafunkamsterdam/undetected-chromedriver/assets/32599626/3b23257f-d120-4f09-8afd-18e478837413)

Is it fixable while still using the latest stable version?

**Comment by NotD4v1d** [comment]
Issue fixed reason:
New chrome version is out
Go update your chrome
