### ISSUE TITLE
Nodriver: Running in docker

### ISSUE THREAD

**Issue by Hillcow** [ultrafunkamsterdam/undetected-chromedriver#1782]
I have trouble trying to get nodriver/undetected-chromedriver running in docker.

Nomatter what I do, I always end up with the following error:

```
  File "/usr/local/lib/python3.12/socket.py", line 837, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
```

For example, some versions of Dockerfiles I tried:

- [Version 1](https://pastebin.com/hyZNQ0Ti) (`FROM python:latest`)
- [Version 2](https://pastebin.com/iggUc6Bm) (`FROM ultrafunk/undetected-chromedriver`)

Thankful for any hints!

Also, if someone figured out how to run nodriver with proxies that need authorization, I'd be happy to hear about it! Cheers.

**Comment by Hillcow** [comment]
Update: Managed to make it run. However, I get the following error when using too many instances at the same time:

`Failed to connect to browser` or more specific, websocket connection `failing connection with code 1006`

This is my Dockerfile:
```
FROM python:latest

WORKDIR /usr/app/src
COPY . ./

#Install Chrome
RUN wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
RUN sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
RUN apt-get -y update
RUN apt-get install -y google-chrome-stable
RUN apt-get install -yqq unzip
RUN wget -O /tmp/chromedriver.zip http://chromedriver.storage.googleapis.com/`curl -sS chromedriver.storage.googleapis.com/LATEST_RELEASE`/chromedriver_linux64.zip
RUN unzip /tmp/chromedriver.zip chromedriver -d /usr/local/bin/

# Install Python Libraries
RUN pip install -r requirements.txt

# Run
ENTRYPOINT [ "python", "-u", "./test.py"]
```x

**Comment by denysmalykhin** [comment]
> Update: Managed to make it run. However, I get the following error when using too many instances at the same time:
> 
> 
> 
> `Failed to connect to browser` or more specific, websocket connection `failing connection with code 1006`:
> 
> 
> 
> ```
> 
> 1 error catched: unhandled errors in a TaskGroup (1 sub-exception)
> 
>   + Exception Group Traceback (most recent call last):
> 
>   |   File "/usr/app/src/./test.py", line 93, in loop
> 
>   |     uc.loop().run_until_complete(start_threads(process_id))
> 
>   |   File "/usr/local/lib/python3.12/asyncio/base_events.py", line 685, in run_until_complete
> 
>   |     return future.result()
> 
>   |            ^^^^^^^^^^^^^^^
> 
>   |   File "/usr/app/src/./test.py", line 85, in start_threads
> 
>   |     async with asyncio.TaskGroup() as tg:
> 
>   |   File "/usr/local/lib/python3.12/asyncio/taskgroups.py", line 145, in __aexit__
> 
>   |     raise me from None
> 
>   | ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
> 
>   +-+---------------- 1 ----------------
> 
>     | Traceback (most recent call last):
> 
>     |   File "/usr/app/src/./test.py", line 52, in scrape
> 
>     |     browser = await uc.start(browser_args=browser_args, headless=headless)
> 
>     |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
>     |   File "/usr/local/lib/python3.12/site-packages/nodriver/core/util.py", line 74, in start
> 
>     |     return await Browser.create(config)
> 
>     |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
>     |   File "/usr/local/lib/python3.12/site-packages/nodriver/core/browser.py", line 87, in create
> 
>     |     await instance.start()
> 
>     |   File "/usr/local/lib/python3.12/site-packages/nodriver/core/browser.py", line 350, in start
> 
>     |     raise Exception(
> 
>     | Exception: 
> 
>     |                 ---------------------
> 
>     |                 Failed to connect to browser
> 
>     |                 ---------------------
> 
>     |                 One of the causes could be when you are running as root.
> 
>     |                 In that case you need to pass no_sandbox=True 
> 
>     |                 
> 
>     +------------------------------------
> 
> ```
> 
> 
> 
> This is my Dockerfile:
> 
> ```
> 
> FROM python:latest
> 
> 
> 
> WORKDIR /usr/app/src
> 
> COPY . ./
> 
> 
> 
> #Install Chrome
> 
> RUN wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
> 
> RUN sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
> 
> RUN apt-get -y update
> 
> RUN apt-get install -y google-chrome-stable
> 
> RUN apt-get install -yqq unzip
> 
> RUN wget -O /tmp/chromedriver.zip http://chromedriver.storage.googleapis.com/`curl -sS chromedriver.storage.googleapis.com/LATEST_RELEASE`/chromedriver_linux64.zip
> 
> RUN unzip /tmp/chromedriver.zip chromedriver -d /usr/local/bin/
> 
> 
> 
> # Install Python Libraries
> 
> RUN pip install -r requirements.txt
> 
> 
> 
> # Run
> 
> ENTRYPOINT [ "python", "-u", "./test.py"]
> 
> ```

Have you solved that?

**Comment by matheusrps** [comment]
Can you provide your test.py file?

**Comment by ven0ms99** [comment]
> Have you solved that?

No, I have not unfortunately. Instead I opted to go with [Ulixee Hero](https://github.com/ulixee/hero). Very easy to scale with docker. Runs flawlessly.

**Comment by jschlafdata** [comment]
yeah you just have to instantiate the browser like this:

browser = await start( headless=True,
                                     sandbox=False )

**Comment by mika-jpd** [comment]
> Can you provide your test.py file? I'm trying to solve this: `Failed to connect to browser One of the causes could be when you are running as root.`

Hey @matheusrps, did you ever manage to solve this ? 

I regularly get the same issue ! Sometimes it works and sometimes it doesn't....

**Comment by lmaddox** [comment]
> yeah you just have to instantiate the browser like this:
> 
> browser = await start( headless=True, sandbox=False )

apparently that is not sufficient. Do I need to install anything special to run this under Docker?

full code:

```
FROM python
RUN pip install --no-cache-dir --upgrade pip
RUN apt update
RUN apt install -y chromium chromium-driver chromium-sandbox
COPY    ./py/ /tmp/py
WORKDIR       /tmp/py
RUN pip install --no-cache-dir           .
RUN rm -rf    /tmp/py
ENTRYPOINT ["python", "-c", "from iaexample import main; main()"]
```

**Comment by ErikCikalleshi** [comment]
Someone managed to fix this issue?
Here my .py file
```
async def main(event, context):

    browser = await nodriver.start(
        browser_executable_path="/opt/chrome/chrome",
        sandbox=True,
        headless=True,
        browser_args=["--window-size=1920,1080", "--user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36"],
        lang="en-US"
    )
   ...
```
Here my dockerfile
```
FROM public.ecr.aws/lambda/python@sha256:bb5a7659611e5719e71ce9d1b7446bdb40b0e5be52061857f54393da6b0c98fd as build
RUN dnf install -y unzip && \
    curl -Lo "/tmp/chromedriver-linux64.zip" "https://storage.googleapis.com/chrome-for-testing-public/128.0.6613.84/linux64/chromedriver-linux64.zip" && \
    curl -Lo "/tmp/chrome-linux64.zip" "https://storage.googleapis.com/chrome-for-testing-public/128.0.6613.84/linux64/chrome-linux64.zip" && \
    unzip /tmp/chromedriver-linux64.zip -d /opt/ && \
    unzip /tmp/chrome-linux64.zip -d /opt/

FROM public.ecr.aws/lambda/python@sha256:bb5a7659611e5719e71ce9d1b7446bdb40b0e5be52061857f54393da6b0c98fd
RUN dnf install -y atk cups-libs gtk3 libXcomposite alsa-lib \
    libXcursor libXdamage libXext libXi libXrandr libXScrnSaver \
    libXtst pango at-spi2-atk libXt xorg-x11-server-Xvfb \
    xorg-x11-xauth dbus-glib dbus-glib-devel nss mesa-libgbm
RUN pip install selenium==4.23.1
RUN pip install nodriver
COPY --from=build /opt/chrome-linux64 /opt/chrome
COPY --from=build /opt/chromedriver-linux64 /opt/

COPY lambda_nodrive_google_login.py ${LAMBDA_TASK_ROOT}

CMD [ "lambda_nodrive_google_login.handler" ]
```

When i run the docker image locally i DON't get any errors - but unfortunately on AWS Lambda I get the same error:

```
{
  "errorMessage": "\n                ---------------------\n                Failed to connect to browser\n                ---------------------\n                One of the causes could be when you are running as root.\n                In that case you need to pass no_sandbox=True \n                ",
  "errorType": "Exception",
  "requestId": "a4c185eb-aea9-408f-a311-dfd0a1252e7a",
  "stackTrace": [
    "  File \"/var/task/lambda_nodrive_google_login.py\", line 100, in handler\n    return nodriver.loop().run_until_complete(main(event, context))\n",
    "  File \"/var/lang/lib/python3.12/asyncio/base_events.py\", line 687, in run_until_complete\n    return future.result()\n",
    "  File \"/var/task/lambda_nodrive_google_login.py\", line 78, in main\n    browser = await nodriver.start(\n",
    "  File \"/var/lang/lib/python3.12/site-packages/nodriver/core/util.py\", line 88, in start\n    return await Browser.create(config)\n",
    "  File \"/var/lang/lib/python3.12/site-packages/nodriver/core/browser.py\", line 91, in create\n    await instance.start()\n",
    "  File \"/var/lang/lib/python3.12/site-packages/nodriver/core/browser.py\", line 347, in start\n    raise Exception(\n"
  ]
}
```

**Comment by ven0ms99** [comment]
Just a quick hint: My solution was to not use nodriver. I switched to [Hero](https://github.com/ulixee/hero), which is perfectly optimised for Docker.

**Comment by ErikCikalleshi** [comment]
Thank you for the response :) Do you know if the package [Hero](https://github.com/ulixee/hero) works on AWS Lambda?

**Comment by OmarZidan1997** [comment]
Also having this issue.. Anyone who solved this? Headless does not work at all in linux and all the options provided to pass for the uc.start function seem outdated and does not apply to the configs...

is this framework even alive anymore ? so unfortunate that it seems pretty dead..

**Comment by Ati1707** [comment]
> Also having this issue.. Anyone who solved this? Headless does not work at all in linux and all the options provided to pass for the uc.start function seem outdated and does not apply to the configs...
> 
> is this framework even alive anymore ? so unfortunate that it seems pretty dead..

No. The fork of this is https://github.com/ultrafunkamsterdam/nodriver
and the fork of nodriver is https://github.com/stephanlensky/zendriver.

I use zendriver because it has more active development right now.

**Comment by dfe168** [comment]
turn off sandbox
`sandbox = False`

and downgrade your websockets: 
`pip install websockets==13.1`

**Comment by dfe168** [comment]
Turn off sandbox
sandbox = False

and downgrade your websockets:
pip install websockets==13.1

**Comment by Viridiana-Sol** [comment]
Had the same problem. Randomly it worked sometimes not.
I solved the problem thru a loop on zd.start .

`browser = None`
`for i in range(20):`
`    try:`
`        browser = await zd.start(no_sandbox=True,headless=True)`
`        if browser:`
`            break`       
`        await asyncio.sleep(0.5)`
`    except Exception as e:`
`        print(f"failed attempt  {e}")`
   `print("failed attempts: " + str(i))`
`if (not browser):`
`    print("failed zd.start")`
`    sys.exit()`
