### ISSUE TITLE
Error when running in Google Cloud Functions

### ISSUE THREAD

**Issue by andrewkrain** [ultrafunkamsterdam/undetected-chromedriver#1790]
Getting this error when trying to run in Google Cloud Functions:

`Exception on / [GET]
Traceback (most recent call last):
  File "/layers/google.python.pip/pip/lib/python3.9/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/layers/google.python.pip/pip/lib/python3.9/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/layers/google.python.pip/pip/lib/python3.9/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/layers/google.python.pip/pip/lib/python3.9/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/layers/google.python.pip/pip/lib/python3.9/site-packages/functions_framework/__init__.py", line 99, in view_func
    return function(request._get_current_object())
  File "/workspace/main.py", line 28, in main
    result = update_ads_campaign(**kwargs)
  File "/workspace/main.py", line 51, in update_ads_campaign
    with webdriver.Chrome(options=chrome_options, seleniumwire_options=seleniumwire_options) as driver:
  File "/layers/google.python.pip/pip/lib/python3.9/site-packages/seleniumwire/undetected_chromedriver/webdriver.py", line 61, in __init__
    super().__init__(*args, **kwargs)
  File "/layers/google.python.pip/pip/lib/python3.9/site-packages/undetected_chromedriver/__init__.py", line 372, in __init__
    options.binary_location = (
  File "/layers/google.python.pip/pip/lib/python3.9/site-packages/selenium/webdriver/chromium/options.py", line 52, in binary_location
    raise TypeError(self.BINARY_LOCATION_ERROR)
TypeError: Binary Location Must be a String`

The issue is that it cannot find Chrome binary. I tried searching for it manually, but couldn't find it either. However, it is clearly present in a temporary cache location at runtime when I run barebone [selenium](https://github.com/SeleniumHQ/selenium):

`UID        PID  PPID  C STIME TTY          TIME CMD
www-data     1     0  1 20:30 ?        00:00:01 /layers/google.python.runtime/python/bin/python3 /layers/google.python.pip/pip/bin/functions-framework
www-data     5     1  0 20:30 ?        00:00:00 /layers/google.python.runtime/python/bin/python3 /layers/google.python.pip/pip/bin/functions-framework
www-data    38     5 25 20:32 ?        00:00:00 /layers/google.python.pip/pip/lib/python3.9/site-packages/chromedriver_binary/chromedriver --port=47197
www-data    44    38 33 20:32 ?        00:00:00 /root/.cache/selenium/chrome/linux64/122.0.6261.128/chrome --allow-pre-commit-input --disable-background-networking --disable-client-side-phishing-detection --disable-default-apps --disable-dev-shm-usage --disable-gpu --disable-hang-monitor --disable-popup-blocking --disable-prompt-on-repost --disable-sync --enable-automation --enable-logging --headless --ignore-certificate-errors --log-level=0 --no-first-run --no-sandbox --no-service-autorun --password-store=basic --proxy-bypass-list=<-loopback> --proxy-server=http=127.0.0.1:24980;https=127.0.0.1:24980 --remote-debugging-port=0 --test-type=webdriver --use-mock-keychain --user-agent="Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.6167.85 Safari/537.36" --user-data-dir=/tmp/.org.chromium.Chromium.6rmWwz --window-size=1920,1080 data:,
www-data    46    44  5 20:32 ?        00:00:00 /tmp/.cache/selenium/chrome/linux64/122.0.6261.128/chrome --type=zygote --no-zygote-sandbox --no-sandbox --enable-logging --headless --log-level=0 --headless
www-data    47    44  5 20:32 ?        00:00:00 /tmp/.cache/selenium/chrome/linux64/122.0.6261.128/chrome --type=zygote --no-sandbox --enable-logging --headless --log-level=0 --headless
www-data    61    46 12 20:32 ?        00:00:00 /tmp/.cache/selenium/chrome/linux64/122.0.6261.128/chrome --type=gpu-process --no-sandbox --disable-dev-shm-usage --enable-logging --headless --log-level=0 --ozone-platform=headless --use-angle=swiftshader-webgl --headless --gpu-preferences=WAAAAAAAAAAgAAAMAAAAAAAAAAAAAAAAAABgAAAAAAA4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGAAAAAAAAAAYAAAAAAAAAAgAAAAAAAAACAAAAAAAAAAIAAAAAAAAAA== --use-gl=angle --use-angle=swiftshader-webgl --enable-logging --log-level=0 --shared-files --field-trial-handle=0,i,11476821902036531739,2795521878887053639,262144 --disable-features=PaintHolding --variations-seed-version
www-data    65    44 14 20:32 ?        00:00:00 /tmp/.cache/selenium/chrome/linux64/122.0.6261.128/chrome --type=utility --utility-sub-type=network.mojom.NetworkService --lang=en-US --service-sandbox-type=none --no-sandbox --disable-dev-shm-usage --enable-logging --ignore-certificate-errors --log-level=0 --proxy-server=http=127.0.0.1:24980;https=127.0.0.1:24980 --use-angle=swiftshader-webgl --use-gl=angle --ignore-certificate-errors --headless --enable-logging --log-level=0 --shared-files=v8_context_snapshot_data:100 --field-trial-handle=0,i,11476821902036531739,2795521878887053639,262144 --disable-features=PaintHolding --variations-seed-version
www-data    67    47 12 20:32 ?        00:00:00 /tmp/.cache/selenium/chrome/linux64/122.0.6261.128/chrome --type=renderer --headless --no-sandbox --disable-dev-shm-usage --enable-automation --enable-logging --log-level=0 --remote-debugging-port=0 --test-type=webdriver --allow-pre-commit-input --ozone-platform=headless --disable-gpu-compositing --lang=en-US --num-raster-threads=1 --renderer-client-id=4 --time-ticks-at-unix-epoch=-1710361811742831 --launch-time-ticks=131981875 --shared-files=v8_context_snapshot_data:100 --field-trial-handle=0,i,11476821902036531739,2795521878887053639,262144 --disable-features=PaintHolding --variations-seed-version
www-data    92     5  0 20:32 ?        00:00:00 /bin/sh -c ps -ef
www-data    93    92  0 20:32 ?        00:00:00 ps -ef`

How do I make it work with [undetected-chromedriver](https://github.com/ultrafunkamsterdam/undetected-chromedriver)?

**Comment by adamclasic** [comment]
unpost me

**Comment by bayramkzk** [comment]
Unalive me

**Comment by ultrafunkamsterdam** [comment]
"andrewkrain" has been deleted
