### ISSUE TITLE
[NODRIVER] Exception: Failed to connect to browser

### ISSUE THREAD

**Issue by kieuhuyhoang** [ultrafunkamsterdam/undetected-chromedriver#1896]
Hello everyone, i'm newbie,
I'm currently having trouble with this Exception for 12 hours and I still haven't been able to resolve it. Has anyone ever had this error? 
If so, have you solved it? 
What is your solution? 
Thank you.

Traceback (most recent call last):
File "SEO_propose_0.py", line 77, in <module>
File "asyncio\base_events.py", line 685, in run_until_complete File "SEO_propose_0.py", line 19, in main
File "nodriver\core\util.py", line 74, in start
File "nodriver\core\browser.py", line 87, in create
File "nodriver\core\browser.py", line 343, in start
Exception:
                    -----------------------------------------
                    Failed to connect to browser
                    -----------------------------------------
                    One of the causes could be when you are running as root.
                    In that case you need to pass no_sandbox=True
[468] Failed to execute script 'SEO_propose_0' due to unhandled exception!
Exception ignored in atexit callback: <function deconstruct_browser at 0x0000015C604EC900> Traceback (most recent call last):
File "nodriver\core\util.py", line 124, in deconstruct_browser
File "nodriver\core\browser.py", line 545, in stop
AttributeError: 'NoneType' object has no attribute 'aclose'

**Comment by Siwanta** [comment]
Hey [kieuhuyhoang](https://github.com/kieuhuyhoang), it could be that you're not correctly closing zombie processes. In terminal type: ls ps aux | grep "Chrome" 

If you see any output, it means you didn't correctly close the browsers after using them. So, do this: pkill -9 -f "Google Chrome"

Which should kill the zombies and get you good.

**Comment by MattWaller** [comment]
typically i see this when my user_data_dir gets corrupted, try changing your user data dir path.

**Comment by kieuhuyhoang** [comment]
Thank you @Siwanta and @MattWaller for giving me the solution, I'm currently busy and will update my solution when I fix it.

**Comment by hashamyounis9** [comment]
Hey @kieuhuyhoang!
hope you are doing well.
Did you get the issue resolved?

**Comment by hashamyounis9** [comment]
Hey @kieuhuyhoang!
hope you are doing well.
Did you get the issue resolved?

**Comment by TimNekk** [comment]
@hashamyounis9 I had same issue and I fixed it by turning off VPN

**Comment by hashamyounis9** [comment]
@TimNekk I am not using any vpn, running my script on an azure vm

**Comment by RafaelSoares12** [comment]
Hey @hashamyounis9 I am having the some issue. Running in a oracle cloud vps, no root, no zombies..

**Comment by keisunl1** [comment]
@RafaelSoares12 @hashamyounis9 have you found solutions? i'm not running on root, no zombies, not sure how to tackle this ...

**Comment by July250229** [comment]
I'm using macOS and just encountered a problem with zombie processes. To fix it, open the Activity Monitor and kill all Chrome processes; this should resolve the issue.

**Comment by RafaelSoares12** [comment]
> have you found solutions? i'm not running on root, no zombies, not sure how to tackle this ...

Bro my fix was move the app to pupeeter and use proxy..

**Comment by RafaelSoares12** [comment]
> > have you found solutions? i'm not running on root, no zombies, not sure how to tackle this ...
> 
> Bro my fix was move the app to pupeeter and use proxy..

I really think that is a chronique problem

**Comment by egor-ryashin** [comment]
It's random, depends on Chrome startup time, https://github.com/unixfox/nodriver/pull/1/files should help fixing that.

**Comment by tikene** [comment]
My issue was caused by user data files filling up my /tmp/ directory, for some reason those are sometimes not properly deleted. After a while the browser connection would start failing because of this. Explains why my scripts would start working again after a system restart

**Comment by dreaded369** [comment]
> It's random, depends on Chrome startup time, https://github.com/unixfox/nodriver/pull/1/files should help fixing that.

I tried your patch but it didin't work.

I'm running a loop, creating the browser at the start of each and executing await tab.close() and browser.stop() at the end of each.  

at the end of the run when after i close tht tab and stop te browser I get this messag: 
```terminated browser with pid 1441951 successfully```

I've tried killing all chrome, crome renderers, and chrome crashpad processes before each run - no luck.
I've tried releasing them after each run (tab = None, browser = None) - no change.
I've tried --no-sandbox - no change.

I don't however get the message that i would when a python script finishes that had used nodriver:
```successfully removed temp profile /tmp/uc_f86w38kj``` 
I would expect that to get deleted when the nodriver driver does, but it remains until the python script finished. I tried deleting it betwen runs - no luck.

I'm led to believe that browser.stop isn't fully stopping the browser, and that it keeps looking for existing instances.

**Comment by tikene** [comment]
> > It's random, depends on Chrome startup time, https://github.com/unixfox/nodriver/pull/1/files should help fixing that.
> 
> I tried your patch but it didin't work.
> 
> I'm running a loop, creating the browser at the start of each and executing await tab.close() and browser.stop() at the end of each.  
> 
> at the end of the run when after i close tht tab and stop te browser I get this messag: 
> ```terminated browser with pid 1441951 successfully```
> 
> I've tried killing all chrome, crome renderers, and chrome crashpad processes before each run - no luck.
> I've tried releasing them after each run (tab = None, browser = None) - no change.
> I've tried --no-sandbox - no change.
> 
> I don't however get the message that i would when a python script finishes that had used nodriver:
> ```successfully removed temp profile /tmp/uc_f86w38kj``` 
> I would expect that to get deleted when the nodriver driver does, but it remains until the python script finished. I tried deleting it betwen runs - no luck.
> 
> I'm led to believe that browser.stop isn't fully stopping the browser, and that it keeps looking for existing instances.


Does this start happening over time after many browser instances? Chrome creates more folders in /tmp/ each run not only those starting with uc_ at least for me, those would eventually fill up my /tmp/ partition which would cause the connection to fail. 
Run df -h

**Comment by egor-ryashin** [comment]
I usually kill stale chrome processes based on '--user-data-dir=[your-data-dir]' in the command line (ie `erp1       83700   0.0  0.4 444839088  65152 s011  S+   11:01AM   0:00.17  /Applications/Google Chrome.app/Contents/Frameworks/Google Chrome Framework.framework/Versions/139.0.7258.155/Helpers/Google Chrome Helper.app/Contents/MacOS/Google Chrome Helper --type=utility --utility-sub-type=network.mojom.NetworkService --lang=en-GB --service-sandbox-type=network --user-data-dir=...`)

**Comment by dreaded369** [comment]
> Does this start happening over time after many browser instances? Chrome creates more folders in /tmp/ each run not only those starting with uc_ at least for me, those would eventually fill up my /tmp/ partition which would cause the connection to fail. Run df -h

Every time. FIrst time i open a browser it's fine. close it and try and open another one - borked. sStop the python script and restart - fine again.

**Comment by harisnaseer191** [comment]
Try Deleting the Lock files (SingletonLock, SingletonCookie, SingletonSocket). This will allow starting multiple instances of Browser using nodriver.
