### ISSUE TITLE
Bug in undetected-chromedriver==3.5.4

### ISSUE THREAD

**Issue by HongLouWang** [ultrafunkamsterdam/undetected-chromedriver#1916]
undetected-chromedriver:3.5.4
Chrome:125.0.6422.142
Python:3.12.1
Selenium: 4.20.0
Windows: Version23H2(Build 22631.3593)

My code:
`
    @staticmethod
    def _setDriver(proxy = None, headless = False):

        chrome_options = uc.ChromeOptions()
        chrome_options.headless = headless
        chrome_options.add_argument("--lang=en")
        chrome_options.add_argument("--disable-popup-blocking")
        chrome_options.add_argument("--disable-infobars")
        chrome_options.add_experimental_option("prefs",{
            "credentials_enable_service": False,
            "profile.password_manager_enabled": False,
            "password_manager_enabled": False,
        })
        
        if proxy:
            proxy_options = {
                'proxy': {
                    'http': proxy,
                    'https': proxy,
                    'no_proxy': 'localhost:127.0.0.1'
                }
            }
        else:
            proxy_options = None
        
        driver = uc.Chrome(options=chrome_options, selenium_options=proxy_options)

        return driver
`
Error:
Traceback (most recent call last):
  File "W:\PinterestMonster\KeywordParser\main.py", line 37, in <module>
    answerThePublic(keys, project_name)
  File "W:\PinterestMonster\KeywordParser\main.py", line 18, in answerThePublic
    answer = Answer(project_folder, email, password, headless=headless, proxy=proxy)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "W:\PinterestMonster\KeywordParser\modules\answerThePublic.py", line 23, in __init__
    self.driver = self._setDriver(proxy, headless)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "W:\PinterestMonster\KeywordParser\modules\answerThePublic.py", line 54, in _setDriver
    driver = uc.Chrome(options=chrome_options, selenium_options=proxy_options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\undetected_chromedriver\__init__.py", line 258, in __init__
    self.patcher.auto()
  File "C:\Python312\Lib\site-packages\undetected_chromedriver\patcher.py", line 178, in auto
    self.unzip_package(self.fetch_package())
                       ^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\undetected_chromedriver\patcher.py", line 289, in fetch_package
    return urlretrieve(download_url)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\urllib\request.py", line 240, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
                            ^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\urllib\request.py", line 215, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\urllib\request.py", line 521, in open
    response = meth(req, response)
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\urllib\request.py", line 630, in http_response
    response = self.parent.error(
               ^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\urllib\request.py", line 559, in error
    return self._call_chain(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\urllib\request.py", line 492, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "C:\Python312\Lib\urllib\request.py", line 639, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

Please do not retrieve chrome from https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/126.0.6478.55/win32/chromedriver-win32.zip, https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/126.0.6478.55/win32/chromedriver-win32.zip is not an exist web page. The latest stable version of Chrome I can download is 125.0.6422.142, I can not install Chrome 126 so undetected-chromedriver==3.5.5 is not available for me.

Please fix this.

**Comment by HongLouWang** [comment]
Finally I upload to Chrome 126 and undetected-chromedriver==3.5. so the issue fixed, Thanks
