### ISSUE TITLE
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=65490): Max retries exceeded with url: /session/31240dfcb6938ff45dac0bff0c28adb4/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002976863E510>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it

### ISSUE THREAD

**Issue by mikolajstanco** [ultrafunkamsterdam/undetected-chromedriver#1923]
OS Name: Microsoft Windows 10 Professional Edition
OS Version: 19045.4529
Python Version: 3.11.9
undetected_chromedriver version: 3.5.5
-----------------------------------------ERROR------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\Mikolaj\Desktop\gen\.venv\Lib\site-packages\urllib3\connection.py", line 198, in _new_conn
    sock = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mikolaj\Desktop\gen\.venv\Lib\site-packages\urllib3\util\connection.py", line 85, in create_connection
    raise err
  File "C:\Users\Mikolaj\Desktop\gen\.venv\Lib\site-packages\urllib3\util\connection.py", line 73, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Mikolaj\Desktop\gen\.venv\Lib\site-packages\urllib3\connectionpool.py", line 793, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mikolaj\Desktop\gen\.venv\Lib\site-packages\urllib3\connectionpool.py", line 496, in _make_request
    conn.request(
  File "C:\Users\Mikolaj\Desktop\gen\.venv\Lib\site-packages\urllib3\connection.py", line 400, in request
    self.endheaders()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\http\client.py", line 1298, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\http\client.py", line 1058, in _send_output
    self.send(msg)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\http\client.py", line 996, in send
    self.connect()
  File "C:\Users\Mikolaj\Desktop\gen\.venv\Lib\site-packages\urllib3\connection.py", line 238, in connect
    self.sock = self._new_conn()
                ^^^^^^^^^^^^^^^^
  File "C:\Users\Mikolaj\Desktop\gen\.venv\Lib\site-packages\urllib3\connection.py", line 213, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x000002976863E510>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it

**Comment by supremecoding9** [comment]
Any luck with this?  I have a very similar issue.  ChatGBT thinks its a segmentation issue, which I don't entirely understand.
