### ISSUE TITLE
line 52, in binary_location     raise TypeError(self.BINARY_LOCATION_ERROR) TypeError: Binary Location Must be a String

### ISSUE THREAD

**Issue by Vimer12** [ultrafunkamsterdam/undetected-chromedriver#1927]
`from selenium import webdriver
import undetected_chromedriver

proxy = "ip_address:port"

options = webdriver.ChromeOptions() 

options.add_argument(f'--proxy-server={proxy}')

driver = undetected_chromedriver.Chrome(options=options)

driver.get("http://example.com")`

c:/Users/Rozhkov/Documents/chrome/213.py
Traceback (most recent call last):
  File "c:\Users\Rozhkov\Documents\chrome\213.py", line 10, in <module>
    driver = undetected_chromedriver.Chrome(options=options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Rozhkov\AppData\Local\Programs\Python\Python312\Lib\site-packages\undetected_chromedriver\__init__.py", line 372, in __init__
    options.binary_location = (
    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Rozhkov\AppData\Local\Programs\Python\Python312\Lib\site-packages\selenium\webdriver\chromium\options.py", line 52, in binary_location
    raise TypeError(self.BINARY_LOCATION_ERROR)
TypeError: Binary Location Must be a String
PS C:\Users\Rozhkov> 
How to fix that on windows?

**Comment by warnes** [comment]
This is also occuring on Ubuntu 22.04.4 LTS with Python 3.10.12.

**Comment by Mingyiz** [comment]
I met same issue in windows, anyone can give some suggestion

**Comment by rafaelneto2** [comment]
Também estou com este problema, alguma solução foi encontrada?

**Comment by jasongst** [comment]
Hello, I resolved the problem on Ubuntu by installing chromium with snap
`sudo snap install chromium`
