### ISSUE TITLE
Getting SSL errors both in Windows and Linux

### ISSUE THREAD

**Issue by mishka** [ultrafunkamsterdam/undetected-chromedriver#1960]
# The code
```py
import undetected_chromedriver as uc

driver = uc.Chrome()
driver.get('https://distilnetworks.com')
```
# The problem
It opens and closes immediately. Throws an SSL issue. Ignoring the SSL error do not help in any way. Keeps crashing.

# Fix I tried for Windows
I found this code piece and edited my installation accordingly: https://github.com/ultrafunkamsterdam/undetected-chromedriver/issues/955#issuecomment-2223076821

However, this did not help either. It only fixed a part of the problem? I think? But I am still battling with the SSL error.

# Windows Python Version
Python 3.12.0

# Windows 10 Error Log
```
Traceback (most recent call last):
  File "C:\Users\mishka\Desktop\stuff\testing.py", line 4, in <module>
    driver.get('https://distilnetworks.com')
  File "C:\Users\mishka\AppData\Local\Programs\Python\Python312\Lib\site-packages\undetected_chromedriver\__init__.py", line 665, in get
    return super().get(url)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\mishka\AppData\Local\Programs\Python\Python312\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 363, in get
    self.execute(Command.GET, {"url": url})
  File "C:\Users\mishka\AppData\Local\Programs\Python\Python312\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 354, in execute
    self.error_handler.check_response(response)
  File "C:\Users\mishka\AppData\Local\Programs\Python\Python312\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_SSL_UNRECOGNIZED_NAME_ALERT
  (Session info: chrome=127.0.6533.73)
Stacktrace:
        GetHandleVerifier [0x0117F653+11395]
        (No symbol) [0x0115B7A4]
        (No symbol) [0x010A1A43]
        (No symbol) [0x0109A102]
        (No symbol) [0x0108E218]
        (No symbol) [0x0108FACB]
        (No symbol) [0x0108E486]
        (No symbol) [0x0108DF50]
        (No symbol) [0x0108DD48]
        (No symbol) [0x0108C436]
        (No symbol) [0x0108C6DB]
        (No symbol) [0x010A4464]
        (No symbol) [0x01120C57]
        (No symbol) [0x0110719C]
        (No symbol) [0x011203DC]
        (No symbol) [0x01106F36]
        (No symbol) [0x010DA276]
        (No symbol) [0x010DAECD]
        GetHandleVerifier [0x01282403+1071667]
        GetHandleVerifier [0x0128C9C4+1114100]
        GetHandleVerifier [0x012854B2+1084130]
        GetHandleVerifier [0x011A013B+145259]
        (No symbol) [0x01161693]
        (No symbol) [0x0115EFB8]
        (No symbol) [0x0115F157]
        (No symbol) [0x0115842E]
        BaseThreadInitThunk [0x772E00C9+25]
        RtlGetAppContainerNamedObjectPath [0x777E7B4E+286]
        RtlGetAppContainerNamedObjectPath [0x777E7B1E+238]
```
# Ubuntu (22.04.4 LTS) Python Version
Python 3.10.12
# I haven't done that comment fix on the Ubuntu installation. I get this error out of the box upon installing and running the library!
# Ubuntu Error Log
```
Traceback (most recent call last):
  File "/home/misha/Desktop/stuff/program.py", line 4, in <module>
    driver.get('https://distilnetworks.com')
  File "/home/misha/.local/lib/python3.10/site-packages/undetected_chromedriver/__init__.py", line 665, in get
    return super().get(url)
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/webdriver.py", line 449, in get
    self.execute(Command.GET, {"url": url})
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/webdriver.py", line 440, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/errorhandler.py", line 245, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_SSL_UNRECOGNIZED_NAME_ALERT
  (Session info: chrome=127.0.6533.72)
Stacktrace:
#0 0x58c2bbe196ba <unknown>
#1 0x58c2bbae9730 <unknown>
#2 0x58c2bbae1761 <unknown>
#3 0x58c2bbad18f9 <unknown>
#4 0x58c2bbad3684 <unknown>
#5 0x58c2bbad1bc5 <unknown>
#6 0x58c2bbad1426 <unknown>
#7 0x58c2bbad131e <unknown>
#8 0x58c2bbacf64c <unknown>
#9 0x58c2bbacf9ca <unknown>
#10 0x58c2bbaec051 <unknown>
#11 0x58c2bbb7acc5 <unknown>
#12 0x58c2bbb5ba52 <unknown>
#13 0x58c2bbb7a1ca <unknown>
#14 0x58c2bbb5b7f3 <unknown>
#15 0x58c2bbb2bec9 <unknown>
#16 0x58c2bbb2c91e <unknown>
#17 0x58c2bbddf9eb <unknown>
#18 0x58c2bbde3972 <unknown>
#19 0x58c2bbdcce15 <unknown>
#20 0x58c2bbde4502 <unknown>
#21 0x58c2bbdb1d2f <unknown>
#22 0x58c2bbe08578 <unknown>
#23 0x58c2bbe08750 <unknown>
#24 0x58c2bbe1848c <unknown>
#25 0x7194f2494ac3 <unknown>
```

So what exactly is the issue, does anyone know for sure? What should I be fixing? I can't make sense of it. I feel like there's something wrong with the latest build. When I installed and ran the `undetected_chromedriver` library a while ago just to try it out, it was working flawlessly.

**Comment by mishka** [comment]
I've reinstalled the library, now I am getting this error after navigating to `https://nowsecure.nl` as shown in the GitHub readme example.

Trying this on Windows.

```
Exception ignored in: <function Chrome.__del__ at 0x0000013DC5DC20C0>
Traceback (most recent call last):
  File "C:\Users\mishka\AppData\Local\Programs\Python\Python312\Lib\site-packages\undetected_chromedriver\__init__.py", line 843, in __del__
  File "C:\Users\mishka\AppData\Local\Programs\Python\Python312\Lib\site-packages\undetected_chromedriver\__init__.py", line 798, in quit
OSError: [WinError 6] The handle is invalid
```

**Comment by mishka** [comment]
I got working on linux so I'm not gonna bother with windows anymore
