### ISSUE TITLE
Undetected chromedriver reported as trojan and deleted

### ISSUE THREAD

**Issue by shnorbluk** [ultrafunkamsterdam/undetected-chromedriver#1991]
On Windows 11, with Python 3.12.5 installed, I run the following commands:
```shell
virtualenv venv
.\venv\Scripts\activate
pip install undetected-chromedriver setuptools
python -c "import undetected_chromedriver as uc; uc.Chrome()"
```
It shows the following error
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\tmp\venv\Lib\site-packages\undetected_chromedriver\__init__.py", line 258, in __init__
    self.patcher.auto()
  File "C:\tmp\venv\Lib\site-packages\undetected_chromedriver\patcher.py", line 178, in auto
    self.unzip_package(self.fetch_package())
  File "C:\tmp\venv\Lib\site-packages\undetected_chromedriver\patcher.py", line 308, in unzip_package
    with zipfile.ZipFile(fp, mode="r") as zf:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\John\scoop\apps\python\3.12.5\Lib\zipfile\__init__.py", line 1331, in __init__
    self.fp = io.open(file, filemode)
              ^^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 22] Invalid argument: 'C:\\Users\\John\\AppData\\Local\\Temp\\tmpqm7095n8'
```
At the same time, Windows Defender, the Microsoft antivirus, reports a threat detected:
Trojan:Script/Wacatac:B!ml in file: C:\Users\John\AppData\Local\Temp\tmpqm7095n8
That's why it had deleted the file and unzip_package could not read it.
I don't undestand! I was using UC many days before without any issue, and this one came suddenly. I would like to point out that I have had this alert frequently in the past, but it also disappeared on its own.
Of course I could tell Windows Defender to autorize on my computer, but I don't want to have to tell other users to do the same thing.
Has anyone encountered this problem before? Thank you!

**Comment by fb-15** [comment]
The same thing happened to me a few days ago. I had to uninstall UC and use the regular webdriver until they fix it. I didn't want to take any risks

**Comment by NeedleFung** [comment]
Currently I met this problem too, so risky to turn off Window Defender to temporarily allow it

**Comment by TollenYT** [comment]
same here

**Comment by zwj808** [comment]
Got the same problem with following error message. 
```python
Traceback (most recent call last):
  File "D:\<<<PLACEHOLDER OF MY EMAIL>>>\OneDrive\Coding\Python Exercise\extract_url_from_txt\get_info.py", line 73, in <module>
    driver = uc.Chrome(options = uc_options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\<<<PLACEHOLDER OF MY USERNAME>>>\AppData\Local\Programs\Python\Python312\Lib\site-packages\undetected_chromedriver\__init__.py", line 258, in __init__
    self.patcher.auto()
  File "C:\Users\<<<PLACEHOLDER OF MY USERNAME>>>\AppData\Local\Programs\Python\Python312\Lib\site-packages\undetected_chromedriver\patcher.py", line 178, in auto
    self.unzip_package(self.fetch_package())
  File "C:\Users\<<<PLACEHOLDER OF MY USERNAME>>>\AppData\Local\Programs\Python\Python312\Lib\site-packages\undetected_chromedriver\patcher.py", line 308, in unzip_package
    with zipfile.ZipFile(fp, mode="r") as zf:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\<<<PLACEHOLDER OF MY USERNAME>>>\AppData\Local\Programs\Python\Python312\Lib\zipfile\__init__.py", line 1323, in __init__
    self.fp = io.open(file, filemode)
              ^^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 22] Invalid argument: 'C:\\Users\\Public\\Documents\\Wondershare\\CreatorTemp\\tmp5fj6p6nb'
``` 
Meanwhile, the Windows Defender has detected this threat.
![image](https://github.com/user-attachments/assets/8e0143f1-77a8-4204-adcb-b73bd7f34b78)

Apparently, whatever unziped was removed immediately by Windows defender.
