### ISSUE TITLE
multithreading uc error

### ISSUE THREAD

**Issue by dropox1** [ultrafunkamsterdam/undetected-chromedriver#1997]
I can't do multithreading, I constantly get errors when

`def main(thread):

    seleniumwire_options = {
        'proxy': {
            'http': proxy_url,
            'https': proxy_url,
        }
    }

    options = uc.ChromeOptions()
    options.add_argument("--disable-gpu")
    options.add_argument("--no-sandbox")
    options.add_argument("--autoplay-policy=no-user-gesture-required")
    options.add_argument("--mute-audio")
    options.add_argument("--disable-background-networking")
    options.add_argument("--disable-client-side-phishing-detection")
    options.add_argument("--disable-sync")
    options.add_argument("--disable-component-update")
    options.add_argument("--process-per-site")
    options.add_argument("--disable-plugins")
    options.add_argument("--disable-background-timer-throttling")
    options.add_argument("--disable-renderer-backgrounding")
    options.add_argument("--disable-features=PreloadMediaEngagementData")
    options.add_argument("--enable-low-end-device-mode")
    options.add_argument('--ignore-certificate-errors') 
    #options.add_argument("--headless=new")

    options.binary_location = r"C:\Program Files\Google\Chrome\Application\chrome.exe"

    driver = uc.Chrome(seleniumwire_options=seleniumwire_options,
                       options=options,
                       no_sandbox=False,
                       user_multi_procs=True,
                       use_subprocess=False
                       )
                       
      ..............
                       
                       

if __name__ == '__main__':
    mp.set_start_method('spawn', force=True) 

    p = Pool(processes=2)
    p.map(main, range(2))
`
error:

Traceback (most recent call last): File "C:\Users\vital\PycharmProjects\\test4.py", line 485, in <module> p.map(main, range(2)) File "C:\Users \vital\AppData\Local\Programs\Python\Python312\Lib\multiprocessing\pool.py", line 367, in map return self._map_async(func, iterable, mapstar, chunksize).get() ^^^^^^ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ^File "C:\Users\vital\AppData\Local\Programs\Python\Python312\Lib\multiprocessing\pool.py", line 774, in get raise self._value File "C:\Users\vital\AppData\Local\Programs \Python\Python312\Lib\multiprocessing\pool.py", line 125, in worker result = (True, func(*args, **kwds)) ^^^^^^^^^^^^^^^^^ ^^^ File "C:\Users\vital\AppData\Local\Programs\Python\Python312\Lib\multiprocessing\pool.py", line 48, in mapstar return list(map(*args)) ^^^^^ ^^^^^^^^^^^ File "C:\Users\vital\PycharmProjects\\test4.py", line 94, in main driver = uc.Chrome(seleniumwire_options=seleniumwire_options, ^^^^^^^^^^^^^^^^^^ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\vital\PycharmProjects\\PycharmProjects\Lib \site-packages\seleniumwire\undetected_chromedriver\webdriver.py", line 61, in __init__ super().__init__(*args, **kwargs) File "C:\Users\vital\PycharmProjects\\PycharmProjects\Lib\site-packages\undetected_chromedriver\__init__.py", line 258, in __init__ self.patcher.auto() File "C:\Users\vital\PycharmProjects\\PycharmProjects\Lib\site-packages\undetected_chromedriver\patcher.py", line 138, in auto list(map(lambda f: f.unlink(), files)) File "C:\Users\vital\PycharmProjects\\PycharmProjects\Lib\site-packages\undetected_chromedriver\patcher.py", line 138, in <lambda> list(map(lambda f: f.unlink(), files)) ^^^^^^^^^^ File "C:\Users\vital\AppData\Local\Programs\Python\Python312\Lib\pathlib.py", line 1343, in unlink os.unlink(self) PermissionError: [WinError 5] Permission denied: 'C:\\Users\\vital\\appdata\\roaming\\undetected_chromedriver\\undetected\\chromedriver-win32'

and when user_multi_procs=False only one instance of the browser is launched

**Comment by Deswer60871** [comment]
> I can't do multithreading, I constantly get errors when
> 
> `def main(thread):
> 
> ```
> seleniumwire_options = {
>     'proxy': {
>         'http': proxy_url,
>         'https': proxy_url,
>     }
> }
> 
> options = uc.ChromeOptions()
> options.add_argument("--disable-gpu")
> options.add_argument("--no-sandbox")
> options.add_argument("--autoplay-policy=no-user-gesture-required")
> options.add_argument("--mute-audio")
> options.add_argument("--disable-background-networking")
> options.add_argument("--disable-client-side-phishing-detection")
> options.add_argument("--disable-sync")
> options.add_argument("--disable-component-update")
> options.add_argument("--process-per-site")
> options.add_argument("--disable-plugins")
> options.add_argument("--disable-background-timer-throttling")
> options.add_argument("--disable-renderer-backgrounding")
> options.add_argument("--disable-features=PreloadMediaEngagementData")
> options.add_argument("--enable-low-end-device-mode")
> options.add_argument('--ignore-certificate-errors') 
> #options.add_argument("--headless=new")
> 
> 
> 
> 
> options.binary_location = r"C:\Program Files\Google\Chrome\Application\chrome.exe"
> 
> 
> driver = uc.Chrome(seleniumwire_options=seleniumwire_options,
>                    options=options,
>                    no_sandbox=False,
>                    user_multi_procs=True,
>                    use_subprocess=False
>                    )
>                    
>   ..............
> ```
> 
> if **name** == '**main**': mp.set_start_method('spawn', force=True)
> 
> ```
> p = Pool(processes=2)
> p.map(main, range(2))
> ```
> 
> ` error:
> 
> Traceback (most recent call last): File "C:\Users\vital\PycharmProjects\test4.py", line 485, in p.map(main, range(2)) File "C:\Users \vital\AppData\Local\Programs\Python\Python312\Lib\multiprocessing\pool.py", line 367, in map return self._map_async(func, iterable, mapstar, chunksize).get() ^^^^^^ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ^File "C:\Users\vital\AppData\Local\Programs\Python\Python312\Lib\multiprocessing\pool.py", line 774, in get raise self._value File "C:\Users\vital\AppData\Local\Programs \Python\Python312\Lib\multiprocessing\pool.py", line 125, in worker result = (True, func(*args, **kwds)) ^^^^^^^^^^^^^^^^^ ^^^ File "C:\Users\vital\AppData\Local\Programs\Python\Python312\Lib\multiprocessing\pool.py", line 48, in mapstar return list(map(*args)) ^^^^^ ^^^^^^^^^^^ File "C:\Users\vital\PycharmProjects\test4.py", line 94, in main driver = uc.Chrome(seleniumwire_options=seleniumwire_options, ^^^^^^^^^^^^^^^^^^ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\vital\PycharmProjects\PycharmProjects\Lib \site-packages\seleniumwire\undetected_chromedriver\webdriver.py", line 61, in **init** super().**init**(*args, **kwargs) File "C:\Users\vital\PycharmProjects\PycharmProjects\Lib\site-packages\undetected_chromedriver__init__.py", line 258, in **init** self.patcher.auto() File "C:\Users\vital\PycharmProjects\PycharmProjects\Lib\site-packages\undetected_chromedriver\patcher.py", line 138, in auto list(map(lambda f: f.unlink(), files)) File "C:\Users\vital\PycharmProjects\PycharmProjects\Lib\site-packages\undetected_chromedriver\patcher.py", line 138, in list(map(lambda f: f.unlink(), files)) ^^^^^^^^^^ File "C:\Users\vital\AppData\Local\Programs\Python\Python312\Lib\pathlib.py", line 1343, in unlink os.unlink(self) PermissionError: [WinError 5] Permission denied: 'C:\Users\vital\appdata\roaming\undetected_chromedriver\undetected\chromedriver-win32'
> 
> and when user_multi_procs=False only one instance of the browser is launched

I think the problem is somewhere with the profiles, I did it so that I created more profiles and made a special function for them to start and it worked

**Comment by dropox1** [comment]
> > Я не могу выполнять многопоточность, я постоянно получаю ошибки, когда
> > `def main(поток):
> > ```
> > seleniumwire_options = {
> >     'proxy': {
> >         'http': proxy_url,
> >         'https': proxy_url,
> >     }
> > }
> > 
> > options = uc.ChromeOptions()
> > options.add_argument("--disable-gpu")
> > options.add_argument("--no-sandbox")
> > options.add_argument("--autoplay-policy=no-user-gesture-required")
> > options.add_argument("--mute-audio")
> > options.add_argument("--disable-background-networking")
> > options.add_argument("--disable-client-side-phishing-detection")
> > options.add_argument("--disable-sync")
> > options.add_argument("--disable-component-update")
> > options.add_argument("--process-per-site")
> > options.add_argument("--disable-plugins")
> > options.add_argument("--disable-background-timer-throttling")
> > options.add_argument("--disable-renderer-backgrounding")
> > options.add_argument("--disable-features=PreloadMediaEngagementData")
> > options.add_argument("--enable-low-end-device-mode")
> > options.add_argument('--ignore-certificate-errors') 
> > #options.add_argument("--headless=new")
> > 
> > 
> > 
> > 
> > options.binary_location = r"C:\Program Files\Google\Chrome\Application\chrome.exe"
> > 
> > 
> > driver = uc.Chrome(seleniumwire_options=seleniumwire_options,
> >                    options=options,
> >                    no_sandbox=False,
> >                    user_multi_procs=True,
> >                    use_subprocess=False
> >                    )
> >                    
> >   ..............
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > if **name** == '**main**': mp.set_start_method('spawn', force=True)
> > ```
> > p = Pool(processes=2)
> > p.map(main, range(2))
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ` error:
> > Traceback (most recent call last): File "C:\Users\vital\PycharmProjects\test4.py", line 485, in p.map(main, range(2)) File "C:\Users \vital\AppData\Local\Programs\Python\Python312\Lib\multiprocessing\pool.py", line 367, in map return self._map_async(func, iterable, mapstar, chunksize).get() ^^^^^^ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ^File "C:\Users\vital\AppData\Local\Programs\Python\Python312\Lib\multiprocessing\pool.py", line 774, in get raise self._value File "C:\Users\vital\AppData\Local\Programs \Python\Python312\Lib\multiprocessing\pool.py", line 125, in worker result = (True, func(*args, **kwds)) ^^^^^^^^^^^^^^^^^ ^^^ File "C:\Users\vital\AppData\Local\Programs\Python\Python312\Lib\multiprocessing\pool.py", line 48, in mapstar return list(map(*args)) ^^^^^ ^^^^^^^^^^^ File "C:\Users\vital\PycharmProjects\test4.py", line 94, in main driver = uc.Chrome(seleniumwire_options=seleniumwire_options, ^^^^^^^^^^^^^^^^^^ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\vital\PycharmProjects\PycharmProjects\Lib \site-packages\seleniumwire\undetected_chromedriver\webdriver.py", line 61, in **init** super().**init**(*args, **kwargs) File "C:\Users\vital\PycharmProjects\PycharmProjects\Lib\site-packages\undetected_chromedriver__init__.py", line 258, in **init** self.patcher.auto() File "C:\Users\vital\PycharmProjects\PycharmProjects\Lib\site-packages\undetected_chromedriver\patcher.py", line 138, in auto list(map(lambda f: f.unlink(), files)) File "C:\Users\vital\PycharmProjects\PycharmProjects\Lib\site-packages\undetected_chromedriver\patcher.py", line 138, in list(map(lambda f: f.unlink(), files)) ^^^^^^^^^^ File "C:\Users\vital\AppData\Local\Programs\Python\Python312\Lib\pathlib.py", line 1343, in unlink os.unlink(self) PermissionError: [WinError 5] Permission denied: 'C:\Users\vital\appdata\roaming\undetected_chromedriver\undetected\chromedriver-win32'
> > and when user_multi_procs=False only one instance of the browser is launched
> 
> I think the problem is somewhere with the profiles, I did it so that I created more profiles and made a special function for them to start and it worked

thanks, I'll try that later

**Comment by boludoz** [comment]
https://docs.python.org/3/library/asyncio-task.html#asyncio.run_coroutine_threadsafe

I use it with the method, running 2 to 3 drivers at the same time with their own daemon and I have not had any kind of problem, each one takes care of its own core.
