### ISSUE TITLE
AttributeError: 'Chrome' object has no attribute 'keep_user_data_dir'

### ISSUE THREAD

**Issue by oddmario** [ultrafunkamsterdam/undetected-chromedriver#201]
Hello,

First of all, I've noticed a lot of issues with undetected-chromedriver when it comes to multi-threading (like starting multiple `uc` instances at once from multiple threads can't work because they all share the same patched executable file)

and now I'm getting the error shown below randomly (usually when I call `driver.quit()`) for no reason
![image](https://user-images.githubusercontent.com/32080032/120909578-a1ec7180-c676-11eb-92ef-339e43377bb9.png)

It's worth mentioning that I'm not playing with anything related to the user data directory at all.

I tried modifying the line https://github.com/ultrafunkamsterdam/undetected-chromedriver/blob/e598e1ca1bfcf9f9347cc64afacc05fe9c8c7df1/undetected_chromedriver/v2.py#L180 to `user_data_dir, language, keep_user_data_dir = None, None, False` but that didn't help

**Comment by ultrafunkamsterdam** [comment]
I'm aware of that. Working on a fix. Regarding multithreading I've got no issues starting multiple (only closing them, same line as you've got).

**Comment by oddmario** [comment]
> I'm aware of that. Working on a fix. Regarding multithreading I've got no issues starting multiple (only closing them, same line as you've got).

Starting multiple here throws this error **sometimes**:
```
  File "C:\Users\Administrator\Desktop\test\bot.py", line 18, in thread
    driver = uc.Chrome()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\undetected_chromedriver\v2.py", line 277, in __init__
    super().__init__(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 73, in __init__
    self.service.start()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\common\service.py", line 86, in start
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: 'chromedriver.exe' executable may have wrong permissions. Please see https://sites.google.com/a/chromium.org/chromedriver/home
```

and I think it happens when one of the threads exits because they have nothing else to do (even if there's no `driver.quit()`)

**Comment by plutocow** [comment]
Did you manage to get this working? I'm also running into this while trying to deploy to Heroku, no options enabled other than "--headless"

**Comment by oddmario** [comment]
> Did you manage to get this working? I'm also running into this while trying to deploy to Heroku, no options enabled other than "--headless"

No, it seems the maintainer of this project has been inactive since their reply to this issue.
I ended up making my own patched chromedriver

**Comment by liuqi0725** [comment]
Hello, I have the same mistake. But I don't add any parameters to my options, I just encapsulate the content in a class.

```python

def browser(self) -> undetected_chromedriver.v2.Chrome:
    import undetected_chromedriver.v2 as uc
    return uc.Chrome(options=self.__options)

```


```phthon
  File "/python3.8/site-packages/undetected_chromedriver/v2.py", line 211, in __init__
    if options.user_data_dir:
AttributeError: 'Options' object has no attribute 'user_data_dir'
Exception ignored in: <function Chrome.__del__ at 0x7f9fcf5d2dc0>
Traceback (most recent call last):
  File "/python3.8/site-packages/undetected_chromedriver/v2.py", line 597, in __del__
  File "/python3.8/site-packages/undetected_chromedriver/v2.py", line 576, in quit
AttributeError: 'Chrome' object has no attribute 'keep_user_data_dir'
```

```python
if hasattr(self, 'keep_user_data_dir') \
    and not self.keep_user_data_dir \
        or self.keep_user_data_dir is False:
    ....

```

**Comment by hassanseoul123** [comment]
> I ended up making my own patched chromedriver

can You share that please?
