### ISSUE TITLE
[NODRIVER] websockets=14.0 breaks browser start

### ISSUE THREAD

**Issue by rhjsong** [ultrafunkamsterdam/undetected-chromedriver#2069]
Got the following exception using websockets=14.0. Downgrading websockets to 13.1 fixes the issue.

```
Traceback (most recent call last):
  File "/handler.py", line 341, in <module>
    main()
  File "/handler.py", line 224, in main
    browser = await uc.start(headless=False)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/nodriver/core/util.py", line 96, in start
    return await Browser.create(config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/nodriver/core/browser.py", line 91, in create
    await instance.start()
  File "/usr/local/lib/python3.12/site-packages/nodriver/core/browser.py", line 394, in start
    await self.connection.send(cdp.target.set_discover_targets(discover=True))
  File "/usr/local/lib/python3.12/site-packages/nodriver/core/connection.py", line 412, in send
    if not self.websocket or self.closed:
                             ^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/nodriver/core/connection.py", line 368, in __getattr__
    return getattr(self.target, item)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'closed'
```

**Comment by YeiSimon** [comment]
I got the same issue here , when I started my initialize my browser?

**Comment by cora527** [comment]
that is good! thank u ,it solve my problme!!

**Comment by tomdav999** [comment]
smh, wasted half a day thinking I was doing something wrong.
