### ISSUE TITLE
Extensions and Selenium-wire not working

### ISSUE THREAD

**Issue by monkylovesfauci** [ultrafunkamsterdam/undetected-chromedriver#207]
Im trying to use proxies with user:pass however two ways to do that are with selenium wire and an extension. Extensions dont load and selenium-wire options dont work.

**Comment by urasoguz** [comment]
did you solve the problem of adding extensions, man ?

**Comment by monkylovesfauci** [comment]
> did you solve the problem of adding extensions, man ?

Nope I dont think either are supported

**Comment by pawanpaudel93** [comment]
@urasoguz @monkylovesfauci

for v1,
import seleniumwire.undetected_chromedriver as uc

for v2,
import seleniumwire.undetected_chromedriver.v2 as uc

**Comment by pawanpaudel93** [comment]
@urasoguz @monkylovesfauci

Extension works only when if you run the chromedriver on a virtual display as Xvfb (Check here [xvfbwrapper](https://github.com/cgoldberg/xvfbwrapper) and also the seleniumwire works with undetected_chromedriver if you import it correctly.

for v1,
import seleniumwire.undetected_chromedriver as uc

for v2,
import seleniumwire.undetected_chromedriver.v2 as uc

**Comment by urasoguz** [comment]
> @urasoguz @monkylovesfauci
> 
> Extension works only when if you run the chromedriver on a virtual display as Xvfb (Check here [xvfbwrapper](https://github.com/cgoldberg/xvfbwrapper)) if you are trying to run headless and also the seleniumwire works with undetected_chromedriver if you import it correctly.
> 
> for v1,
> import seleniumwire.undetected_chromedriver as uc
> 
> for v2,
> import seleniumwire.undetected_chromedriver.v2 as uc

is there a sample code for what you're saying?

**Comment by urasoguz** [comment]
> > did you solve the problem of adding extensions, man ?
> 
> Nope I dont think either are supported

my brother solved this problem as crx, not as a plugin package, installing the plugin seamlessly
https://intoli.com/blog/chrome-extensions-with-selenium/
`options.add_argument('--load-extension=chrome-extension')
`

**Comment by pawanpaudel93** [comment]
@urasoguz @monkylovesfauci 

```python
def set_proxy(PROXY_HOST, PROXY_PORT, PROXY_USER, PROXY_PASS, options):
    manifest_json = """
    {
        "version": "1.0.0",
        "manifest_version": 2,
        "name": "Chrome Proxy",
        "permissions": [
            "proxy",
            "tabs",
            "unlimitedStorage",
            "storage",
            "<all_urls>",
            "webRequest",
            "webRequestBlocking"
        ],
        "background": {
            "scripts": ["background.js"]
        },
        "minimum_chrome_version":"22.0.0"
    }
    """

    background_js = """
    var config = {
            mode: "fixed_servers",
            rules: {
            singleProxy: {
                scheme: "http",
                host: "%s",
                port: parseInt(%s)
            },
            bypassList: ["localhost"]
            }
        };
    chrome.proxy.settings.set({value: config, scope: "regular"}, function() {});
    function callbackFn(details) {
        return {
            authCredentials: {
                username: "%s",
                password: "%s"
            }
        };
    }
    chrome.webRequest.onAuthRequired.addListener(
                callbackFn,
                {urls: ["<all_urls>"]},
                ['blocking']
    );
    """ % (PROXY_HOST, PROXY_PORT, PROXY_USER, PROXY_PASS)
    pluginfile = 'proxy_auth_plugin.zip'

    with zipfile.ZipFile(pluginfile, 'w') as zp:
        zp.writestr("manifest.json", manifest_json)
        zp.writestr("background.js", background_js)
    options.add_extension(pluginfile)
    return options
```

Modify this as per your need. Install Xvfb (apt-get install Xvfb) and https://github.com/cgoldberg/xvfbwrapper. Extensions doesnot work with headless mode so you need Xvfb to run the extension with chromedriver in server without setting headless mode in options.

**Comment by pawanpaudel93** [comment]
> > @urasoguz @monkylovesfauci
> > Extension works only when if you run the chromedriver on a virtual display as Xvfb (Check here [xvfbwrapper](https://github.com/cgoldberg/xvfbwrapper)) if you are trying to run headless and also the seleniumwire works with undetected_chromedriver if you import it correctly.
> > for v1,
> > import seleniumwire.undetected_chromedriver as uc
> > for v2,
> > import seleniumwire.undetected_chromedriver.v2 as uc
> 
> is there a sample code for what you're saying?

@urasoguz Please read the selenium-wire readme for proxy and bot-detection section ([proxy section](https://github.com/wkeeling/selenium-wire#proxies) and [bot detection section](https://github.com/wkeeling/selenium-wire#bot-detection)). You will be clear. I have been using selenium-wire unison with undetected-chromedriver and proxies successful.

**Comment by dimitrivisser** [comment]
> Im trying to use proxies with user:pass however two ways to do that are with selenium wire and an extension. Extensions dont load and selenium-wire options dont work.

I had the same problem, my proxies had a username and password. I used 3proxy on a VPS to make a forwarding system. I now have proxies with IP authentication on that VPS, but everything is redirected to the proxies that are using username/passwd. 
I am not sure if this is the right place to explain and post cfg files about proxy software. But I can try. It's not exactly what you asked, but it does work fine.

**Comment by pawanpaudel93** [comment]
@dimitrivisser you can use proxy with user/password authentication with selenium-wire and also with the extension running chromedriver on the virtual display.

**Comment by pawanpaudel93** [comment]
@monkylovesfauci @dimitrivisser @urasoguz 

Replace the proxyUsername, proxyPassword, proxyHost and proxyPort with your proxy config.

### With selenium-wire and undetected-chromedriver:

**For v1,**

```python

import seleniumwire.undetected_chromedriver as uc

seleniumwire_options = {
    'disable_capture': True,
    'proxy': {
        'http': 'http://proxyUsername:proxyPassword@proxyHost.io:proxyPort',
        'https': 'https://proxyUsername:proxyPassword@proxyHost.io:proxyPort',
    }
}

options = uc.ChromeOptions()
driver = uc.Chrome(options=options, seleniumwire_options=seleniumwire_options)
driver.get('https://distilnetworks.com')
```

**For v2,**

```python
import seleniumwire.undetected_chromedriver.v2 as uc

seleniumwire_options = {
    'disable_capture': True,
    'proxy': {
        'http': 'http://proxyUsername:proxyPassword@proxyHost.io:proxyPort',
        'https': 'https://proxyUsername:proxyPassword@proxyHost.io:proxyPort',
    }
}

options = uc.ChromeOptions()
# just some options passing in to skip annoying popups
options.add_argument('--no-first-run --no-service-autorun --password-store=basic')
driver = uc.Chrome(options=options, seleniumwire_options=seleniumwire_options)
# driver = uc.Chrome(options=options)
with driver:
    driver.get('https://nowsecure.nl')  # known url using cloudflare's "under attack mode"

```

### With extension and undetected-chromedriver

**For v1**
```python
import undetected_chromedriver as uc
import zipfile

def set_proxy(PROXY_HOST, PROXY_PORT, PROXY_USER, PROXY_PASS, options):
    manifest_json = """
    {
        "version": "1.0.0",
        "manifest_version": 2,
        "name": "Chrome Proxy",
        "permissions": [
            "proxy",
            "tabs",
            "unlimitedStorage",
            "storage",
            "<all_urls>",
            "webRequest",
            "webRequestBlocking"
        ],
        "background": {
            "scripts": ["background.js"]
        },
        "minimum_chrome_version":"22.0.0"
    }
    """

    background_js = """
    var config = {
            mode: "fixed_servers",
            rules: {
            singleProxy: {
                scheme: "http",
                host: "%s",
                port: parseInt(%s)
            },
            bypassList: ["localhost"]
            }
        };

    chrome.proxy.settings.set({value: config, scope: "regular"}, function() {});

    function callbackFn(details) {
        return {
            authCredentials: {
                username: "%s",
                password: "%s"
            }
        };
    }

    chrome.webRequest.onAuthRequired.addListener(
                callbackFn,
                {urls: ["<all_urls>"]},
                ['blocking']
    );
    """ % (PROXY_HOST, PROXY_PORT, PROXY_USER, PROXY_PASS)
    pluginfile = 'proxy_auth_plugin.zip'
    with zipfile.ZipFile(pluginfile, 'w') as zp:
        zp.writestr("manifest.json", manifest_json)
        zp.writestr("background.js", background_js)
    options.add_extension(pluginfile)
    return options

options = uc.ChromeOptions()
options = set_proxy("proxyHost.io", "proxyPort", "proxyUsername", "proxyPassword",options)
driver = uc.Chrome(options=options)
driver.get('https://distilnetworks.com')

```
**For v2**
```python

import undetected_chromedriver.v2 as uc
import os

def set_proxy(PROXY_HOST, PROXY_PORT, PROXY_USER, PROXY_PASS, options):
    manifest_json = """
    {
        "version": "1.0.0",
        "manifest_version": 2,
        "name": "Chrome Proxy",
        "permissions": [
            "proxy",
            "tabs",
            "unlimitedStorage",
            "storage",
            "<all_urls>",
            "webRequest",
            "webRequestBlocking"
        ],
        "background": {
            "scripts": ["background.js"]
        },
        "minimum_chrome_version":"22.0.0"
    }
    """

    background_js = """
    var config = {
            mode: "fixed_servers",
            rules: {
            singleProxy: {
                scheme: "http",
                host: "%s",
                port: parseInt(%s)
            },
            bypassList: ["localhost"]
            }
        };

    chrome.proxy.settings.set({value: config, scope: "regular"}, function() {});

    function callbackFn(details) {
        return {
            authCredentials: {
                username: "%s",
                password: "%s"
            }
        };
    }

    chrome.webRequest.onAuthRequired.addListener(
                callbackFn,
                {urls: ["<all_urls>"]},
                ['blocking']
    );
    """ % (PROXY_HOST, PROXY_PORT, PROXY_USER, PROXY_PASS)
    pluginfile = 'proxy_auth_plugin'
    if not os.path.exists(pluginfile):
        os.makedirs(pluginfile)
    with open("%s/manifest.json"%(pluginfile), "w") as f:
        f.write(manifest_json)
    with open("%s/background.js"%(pluginfile), "w") as f:
        f.write(background_js)
    options.add_argument('--load-extension=proxy_auth_plugin')
    return options

options = uc.ChromeOptions()
options = set_proxy("proxyHost.io", "proxyPort", "proxyUsername", "proxyPassword",options)
driver = uc.Chrome(options=options)
with driver:
    driver.get('https://nowsecure.nl')  # known url using cloudflare's "under attack mode"
```

**NOTE for undetected-chromedriver with extension**: If you want to run the code in server then you have to use virtual display such as Xvfb and donot set headless mode on options and follow a python package for it [xvfbwrapper](https://github.com/cgoldberg/xvfbwrapper). Using selenium-wire with undetected-chromedriver can be run headless with proxy.

**Comment by rndomusr** [comment]
Hey! I've chosen the "extension way" for using proxies with user/pass. However, even though my proxy is a mobile one, i am stuck in the "cloudflare loop". Any idea what the issue can be? 

Thanks!

**Comment by ozandastan** [comment]
> @monkylovesfauci @dimitrivisser @urasoguz
> 
> Replace the proxyUsername, proxyPassword, proxyHost and proxyPort with your proxy config.
> 
> ### With selenium-wire and undetected-chromedriver:
> **For v1,**
> 
> ```python
> import seleniumwire.undetected_chromedriver as uc
> 
> seleniumwire_options = {
>     'disable_capture': True,
>     'proxy': {
>         'http': 'http://proxyUsername:proxyPassword@proxyHost:proxyPort',
>         'https': 'https://proxyUsername:proxyPassword@proxyHost:proxyPort',
>     }
> }
> 
> options = uc.ChromeOptions()
> driver = uc.Chrome(options=options, seleniumwire_options=seleniumwire_options)
> driver.get('https://distilnetworks.com')
> ```
> 
> **For v2,**
> 
> ```python
> import seleniumwire.undetected_chromedriver.v2 as uc
> 
> seleniumwire_options = {
>     'disable_capture': True,
>     'proxy': {
>         'http': 'http://proxyUsername:proxyPassword@proxyHost:proxyPort',
>         'https': 'https://proxyUsername:proxyPassword@proxyHost:proxyPort',
>     }
> }
> 
> options = uc.ChromeOptions()
> # just some options passing in to skip annoying popups
> options.add_argument('--no-first-run --no-service-autorun --password-store=basic')
> driver = uc.Chrome(options=options, seleniumwire_options=seleniumwire_options)
> # driver = uc.Chrome(options=options)
> with driver:
>     driver.get('https://nowsecure.nl')  # known url using cloudflare's "under attack mode"
> ```
> 
> ### With extension and undetected-chromedriver
> **For v1**
> 
> ```python
> import undetected_chromedriver as uc
> import zipfile
> 
> def set_proxy(PROXY_HOST, PROXY_PORT, PROXY_USER, PROXY_PASS, options):
>     manifest_json = """
>     {
>         "version": "1.0.0",
>         "manifest_version": 2,
>         "name": "Chrome Proxy",
>         "permissions": [
>             "proxy",
>             "tabs",
>             "unlimitedStorage",
>             "storage",
>             "<all_urls>",
>             "webRequest",
>             "webRequestBlocking"
>         ],
>         "background": {
>             "scripts": ["background.js"]
>         },
>         "minimum_chrome_version":"22.0.0"
>     }
>     """
> 
>     background_js = """
>     var config = {
>             mode: "fixed_servers",
>             rules: {
>             singleProxy: {
>                 scheme: "http",
>                 host: "%s",
>                 port: parseInt(%s)
>             },
>             bypassList: ["localhost"]
>             }
>         };
> 
>     chrome.proxy.settings.set({value: config, scope: "regular"}, function() {});
> 
>     function callbackFn(details) {
>         return {
>             authCredentials: {
>                 username: "%s",
>                 password: "%s"
>             }
>         };
>     }
> 
>     chrome.webRequest.onAuthRequired.addListener(
>                 callbackFn,
>                 {urls: ["<all_urls>"]},
>                 ['blocking']
>     );
>     """ % (PROXY_HOST, PROXY_PORT, PROXY_USER, PROXY_PASS)
>     pluginfile = 'proxy_auth_plugin.zip'
>     with zipfile.ZipFile(pluginfile, 'w') as zp:
>         zp.writestr("manifest.json", manifest_json)
>         zp.writestr("background.js", background_js)
>     options.add_extension(pluginfile)
>     return options
> 
> options = uc.ChromeOptions()
> options = set_proxy("proxyHost", "proxyPort", "proxyUsername", "proxyPassword",options)
> driver = uc.Chrome(options=options)
> driver.get('https://distilnetworks.com')
> ```
> 
> **For v2**
> 
> ```python
> import undetected_chromedriver.v2 as uc
> import os
> 
> def set_proxy(PROXY_HOST, PROXY_PORT, PROXY_USER, PROXY_PASS, options):
>     manifest_json = """
>     {
>         "version": "1.0.0",
>         "manifest_version": 2,
>         "name": "Chrome Proxy",
>         "permissions": [
>             "proxy",
>             "tabs",
>             "unlimitedStorage",
>             "storage",
>             "<all_urls>",
>             "webRequest",
>             "webRequestBlocking"
>         ],
>         "background": {
>             "scripts": ["background.js"]
>         },
>         "minimum_chrome_version":"22.0.0"
>     }
>     """
> 
>     background_js = """
>     var config = {
>             mode: "fixed_servers",
>             rules: {
>             singleProxy: {
>                 scheme: "http",
>                 host: "%s",
>                 port: parseInt(%s)
>             },
>             bypassList: ["localhost"]
>             }
>         };
> 
>     chrome.proxy.settings.set({value: config, scope: "regular"}, function() {});
> 
>     function callbackFn(details) {
>         return {
>             authCredentials: {
>                 username: "%s",
>                 password: "%s"
>             }
>         };
>     }
> 
>     chrome.webRequest.onAuthRequired.addListener(
>                 callbackFn,
>                 {urls: ["<all_urls>"]},
>                 ['blocking']
>     );
>     """ % (PROXY_HOST, PROXY_PORT, PROXY_USER, PROXY_PASS)
>     pluginfile = 'proxy_auth_plugin'
>     if not os.path.exists(pluginfile):
>         os.makedirs(pluginfile)
>     with open("%s/manifest.json"%(pluginfile), "w") as f:
>         f.write(manifest_json)
>     with open("%s/background.js"%(pluginfile), "w") as f:
>         f.write(background_js)
>     options.add_argument('--load-extension=proxy_auth_plugin')
>     return options
> 
> options = uc.ChromeOptions()
> options = set_proxy("proxyHost", "proxyPort", "proxyUsername", "proxyPassword",options)
> driver = uc.Chrome(options=options)
> with driver:
>     driver.get('https://nowsecure.nl')  # known url using cloudflare's "under attack mode"
> ```
> 
> **NOTE for undetected-chromedriver with extension**: If you want to run the code in server then you have to use virtual display such as Xvfb and donot set headless mode on options and follow a python package for it [xvfbwrapper](https://github.com/cgoldberg/xvfbwrapper). Using selenium-wire with undetected-chromedriver can be run headless with proxy.

When i try 

"import seleniumwire.undetected_chromedriver.v2 as uc

seleniumwire_options = {
    'disable_capture': True,
    'proxy': {
        'http': 'http://proxyUsername:proxyPassword@proxyHost:proxyPort',
        'https': 'https://proxyUsername:proxyPassword@proxyHost:proxyPort',
    }
}

options = uc.ChromeOptions()
# just some options passing in to skip annoying popups
options.add_argument('--no-first-run --no-service-autorun --password-store=basic')
driver = uc.Chrome(options=options, seleniumwire_options=seleniumwire_options)
# driver = uc.Chrome(options=options)
with driver:
    driver.get('https://nowsecure.nl')  # known url using cloudflare's "under attack mode"

"

this line of code it gives this error: 

Traceback (most recent call last):
  File "C:\Users\PC\PycharmProjects\pythonProject5\main.py", line 2, in <module>
    import seleniumwire.undetected_chromedriver.v2 as uc
  File "C:\Users\PC\PycharmProjects\pythonProject5\venv\lib\site-packages\seleniumwire\undetected_chromedriver\__init__.py", line 8, in <module>
    from seleniumwire.webdriver import Chrome
  File "C:\Users\PC\PycharmProjects\pythonProject5\venv\lib\site-packages\seleniumwire\webdriver.py", line 4, in <module>
    from packaging import version
ModuleNotFoundError: No module named 'packaging'
