### ISSUE TITLE
Exception ignored in: <function Chrome.__del__ at 0x00000295827B4900>

### ISSUE THREAD

**Issue by TheMrZenith** [ultrafunkamsterdam/undetected-chromedriver#2084]
Exception ignored in: <function Chrome.__del__ at 0x00000295827B4900>
Traceback (most recent call last):
  File "C:\Users\Utente\Desktop\Zenith\.venv\Lib\site-packages\undetected_chromedriver\__init__.py", line 843, in __del__
  File "C:\Users\Utente\Desktop\Zenith\.venv\Lib\site-packages\undetected_chromedriver\__init__.py", line 798, in quit
OSError: [WinError 6] Handle non valido

**Comment by DingDangCat2** [comment]
the chrome version have any problem maybe.130->131

**Comment by ebulku** [comment]
same issue
