### ISSUE TITLE
mac  error urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)>

### ISSUE THREAD

**Issue by PalaChen** [ultrafunkamsterdam/undetected-chromedriver#227]
my code 
```
import undetected_chromedriver as uc

uc.TARGET_VERSION = 91
uc.install(
    executable_path='/Users/xxx/Documents/GitHub/grecapcha/chromedriver.exe',
)

options = uc.ChromeOptions()
options.headless=True
options.add_argument('--headless')
chrome = uc.Chrome(options=options)


url="https://www.google.com/"
chrome.get(url)
chrome.save_screenshot('datadome_undetected_webddriver.png')
```
error message 
```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 1319, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 1230, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 1276, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 1225, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 1004, in _send_output
    self.send(msg)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 944, in send
    self.connect()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 1399, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/chenxin/Documents/GitHub/grecapcha/ucd.py", line 4, in <module>
    uc.install(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/undetected_chromedriver/__init__.py", line 265, in install
    ChromeDriverManager(executable_path, target_version, *args, **kwargs).install()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/undetected_chromedriver/__init__.py", line 195, in install
    self.fetch_chromedriver()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/undetected_chromedriver/__init__.py", line 224, in fetch_chromedriver
    ver = self.get_release_version_number().vstring
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/undetected_chromedriver/__init__.py", line 214, in get_release_version_number
    return LooseVersion(urlopen(self.__class__.DL_BASE + path).read().decode())
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 1362, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 1322, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)>


```
but mac  can't  install 
```
brew install -y python3.8-dev
brew install -y build-essential checkinstall libreadline-gplv2-dev ibncursesw5-dev libssl-dev libsqlite3-dev tk-dev libgdbm-dev libc6-dev libbz2-dev

```

**Comment by Spring-0** [comment]
bump, I am having the same issue

**Comment by ycq0125** [comment]
> my code
> 
> ```
> import undetected_chromedriver as uc
> 
> uc.TARGET_VERSION = 91
> uc.install(
>     executable_path='/Users/xxx/Documents/GitHub/grecapcha/chromedriver.exe',
> )
> 
> options = uc.ChromeOptions()
> options.headless=True
> options.add_argument('--headless')
> chrome = uc.Chrome(options=options)
> 
> 
> url="https://www.google.com/"
> chrome.get(url)
> chrome.save_screenshot('datadome_undetected_webddriver.png')
> ```
> 
> error message
> 
> ```
> Traceback (most recent call last):
>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 1319, in do_open
>     h.request(req.get_method(), req.selector, req.data, headers,
>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 1230, in request
>     self._send_request(method, url, body, headers, encode_chunked)
>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 1276, in _send_request
>     self.endheaders(body, encode_chunked=encode_chunked)
>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 1225, in endheaders
>     self._send_output(message_body, encode_chunked=encode_chunked)
>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 1004, in _send_output
>     self.send(msg)
>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 944, in send
>     self.connect()
>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 1399, in connect
>     self.sock = self._context.wrap_socket(self.sock,
>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/ssl.py", line 500, in wrap_socket
>     return self.sslsocket_class._create(
>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/ssl.py", line 1040, in _create
>     self.do_handshake()
>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/ssl.py", line 1309, in do_handshake
>     self._sslobj.do_handshake()
> ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/Users/chenxin/Documents/GitHub/grecapcha/ucd.py", line 4, in <module>
>     uc.install(
>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/undetected_chromedriver/__init__.py", line 265, in install
>     ChromeDriverManager(executable_path, target_version, *args, **kwargs).install()
>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/undetected_chromedriver/__init__.py", line 195, in install
>     self.fetch_chromedriver()
>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/undetected_chromedriver/__init__.py", line 224, in fetch_chromedriver
>     ver = self.get_release_version_number().vstring
>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/undetected_chromedriver/__init__.py", line 214, in get_release_version_number
>     return LooseVersion(urlopen(self.__class__.DL_BASE + path).read().decode())
>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 222, in urlopen
>     return opener.open(url, data, timeout)
>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 525, in open
>     response = self._open(req, data)
>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 542, in _open
>     result = self._call_chain(self.handle_open, protocol, protocol +
>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 502, in _call_chain
>     result = func(*args)
>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 1362, in https_open
>     return self.do_open(http.client.HTTPSConnection, req,
>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 1322, in do_open
>     raise URLError(err)
> urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)>
> ```
> 
> but mac can't install
> 
> ```
> brew install -y python3.8-dev
> brew install -y build-essential checkinstall libreadline-gplv2-dev ibncursesw5-dev libssl-dev libsqlite3-dev tk-dev libgdbm-dev libc6-dev libbz2-dev
> ```

import ssl
ssl._create_default_https_context = ssl._create_unverified_context

**Comment by edde746** [comment]
[Solution here](https://stackoverflow.com/a/70495761)

**Comment by HenryXiaoYang** [comment]
> For mac: [Do this](https://stackoverflow.com/a/70495761)

works
