### ISSUE TITLE
Type Error for subprocess.Popen(...

### ISSUE THREAD

**Issue by DanForLoop** [ultrafunkamsterdam/undetected-chromedriver#247]
Trying to install this on Windows using python 3.9.1 and the following trying to open the driver leads to the following issue.
My code: 
```
import undetected_chromedriver.v2 as uc
driver = uc.Chrome()
```

The error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\asmith\Documents\Python391\lib\site-packages\undetected_chromedriver\v2.py", line 283, in __init__
    self.browser = subprocess.Popen(
  File "C:\Users\asmith\Documents\Python391\lib\subprocess.py", line 947, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\asmith\Documents\Python391\lib\subprocess.py", line 1356, in _execute_child
    args = list2cmdline(args)
  File "C:\Users\asmith\Documents\Python391\lib\subprocess.py", line 561, in list2cmdline
    for arg in map(os.fsdecode, seq):
  File "C:\Users\asmith\Documents\Python391\lib\os.py", line 822, in fsdecode
    filename = fspath(filename)  # Does type-checking of `filename`.
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

I had it working on another VM that was using python 3.8.2 so I'm not sure if it's a version issue?
Any help would be appreciated!

**Comment by DanForLoop** [comment]
It definitely is a version issue as I ran it with python 3.8.0 successfully on the same system, but I can't see whats causing the issue exactly from the docs.

Closing as I have a solution, but still unsure what the cause is/was.
