### ISSUE TITLE
AttributeError: 'Chrome' object has no attribute 'service'

### ISSUE THREAD

**Issue by Failton** [ultrafunkamsterdam/undetected-chromedriver#259]
I'm trying to run the example "The Version 2 way", but I get an error. System: Manyaro, Kernel: 5.10.53-1-MANJARO. Everything works fine for Windows.

`Traceback (most recent call last):
  File "/home/ilya/AWauto/uc.py", line 2, in <module>
    driver = uc.Chrome()
  File "/home/ilya/.local/lib/python3.9/site-packages/undetected_chromedriver/v2.py", line 294, in __init__
    self.browser = subprocess.Popen(
  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1696, in _execute_child
    and os.path.dirname(executable)
  File "/usr/lib/python3.9/posixpath.py", line 152, in dirname
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not NoneType
Exception ignored in: <function Chrome.__del__ at 0x7f7bd218e280>
Traceback (most recent call last):
  File "/home/ilya/.local/lib/python3.9/site-packages/undetected_chromedriver/v2.py", line 623, in __del__
  File "/home/ilya/.local/lib/python3.9/site-packages/undetected_chromedriver/v2.py", line 581, in quit
AttributeError: 'Chrome' object has no attribute 'service'
`

**Comment by askvrtsv** [comment]
It looks like you are passing Options from the webdriver module when you create Chrome, not from undetected_chromedriver.
