### ISSUE TITLE
Subprocces issue?

### ISSUE THREAD

**Issue by thiva7** [ultrafunkamsterdam/undetected-chromedriver#265]
Based on this
https://github.com/ultrafunkamsterdam/undetected-chromedriver/issues/263

Hey , i am using python 3.7
and using this command to create my EXE file
pyinstaller -F demo.py

The exe that created , is working fine on 2 PCs , but on other 2 that i tested show the error

File "demo.py", line 5, in <module>
  File "undetected_chromedriver\v2.py", line 283, in __init__
  File "subprocess.py", line 854, in __init__
  File "subprocess.py", line 1247, in _execute_child
  File "subprocess.py", line 549, in list2cmdline
  File "os.py", line 818, in fsdecode
TypeError: expected str, bytes or os.PathLike object, not NoneType

**Comment by thiva7** [comment]
hey again, this code

```
import undetected_chromedriver.v2 as uc
driver = uc.Chrome()
with driver:
    driver.get('https://nowsecure.nl')  # known url using cloudflare's "under attack mode"
```

give me this error:

```
Traceback (most recent call last):
  File "demo.py", line 2, in <module>
  File "undetected_chromedriver\v2.py", line 295, in __init__
  File "subprocess.py", line 854, in __init__
  File "subprocess.py", line 1247, in _execute_child
  File "subprocess.py", line 549, in list2cmdline
  File "os.py", line 818, in fsdecode
TypeError: expected str, bytes or os.PathLike object, not NoneType
[9996] Failed to execute script demo
Exception ignored in: <function Chrome.__del__ at 0x03D21610>
Traceback (most recent call last):
  File "undetected_chromedriver\v2.py", line 625, in __del__
  File "undetected_chromedriver\v2.py", line 583, in quit
AttributeError: 'Chrome' object has no attribute 'service'
```

**Comment by FeelsBadMan1** [comment]
same issue here:

```  File "D:\Downloads\Python\python 3.9.6\lib\site-packages\undetected_chromedriver\v2.py", line 188, in __init__
    self.browser = subprocess.Popen(
  File "D:\Downloads\Python\python 3.9.6\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "D:\Downloads\Python\python 3.9.6\lib\subprocess.py", line 1360, in _execute_child
    args = list2cmdline(args)
  File "D:\Downloads\Python\python 3.9.6\lib\subprocess.py", line 565, in list2cmdline
    for arg in map(os.fsdecode, seq):
  File "D:\Downloads\Python\python 3.9.6\lib\os.py", line 822, in fsdecode
    filename = fspath(filename)  # Does type-checking of `filename`.
TypeError: expected str, bytes or os.PathLike object, not NoneType

Process finished with exit code 1
``

**Comment by MlataIbrahim** [comment]
I have the same issue, any solutions guys?

**Comment by BenRoe** [comment]
Try 
```python
self.driver = uc.Chrome(use_subprocess=True)
```
