### ISSUE TITLE
TypeError: expected str, bytes or os.PathLike object, not NoneType

### ISSUE THREAD

**Issue by dtomper** [ultrafunkamsterdam/undetected-chromedriver#285]
```
>>> import undetected_chromedriver.v2 as uc
>>> driver = uc.Chrome()

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Dtomper\AppData\Local\Programs\Python\Python39-32\lib\site-packages\undetected_chromedriver\v2.py", line 294, in __init__
    self.browser = subprocess.Popen(
  File "C:\Users\Dtomper\AppData\Local\Programs\Python\Python39-32\lib\subprocess.py", line 947, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\Dtomper\AppData\Local\Programs\Python\Python39-32\lib\subprocess.py", line 1356, in _execute_child
    args = list2cmdline(args)
  File "C:\Users\Dtomper\AppData\Local\Programs\Python\Python39-32\lib\subprocess.py", line 561, in list2cmdline
    for arg in map(os.fsdecode, seq):
  File "C:\Users\Dtomper\AppData\Local\Programs\Python\Python39-32\lib\os.py", line 822, in fsdecode
    filename = fspath(filename)  # Does type-checking of `filename`.
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

which path am I supposed to give to this function? I thought it automatically downloads the suitable chromedriver.exe version and patches it.

**Comment by willnaoosmith** [comment]
same here
