### ISSUE TITLE
headless can not work

### ISSUE THREAD

**Issue by miladrajabi2002** [ultrafunkamsterdam/undetected-chromedriver#298]
i try any code and any version of google-chrome and chromedriver and all of them not working in headless mode(can not bypass cloudflare just open normal site) pleas fix it

**Comment by IgrutinovicL** [comment]
This better be a troll comment.

**Comment by maestre7** [comment]
Traceback (most recent call last):
  File "C:\Users\XXXXXX\Desktop\Python\Leecher datos\Leecher datos V2\TMO_inicio.py", line 60, in tmo_inicio
    driver.get(url)
  File "C:\ProgramData\Miniconda3\lib\site-packages\undetected_chromedriver\v2.py", line 391, in get_wrapped
    if self.options.mock_permissions:
AttributeError: 'Options' object has no attribute 'mock_permissions'

**Comment by NiamurRashid** [comment]
headless not working 
its true headless .is not able to bypass
