### ISSUE TITLE
This version of ChromeDriver only supports Chrome version 92

### ISSUE THREAD

**Issue by smamczak** [ultrafunkamsterdam/undetected-chromedriver#301]
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot connect to chrome at 127.0.0.1:49426
from session not created: This version of ChromeDriver only supports Chrome version 92
Current browser version is 94.0.4606.30

**Comment by pl77** [comment]
Which version of undetected-chromedriver are you using?  latest is 3.0.3

**Comment by nhwalkman** [comment]
kubuntu 18.04.6 LTS
Python 3.6.9 (default, Jan 26 2021, 15:33:00) 
[GCC 8.4.0] on linux

I too have similar problem.

I saw notes regarding 3.0.3, how to specify version:: browser = uc.Chrome(version_main=91), so I am trying to upgrade to 3.0.3 to use this new parameter(version_main) ... BUT... I can't install 3.0.3 due to this error
------  when trying to upgrade UC:: ERROR: Could not find a version that satisfies the requirement selenium==4.0.0b4 

If I revert back to using UC v3.0.1 or v3.0.2 on system (details above), produces this error:
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 91
Current browser version is 93.0.4577.63 with binary path /usr/bin/chromium-browser

If I try other possibility:: using "import undetected_chromedriver.v2", I end up with "future annotation error"

import undetected_chromedriver.v2 as uc
browser = uc.Chrome()

Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 781, in get_code
  File "<frozen importlib._bootstrap_external>", line 741, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/lib/python3.6/dist-packages/undetected_chromedriver/v2.py", line 4
    from __future__ import annotations
    ^
SyntaxError: future feature annotations is not defined
python-BaseException

**Comment by boludoz** [comment]
Apparently  ud chromedriver always downloads the latest version of chromedriver and replaces a text to make it undetectable, update your version of chrome.

**Comment by chrisspen** [comment]
This doesn't work. I've updated to version 108 but UC still complains "Current browser version is 107.0.5304.121". Yet I'm literally typing this comment in Chrome 108.0.5359.94.
