### ISSUE TITLE
It doesn't start and also it seems to be downloading an incorrect version of chromedriver

### ISSUE THREAD

**Issue by mcarnerero** [ultrafunkamsterdam/undetected-chromedriver#302]
Hi!

I'm testing v2 but it doesn't work for me. I have the following ouput:

```text
[2021-09-09 10:51:22,992] [easyprocess] [DEBUG] command: ['Xvfb', '-help']
[2021-09-09 10:51:22,998] [easyprocess] [DEBUG] process was started (pid=18555)
[2021-09-09 10:51:23,003] [easyprocess] [DEBUG] process has ended, return code=0
[2021-09-09 10:51:23,004] [pyvirtualdisplay.abstractdisplay] [DEBUG] command: ['Xvfb', '-br', '-nolisten', 'tcp', '-screen', '0', '1280x1024x24', '-displayfd', '5']
[2021-09-09 10:51:23,082] [pyvirtualdisplay.abstractdisplay] [DEBUG] set $DISPLAY=:1
[2021-09-09 10:51:23,083] [root] [INFO] Loading UNDETECTED chromedriver (headless,even)...
[2021-09-09 10:51:23,085] [undetected_chromedriver.patcher] [DEBUG] getting release number from /LATEST_RELEASE
[2021-09-09 10:51:23,215] [undetected_chromedriver.patcher] [DEBUG] downloading from https://chromedriver.storage.googleapis.com/92.0.4515.107/chromedriver_linux64.zip
[2021-09-09 10:51:23,492] [undetected_chromedriver.patcher] [DEBUG] unzipping /tmp/tmp8h9nukgw
[2021-09-09 10:51:23,626] [undetected_chromedriver.patcher] [INFO] patching driver executable /usr/bin/chromedriver
[2021-09-09 10:51:24,825] [selenium.webdriver.remote.remote_connection] [DEBUG] POST http://127.0.0.1:36987/session {"capabilities": {"firstMatch": [{}], "alwaysMatch": {"browserName": "chrome", "platformName": "any", "pageLoadStrategy": "normal", "goog:chromeOptions": {"extensions": [], "binary": "/bin/google-chrome", "args": ["--no-first-run --no-service-autorun --password-store=basic", "--remote-debugging-host=127.0.0.1", "--remote-debugging-port=60625", "--user-data-dir=/opt/testing/data/temp", "--lang=en-GB", "--log-level=0"], "debuggerAddress": "127.0.0.1:60625"}}}, "desiredCapabilities": {"browserName": "chrome", "version": "", "platform": "ANY", "pageLoadStrategy": "normal", "goog:chromeOptions": {"extensions": [], "binary": "/bin/google-chrome", "args": ["--no-first-run --no-service-autorun --password-store=basic", "--remote-debugging-host=127.0.0.1", "--remote-debugging-port=60625", "--user-data-dir=/opt/testing/data/temp", "--lang=en-GB", "--log-level=0"], "debuggerAddress": "127.0.0.1:60625"}}}
[2021-09-09 10:51:24,828] [urllib3.connectionpool] [DEBUG] Starting new HTTP connection (1): 127.0.0.1:36987
[2021-09-09 10:52:24,896] [urllib3.connectionpool] [DEBUG] http://127.0.0.1:36987 "POST /session HTTP/1.1" 500 767
[2021-09-09 10:52:24,897] [selenium.webdriver.remote.remote_connection] [DEBUG] Finished Request
[2021-09-09 10:52:24,898] [root] [ERROR] Message: unknown error: cannot connect to chrome at 127.0.0.1:60625
from chrome not reachable
Traceback (most recent call last):
  File "/opt/testing/test_undetected_chromedriver.py", line 117, in <module>
    driver = uc.Chrome(executable_path=CHROME_DRIVER_PATH, options=options)
  File "/opt/testing/env/lib/python3.9/site-packages/undetected_chromedriver/v2.py", line 291, in __init__
    super().__init__(
  File "/opt/testing/env/lib/python3.9/site-packages/selenium/webdriver/chrome/webdriver.py", line 76, in __init__
    RemoteWebDriver.__init__(
  File "/opt/testing/env/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/opt/testing/env/lib/python3.9/site-packages/undetected_chromedriver/v2.py", line 553, in start_session
    super().start_session(capabilities, browser_profile)
  File "/opt/testing/env/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/opt/testing/env/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/opt/testing/env/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot connect to chrome at 127.0.0.1:60625
from chrome not reachable

[2021-09-09 10:52:24,904] [pyvirtualdisplay.abstractdisplay] [DEBUG] set $DISPLAY=:0.0
[2021-09-09 10:52:24,911] [pyvirtualdisplay.abstractdisplay] [DEBUG] stdout=b''
[2021-09-09 10:52:24,911] [pyvirtualdisplay.abstractdisplay] [DEBUG] stderr=b'_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n'
```

I have tested it in different machines, all Debian 10 instances. The version of installed chrome is 93.0.4577.63 and Chromedriver version is 93.0.4577.15.

The lines of code of my python script involved are:

```python
CHROME_DRIVER_PATH = '/usr/bin/chromedriver'
options = uc.ChromeOptions()
options.user_data_dir = '/opt/testing/data/temp/'
options.add_argument('--no-first-run --no-service-autorun --password-store=basic')
driver = uc.Chrome(executable_path=CHROME_DRIVER_PATH, options=options)
```

Other versions of interest:
 - undetected-chromedriver 3.0.2
 - Python 3.9

Thank you in advance to anyone who could help me.

**Comment by pl77** [comment]
> * undetected-chromedriver 3.0.2

Update to 3.0.3?

**Comment by mcarnerero** [comment]
I updated to version 3.0.3 of undetected-chromedriver, but the result is the same.

```
[2021-09-13 09:45:03,428] [easyprocess] [DEBUG] command: ['Xvfb', '-help']
[2021-09-13 09:45:03,433] [easyprocess] [DEBUG] process was started (pid=19336)
[2021-09-13 09:45:03,438] [easyprocess] [DEBUG] process has ended, return code=0
[2021-09-13 09:45:03,439] [pyvirtualdisplay.abstractdisplay] [DEBUG] command: ['Xvfb', '-br', '-nolisten', 'tcp', '-screen', '0', '1280x1024x24', '-displayfd', '5']
[2021-09-13 09:45:03,523] [pyvirtualdisplay.abstractdisplay] [DEBUG] set $DISPLAY=:1
[2021-09-13 09:45:03,524] [root] [INFO] Loading UNDETECTED chromedriver (headless,even)...
[2021-09-13 09:45:04,155] [selenium.webdriver.remote.remote_connection] [DEBUG] POST http://localhost:36551/session {"capabilities": {"firstMatch": [{}], "alwaysMatch": {"browserName": "chrome", "platformName": "any", "pageLoadStrategy": "normal", "goog:chromeOptions": {"extensions": [], "binary": "/bin/google-chrome", "args": ["--no-sandbox --no-first-run --no-service-autorun --password-store=basic", "--remote-debugging-host=127.0.0.1", "--remote-debugging-port=51999", "--user-data-dir=/opt/data/temp", "--lang=en-GB", "--log-level=0"], "debuggerAddress": "127.0.0.1:51999"}}}, "desiredCapabilities": {"browserName": "chrome", "version": "", "platform": "ANY", "pageLoadStrategy": "normal", "goog:chromeOptions": {"extensions": [], "binary": "/bin/google-chrome", "args": ["--no-sandbox --no-first-run --no-service-autorun --password-store=basic", "--remote-debugging-host=127.0.0.1", "--remote-debugging-port=51999", "--user-data-dir=/opt/data/temp", "--lang=en-GB", "--log-level=0"], "debuggerAddress": "127.0.0.1:51999"}}}
[2021-09-13 09:45:04,157] [urllib3.connectionpool] [DEBUG] Starting new HTTP connection (1): localhost:36551
[2021-09-13 09:46:04,211] [urllib3.connectionpool] [DEBUG] http://localhost:36551 "POST /session HTTP/1.1" 500 767
[2021-09-13 09:46:04,213] [selenium.webdriver.remote.remote_connection] [DEBUG] Finished Request
[2021-09-13 09:46:04,214] [root] [ERROR] Message: unknown error: cannot connect to chrome at 127.0.0.1:51999
from chrome not reachable
Stacktrace:
#0 0x55a78a7b9a63 <unknown>
#1 0x55a78a52e2ef <unknown>
#2 0x55a78a51d1e4 <unknown>
#3 0x55a78a55473f <unknown>
#4 0x55a78a54c676 <unknown>
#5 0x55a78a586b72 <unknown>
#6 0x55a78a580fd3 <unknown>
#7 0x55a78a557514 <unknown>
#8 0x55a78a558505 <unknown>
#9 0x55a78a7e5e2e <unknown>
#10 0x55a78a7fb886 <unknown>
#11 0x55a78a7e6d75 <unknown>
#12 0x55a78a7fcd94 <unknown>
#13 0x55a78a7dd8eb <unknown>
#14 0x55a78a817cd8 <unknown>
#15 0x55a78a817e58 <unknown>
#16 0x55a78a831dfd <unknown>
#17 0x7fa128d5bfa3 start_thread
Traceback (most recent call last):
  File "/opt/testing/test_undetected_chromedriver.py", line 117, in <module>
    driver = uc.Chrome(executable_path=CHROME_DRIVER_PATH, options=options)
  File "/opt/env/lib/python3.9/site-packages/undetected_chromedriver/v2.py", line 302, in __init__
    super(Chrome, self).__init__(
  File "/opt/env/lib/python3.9/site-packages/selenium/webdriver/chrome/webdriver.py", line 69, in __init__
    super(WebDriver, self).__init__(DesiredCapabilities.CHROME['browserName'], "goog",
  File "/opt/env/lib/python3.9/site-packages/selenium/webdriver/chromium/webdriver.py", line 93, in __init__
    RemoteWebDriver.__init__(
  File "/opt/env/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 248, in __init__
    self.start_session(capabilities, browser_profile)
  File "/opt/env/lib/python3.9/site-packages/undetected_chromedriver/v2.py", line 577, in start_session
    super(Chrome, self).start_session(capabilities, browser_profile)
  File "/opt/env/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 339, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/opt/env/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 400, in execute
    self.error_handler.check_response(response)
  File "/opt/env/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py", line 236, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot connect to chrome at 127.0.0.1:51999
from chrome not reachable
Stacktrace:
#0 0x55a78a7b9a63 <unknown>
#1 0x55a78a52e2ef <unknown>
#2 0x55a78a51d1e4 <unknown>
#3 0x55a78a55473f <unknown>
#4 0x55a78a54c676 <unknown>
#5 0x55a78a586b72 <unknown>
#6 0x55a78a580fd3 <unknown>
#7 0x55a78a557514 <unknown>
#8 0x55a78a558505 <unknown>
#9 0x55a78a7e5e2e <unknown>
#10 0x55a78a7fb886 <unknown>
#11 0x55a78a7e6d75 <unknown>
#12 0x55a78a7fcd94 <unknown>
#13 0x55a78a7dd8eb <unknown>
#14 0x55a78a817cd8 <unknown>
#15 0x55a78a817e58 <unknown>
#16 0x55a78a831dfd <unknown>
#17 0x7fa128d5bfa3 start_thread

[2021-09-13 09:46:04,221] [pyvirtualdisplay.abstractdisplay] [DEBUG] set $DISPLAY=:0.0
[2021-09-13 09:46:04,228] [pyvirtualdisplay.abstractdisplay] [DEBUG] stdout=b''
[2021-09-13 09:46:04,229] [pyvirtualdisplay.abstractdisplay] [DEBUG] stderr=b'_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed\n_XSERVTransMakeAllCOTSServerListeners: server already running\n'
```

**Comment by f2ostie** [comment]
Facing the same issue when using pyvirtualdisplay

**Comment by ultrafunkamsterdam** [comment]
you shouldn't specify executable path if it does not yet exist. to download different version use Chrome(version_main=91) where 91 could also be 92 , 93. better option is to keep Chrome updated. driver downloads for the current (google declared) version rsion by default.

**Comment by mcarnerero** [comment]
Hi. Chrome and chromedriver were correctly installed on all the machines. Actually, in one of the machines I have tested this I'm using your library (v1) without any problem. I also have notice that after run the testing script, the chromedriver version installed is downgraded from version 93 to version 92. Maybe, it should be good to test first which version is running or installed before start patching the chromedriver. In spite of everything, thanks for answering.

**Comment by mcarnerero** [comment]
Executing chromedriver directly I could see that the problem here seems to be related with the port used by selemium instantiation and the port used in the first call. They should be the same.
