### ISSUE TITLE
V3 problems can you help please :) ?

### ISSUE THREAD

**Issue by skintflickz** [ultrafunkamsterdam/undetected-chromedriver#305]
Hi sorry totally rubbish at this, I installed via pip.. all good
checked packages.. v2 and v3 are there.

**ran**

import undetected_chromedriver.v2 as uc

driver = uc.Chrome()
with driver:
    driver.get('https://nowsecure.nl')

**got**

C:\Users\cube\PycharmProjects\pythonProject\venv\Scripts\python.exe C:/Users/cube/PycharmProjects/pythonProject/main.py
Traceback (most recent call last):
  File "C:\Users\cube\PycharmProjects\pythonProject\main.py", line 3, in <module>
    driver = uc.Chrome()
  File "C:\Users\cube\PycharmProjects\pythonProject\venv\lib\site-packages\undetected_chromedriver\v2.py", line 294, in __init__
    self.browser = subprocess.Popen(
  File "C:\Users\cube\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\cube\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 1360, in _execute_child
    args = list2cmdline(args)
  File "C:\Users\cube\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 565, in list2cmdline
    for arg in map(os.fsdecode, seq):
  File "C:\Users\cube\AppData\Local\Programs\Python\Python39\lib\os.py", line 822, in fsdecode
    filename = fspath(filename)  # Does type-checking of `filename`.
TypeError: expected str, bytes or os.PathLike object, not NoneType
Exception ignored in: <function Chrome.__del__ at 0x00000218CC019790>
Traceback (most recent call last):
  File "C:\Users\cube\PycharmProjects\pythonProject\venv\lib\site-packages\undetected_chromedriver\v2.py", line 623, in __del__
  File "C:\Users\cube\PycharmProjects\pythonProject\venv\lib\site-packages\undetected_chromedriver\v2.py", line 581, in quit
AttributeError: 'Chrome' object has no attribute 'service'

Process finished with exit code 1

**ran** 

import undetected_chromedriver.v2 as uc

driver = uc.Chrome()
with driver:
    driver.get('https://nowsecure.nl')

**got**

Cannot find reference 'Chrome' in 'v3.py' 

**and**

import undetected_chromedriver as uc

driver = uc.Chrome()
with driver:
    driver.get('https://nowsecure.nl')

C:\Users\cube\PycharmProjects\pythonProject\venv\Scripts\python.exe C:/Users/cube/PycharmProjects/pythonProject/main.py
Traceback (most recent call last):
  File "C:\Users\cube\PycharmProjects\pythonProject\main.py", line 3, in <module>
    driver = uc.Chrome()
  File "C:\Users\cube\PycharmProjects\pythonProject\venv\lib\site-packages\undetected_chromedriver\__init__.py", line 57, in __new__
    instance.__init__(*args, **kwargs)
  File "C:\Users\cube\PycharmProjects\pythonProject\venv\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 69, in __init__
    super(WebDriver, self).__init__(DesiredCapabilities.CHROME['browserName'], "goog",
  File "C:\Users\cube\PycharmProjects\pythonProject\venv\lib\site-packages\selenium\webdriver\chromium\webdriver.py", line 93, in __init__
    RemoteWebDriver.__init__(
  File "C:\Users\cube\PycharmProjects\pythonProject\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 248, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Users\cube\PycharmProjects\pythonProject\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 339, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Users\cube\PycharmProjects\pythonProject\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 400, in execute
    self.error_handler.check_response(response)
  File "C:\Users\cube\PycharmProjects\pythonProject\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 236, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot find Chrome binary
Stacktrace:
Backtrace:
	Ordinal0 [0x006CD403+2479107]
	Ordinal0 [0x00667D51+2063697]
	Ordinal0 [0x005720C8+1056968]
	Ordinal0 [0x0058B54C+1160524]
	Ordinal0 [0x00589B7F+1153919]
	Ordinal0 [0x005B9CBF+1350847]
	Ordinal0 [0x005B992A+1349930]
	Ordinal0 [0x005B583B+1333307]
	Ordinal0 [0x00591F94+1187732]
	Ordinal0 [0x00592DE9+1191401]
	GetHandleVerifier [0x0084F3F6+1531734]
	GetHandleVerifier [0x008FE9AE+2249998]
	GetHandleVerifier [0x007539AB+501003]
	GetHandleVerifier [0x00752A29+497033]
	Ordinal0 [0x0066D11D+2085149]
	Ordinal0 [0x006711C8+2101704]
	Ordinal0 [0x00671302+2102018]
	Ordinal0 [0x0067AA71+2140785]
	BaseThreadInitThunk [0x766BFA29+25]
	RtlGetAppContainerNamedObjectPath [0x77B57A7E+286]
	RtlGetAppContainerNamedObjectPath [0x77B57A4E+238]

Process finished with exit code 1

**Comment by pl77** [comment]
> import undetected_chromedriver.v2 as uc

Change this to `import undetected_chromedriver as uc`

**Comment by skintflickz** [comment]
Thanks it works now, I was trying to use chrome portable for what I'm writing but standard chromes fine.
Does v3 work yet ?
