### ISSUE TITLE
MacOs M1 Error When Start

### ISSUE THREAD

**Issue by NameEgor** [ultrafunkamsterdam/undetected-chromedriver#310]
Traceback Error (Python 3.8.2): 
Traceback (most recent call last):
  File "scrappy/browser.py", line 7, in <module>
    driver = uc.Chrome(executable_path=path_to_driver, port=9515)
  File "/Users/github-localhost/Desktop/Projects/python_projects/att_scrappy/venv_pycharm/lib/python3.8/site-packages/undetected_chromedriver/v2.py", line 163, in __init__
    patcher.auto()
  File "/Users/github-localhost/Desktop/Projects/python_projects/att_scrappy/venv_pycharm/lib/python3.8/site-packages/undetected_chromedriver/patcher.py", line 91, in auto
    ispatched = self.is_binary_patched(self.executable_path)
  File "/Users/github-localhost/Desktop/Projects/python_projects/att_scrappy/venv_pycharm/lib/python3.8/site-packages/undetected_chromedriver/patcher.py", line 209, in is_binary_patched
    with io.open(executable_path, "rb") as fh:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/github-localhost/Download/chromedriver'
Exception ignored in: <function Chrome.__del__ at 0x105b360d0>
Traceback (most recent call last):
  File "/Users/github-localhost/Desktop/Projects/python_projects/att_scrappy/venv_pycharm/lib/python3.8/site-packages/undetected_chromedriver/v2.py", line 623, in __del__
    self.quit()
  File "/Users/github-localhost/Desktop/Projects/python_projects/att_scrappy/venv_pycharm/lib/python3.8/site-packages/undetected_chromedriver/v2.py", line 581, in quit
    self.service.process.kill()
AttributeError: 'Chrome' object has no attribute 'service'

Version:
undetected-chromedriver 3.0.3
selenium                4.0.0b4

Native selenium work's but not this library.
How I start:

```
import undetected_chromedriver.v2 as uc
from selenium import webdriver

path_to_driver = "/Users/github-localhost/Download/chromedriver"

driver = uc.Chrome(executable_path=path_to_driver, port=9515)
```

**Comment by NameEgor** [comment]
I'm sorry, this is the real traceback error:

Traceback (most recent call last):
  File "scrappy/browser.py", line 7, in <module>
    driver = uc.Chrome(executable_path=path_to_driver, port=9515)
  File "/Users/github-localhost/Desktop/Projects/python_projects/att_scrappy/venv_pycharm/lib/python3.8/site-packages/undetected_chromedriver/v2.py", line 163, in __init__
    patcher.auto()
  File "/Users/github-localhost/Desktop/Projects/python_projects/att_scrappy/venv_pycharm/lib/python3.8/site-packages/undetected_chromedriver/patcher.py", line 91, in auto
    ispatched = self.is_binary_patched(self.executable_path)
  File "/Users/github-localhost/Desktop/Projects/python_projects/att_scrappy/venv_pycharm/lib/python3.8/site-packages/undetected_chromedriver/patcher.py", line 209, in is_binary_patched
    with io.open(executable_path, "rb") as fh:
PermissionError: [Errno 1] Operation not permitted: '/Users/github-localhost/Downloads/chromedriver'
Exception ignored in: <function Chrome.__del__ at 0x101a660d0>
Traceback (most recent call last):
  File "/Users/github-localhost/Desktop/Projects/python_projects/att_scrappy/venv_pycharm/lib/python3.8/site-packages/undetected_chromedriver/v2.py", line 623, in __del__
    self.quit()
  File "/Users/github-localhost/Desktop/Projects/python_projects/att_scrappy/venv_pycharm/lib/python3.8/site-packages/undetected_chromedriver/v2.py", line 581, in quit
    self.service.process.kill()
AttributeError: 'Chrome' object has no attribute 'service'

**Comment by kyleliang919** [comment]
Not sure if it's related, but I am getting this on my M1 Macbook
```
OSError: [Errno 86] Bad CPU type in executable
```

**Comment by Juba1806** [comment]
same here

**Comment by Haris1996** [comment]
Install Rosetta this solved my issue

Here's How to install Rosetta 2 on the Mac is by using the familiar softwareupdate command line tool.

`softwareupdate --install-rosetta
`

This will launch the rosetta installer and you’ll have to agree to a license agreement, which I’m sure you’ll read completely and thoroughly as we all do every time we install anything on every device.

You can also skip the license agreement by providing an additional flag:

`/usr/sbin/softwareupdate --install-rosetta --agree-to-license`
