### ISSUE TITLE
Running into errors when attempting to have concurrent run

### ISSUE THREAD

**Issue by josephexequiel** [ultrafunkamsterdam/undetected-chromedriver#314]
INFO  | patching driver executable /home/joseph/.local/share/undetected_chromedriver/chromedriver
Traceback (most recent call last):
  File "action.py", line 347, in <module>
    selenium_object = SeleniumDriver(args)
  File "action.py", line 46, in __init__
    self.driver = uc.Chrome(options=chrome_options)
  File "/home/joseph/Code/python3_global/env/lib/python3.8/site-packages/undetected_chromedriver/v2.py", line 163, in __init__
    patcher.auto()
  File "/home/joseph/Code/python3_global/env/lib/python3.8/site-packages/undetected_chromedriver/patcher.py", line 121, in auto
    self.unzip_package(self.fetch_package())
  File "/home/joseph/Code/python3_global/env/lib/python3.8/site-packages/undetected_chromedriver/patcher.py", line 175, in unzip_package
    zf.extract(self.exe_name, os.path.dirname(self.executable_path))
  File "/usr/lib/python3.8/zipfile.py", line 1630, in extract
    return self._extract_member(member, path, pwd)
  File "/usr/lib/python3.8/zipfile.py", line 1701, in _extract_member
    open(targetpath, "wb") as target:
OSError: [Errno 26] Text file busy: '/home/joseph/.local/share/undetected_chromedriver/chromedriver'
Exception ignored in: <function Chrome.__del__ at 0x7f57acd63790>
Traceback (most recent call last):
  File "/home/joseph/Code/python3_global/env/lib/python3.8/site-packages/undetected_chromedriver/v2.py", line 623, in __del__
    self.quit()
  File "/home/joseph/Code/python3_global/env/lib/python3.8/site-packages/undetected_chromedriver/v2.py", line 581, in quit
    self.service.process.kill()
AttributeError: 'Chrome' object has no attribute 'service'

**Comment by josephexequiel** [comment]
Is it possible to declare a custom path for the chromedriver that is generated by uc.Chrome(options=chrome_options)?

**Comment by josephexequiel** [comment]
I just figured out a workaround for this one. We can use the executable path parameter to define a custom chromedriver:

uc.Chrome(options=chrome_options, executable_path='driver/chromedriver_1' ,)

**Comment by rbecerril** [comment]
> I just figured out a workaround for this one. We can use the executable path parameter to define a custom chromedriver:
> 
> uc.Chrome(options=chrome_options, executable_path='driver/chromedriver_1' ,)

I have the same problem, and I will try your workaround. This is not a problem with webdriver. I wonder why undetected_chromedriver needs to lock the file.

**Comment by rbecerril** [comment]
https://github.com/ultrafunkamsterdam/undetected-chromedriver/pull/434#issuecomment-1027029297
