### ISSUE TITLE
 undetected-chromedriver not running on VPS

### ISSUE THREAD

**Issue by makeukus** [ultrafunkamsterdam/undetected-chromedriver#320]
It works normally on PC, but it doesn't work on VPS. Please help me.

raceback (most recent call last):
  File "C:\douyin\2.py", line 2, in <module>
    driver = uc.Chrome()
  File "C:\Python39\lib\site-packages\undetected_chromedriver\v2.py", line 294, in __init__
    self.browser = subprocess.Popen(
  File "C:\Python39\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Python39\lib\subprocess.py", line 1360, in _execute_child
    args = list2cmdline(args)
  File "C:\Python39\lib\subprocess.py", line 565, in list2cmdline
    for arg in map(os.fsdecode, seq):
  File "C:\Python39\lib\os.py", line 822, in fsdecode
    filename = fspath(filename)  # Does type-checking of `filename`.
TypeError: expected str, bytes or os.PathLike object, not NoneType
Exception ignored in: <function Chrome.__del__ at 0x000002157FC191F0>
Traceback (most recent call last):
  File "C:\Python39\lib\site-packages\undetected_chromedriver\v2.py", line 623, in __del__
  File "C:\Python39\lib\site-packages\undetected_chromedriver\v2.py", line 581, in quit
AttributeError: 'Chrome' object has no attribute 'service'
![Screenshot (1)](https://user-images.githubusercontent.com/57167180/135008310-2d0c4179-5c10-42bd-89fd-94af8f1c107a.png)

**Comment by xjxckk** [comment]
That error means uc can't find Chrome.

Set the location of your chrome install manually with options.binary_location.:
options.binary_location = 'C:/Users/Administrator/AppData/Local/Chromium/Application/chrome.exe'

**Comment by makeukus** [comment]
Your help was very much appreciated

> That error means uc can't find Chrome.
> 
> Set the location of your chrome install manually with options.binary_location.: options.binary_location = 'C:/Users/Administrator/AppData/Local/Chromium/Application/chrome.exe'

Your help was greatly appreciated!

**Comment by makeukus** [comment]
> That error means uc can't find Chrome.
> 
> Set the location of your chrome install manually with options.binary_location.: options.binary_location = 'C:/Users/Administrator/AppData/Local/Chromium/Application/chrome.exe'

Your help was greatly appreciated
