### ISSUE TITLE
Unknown error cannot connect to Chrome error on VM

### ISSUE THREAD

**Issue by anthonypiccolo** [ultrafunkamsterdam/undetected-chromedriver#334]
I'm getting this Chromedriver error when running on a VM on GCP using the `ubuntu-2110-impish-v20211014` image. However, locally, the code runs fine. Any idea what this error actually means?

```Message: unknown error: cannot connect to chrome at 127.0.0.1:59993
from chrome not reachable
Stacktrace:
#0 0x556ec1c758f3 (/root/.local/share/undetected_chromedriver/chromedriver (deleted)+0xa2a8f2)
#1 0x556ec175aa3f (/root/.local/share/undetected_chromedriver/chromedriver (deleted)+0x50fa3e)
#2 0x556ec1749854 (/root/.local/share/undetected_chromedriver/chromedriver (deleted)+0x4fe853)
#3 0x556ec178128f (/root/.local/share/undetected_chromedriver/chromedriver (deleted)+0x53628e)
#4 0x556ec17791c6 (/root/.local/share/undetected_chromedriver/chromedriver (deleted)+0x52e1c5)
#5 0x556ec17b3995 (/root/.local/share/undetected_chromedriver/chromedriver (deleted)+0x568994)
#6 0x556ec17add63 (/root/.local/share/undetected_chromedriver/chromedriver (deleted)+0x562d62)
#7 0x556ec1784144 (/root/.local/share/undetected_chromedriver/chromedriver (deleted)+0x539143)
#8 0x556ec1785135 (/root/.local/share/undetected_chromedriver/chromedriver (deleted)+0x53a134)
#9 0x556ec1ca4c3e (/root/.local/share/undetected_chromedriver/chromedriver (deleted)+0xa59c3d)
#10 0x556ec1cba6b7 (/root/.local/share/undetected_chromedriver/chromedriver (deleted)+0xa6f6b6)
#11 0x556ec1ca5b95 (/root/.local/share/undetected_chromedriver/chromedriver (deleted)+0xa5ab94)
#12 0x556ec1cbbb05 (/root/.local/share/undetected_chromedriver/chromedriver (deleted)+0xa70b04)
#13 0x556ec1c9a2ab (/root/.local/share/undetected_chromedriver/chromedriver (deleted)+0xa4f2aa)
#14 0x556ec1cd6248 (/root/.local/share/undetected_chromedriver/chromedriver (deleted)+0xa8b247)
#15 0x556ec1cd63c8 (/root/.local/share/undetected_chromedriver/chromedriver (deleted)+0xa8b3c7)
#16 0x556ec1cf133d (/root/.local/share/undetected_chromedriver/chromedriver (deleted)+0xaa633c)
#17 0x7f7de4ceb927 <unknown>
Exception ignored in: <function Chrome.__del__ at 0x7f98b377d430>
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/undetected_chromedriver/v2.py", line 623, in __del__
    self.quit()
  File "/usr/local/lib/python3.9/dist-packages/undetected_chromedriver/v2.py", line 581, in quit
    self.service.process.kill()
AttributeError: 'NoneType' object has no attribute 'kill'```

**Comment by anthonypiccolo** [comment]
Also, to clarify current options and libraries imported are as follows:

```
from os import curdir
from seleniumwire import webdriver
from seleniumwire.undetected_chromedriver.v2 import Chrome, ChromeOptions
import undetected_chromedriver.v2 as uc
import time
import pathlib
import math, random
import logging
import requests

def set_chrome_settings():
    """ set up the chrome settings """
    #interesting thread here https://intoli.com/blog/making-chrome-headless-undetectable/
    chrome_options = Options()
    user_agent = 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.50 Safari/537.36'
    chrome_options.add_argument("--headless")
    chrome_options.add_argument(f'user-agent={user_agent}')
    chrome_options.add_argument("--disable-gpu")
    chrome_options.add_argument("--no-sandbox")
    chrome_options.add_argument("--disable-dev-shm-usage")
    chrome_options.add_argument("--window-size=1920,1200")
    ```
