### ISSUE TITLE
cronjob fails: encountering TypeError & AttributeError

### ISSUE THREAD

**Issue by nhwalkman** [ultrafunkamsterdam/undetected-chromedriver#347]
My python script runs/executes without any errors from bash shell but fails from crontab. 
I don't understand why I'm getting a TypeError & AttributeError when my python script is run from crontab. Please advise.

kubuntu 20.0.4 LTS
GNU bash, version 5.0.17(1)-release (x86_64-pc-linux-gnu)
python 3.8.10 [GCC9.3.0]
Chromium installed & updated via snap( current version 95.0.4638.54)
ChromeDriver 95.0.4638.54 (permissions = 0755)

crontab notes from "man" on 20.0.4 LTS:
    The crontab command conforms to IEEE Std1003.2-1992 (``POSIX'').  
    This new command syntax differs from previous versions of Vixie Cron, as well as from the classic SVR3 syntax.

I can't get my python script to execute from a cronjob, but it runs perfectly from the bash shell.
I've tried adding chromedriver's path to the cron environment path, but this still fails.
I've tried using chromium's path installed via snap (/snap/bin/chromium), this also produces errors(different).

---crontab environment settings
SHELL=/bin/bash
PATH=/sbin:/bin:/usr/sbin:/usr/bin:/home/me/.local/bin
MAILTO=me
HOME=/home/me
---this cron environment variable is for necessary for kubuntu v16.0.4, v18.0.4 to get python scripts using selenium webdriver to work
DISPLAY=:0

relevant code in python
`import undetected_chromedriver.v2 as uc`
`opts = uc.ChromeOptions()`
`opts.add_argument("--window-size=1400,900")`
`chrome_path = '/home/me/.local/bin/chromedriver`
`browser = uc.Chrome(options=opts, executable_path=chrome_path)`

ERROR MSG
Traceback (most recent call last):
  File "/home/me/scripts/py34/ino.com/Kub04SelundChrom04a.py", line 286, in <module>
    browser = uc.Chrome(options=opts, executable_path=chrome_path)
  File "/usr/local/lib/python3.8/dist-packages/undetected_chromedriver/v2.py", line 294, in __init__
    self.browser = subprocess.Popen(
  File "/usr/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1585, in _execute_child
    and os.path.dirname(executable)
  File "/usr/lib/python3.8/posixpath.py", line 152, in dirname
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not NoneType
Exception ignored in: <function Chrome.__del__ at 0x7f18e7fcd5e0>
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/undetected_chromedriver/v2.py", line 623, in __del__
  File "/usr/local/lib/python3.8/dist-packages/undetected_chromedriver/v2.py", line 581, in quit
AttributeError: 'Chrome' object has no attribute 'service'

**Comment by QIN2DIM** [comment]
hi.I just ran into this problem in development, but I found a solution. 

just... do you have Chrome installed?

**Comment by QIN2DIM** [comment]
Chrome bro! Not chromium

**Comment by nhwalkman** [comment]
Nice.
I've been banging around with this for 10 weeks. And I got to the same idea as you, but here's my method for getting the version

> cvn = os.popen('chromium-browser --version').read().strip()
> p = cvn.split()
> major_version_number = p[1].split('.')[0]
> browser = uc.Chrome(version_main=major_version_number)


As for using chromium, it works just fine. The issue was finding the correct path and using the author's new method for v3.1+ "browser_executable_path="

> chrome_path = '/usr/lib/chromium-browser/chromium-browser'   (native install)
> if host == 'snap_based_ubuntu' or host == 'snap_based_kubuntu':
> ......chrome_path = '/snap/chromium/1895/usr/lib/chromium-browser/chrome'  (snap install)
> browser = uc.Chrome(options=opts, browser_executable_path=chrome_path, version_main=major_version_number)
> 

But for clarity, when I posted this behavior, I was using an older UC version(v3.0.3). And that version required chromedriver to be installed. Now with 3.1+, UC fetches all current drivers automatically. We no longer need to fetch and install "chromedriver".
This upgrade from the author eliminated the conflict of being out of sync between: chromedriver version versus chrome/chromium version and uc version.

**Comment by nhwalkman** [comment]
Nice. I stopped trying to use headless mode months ago b/c of the author's README

> just to mention it another time, since some people have hard time reading: headless is still WIP. Raising issues is needless

But now, after your example, I'll try again. 

BTW, Kudos to the author of UC for the continued steady progress. I'm sure this is a never ending game of "cat and mouse"
