### ISSUE TITLE
cannot import name 'Mapping' from 'collections'

### ISSUE THREAD

**Issue by lobatim** [ultrafunkamsterdam/undetected-chromedriver#356]
I get this error when I import undetected_chromedriver, someone can help me ?
```
>>> import undetected_chromedriver as uc
Traceback (most recent call last):
  File "<input>", line 1, in <module>
    import undetected_chromedriver as uc
  File "/home/lobatim/.local/lib/python3.10/site-packages/undetected_chromedriver/__init__.py", line 31, in <module>
    from . import v2
  File "/home/lobatim/.local/lib/python3.10/site-packages/undetected_chromedriver/v2.py", line 21, in <module>
    from .cdp import CDP
  File "/home/lobatim/.local/lib/python3.10/site-packages/undetected_chromedriver/cdp.py", line 6, in <module>
    from collections import Mapping, Sequence
ImportError: cannot import name 'Mapping' from 'collections' (/usr/lib64/python3.10/collections/__init__.py)
```

**Comment by Mohamed-0-Amine** [comment]
me too
How did u solve it

**Comment by lobatim** [comment]
Yes. I installed python 3.7 and solved the problem

Em seg., 22 de nov. de 2021 16:38, Mohamed-0-Amine ***@***.***>
escreveu:
