### ISSUE TITLE
AttributeError: 'Chrome' object has no attribute 'keep_user_data_dir'

### ISSUE THREAD

**Issue by Oleh-Hrebchuk** [ultrafunkamsterdam/undetected-chromedriver#359]
Connected to pydev debugger (build 212.5457.59)
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 1317, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1229, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1275, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1224, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1016, in _send_output
    self.send(msg)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 956, in send
    self.connect()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1392, in connect
    server_hostname=server_hostname)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 412, in wrap_socket
    session=session
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 853, in _create
    self.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 1117, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1051)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 1319, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1051)>
python-BaseException
Exception ignored in: <function Chrome.__del__ at 0x7fed6bb63488>
Traceback (most recent call last):
  File "/Users/oleh/Projects/store-in-stocks/venv/lib/python3.7/site-packages/undetected_chromedriver/v2.py", line 590, in __del__
    self.quit()
  File "/Users/oleh/Projects/store-in-stocks/venv/lib/python3.7/site-packages/undetected_chromedriver/v2.py", line 573, in quit
    if not self.keep_user_data_dir or self.keep_user_data_dir is False:
AttributeError: 'Chrome' object has no attribute 'keep_user_data_dir'

Process finished with exit code 1

**Comment by Duartemartins** [comment]
I have the same issue using python 3.8.10 and UC 3.0.2
