### ISSUE TITLE
Docker issue

### ISSUE THREAD

**Issue by iDevo** [ultrafunkamsterdam/undetected-chromedriver#370]
Hi there, 
thank you first of all for making this great package! 

I got everything running locally and are currently preparing my python code for Docker deployment. 
I am using amazon linux latest version with python 3.9 installed. 

I can install all my python packages using pip in my Dockerfile but for some reason only undetected-chromedriver is failing

```
Step 26/29 : RUN pip install undetected_chromedriver~=3.0.5
 ---> Running in 61da03a92802
Collecting undetected_chromedriver~=3.0.5
  Downloading undetected-chromedriver-3.0.5.tar.gz (40 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
  ERROR: Command errored out with exit status 1:
   command: /usr/local/bin/python3.9 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-qqel5z8q/undetected-chromedriver_655ce593b1264528a3a5943ba9489577/setup.py'"'"'; __file__='"'"'/tmp/pip-install-qqel5z8q/undetected-chromedriver_655ce593b1264528a3a5943ba9489577/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-y___g8dk
       cwd: /tmp/pip-install-qqel5z8q/undetected-chromedriver_655ce593b1264528a3a5943ba9489577/
  Complete output (26 lines):
  running egg_info
  creating /tmp/pip-pip-egg-info-y___g8dk/undetected_chromedriver.egg-info
  writing /tmp/pip-pip-egg-info-y___g8dk/undetected_chromedriver.egg-info/PKG-INFO
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-qqel5z8q/undetected-chromedriver_655ce593b1264528a3a5943ba9489577/setup.py", line 33, in <module>
      setup(
    File "/usr/local/lib/python3.9/site-packages/setuptools/__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "/usr/local/lib/python3.9/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/local/lib/python3.9/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/usr/local/lib/python3.9/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/usr/local/lib/python3.9/site-packages/setuptools/command/egg_info.py", line 292, in run
      writer(self, ep.name, os.path.join(self.egg_info, ep.name))
    File "/usr/local/lib/python3.9/site-packages/setuptools/command/egg_info.py", line 656, in write_pkg_info
      metadata.write_pkg_info(cmd.egg_info)
    File "/usr/local/lib/python3.9/distutils/dist.py", line 1117, in write_pkg_info
      self.write_pkg_file(pkg_info)
    File "/usr/local/lib/python3.9/site-packages/setuptools/dist.py", line 167, in write_pkg_file
      write_field('Summary', single_line(self.get_description()))
    File "/usr/local/lib/python3.9/site-packages/setuptools/dist.py", line 151, in single_line
      raise ValueError('Newlines are not allowed')
  ValueError: Newlines are not allowed
  ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/a1/00/9cabdd21f62efda54d6a01e972b66bb392fafc1f2f332e9f04974158d53e/undetected-chromedriver-3.0.5.tar.gz#sha256=9678c96b6678a421f660f0eeb5793d937dc8a1ff91e4238e04a0705da2cb0125 (from https://pypi.org/simple/undetected-chromedriver/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement undetected_chromedriver~=3.0.5 (from versions: 1.3.5, 1.3.6, 1.3.7, 1.4.0, 1.4.2, 1.5.0, 1.5.1, 1.5.2, 2.0b0, 2.0.0, 2.0.1, 2.0.2, 2.1.0, 2.1.1, 2.1.2, 2.2.0, 2.2.1, 2.2.7, 3.0.0, 3.0.1, 3.0.2, 3.0.3, 3.0.4, 3.0.5)
ERROR: No matching distribution found for undetected_chromedriver~=3.0.5
```

The interesting part is that when I do not specify a explicit version, pip retries all versions down until 1.4.0 which is then succeeding: 

```
  Downloading undetected_chromedriver-1.4.0-py3-none-any.whl (18 kB)
Collecting selenium
  Downloading selenium-4.1.0-py3-none-any.whl (958 kB)
Collecting urllib3[secure]~=1.26
  Downloading urllib3-1.26.7-py2.py3-none-any.whl (138 kB)
Collecting trio~=0.17
  Downloading trio-0.19.0-py3-none-any.whl (356 kB)
Collecting trio-websocket~=0.9
  Downloading trio_websocket-0.9.2-py3-none-any.whl (16 kB)
Collecting attrs>=19.2.0
  Downloading attrs-21.2.0-py2.py3-none-any.whl (53 kB)
Collecting outcome
  Downloading outcome-1.1.0-py2.py3-none-any.whl (9.7 kB)
Collecting sniffio
  Downloading sniffio-1.2.0-py3-none-any.whl (10 kB)
Collecting async-generator>=1.9
  Downloading async_generator-1.10-py3-none-any.whl (18 kB)
Collecting idna
  Downloading idna-3.3-py3-none-any.whl (61 kB)
Collecting sortedcontainers
  Downloading sortedcontainers-2.4.0-py2.py3-none-any.whl (29 kB)
Collecting wsproto>=0.14
  Downloading wsproto-1.0.0-py3-none-any.whl (24 kB)
Collecting cryptography>=1.3.4
  Downloading cryptography-36.0.0-cp36-abi3-manylinux_2_24_x86_64.whl (3.6 MB)
Collecting pyOpenSSL>=0.14
  Downloading pyOpenSSL-21.0.0-py2.py3-none-any.whl (55 kB)
Collecting certifi
  Downloading certifi-2021.10.8-py2.py3-none-any.whl (149 kB)
Collecting cffi>=1.12
  Downloading cffi-1.15.0-cp39-cp39-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (444 kB)
Collecting six>=1.5.2
  Downloading six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting h11<1,>=0.9.0
  Downloading h11-0.12.0-py3-none-any.whl (54 kB)
Collecting pycparser
  Downloading pycparser-2.21-py2.py3-none-any.whl (118 kB)
Installing collected packages: pycparser, cffi, attrs, sortedcontainers, sniffio, six, outcome, idna, h11, cryptography, async-generator, wsproto, urllib3, trio, pyOpenSSL, certifi, trio-websocket, selenium, undetected-chromedriver
```

Until this is a very specific issue I do understand that this might be a bit time consuming to find out but still I wanted to share, in case someone remembers what happened between 1.4.0 and after.

Anyway I will further investigate on my own and share results when I find something. 

Thank you! 

**EDIT here my Dockerfile**

```
FROM public.ecr.aws/amazonlinux/amazonlinux:latest

# Needed libraries
RUN yum update -y
RUN yum install -y wget xvfb unzip curl

# Install python 3.9
RUN yum -y groupinstall "Development Tools"
RUN yum -y install gcc openssl-devel bzip2-devel libffi-devel
RUN wget https://www.python.org/ftp/python/3.9.7/Python-3.9.7.tgz
RUN tar zxvf Python-3.9.7.tgz
RUN (cd ./Python-3.9.7 && ./configure)
RUN ls ./Python-3.9.7/
RUN (cd ./Python-3.9.7/ && make)
RUN (cd ./Python-3.9.7/ && make altinstall)
RUN python3.9 --version

# Install pip
RUN python3.9 -m pip install -U pip
RUN python3.9 -m pip install -U setuptools

# Set up the Chrome PPA
RUN wget https://dl.google.com/linux/direct/google-chrome-stable_current_x86_64.rpm
RUN yum install -y ./google-chrome-stable_current_*.rpm

# Install Chrome
RUN yum install -y google-chrome-stable
RUN google-chrome-stable --version
RUN google-chrome --version

# DO NOT USE YUM AFTER THIS POINT

# Set default
RUN ln -fs /usr/local/bin/python3.9 /usr/bin/python
RUN ln -fs /usr/local/bin/pip3.9 /usr/bin/pip

# Double check versions
RUN python --version
RUN python3.9 --version
RUN pip --version
RUN pip3.9 --version

# Copy all data into docker container
COPY . .

# Test undetected_chromedriver
RUN pip install undetected_chromedriver

# Install all pip packages
RUN pip install -r requirements.txt

# Set entrypoint
CMD [ "python", "./venv/include/main.py" ]
```

**Comment by MC1R-13** [comment]
Don't think it's limited to Docker.  I don't use it and am having the same issue on macOS 11.6.1 (Big Sur) with Python 3.9.9.  Other than that, I can't really add much.  Basically had the same errors and ended up with version 1.4.0.

**Comment by iDevo** [comment]
Good to hear someone else have this issue too. 
I am testing also on a macOS 11.4 / python 3.9.4 but for me it works fine locally. 

I am not super deep into the abstraction layers with python but maybe it has something to do with the architecture.

**Comment by ultrafunkamsterdam** [comment]
you may use pip jnstall undetected-chromedriver (mind the DASH)

**Comment by iDevo** [comment]
Hi @ultrafunkamsterdam thanks for your comment, stupid mistake but I just saw pip actually automatically corrected it (please find logs in my first post): `Downloading undetected-chromedriver-3.0.5.tar.gz`

Of course I also changed the line in my code but getting the same error. 

Maybe you have another hint, thank you so much for helping! 

```
Collecting undetected-chromedriver~=3.0.5
  Downloading undetected-chromedriver-3.0.5.tar.gz (40 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
  ERROR: Command errored out with exit status 1:
   command: /usr/local/bin/python3.9 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ad6lv0a0/undetected-chromedriver_10e6aad8a7c24151aef5136739756e75/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ad6lv0a0/undetected-chromedriver_10e6aad8a7c24151aef5136739756e75/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-msd2emgm
       cwd: /tmp/pip-install-ad6lv0a0/undetected-chromedriver_10e6aad8a7c24151aef5136739756e75/
  Complete output (26 lines):
  running egg_info
  creating /tmp/pip-pip-egg-info-msd2emgm/undetected_chromedriver.egg-info
  writing /tmp/pip-pip-egg-info-msd2emgm/undetected_chromedriver.egg-info/PKG-INFO
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-ad6lv0a0/undetected-chromedriver_10e6aad8a7c24151aef5136739756e75/setup.py", line 33, in <module>
      setup(
    File "/usr/local/lib/python3.9/site-packages/setuptools/__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "/usr/local/lib/python3.9/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/local/lib/python3.9/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/usr/local/lib/python3.9/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/usr/local/lib/python3.9/site-packages/setuptools/command/egg_info.py", line 292, in run
      writer(self, ep.name, os.path.join(self.egg_info, ep.name))
    File "/usr/local/lib/python3.9/site-packages/setuptools/command/egg_info.py", line 656, in write_pkg_info
      metadata.write_pkg_info(cmd.egg_info)
    File "/usr/local/lib/python3.9/distutils/dist.py", line 1117, in write_pkg_info
      self.write_pkg_file(pkg_info)
    File "/usr/local/lib/python3.9/site-packages/setuptools/dist.py", line 167, in write_pkg_file
      write_field('Summary', single_line(self.get_description()))
    File "/usr/local/lib/python3.9/site-packages/setuptools/dist.py", line 151, in single_line
      raise ValueError('Newlines are not allowed')
  ValueError: Newlines are not allowed
  ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/a1/00/9cabdd21f62efda54d6a01e972b66bb392fafc1f2f332e9f04974158d53e/undetected-chromedriver-3.0.5.tar.gz#sha256=9678c96b6678a421f660f0eeb5793d937dc8a1ff91e4238e04a0705da2cb0125 (from https://pypi.org/simple/undetected-chromedriver/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement undetected-chromedriver~=3.0.5 (from versions: 1.3.5, 1.3.6, 1.3.7, 1.4.0, 1.4.2, 1.5.0, 1.5.1, 1.5.2, 2.0b0, 2.0.0, 2.0.1, 2.0.2, 2.1.0, 2.1.1, 2.1.2, 2.2.0, 2.2.1, 2.2.7, 3.0.0, 3.0.1, 3.0.2, 3.0.3, 3.0.4, 3.0.5)
ERROR: No matching distribution found for undetected-chromedriver~=3.0.5
```

**Comment by linrongbin16** [comment]
same issue, using `sudo pip3 install undetected-chromedriver` in macOS 10.14.
iterate from 3.0.6 until 1.4.0, finally 1.4.0 installed.

**Comment by hanzhaozxd** [comment]
same issue. My operating environment is `Python 3.9.9` in macOS 12.1 on Apple M1 Max
I changed version to `Python 3.8.12` and It works

**Comment by ultrafunkamsterdam** [comment]
https://hub.docker.com/r/ultrafunk/undetected-chromedriver

**Comment by Anticope12** [comment]
Hi @ultrafunkamsterdam , Thank you for sharing the Docker Image, 

I'm wondering if you could advise/help with connecting Python with This docker image via a Remote connection.

driver = webdriver.Remote("http://127.0.0.1:4444/wd/hub")

In my process, every browser would have an isolated container. Would really appreciate your thoughts.

**Comment by Write** [comment]
> Hi @ultrafunkamsterdam , Thank you for sharing the Docker Image,
> 
> I'm wondering if you could advise/help with connecting Python with This docker image via a Remote connection.
> 
> driver = webdriver.Remote("http://127.0.0.1:4444/wd/hub")
> 
> In my process, every browser would have an isolated container. Would really appreciate your thoughts.

Same question here, would be awesome :)

**Comment by iamumairayub** [comment]
> Hi @ultrafunkamsterdam , Thank you for sharing the Docker Image,
> 
> I'm wondering if you could advise/help with connecting Python with This docker image via a Remote connection.
> 
> driver = webdriver.Remote("http://127.0.0.1:4444/wd/hub")
> 
> In my process, every browser would have an isolated container. Would really appreciate your thoughts.

I was wondering the same!
