### ISSUE TITLE
Docker Issue 2

### ISSUE THREAD

**Issue by iDevo** [ultrafunkamsterdam/undetected-chromedriver#375]
Hi there, 
thank you first of all for making this great package! 

I am referring to ticket #370 because it is closed by a misunderstanding and I would like to keep the chance that maybe someone has the same issue. 

I got everything running locally and are currently preparing my python code for Docker deployment. 
I am using amazon linux latest version with python 3.9 installed. 

I can install all my python packages using pip in my Dockerfile but for some reason only undetected-chromedriver (mind the dash)  is failing

**Dockerfile**

```
FROM public.ecr.aws/amazonlinux/amazonlinux:latest

# Needed libraries
RUN yum update -y
RUN yum install -y wget xvfb unzip curl

# Install python 3.9
RUN yum -y groupinstall "Development Tools"
RUN yum -y install gcc openssl-devel bzip2-devel libffi-devel
RUN wget https://www.python.org/ftp/python/3.9.7/Python-3.9.7.tgz
RUN tar zxvf Python-3.9.7.tgz
RUN (cd ./Python-3.9.7 && ./configure)
RUN ls ./Python-3.9.7/
RUN (cd ./Python-3.9.7/ && make)
RUN (cd ./Python-3.9.7/ && make altinstall)
RUN python3.9 --version

# Install pip
RUN python3.9 -m pip install -U pip
RUN python3.9 -m pip install -U setuptools

# Set up the Chrome PPA
RUN wget https://dl.google.com/linux/direct/google-chrome-stable_current_x86_64.rpm
RUN yum install -y ./google-chrome-stable_current_*.rpm

# Install Chrome
RUN yum install -y google-chrome-stable
RUN google-chrome-stable --version
RUN google-chrome --version

# DO NOT USE YUM AFTER THIS POINT

# Set default
RUN ln -fs /usr/local/bin/python3.9 /usr/bin/python
RUN ln -fs /usr/local/bin/pip3.9 /usr/bin/pip

# Double check versions
RUN python --version
RUN python3.9 --version
RUN pip --version
RUN pip3.9 --version

# Copy all data into docker container
COPY . .

# Test undetected-chromedriver
RUN pip install undetected-chromedriver~=3.0.5

# Install all pip packages
RUN pip install -r requirements.txt

# Set entrypoint
CMD [ "python", "./venv/include/main.py" ]
```

**Installation logs**

```
Step 27/29 : RUN pip install undetected-chromedriver
 ---> Running in 2625abb4d3a4
Collecting undetected-chromedriver
  Downloading undetected-chromedriver-3.0.5.tar.gz (40 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
  ERROR: Command errored out with exit status 1:
   command: /usr/local/bin/python3.9 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-yrcj8j5f/undetected-chromedriver_cd187522933b46248153ae246989880e/setup.py'"'"'; __file__='"'"'/tmp/pip-install-yrcj8j5f/undetected-chromedriver_cd187522933b46248153ae246989880e/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-bcnx9tvu
       cwd: /tmp/pip-install-yrcj8j5f/undetected-chromedriver_cd187522933b46248153ae246989880e/
  Complete output (26 lines):
  running egg_info
  creating /tmp/pip-pip-egg-info-bcnx9tvu/undetected_chromedriver.egg-info
  writing /tmp/pip-pip-egg-info-bcnx9tvu/undetected_chromedriver.egg-info/PKG-INFO
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-yrcj8j5f/undetected-chromedriver_cd187522933b46248153ae246989880e/setup.py", line 33, in <module>
      setup(
    File "/usr/local/lib/python3.9/site-packages/setuptools/__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "/usr/local/lib/python3.9/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/local/lib/python3.9/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/usr/local/lib/python3.9/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/usr/local/lib/python3.9/site-packages/setuptools/command/egg_info.py", line 292, in run
      writer(self, ep.name, os.path.join(self.egg_info, ep.name))
    File "/usr/local/lib/python3.9/site-packages/setuptools/command/egg_info.py", line 656, in write_pkg_info
      metadata.write_pkg_info(cmd.egg_info)
    File "/usr/local/lib/python3.9/distutils/dist.py", line 1117, in write_pkg_info
      self.write_pkg_file(pkg_info)
    File "/usr/local/lib/python3.9/site-packages/setuptools/dist.py", line 167, in write_pkg_file
      write_field('Summary', single_line(self.get_description()))
    File "/usr/local/lib/python3.9/site-packages/setuptools/dist.py", line 151, in single_line
      raise ValueError('Newlines are not allowed')
  ValueError: Newlines are not allowed
  ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/a1/00/9cabdd21f62efda54d6a01e972b66bb392fafc1f2f332e9f04974158d53e/undetected-chromedriver-3.0.5.tar.gz#sha256=9678c96b6678a421f660f0eeb5793d937dc8a1ff91e4238e04a0705da2cb0125 (from https://pypi.org/simple/undetected-chromedriver/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

The interesting part is that when I do not specify a explicit version, pip retries all versions down until 1.4.0 which is then succeeding: 

```
  Downloading undetected-chromedriver-1.4.2.tar.gz (5.8 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
  ERROR: Command errored out with exit status 1:
   command: /usr/local/bin/python3.9 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-yrcj8j5f/undetected-chromedriver_ebedb57f8f6a4e7a820167c4427f1a37/setup.py'"'"'; __file__='"'"'/tmp/pip-install-yrcj8j5f/undetected-chromedriver_ebedb57f8f6a4e7a820167c4427f1a37/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-d63mwsne
       cwd: /tmp/pip-install-yrcj8j5f/undetected-chromedriver_ebedb57f8f6a4e7a820167c4427f1a37/
  Complete output (26 lines):
  running egg_info
  creating /tmp/pip-pip-egg-info-d63mwsne/undetected_chromedriver.egg-info
  writing /tmp/pip-pip-egg-info-d63mwsne/undetected_chromedriver.egg-info/PKG-INFO
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-yrcj8j5f/undetected-chromedriver_ebedb57f8f6a4e7a820167c4427f1a37/setup.py", line 17, in <module>
      setup(
    File "/usr/local/lib/python3.9/site-packages/setuptools/__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "/usr/local/lib/python3.9/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/local/lib/python3.9/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/usr/local/lib/python3.9/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/usr/local/lib/python3.9/site-packages/setuptools/command/egg_info.py", line 292, in run
      writer(self, ep.name, os.path.join(self.egg_info, ep.name))
    File "/usr/local/lib/python3.9/site-packages/setuptools/command/egg_info.py", line 656, in write_pkg_info
      metadata.write_pkg_info(cmd.egg_info)
    File "/usr/local/lib/python3.9/distutils/dist.py", line 1117, in write_pkg_info
      self.write_pkg_file(pkg_info)
    File "/usr/local/lib/python3.9/site-packages/setuptools/dist.py", line 167, in write_pkg_file
      write_field('Summary', single_line(self.get_description()))
    File "/usr/local/lib/python3.9/site-packages/setuptools/dist.py", line 151, in single_line
      raise ValueError('Newlines are not allowed')
  ValueError: Newlines are not allowed
  ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/bd/4a/a1a79eba316b415810b0d45783a836aa48775b142f5e4d278d77757e517e/undetected-chromedriver-1.4.2.tar.gz#sha256=177bc3424c2b5d7cb11ddc07b8a876fbeedd59921be3de6f592cab24fa66ce4f (from https://pypi.org/simple/undetected-chromedriver/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

  Downloading undetected_chromedriver-1.4.0-py3-none-any.whl (18 kB)
```

Please not the last line above, where it is retrying every possible version from 3.0.5 down to 1.4.0 until this version finally succeeds installing.

Until this is a very specific issue I do understand that this might be a bit time consuming to find out but still I wanted to share, in case someone remembers what happened between 1.4.0 and after.

Anyway I will further investigate on my own and share results when I find something. 

Thank you!

**Comment by mostdoqe** [comment]
Hello could you give me your discord or telegram

**Comment by iDevo** [comment]
Hi @mostdoqe, my username on Telegram is iDevo2

**Comment by Adwich** [comment]
Hi @iDevo, also having this issue.

i'm on mac using python3. It was working perfectly but failed after setting up my code on Docker for Lambda.

now it does not work either.

Did you found a solution ?

**Comment by brandfocus** [comment]
Simple fix in https://github.com/ultrafunkamsterdam/undetected-chromedriver/pull/420
