### ISSUE TITLE
FileNotFoundError when creating Chrome driver

### ISSUE THREAD

**Issue by craneworks** [ultrafunkamsterdam/undetected-chromedriver#378]
I tried using the lib but I can't even start it.
Selenium itself is working fine.

```
$ python3 --version
Python 3.9.7

$ pip3 freeze
undetected-chromedriver==3.0.6
selenium==4.0.0
selenium-wire==4.5.6
requests==2.26.0
[...]
```

```
import undetected_chromedriver.v2 as uc
driver = uc.Chrome()

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/usr/local/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/usr/local/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/usr/local/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/usr/local/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 267, in run_path
    code, fname = _get_code_from_file(run_name, path_name)
  File "/usr/local/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 237, in _get_code_from_file
    with io.open_code(decoded_path) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/crane/my_project/<input>'
```

**Comment by craneworks** [comment]
I reseted my hole env and tried to debug whats going on.
My problem is now gone but looks now like https://github.com/ultrafunkamsterdam/undetected-chromedriver/issues/384
Will document there further. :)
