### ISSUE TITLE
No module named 'undetected_chromedriver.v2'

### ISSUE THREAD

**Issue by HelloAllenZHU** [ultrafunkamsterdam/undetected-chromedriver#403]
My code below:

```
import undetected_chromedriver.v2 as uc
driver = uc.Chrome()
driver.get('https://nowsecure.nl')
```

**Comment by richdevid** [comment]
Try reinstalling the module.
pip install undetected-chromedriver

**Comment by HelloAllenZHU** [comment]
> Try reinstalling the module. pip install undetected-chromedriver

Thanks!

**Comment by apetrichkovich** [comment]
Hello.
Reinstalling makes nothing with this error.

```
python -V

Python 3.10.7
```

```
pip install undetected-chromedriver
Requirement already satisfied: undetected-chromedriver in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (3.1.5.post4)
Requirement already satisfied: selenium>=4.0.0 in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from undetected-chromedriver) (4.5.0)
Requirement already satisfied: requests in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from undetected-chromedriver) (2.28.1)
Requirement already satisfied: websockets in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from undetected-chromedriver) (10.3)
Requirement already satisfied: trio-websocket~=0.9 in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from selenium>=4.0.0->undetected-chromedriver) (0.9.2)
Requirement already satisfied: urllib3[socks]~=1.26 in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from selenium>=4.0.0->undetected-chromedriver) (1.26.12)
Requirement already satisfied: certifi>=2021.10.8 in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from selenium>=4.0.0->undetected-chromedriver) (2022.9.24)
Requirement already satisfied: trio~=0.17 in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from selenium>=4.0.0->undetected-chromedriver) (0.22.0)
Requirement already satisfied: charset-normalizer<3,>=2 in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from requests->undetected-chromedriver) (2.1.1)
Requirement already satisfied: idna<4,>=2.5 in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from requests->undetected-chromedriver) (3.4)
Requirement already satisfied: attrs>=19.2.0 in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from trio~=0.17->selenium>=4.0.0->undetected-chromedriver) (22.1.0)
Requirement already satisfied: exceptiongroup>=1.0.0rc9 in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from trio~=0.17->selenium>=4.0.0->undetected-chromedriver) (1.0.0rc9)
Requirement already satisfied: sortedcontainers in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from trio~=0.17->selenium>=4.0.0->undetected-chromedriver) (2.4.0)
Requirement already satisfied: cffi>=1.14 in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from trio~=0.17->selenium>=4.0.0->undetected-chromedriver) (1.15.1)
Requirement already satisfied: async-generator>=1.9 in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from trio~=0.17->selenium>=4.0.0->undetected-chromedriver) (1.10)
Requirement already satisfied: sniffio in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from trio~=0.17->selenium>=4.0.0->undetected-chromedriver) (1.3.0)
Requirement already satisfied: outcome in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from trio~=0.17->selenium>=4.0.0->undetected-chromedriver) (1.2.0)
Requirement already satisfied: wsproto>=0.14 in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from trio-websocket~=0.9->selenium>=4.0.0->undetected-chromedriver) (1.2.0)
Requirement already satisfied: PySocks!=1.5.7,<2.0,>=1.5.6 in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from urllib3[socks]~=1.26->selenium>=4.0.0->undetected-chromedriver) (1.7.1)
Requirement already satisfied: pycparser in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from cffi>=1.14->trio~=0.17->selenium>=4.0.0->undetected-chromedriver) (2.21)
Requirement already satisfied: h11<1,>=0.9.0 in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from wsproto>=0.14->trio-websocket~=0.9->selenium>=4.0.0->undetected-chromedriver) (0.14.0)
```

```
import undetected_chromedriver.v2 as uc
driver = uc.Chrome()
driver.get('https://xxx.io')
```

```
python undetected_chromedriver.py
Traceback (most recent call last):
  File "C:\projects\undetected_chromedriver.py", line 1, in <module>
    import undetected_chromedriver.v2 as uc
  File "C:\projects\undetected_chromedriver.py", line 1, in <module>
    import undetected_chromedriver.v2 as uc
ModuleNotFoundError: No module named 'undetected_chromedriver.v2'; 'undetected_chromedriver' is not a package
```

**Comment by ultrafunkamsterdam** [comment]
RTFM

**Comment by apetrichkovich** [comment]
I have moved to Java/Selenium/Chrome.

**Comment by LucasGorgal** [comment]
I had the same err and I fixed by checking that pip was using another python install than the python command

**Comment by firmshare** [comment]
Same issue on Debian 11 . In pip and pip3 packages list i can see it. 
But when i try to run test script, i get error:
`root@debian-s-1vcpu-1gb-amd-nyc3-01:~# python3 chromedriver.py
Traceback (most recent call last):
  File "/root/chromedriver.py", line 1, in <module>
    import undetected_chromedriver.v2 as uc
ModuleNotFoundError: No module named 'undetected_chromedriver'
`

**Comment by acidbotmaker** [comment]
Same issue.
When I tried building docker image (from debian buster python 3.8), it was working before but today it started to fail.
Even though I'm using pipfile and pipfile.lock for same version.

**Comment by acidbotmaker** [comment]
It's given in the latest readme docs [here](https://github.com/ultrafunkamsterdam/undetected-chromedriver#310).
After changing from  `import undetected_chromedriver.v2 as uc` to  `import undetected_chromedriver as uc`.
Worked for me.

**Comment by g3th** [comment]
The problem persists with the import as requested in the 'RTFM':

```import undetected_chromedriver``` (without .v2)

Moreover there are a myriad of other problems which make the library not really worth using most of the time, like for instance being able to detect which Chrome version is being used.

Just stick to vanilla webdriver or use the library on something other than Windows.

**Comment by Raulbarossi** [comment]
ao digitar code . em alguma pasta do wsl ele abre o vscode normal no meu windows, mas n sei se é algo configurado ou por padrão ele abriria no host, mas qnd tentei rodar sem ter o chrome no arch do wsl ele avisou e eu instalei com yay antes de chegar a esse ponto
