### ISSUE TITLE
How to create exe with undetected-chromedriver with Pyinstaller?

### ISSUE THREAD

**Issue by saintdanelimbu** [ultrafunkamsterdam/undetected-chromedriver#405]
Pyinstaller successfully created an exe file with undetected-chromedriver. However, it will not push through and start again in the beginning. Any solutions?

**Comment by SoHardDay** [comment]
It's the same for me. 
The application restarts without error after 
`driver = uc.Chrome (... `

**Comment by SoHardDay** [comment]
> 

use undetected-chromedriver 3.0.3 version

**Comment by rosatheagraham** [comment]
Yes, PyInstaller works well to convert the script into an exe file. But, there is a small problem I would like report.  The problem appears after packing the script with PyInstaller to exe. (Therefore , I didn't open a new issue for that, as the problem appears when using pyInstaller + webview + undetected-chromedriver all together, if you want me to open a new issue for that, I can.)

Here is the problem in detail:

Before packing the script with PyInstaller, if we used the webview module in our python code, 
(webview: which is to be used when we want to have an html code as a gui for our programme, resulting as our programme works as desktop application rather than browser initialised one.) 

Webviev starts like that usinf CEF: example start is like that: 
`webview.create_window("http://localhost:5000")`
`webview.start(gui='cef')`
For your information: CEF is Chromium Embedded Framework, which is used by webview as an embedded browser, and in runtime it enables a frame for the html interface look like a desktop programme.
you might know webview.

The real problem is: There is conflict appear, when running undetected-chromedriver in a function, when out programme is packed as an exe by PyInstaller.

The exe program starts normally and webview starts with CEF as descripbed above, and shows html interface in a frame, just as a desktop application.Everything is normal until now.

But then, when we start a function which uses undetected-chromedriver, the undetected-chromedriver picks the chrome interface under the Webview/CEF and starts a desktop interface rather than a fresh browser, which the UC supposed to start.
I guess the chromedriver we have placed for the UC is completely ignored and another preinstalled chrome driver in initiated. (which belongs to webview + CEF)

Therefore this line of UC:

`    with driver:`
`        driver.get(url)`

Does not open the url we wished for. It opens the one that is given to webview.create_window in the begining. Which was http://localhost:5000

No fresh UC browser. No other operations can be done supported by UC.

Trying such things like 
`driver = uc.Chrome(version_main=96,executable_path=chromedriverpath)`
To specify the chromedriver.exe path didn't work.

Also Packing the chromedriver.exe inside the .exe file, while packing with PyInstaller did not work as well.  (pyinstaller example --add-data "driver;driver" script.py) where driver is a folder contains chromedriver.exe

I would be happy to hear your advice, in how to make UC driver to start a fresh browser to do operations normally, without starting anything else related to webview. Thanks for everything.

**Comment by albrechtmate** [comment]
@SoHardDay  do you have any idea how can i create exe with the new version? Or if dont, can you tell me how can i choose the 3.0.3 version? I only find the 3.0.4 version.. Thank you

**Comment by SoHardDay** [comment]
> @SoHardDay do you have any idea how can i create exe with the new version? Or if dont, can you tell me how can i choose the 3.0.3 version? I only find the 3.0.4 version.. Thank you

pip install pyinstaller==3.0.3

**Comment by albrechtmate** [comment]
@SoHardDay  I've tried with pyinstaller, after running the exe file it starts the browser and closing it automatically after 2 secund and shows this problem, but the program is keep running. 

DevTools listening on ws://127.0.0.1:55938/devtools/browser/fce3d051-e3eb-47a9-99c9-59641e08f616
[13628:15776:0207/120519.749:ERROR:chrome_browser_main_extra_parts_metrics.cc(227)] START: ReportBluetoothAvailability(). If you don't see the END: message, this is crbug.com/1216328.
[13628:15776:0207/120519.749:ERROR:chrome_browser_main_extra_parts_metrics.cc(230)] END: ReportBluetoothAvailability()
[13628:6324:0207/120519.751:ERROR:device_event_log_impl.cc(214)] [12:05:19.751] USB: usb_device_handle_win.cc:1049 Failed to read descriptor from node connection: a device attached to the system is not functioning (0x1F)
[13628:6324:0207/120519.752:ERROR:device_event_log_impl.cc(214)] [12:05:19.752] USB: usb_device_handle_win.cc:1049 Failed to read descriptor from node connection:a device attached to the system is not functioning(0x1F)
[13628:6324:0207/120519.752:ERROR:device_event_log_impl.cc(214)] [12:05:19.752] USB: usb_device_handle_win.cc:1049 Failed to read descriptor from node connection: a device attached to the system is not functioning (0x1F)
[13628:15776:0207/120519.753:ERROR:chrome_browser_main_extra_parts_metrics.cc(235)] START: GetDefaultBrowser(). If you don't see the END: message, this is crbug.com/1216328.
[13628:15776:0207/120519.799:ERROR:chrome_browser_main_extra_parts_metrics.cc(239)] END: GetDefaultBrowser()


Can you help me with that?

**Comment by albrechtmate** [comment]
Traceback (most recent call last):
  File "C:\Users\albre\Documents\ProfilsSetup\test_msgsender_proxy_nelku\undetectable_chromedriver.py", line 1, in <module>
    import undetected_chromedriver.v3 as uc
  File "C:\Users\albre\AppData\Local\Programs\Python\Python310\lib\site-packages\undetected_chromedriver\__init__.py", line 31, in <module>
    from . import v2
  File "C:\Users\albre\AppData\Local\Programs\Python\Python310\lib\site-packages\undetected_chromedriver\v2.py", line 21, in <module>
    from .cdp import CDP
  File "C:\Users\albre\AppData\Local\Programs\Python\Python310\lib\site-packages\undetected_chromedriver\cdp.py", line 6, in <module>Traceback (most recent call last):
  File "C:\Users\albre\Documents\ProfilsSetup\test_msgsender_proxy_nelku\undetectable_chromedriver.py", line 1, in <module>
    import undetected_chromedriver.v3 as uc
  File "C:\Users\albre\AppData\Local\Programs\Python\Python310\lib\site-packages\undetected_chromedriver\__init__.py", line 31, in <module>
    from . import v2
  File "C:\Users\albre\AppData\Local\Programs\Python\Python310\lib\site-packages\undetected_chromedriver\v2.py", line 21, in <module>
    from .cdp import CDP
  File "C:\Users\albre\AppData\Local\Programs\Python\Python310\lib\site-packages\undetected_chromedriver\cdp.py", line 6, in <module>
    from collections import Mapping, Sequence
ImportError: cannot import name 'Mapping' from 'collections'

@SoHardDay  I get this error after installing uc with 3.0.3 version.


My imports looks like this:

import undetected_chromedriver as uc
import mysql.connector
from selenium import webdriver
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.common.by import By
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.common.keys import Keys


Could you help me with that?

**Comment by developerhafiz** [comment]
have you find the solution?
