### ISSUE TITLE
AttributeError: 'Chrome' object has no attribute 'service'

### ISSUE THREAD

**Issue by alimp5** [ultrafunkamsterdam/undetected-chromedriver#407]
Greetings! :X

windows: 10 - 64 bit
uc: 3.0.6
python: 3.8.10 - 64 bit
chrome: 96

```
        self.profile_path = "C:\\selenium_profiles\\sel_profile200"
        self.cookie_path = "C:\\selenium_profiles\\sel_cookie200.pkl"
        self.chrome_driver_path = "C:\\selenium_profiles\\chromedriver96.exe"
        self.driver = None
        self.my_url = "https://pendarepars.com"
        
        options = uc.ChromeOptions()
        options.user_data_dir = self.profile_path
        options.add_argument('--user-data-dir={}'.format(self.profile_path))
        options.add_argument('--no-first-run --no-service-autorun --password-store=basic')
        options.add_argument('--excludeSwitches --enable-logging')
        self.driver = uc.Chrome (executable_path=self.chrome_driver_path, options=options, version_main=96)
        self.driver.implicitly_wait(60)
        self.driver.get(self.my_url)
```

#### Error:
```
PS C:\Users\linux10\Desktop\ea_project> & C:/Python38/python.exe c:/Users/linux10/Desktop/ea_project/other_selenium.py
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Python38\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Python38\lib\multiprocessing\spawn.py", line 125, in _main
    prepare(preparation_data)
  File "C:\Python38\lib\multiprocessing\spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Python38\lib\multiprocessing\spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "C:\Python38\lib\runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "C:\Python38\lib\runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "C:\Python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "c:\Users\linux10\Desktop\ea_project\other_selenium.py", line 92, in <module>
    pendar()
  File "c:\Users\linux10\Desktop\ea_project\other_selenium.py", line 30, in __init__
    self.driver = uc.Chrome (executable_path=self.chrome_driver_path, options=options, version_main=96)
  File "C:\Python38\lib\site-packages\undetected_chromedriver\v2.py", line 299, in __init__
    self.browser_pid = start_detached(options.binary_location, *options.arguments)
  File "C:\Python38\lib\site-packages\undetected_chromedriver\dprocess.py", line 30, in start_detached
    multiprocessing.Process(target=_start_detached, args=(executable, *args), kwargs={'writer': writer},
  File "C:\Python38\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "C:\Python38\lib\multiprocessing\context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Python38\lib\multiprocessing\context.py", line 327, in _Popen
    return Popen(process_obj)
  File "C:\Python38\lib\multiprocessing\popen_spawn_win32.py", line 45, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "C:\Python38\lib\multiprocessing\spawn.py", line 154, in get_preparation_data
    _check_not_importing_main()
  File "C:\Python38\lib\multiprocessing\spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
Exception ignored in: <function Chrome.__del__ at 0x00000261A5CC4310>
Traceback (most recent call last):
  File "C:\Python38\lib\site-packages\undetected_chromedriver\v2.py", line 647, in __del__
  File "C:\Python38\lib\site-packages\undetected_chromedriver\v2.py", line 604, in quit
AttributeError: 'Chrome' object has no attribute 'service'
```

**Comment by auror44** [comment]
I solved it by running the program under  -  if __name__ == '__main__': -.

**Comment by 90xboy** [comment]
i also got this problem, did you solve this problem?

**Comment by hackerin0** [comment]
> I solved it by running the program under {if **name** == '**main**':}

Thanks mate, solution works

**Comment by alimp5** [comment]
@auror44  

thanks works.
