### ISSUE TITLE
install error，please help

### ISSUE THREAD

**Issue by lux182** [ultrafunkamsterdam/undetected-chromedriver#408]
(v3.8.3) PS E:\bob\pc-demo> pip install undetected-chromedriver --no-cache-dir
Collecting undetected-chromedriver
  Downloading undetected-chromedriver-3.0.6.tar.gz (51 kB)
     |████████████████████████████████| 51 kB 3.0 kB/s
    ERROR: Command errored out with exit status 1:
     command: 'D:\conda\miniconda3\envs\v3.8.3\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\gzg\\AppData\\Local\\Temp\\pip-install-tbykgv4n\\undetected-chromedriver_72f90d451c364db48b52ae0fa4ce7b3c\\setup.py'"'"'; __file__='"'"'C:\\Users\\gzg\\AppData\\Local\\Temp\\pip-install-tbykgv4n\\undetected-chromedriver_72f90d451c364db48b52ae0fa4ce7b3c\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\gzg\AppData\Local\Temp\pip-pip-egg-info-sx701ud8'
         cwd: C:\Users\gzg\AppData\Local\Temp\pip-install-tbykgv4n\undetected-chromedriver_72f90d451c364db48b52ae0fa4ce7b3c\
    Complete output (28 lines):
    Traceback (most recent call last):
      File "D:\conda\miniconda3\envs\v3.8.3\lib\site-packages\pkg_resources\__init__.py", line 2848, in get_entry_map
        ep_map = self._ep_map
      File "D:\conda\miniconda3\envs\v3.8.3\lib\site-packages\pkg_resources\__init__.py", line 2810, in __getattr__
        raise AttributeError(attr)
    AttributeError: _ep_map

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\gzg\AppData\Local\Temp\pip-install-tbykgv4n\undetected-chromedriver_72f90d451c364db48b52ae0fa4ce7b3c\setup.py", line 33, in <module>
        setup(
      File "D:\conda\miniconda3\envs\v3.8.3\lib\site-packages\setuptools\__init__.py", line 152, in setup
        _install_setup_requires(attrs)
      File "D:\conda\miniconda3\envs\v3.8.3\lib\site-packages\setuptools\__init__.py", line 142, in _install_setup_requires
        dist = MinimalDistribution(attrs)
      File "D:\conda\miniconda3\envs\v3.8.3\lib\site-packages\setuptools\__init__.py", line 134, in __init__
        distutils.core.Distribution.__init__(self, filtered)
      File "D:\conda\miniconda3\envs\v3.8.3\lib\site-packages\setuptools\dist.py", line 421, in __init__
        for ep in pkg_resources.iter_entry_points('distutils.setup_keywords'):
      File "D:\conda\miniconda3\envs\v3.8.3\lib\site-packages\pkg_resources\__init__.py", line 640, in <genexpr>
        for entry in dist.get_entry_map(group).values()
      File "D:\conda\miniconda3\envs\v3.8.3\lib\site-packages\pkg_resources\__init__.py", line 2850, in get_entry_map
        ep_map = self._ep_map = EntryPoint.parse_map(
      File "D:\conda\miniconda3\envs\v3.8.3\lib\site-packages\pkg_resources\__init__.py", line 2535, in parse_map
        raise ValueError("Entry points must be listed in groups")
    ValueError: Entry points must be listed in groups
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by ultrafunkamsterdam** [comment]
please try again now
```
pip install -U undetected-chromedriver
```
