### ISSUE TITLE
undetected_chromedriver running error

### ISSUE THREAD

**Issue by 90xboy** [ultrafunkamsterdam/undetected-chromedriver#412]
I try the simple code but got errors, please help me
**my code:** 
import undetected_chromedriver.v2 as uc
if __name__ == '__main__':
    options = uc.ChromeOptions()
    options.add_argument("--disable-notifications")
    options.add_argument('--user-data-dir=c:\\temp\\profile2')
    driver = uc.Chrome(options=options,version_main=96)
    driver.get('https://google.com/')
**Error**
Traceback (most recent call last):
  File "d:\python\myproject\Untitled-1.py", line 6, in <module>
    driver = uc.Chrome(options=options,version_main=96)
  File "C:\Users\Hoaison\AppData\Local\Programs\Python\Python310\lib\site-packages\undetected_chromedriver\v2.py", line 309, in __init__
    super(Chrome, self).__init__(
  File "C:\Users\Hoaison\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 70, in __init__  
    super(WebDriver, self).__init__(DesiredCapabilities.CHROME['browserName'], "goog",
  File "C:\Users\Hoaison\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\chromium\webdriver.py", line 93, in __init__
    RemoteWebDriver.__init__(
  File "C:\Users\Hoaison\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 268, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Users\Hoaison\AppData\Local\Programs\Python\Python310\lib\site-packages\undetected_chromedriver\v2.py", line 600, in start_session
    super(Chrome, self).start_session(capabilities, browser_profile)
  File "C:\Users\Hoaison\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 359, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Users\Hoaison\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 424, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Hoaison\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot connect to chrome at 127.0.0.1:49345
from chrome not reachable

**Comment by 90xboy** [comment]
the program still work properly before but now get problem like above
