### ISSUE TITLE
Errno 22

### ISSUE THREAD

**Issue by BrentGregath** [ultrafunkamsterdam/undetected-chromedriver#416]
When doing the followng an error pops up.  I have NO idea what is causing this. This is on the 3.1.1.  If I use 2.2.7 everything is all good.

```
import undetected_chromedriver. as uc

PATH = "C:\Program Files (x86)\chromedriver.exe"
driver = uc.Chrome()
```

I get this error in the console. 

```
C:\Python_Projects\ProjcetB\venv\Scripts\python.exe "C:\Program Files\JetBrains\PyCharm Community Edition 2021.2.1\plugins\python-ce\helpers\pydev\pydevconsole.py" --mode=client --port=60667
import sys; print('Python %s on %s' % (sys.version, sys.platform))
sys.path.extend(['C:\\Python_Projects\\ProjcetB', 'C:/Python_Projects/ProjcetB'])
PyDev console: starting.
Python 3.9.7 (tags/v3.9.7:1016ef3, Aug 30 2021, 20:19:38) [MSC v.1929 64 bit (AMD64)] on win32
import undetected_chromedriver.v2 as uc
PATH = "C:\Program Files (x86)\chromedriver.exe"
driver = uc.Chrome(version_main=95)
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Python\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Python\lib\multiprocessing\spawn.py", line 125, in _main
    prepare(preparation_data)
  File "C:\Python\lib\multiprocessing\spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Python\lib\multiprocessing\spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "C:\Python\lib\runpy.py", line 267, in run_path
    code, fname = _get_code_from_file(run_name, path_name)
  File "C:\Python\lib\runpy.py", line 237, in _get_code_from_file
    with io.open_code(decoded_path) as f:
OSError: [Errno 22] Invalid argument: 'C:\\Python_Projects\\ProjcetB\\<input>'
```

**Comment by sunny9495-dev** [comment]
import undetected_chromedriver. as uc
driver = uc.Chrome(executable_path=r'C:\Program Files (x86)\chromedriver.exe')

**Comment by BenoitYU** [comment]
I got the same issue when I call the `driver = uc.Chrome(executable_path=r'C:\Program Files (x86)\chromedriver.exe')` , this code is trying to create 2 driver objects then cause the error shown as above. Any suggestion would be appriciated.
