### ISSUE TITLE
Could not find a version that satisfies the requirement (choosed a existing version (3.0.2)

### ISSUE THREAD

**Issue by FuckingToasters** [ultrafunkamsterdam/undetected-chromedriver#424]
```py
Collecting undetected-chromedriver==3.0.2
  Using cached undetected-chromedriver-3.0.2.tar.gz (37 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'

WARNING: Ignoring invalid distribution -ip (d:\private\downloads\python\lib\site-packages)
WARNING: Ignoring invalid distribution -ip (d:\private\downloads\python\lib\site-packages)
  ERROR: Command errored out with exit status 1:
   command: 'D:\Private\Downloads\python\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Administrator\\AppData\\Local\\Temp\\pip-install-8ts3uhar\\undetected-chromedriver_e01ae198fb904de0b96deee3ee17a40b\\setup.py'"'"'; __file__='"'"'C:\\Users\\Administrator\\AppData\\Local\\Temp\\pip-install-8ts3uhar\\undetected-chromedriver_e01ae198fb904de0b96deee3ee17a40b\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\Administrator\AppData\Local\Temp\pip-pip-egg-info-fbq4rsz4'
       cwd: C:\Users\Administrator\AppData\Local\Temp\pip-install-8ts3uhar\undetected-chromedriver_e01ae198fb904de0b96deee3ee17a40b\
  Complete output (26 lines):
  running egg_info
  creating C:\Users\Administrator\AppData\Local\Temp\pip-pip-egg-info-fbq4rsz4\undetected_chromedriver.egg-info
  writing C:\Users\Administrator\AppData\Local\Temp\pip-pip-egg-info-fbq4rsz4\undetected_chromedriver.egg-info\PKG-INFO
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\Administrator\AppData\Local\Temp\pip-install-8ts3uhar\undetected-chromedriver_e01ae198fb904de0b96deee3ee17a40b\setup.py", line 33, in <module>
      setup(
    File "D:\Private\Downloads\python\lib\site-packages\setuptools\__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "D:\Private\Downloads\python\lib\distutils\core.py", line 148, in setup
      dist.run_commands()
    File "D:\Private\Downloads\python\lib\distutils\dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "D:\Private\Downloads\python\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "D:\Private\Downloads\python\lib\site-packages\setuptools\command\egg_info.py", line 292, in run
      writer(self, ep.name, os.path.join(self.egg_info, ep.name))
    File "D:\Private\Downloads\python\lib\site-packages\setuptools\command\egg_info.py", line 656, in write_pkg_info
      metadata.write_pkg_info(cmd.egg_info)
    File "D:\Private\Downloads\python\lib\distutils\dist.py", line 1117, in write_pkg_info
      self.write_pkg_file(pkg_info)
    File "D:\Private\Downloads\python\lib\site-packages\setuptools\dist.py", line 167, in write_pkg_file
      write_field('Summary', single_line(self.get_description()))
    File "D:\Private\Downloads\python\lib\site-packages\setuptools\dist.py", line 151, in single_line
      raise ValueError('Newlines are not allowed')
  ValueError: Newlines are not allowed
  ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/42/64/91559bf5a2202d9a0aa82f2c5c02f716055b36beb4c725992a48e1f934b9/undetected-chromedriver-3.0.2.tar.gz#sha256=febbc1ed7cabda2b94934f8f27c29add4f44c1290014e166aa0a562e7fc06af7 (from https://pypi.org/simple/undetected-chromedriver/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement undetected-chromedriver==3.0.2 (from versions: 1.3.5, 1.3.6, 1.3.7, 1.4.0, 1.4.2, 1.5.0, 1.5.1, 1.5.2, 2.0b0, 2.0.0, 2.0.1, 2.0.2, 2.1.0, 2.1.1, 2.1.2, 2.2.0, 2.2.1, 2.2.7, 3.0.0, 3.0.1, 3.0.2, 3.0.3, 3.0.4, 3.0.5, 3.0.6, 3.1.0rc1, 3.1.0, 3.1.1, 3.1.2, 3.1.3)
ERROR: No matching distribution found for undetected-chromedriver==3.0.2
WARNING: Ignoring invalid distribution -ip (d:\private\downloads\python\lib\site-packages)
WARNING: Ignoring invalid distribution -ip (d:\private\downloads\python\lib\site-packages)
```

**Comment by ultrafunkamsterdam** [comment]
use pip install -U undetected-chromedriver
