### ISSUE TITLE
Path to driver is not being returned

### ISSUE THREAD

**Issue by CodeInfinity07** [ultrafunkamsterdam/undetected-chromedriver#425]
I am getting this error whenever I try to use it. 

File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ryzon/.local/lib/python3.9/site-packages/undetected_chromedriver/dprocess.py", line 59, in _start_detached
    p = Popen([executable, *args], stdin=PIPE, stdout=PIPE, stderr=PIPE, **kwargs)
  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1696, in _execute_child
    and os.path.dirname(executable)
  File "/usr/lib/python3.9/posixpath.py", line 152, in dirname
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not NoneType
^CTraceback (most recent call last):
  File "/home/ryzon/Projects/fiverr_automation/run.py", line 40, in <module>
    f_browser = uc.Chrome(options=chrome_options, version_main=96)
  File "/home/ryzon/.local/lib/python3.9/site-packages/undetected_chromedriver/__init__.py", line 356, in __init__
    self.browser_pid = start_detached(
  File "/home/ryzon/.local/lib/python3.9/site-packages/undetected_chromedriver/dprocess.py", line 37, in start_detached
    pid = reader.recv()
  File "/usr/lib/python3.9/multiprocessing/connection.py", line 255, in recv
    buf = self._recv_bytes()
  File "/usr/lib/python3.9/multiprocessing/connection.py", line 419, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.9/multiprocessing/connection.py", line 384, in _recv
    chunk = read(handle, remaining)
KeyboardInterrupt

**Comment by tnusser** [comment]
I encounter the same error using Python 3.8 on Ubuntu 20.04

**Comment by GeorgeSp1** [comment]
Hello, I face the same issue with Chrome Version 97.0.4692.99 (Official Build) (64-bit) on Windows 11, fully updated. Can I provide any more info to help you?

**Comment by ultrafunkamsterdam** [comment]
try 
```python
driver = uc.Chrome(use_subprocess=True)
```
