### ISSUE TITLE
Same RuntimeError in "fixed" 3.1.3 version as before

### ISSUE THREAD

**Issue by Avnsx** [ultrafunkamsterdam/undetected-chromedriver#432]
Original issue(https://github.com/ultrafunkamsterdam/undetected-chromedriver/issues/384) was falsely closed, pretending the issue is fixed but it's not...
Literally can't run any version above 3.0.6

```python
import undetected_chromedriver.v2 as uc
print(uc.__version__)
driver = uc.Chrome()
driver.get('https://nowsecure.nl')
````

```python
3.1.3
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\ProgramData\Miniconda3\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\ProgramData\Miniconda3\lib\multiprocessing\spawn.py", line 125, in _main
    prepare(preparation_data)
  File "C:\ProgramData\Miniconda3\lib\multiprocessing\spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\ProgramData\Miniconda3\lib\multiprocessing\spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "C:\ProgramData\Miniconda3\lib\runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "C:\ProgramData\Miniconda3\lib\runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "C:\ProgramData\Miniconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\canmi\Desktop\recent_projects\AIO_Proxy_Tools\uc_test.py", line 3, in <module>
    driver = uc.Chrome()
  File "C:\ProgramData\Miniconda3\lib\site-packages\undetected_chromedriver\__init__.py", line 356, in __init__
    self.browser_pid = start_detached(
  File "C:\ProgramData\Miniconda3\lib\site-packages\undetected_chromedriver\dprocess.py", line 30, in start_detached
    multiprocessing.Process(
  File "C:\ProgramData\Miniconda3\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "C:\ProgramData\Miniconda3\lib\multiprocessing\context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\ProgramData\Miniconda3\lib\multiprocessing\context.py", line 327, in _Popen
    return Popen(process_obj)
  File "C:\ProgramData\Miniconda3\lib\multiprocessing\popen_spawn_win32.py", line 45, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "C:\ProgramData\Miniconda3\lib\multiprocessing\spawn.py", line 154, in get_preparation_data
    _check_not_importing_main()
  File "C:\ProgramData\Miniconda3\lib\multiprocessing\spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
3.1.3
```

Actually it's gotten even worse, even when just importing v1 I just get the same RuntimeError now

```python
import undetected_chromedriver as uc
print(uc.__version__)
driver = uc.Chrome()
driver.get('https://nowsecure.nl')
```
```python
3.1.3
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\ProgramData\Miniconda3\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\ProgramData\Miniconda3\lib\multiprocessing\spawn.py", line 125, in _main
    prepare(preparation_data)
  File "C:\ProgramData\Miniconda3\lib\multiprocessing\spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\ProgramData\Miniconda3\lib\multiprocessing\spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "C:\ProgramData\Miniconda3\lib\runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "C:\ProgramData\Miniconda3\lib\runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "C:\ProgramData\Miniconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\canmi\Desktop\recent_projects\AIO_Proxy_Tools\uc_test.py", line 3, in <module>
    driver = uc.Chrome()
  File "C:\ProgramData\Miniconda3\lib\site-packages\undetected_chromedriver\__init__.py", line 356, in __init__
    self.browser_pid = start_detached(
  File "C:\ProgramData\Miniconda3\lib\site-packages\undetected_chromedriver\dprocess.py", line 30, in start_detached
    multiprocessing.Process(
  File "C:\ProgramData\Miniconda3\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "C:\ProgramData\Miniconda3\lib\multiprocessing\context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\ProgramData\Miniconda3\lib\multiprocessing\context.py", line 327, in _Popen
    return Popen(process_obj)
  File "C:\ProgramData\Miniconda3\lib\multiprocessing\popen_spawn_win32.py", line 45, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "C:\ProgramData\Miniconda3\lib\multiprocessing\spawn.py", line 154, in get_preparation_data
    _check_not_importing_main()
  File "C:\ProgramData\Miniconda3\lib\multiprocessing\spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
3.1.3
```

Python 3.8.10 for windows 10

**Comment by perinm** [comment]
You could try using WSL for windows 11. Don't try at windows 10, because windows 11's WSL offers native support for GUI, and will save good 10 hours of your's time.

**Comment by BenoitYU** [comment]
I have got this error too when I run the code from readme. Then I tested on my another PC and same error remains unless I call the code from main in this way 
```
 if __name__ == '__main__':
     freeze_support()
    + My own function
```
So this bug is effectively not a rare one and maybe I'm a newbie and can not figure out why. But I would keep tracking on this issue and hope @ultrafunkamsterdam could fix this as soon as possible.

**Comment by ultrafunkamsterdam** [comment]
```python
 driver = uc.Chrome(use_subprocess=True)
 ```

**Comment by BenoitYU** [comment]
> @ultrafunkamsterdam appreciate it man, it works on my PC now. NICE JOB!

**Comment by ultrafunkamsterdam** [comment]
For others who read this. Make sure you have version at least (3.1.3) by using
`pip install -U undetected-chromedriver`

**Comment by Avnsx** [comment]
> ```python
>  driver = uc.Chrome(use_subprocess=True)
> ```

Finally, thanks this works 👍 Now if you would somehow manage to add authenticated proxies support for uc, I could die happily 🙌

**Comment by BenoitYU** [comment]
![image](https://user-images.githubusercontent.com/22321344/148213939-8af66d53-143e-4a41-ace7-8933e28e3e7d.png)
It's quite weird cause I get another error after testing the same code on another PC. What do you think? @ultrafunkamsterdam (the new PC I tested on is not configured originally in English US, that's the only difference I could say so far) appreciate it in advance

**Comment by BenoitYU** [comment]
@ultrafunkamsterdam It seems like the `os.getenv("HOME")` is not working on part of windows PC. I have the working PC which I log on to a domain with a local home directory, the test code works perfectly. while on my personal PC, there is no home profile, then return back the error. you could check[ here](https://stackoverflow.com/questions/4028904/what-is-the-correct-cross-platform-way-to-get-the-home-directory-in-python)

**Comment by BenoitYU** [comment]
@ultrafunkamsterdam Finally I found where is the problem:
![image](https://user-images.githubusercontent.com/22321344/148266928-6fe47514-dbbc-4a06-a676-c99f6247c44e.png)
actually the function `find_chrome_executable()` doesn't return the right path as shown on the screenshot and then causes the chrome.exe nonfoundable. it is probably because it's on Python 32 bit rather than 64 bit. I will do a double-check with it.
@Avnsx so temp solution would be directly send the chrome path like this: 
```
exe_path = os.path.normpath("C:\Program Files\Google\Chrome\Application\chrome.exe")
driver = uc.Chrome(browser_executable_path = exe_path)
```

**Comment by mohit1337** [comment]
Latest version is not working without 

```
 driver = uc.Chrome(use_subprocess=True)
```

Should be documented if that is mandatory or set default value as true

**Comment by cpu114** [comment]
https://i.imgur.com/Kn0vzoh.png
