### ISSUE TITLE
Undetected_chromedriver package generated exe invalid

### ISSUE THREAD

**Issue by kingtianbao** [ultrafunkamsterdam/undetected-chromedriver#438]
import undetected_chromedriver as uc

if __name__ == '__main__':
    driver = uc.Chrome()
    driver.get("https://www.google.com/")

Traceback (most recent call last):
  File "main.py", line 4, in <module>
  File "undetected_chromedriver\__init__.py", line 208, in __init__
  File "undetected_chromedriver\patcher.py", line 121, in auto
  File "undetected_chromedriver\patcher.py", line 158, in fetch_package
  File "urllib\request.py", line 276, in urlretrieve
  File "http\client.py", line 461, in read
  File "http\client.py", line 505, in readinto
  File "socket.py", line 589, in readinto
  File "ssl.py", line 1071, in recv_into
  File "ssl.py", line 929, in read

**Comment by dmitrymaslov99** [comment]
I'm not going to build either. It only works on version 3.0.3, but the antidetect itself does not work on it.
