### ISSUE TITLE
selenium.common.exceptions.SessionNotCreatedException: Message: session not created

### ISSUE THREAD

**Issue by 41v4** [ultrafunkamsterdam/undetected-chromedriver#448]
Hi there,

I am facing a problem when running undetected-chromedriver in headless mode and I have no idea how to solve this error.
I tried running it on my home PC (Ubuntu 20.04) and on my VPS (also Ubuntu).

The code I am using:
```
import undetected_chromedriver as uc

options = uc.ChromeOptions()
options.headless=True
options.add_argument('--headless')
driver = uc.Chrome(options=options)

url = 'https://stackoverflow.com/'

driver.get(url)
driver.save_screenshot('stackoverflow.png')
driver.close()
```

The error I am getting:
```
Traceback (most recent call last):
  File "chrome_testing.py", line 7, in <module>
    driver = uc.Chrome(options=options)
  File "/home/chromedriver_testing/venv/lib/python3.8/site-packages/undetected_chromedriver/__init__.py", line 369, in __init__
    super(Chrome, self).__init__(
  File "/home/chromedriver_testing/venv/lib/python3.8/site-packages/selenium/webdriver/chrome/webdriver.py", line 70, in __init__
    super(WebDriver, self).__init__(DesiredCapabilities.CHROME['browserName'], "goog",
  File "/home/chromedriver_testing/venv/lib/python3.8/site-packages/selenium/webdriver/chromium/webdriver.py", line 93, in __init__
    RemoteWebDriver.__init__(
  File "/home/chromedriver_testing/venv/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 268, in __init__
    self.start_session(capabilities, browser_profile)
  File "/home/chromedriver_testing/venv/lib/python3.8/site-packages/undetected_chromedriver/__init__.py", line 552, in start_session
    super(selenium.webdriver.chrome.webdriver.WebDriver, self).start_session(
  File "/home/chromedriver_testing/venv/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 359, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/chromedriver_testing/venv/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 424, in execute
    self.error_handler.check_response(response)
  File "/home/chromedriver_testing/venv/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created
from timeout: Timed out receiving message from renderer: 600.000
  (Session info: headless chrome=97.0.4692.71)
Stacktrace:
#0 0x55a3f4264a23 <unknown>
#1 0x55a3f3d2fe18 <unknown>
#2 0x55a3f3d1b8a5 <unknown>
#3 0x55a3f3d1a5e3 <unknown>
#4 0x55a3f3d1a933 <unknown>
#5 0x55a3f3d19f61 <unknown>
#6 0x55a3f3d294f0 <unknown>
#7 0x55a3f3d19f03 <unknown>
#8 0x55a3f3d1b279 <unknown>
#9 0x55a3f3d1a5e3 <unknown>
#10 0x55a3f3d1a933 <unknown>
#11 0x55a3f3d19f61 <unknown>
#12 0x55a3f3d221a0 <unknown>
#13 0x55a3f3d221ec <unknown>
#14 0x55a3f3d19f03 <unknown>
#15 0x55a3f3d1b279 <unknown>
#16 0x55a3f3d1a5e3 <unknown>
#17 0x55a3f3d1a933 <unknown>
#18 0x55a3f3d19f61 <unknown>
#19 0x55a3f3d26dad <unknown>
#20 0x55a3f3d19f03 <unknown>
#21 0x55a3f3d1b279 <unknown>
#22 0x55a3f3d1a5e3 <unknown>
#23 0x55a3f3d1a933 <unknown>
#24 0x55a3f3d19f61 <unknown>
#25 0x55a3f3d226eb <unknown>
#26 0x55a3f3d19f03 <unknown>
#27 0x55a3f3d1b279 <unknown>
#28 0x55a3f3d1a5e3 <unknown>
#29 0x55a3f3d1a933 <unknown>
#30 0x55a3f3d19f61 <unknown>
#31 0x55a3f3d2171a <unknown>
#32 0x55a3f3d19f03 <unknown>
#33 0x55a3f3d1b279 <unknown>
#34 0x55a3f3d1a5e3 <unknown>
#35 0x55a3f3d1a933 <unknown>
#36 0x55a3f3d19f61 <unknown>
#37 0x55a3f3d14b8a <unknown>
#38 0x55a3f3d19f03 <unknown>
#39 0x55a3f3d19e1b <unknown>
#40 0x55a3f3d198a0 <unknown>
#41 0x55a3f3d31212 <unknown>
#42 0x55a3f3d8ab54 <unknown>
#43 0x55a3f3d83883 <unknown>
#44 0x55a3f3d593fa <unknown>
#45 0x55a3f3d5a4c5 <unknown>
#46 0x55a3f429416d <unknown>
#47 0x55a3f42aa5bb <unknown>
#48 0x55a3f4295e75 <unknown>
#49 0x55a3f42aae85 <unknown>
#50 0x55a3f428986f <unknown>
#51 0x55a3f42c5ae8 <unknown>
#52 0x55a3f42c5c68 <unknown>
#53 0x55a3f42e0aad <unknown>
#54 0x7f724a087609 <unknown>
```

Any ideas what's wrong with it or how I could solve this issue? Thank you in advance!

**Comment by 41v4** [comment]
My bad. Everything works fine. Forgot to add:
options.add_argument('--disable-gpu')
