### ISSUE TITLE
chromedriver starting issue

### ISSUE THREAD

**Issue by ahmedmani** [ultrafunkamsterdam/undetected-chromedriver#463]
problem occur when trying to launch the driver 
>import undetected_chromedriver as uc
>driver = uc.Chrome()
traceback 
***
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\python\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\python\lib\multiprocessing\spawn.py", line 114, in _main
    prepare(preparation_data)
  File "C:\python\lib\multiprocessing\spawn.py", line 225, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\python\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
    run_name="__mp_main__")
  File "C:\python\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "C:\python\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\python\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\user\OneDrive\Bureau\test.py", line 6, in <module>
    driver = uc.Chrome()
  File "C:\python\lib\site-packages\undetected_chromedriver\__init__.py", line 357, in __init__
    options.binary_location, *options.arguments
  File "C:\python\lib\site-packages\undetected_chromedriver\dprocess.py", line 34, in start_detached
    daemon=True,
  File "C:\python\lib\multiprocessing\process.py", line 112, in start
    self._popen = self._Popen(self)
  File "C:\python\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\python\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\python\lib\multiprocessing\popen_spawn_win32.py", line 46, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "C:\python\lib\multiprocessing\spawn.py", line 143, in get_preparation_data
    _check_not_importing_main()
  File "C:\python\lib\multiprocessing\spawn.py", line 136, in _check_not_importing_main
    is not going to be frozen to produce an executable.''')
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
***

**Comment by akatasonov** [comment]
having the same issue, Python 3.9.7 OSX on M1

**Comment by sebdelsol** [comment]
@gabrielsilvabrpy according to the [docstring](https://github.com/ultrafunkamsterdam/undetected-chromedriver/blob/33aa8c3905679d1863f38ccac1203d2b29660790/undetected_chromedriver/__init__.py#L203) setting `use_subprocess` to `True` might be a bad idea if you want to stay undetected. 
The solution is actually in the error message:
```python
import undetected_chromedriver as webdriver

if __name__ == "__main__":
    driver = webdriver.Chrome()
    driver.get("https://www.google.com/")
```

**Comment by akatasonov** [comment]
great catch, @sebdelsol !
