### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by intopes** [ultrafunkamsterdam/undetected-chromedriver#48]
Hello,

I am amateur working with python3 + Selenium in Pycharm
I have installed and working with selenium and python3 via:  pip3

In your readme I view that you said install via "pip install undetected-chromedriver"  
but i think that in my case I need to install via "pip3 install undetected-chromedriver"  
It would be correct?

I have tried installing using "pip3" And it seems that it has been installed successfully but when go with the script have this error: 
`ModuleNotFoundError: No module named 'undetected_chromedriver'`

This is part of my code:

```
import undetected_chromedriver as uc
opts = uc.ChromeOptions()
opts.add_argument("--incognito")
opts.add_argument("--disable-blink-features")  
opts.add_argument("--disable-blink-features=AutomationControlled") 
browser = uc.Chrome(options=opts)
```

Could you tell me that I'm doing wrong?
thanks!

**Comment by intopes** [comment]
New.
I install direct via Pycharm Terminal with this: "pip install undetected-chromedriver"
The text form Terminal
`Collecting undetected-chromedriver
  Using cached undetected-chromedriver-1.5.0.tar.gz (6.5 kB)
Requirement already satisfied: selenium in ./venv/lib/python3.8/site-packages (from undetected-chromedriver) (3.141.0)
Requirement already satisfied: urllib3 in ./venv/lib/python3.8/site-packages (from selenium->undetected-chromedriver) (1.25.9)
Using legacy setup.py install for undetected-chromedriver, since package 'wheel' is not installed.
Installing collected packages: undetected-chromedriver
    Running setup.py install for undetected-chromedriver ... done
Successfully installed undetected-chromedriver-1.5.0
WARNING: You are using pip version 20.1.1; however, version 20.2.4 is available.
`

Then go with play the script with the easy way (recommended)
import undetected_chromedriver as uc
browser = uc.Chrome()

but have this error.
`Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 1350, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 1240, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 1286, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 1235, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 1006, in _send_output
    self.send(msg)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 946, in send
    self.connect()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 1409, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/Unax/PycharmProjects/just1/test.py", line 83, in <module>
    browser = uc.Chrome()
  File "/Users/Unax/PycharmProjects/just1/venv/lib/python3.8/site-packages/undetected_chromedriver/__init__.py", line 41, in __new__
    ChromeDriverManager(*args, **kwargs).install()
  File "/Users/Unax/PycharmProjects/just1/venv/lib/python3.8/site-packages/undetected_chromedriver/__init__.py", line 133, in __init__
    self.target_version = self.get_release_version_number().version[
  File "/Users/Unax/PycharmProjects/just1/venv/lib/python3.8/site-packages/undetected_chromedriver/__init__.py", line 198, in get_release_version_number
    return LooseVersion(urlopen(self.__class__.DL_BASE + path).read().decode())
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 1393, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 1353, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)>
`

**Comment by JonasGantner** [comment]
Hey, I am having a similar problem:

![image](https://user-images.githubusercontent.com/64733164/98654233-5707b700-233e-11eb-9d49-744e5255829e.png)
![image](https://user-images.githubusercontent.com/64733164/98654263-625ae280-233e-11eb-933b-fe80a0de38ce.png)

Python says this:
![image](https://user-images.githubusercontent.com/64733164/98654335-7b639380-233e-11eb-96af-bd666e9a05c8.png)

I followed all the steps..

**Comment by ultrafunkamsterdam** [comment]
> Hello,
> 
> I am amateur working with python3 + Selenium in Pycharm
> I have installed and working with selenium and python3 via: pip3
> 
> In your readme I view that you said install via "pip install undetected-chromedriver"
> but i think that in my case I need to install via "pip3 install undetected-chromedriver"
> It would be correct?
> 
> I have tried installing using "pip3" And it seems that it has been installed successfully but when go with the script have this error:
> `ModuleNotFoundError: No module named 'undetected_chromedriver'`
> 
> This is part of my code:
> 
> ```
> import undetected_chromedriver as uc
> opts = uc.ChromeOptions()
> opts.add_argument("--incognito")
> opts.add_argument("--disable-blink-features")  
> opts.add_argument("--disable-blink-features=AutomationControlled") 
> browser = uc.Chrome(options=opts)
> ```
> 
> Could you tell me that I'm doing wrong?
> thanks!

Besides adding arguments to your options object while this is already done for you the correct way out of the box? No :)

This is not an error in this program, but something wrong in your python installation/pip/etc.

[google for it ](https://www.google.com/search?q=ssl.SSLCertVerificationError:%20[SSL:%20CERTIFICATE_VERIFY_FAILED]%20certificate%20verify%20failed:%20unable%20to%20get%20local%20issuer%20certificate%20(_ssl.c:1108))



@JonasGantner This is an IDE issue (vscode is an IDE? hmm), first try to just run the code and ignore IDE warnings.
