### ISSUE TITLE
start error, TypeError: expected str, bytes or os.PathLike object, not NoneType

### ISSUE THREAD

**Issue by evensonliu** [ultrafunkamsterdam/undetected-chromedriver#497]
Hi,
       I meet this error below, and I cannot solve it. Coud you help me ?

> d = uc.Chrome(use_subprocess=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\38957\anaconda3\lib\site-packages\undetected_chromedriver\__init__.py", line 362, in __init__
    browser = subprocess.Popen(
  File "C:\Users\38957\anaconda3\lib\subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\38957\anaconda3\lib\subprocess.py", line 1251, in _execute_child
    args = list2cmdline(args)
  File "C:\Users\38957\anaconda3\lib\subprocess.py", line 553, in list2cmdline
    for arg in map(os.fsdecode, seq):
  File "C:\Users\38957\anaconda3\lib\os.py", line 818, in fsdecode
    filename = fspath(filename)  # Does type-checking of `filename`.
TypeError: expected str, bytes or os.PathLike object, not NoneType

This error shows no matter "use_subprocess=True" is set or not.

**[Environmant]**
- Python 3.8.8 (default, Apr 13 2021, 15:08:07) [MSC v.1916 32 bit (Intel)] :: Anaconda, Inc. on win32

- undetected-chromedriver, both 3.1.2 and 3.1.3

**Comment by evensonliu** [comment]
**Reason Found:**

find_chrome_executable cannot find the path of my Chrome.exe 
This was caused in __init__.py:639 ~ 640.

        for item in map(
            os.environ.get, ("PROGRAMFILES", "PROGRAMFILES(X86)", "LOCALAPPDATA")
        ):
            for subitem in (
                "Google/Chrome/Application",
                "Google/Chrome Beta/Application",
                "Google/Chrome Canary/Application",
            ):
                candidate

I test it:
> m = map(os.environ.get, ("PROGRAMFILES", "PROGRAMFILES(X86)", "LOCALAPPDATA"))
> for i in m:print(i)
> output:
C:\Program Files (x86)
C:\Program Files (x86)
C:\Users\me\AppData\Local

Actully, my Chrome.exe is located in:
> "C:\Program Files\Google\Chrome\Application\chrome.exe"

**Comment by evensonliu** [comment]
in some windows system, os.environ.get("PROGRAMFILES")  will alwasy return "C:\Program Files (x86)",

if you want to find "C:\Program Files", you should use os.environ.get("ProgramW6432 ")

so 
>for item in map(
        os.environ.get, ("PROGRAMFILES", "PROGRAMFILES(X86)", "LOCALAPPDATA")
    ):

need change to :
>for item in map(
        os.environ.get, ("PROGRAMFILES", "**ProgramW6432**", "PROGRAMFILES(X86)", "LOCALAPPDATA")
    ):


refers:
- https://stackoverflow.com/questions/1283664/python-get-wrong-value-for-os-environprogramfiles-on-64bit-vista

**Comment by saif-byte** [comment]
@evensonliu Hi, I have tried what you suggested but it still does not work. 
Here is the error:
`Traceback (most recent call last):
  File "C:\Users\DC\OneDrive\Desktop\check.py", line 5, in <module>
    driver = uc.Chrome(executable_path = 'C:\SeleniumDrivers\chromedriver.exe')
  File "C:\Users\DC\AppData\Local\Programs\Python\Python39\lib\site-packages\undetected_chromedriver\__init__.py", line 421, in __init__
    browser = subprocess.Popen(
  File "C:\Users\DC\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 947, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\DC\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 1356, in _execute_child
    args = list2cmdline(args)
  File "C:\Users\DC\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 561, in list2cmdline
    for arg in map(os.fsdecode, seq):
  File "C:\Users\DC\AppData\Local\Programs\Python\Python39\lib\os.py", line 822, in fsdecode
    filename = fspath(filename)  # Does type-checking of `filename`.
TypeError: expected str, bytes or os.PathLike object, not NoneType`

**Comment by bengabp** [comment]
@evensonliu , @saif-byte , I got this stuff working. So i was running my script periodically using the crontab service in linux. The actual problem here is that the interpreter somehow was not able to find the chromium executable and then it gave that error:
So i had to manually navigate into that directory and execute chomium myself
![image](https://user-images.githubusercontent.com/84660669/234131047-ec2439cc-cd0d-45ee-8798-854484ab8f53.png)

Then i went to my code and edited the initialization line 
from this:
```
driver = Chrome(version_main=112)
```
to this:
```
driver = Chrome(version_main=112,browser_executable_path="/snap/bin/chromium")
```

The `browser_executable_path` parameter is the path to the chromium executable. Sorry my solution is for linux but i think windows users can easily change this in their own code .
