### ISSUE TITLE
syntax error on ubuntu server

### ISSUE THREAD

**Issue by shahrooz1397** [ultrafunkamsterdam/undetected-chromedriver#499]
hi 
i have installed your driver on my computer and it works perfectly
but on my ubuntu server i get this error:
Traceback (most recent call last):
  File "main.py", line 8, in <module>
    import undetected_chromedriver as uc
  File "/usr/lib/python3.6/site-packages/undetected_chromedriver/__init__.py", line 31, in <module>
    from . import v2
  File "/usr/lib/python3.6/site-packages/undetected_chromedriver/v2.py", line 4
    from __future__ import annotations
    ^
SyntaxError: future feature annotations is not defined

**Comment by shahrooz1397** [comment]
problem fix it was because of using python3.6 i think
