### ISSUE TITLE
Argument version_main has no effect

### ISSUE THREAD

**Issue by chrisspen** [ultrafunkamsterdam/undetected-chromedriver#507]
The README states that if you get an error like:

    This version of ChromeDriver only supports Chrome version 96

then to initialize with an earlier version using the `version_main` parameter like:

    import undetected_chromedriver.v2 as uc
    driver = uc.Chrome(version_main=95)

However, this has no effect. If I use the above code, it just gives me the same error for that version, even though it looks to be downloading that version:

    [2022-02-21 03:29:19] undetected_chromedriver.patcher DEBUG getting release number from /LATEST_RELEASE_95
    [2022-02-21 03:29:19] undetected_chromedriver.patcher DEBUG downloading from https://chromedriver.storage.googleapis.com/95.0.4638.69/chromedriver_linux64.zip
    [2022-02-21 03:29:19] undetected_chromedriver.patcher DEBUG unzipping /tmp/tmppy1z5x0c
    [2022-02-21 03:29:20] undetected_chromedriver.patcher INFO patching driver executable /home/chris/.local/share/undetected_chromedriver/chromedriver
    [2022-02-21 03:29:20] uc DEBUG created a temporary folder in which the user-data (profile) will be stored during this
    session, and added it to chrome startup arguments: --user-data-dir=/tmp/tmpm1akox68
    [2022-02-21 03:29:20] uc DEBUG did not find a bad exit_type flag 
    [2022-02-21 03:29:20] selenium.webdriver.remote.remote_connection DEBUG POST http://localhost:56615/session {"capabilities": {"firstMatch": [{}], "alwaysMatch": {"browserName": "chrome", "pageLoadStrategy": "normal", "goog:chromeOptions": {"extensions": [], "binary": "/usr/bin/chromium-browser", "args": ["--headless", "--remote-debugging-host=127.0.0.1", "--remote-debugging-port=55859", "--user-data-dir=/tmp/tmpm1akox68", "--lang=en-US", "--no-default-browser-check", "--no-first-run", "--headless", "--window-size=1920,1080", "--start-maximized", "--no-sandbox", "--log-level=0"], "debuggerAddress": "127.0.0.1:55859"}}}, "desiredCapabilities": {"browserName": "chrome", "pageLoadStrategy": "normal", "goog:chromeOptions": {"extensions": [], "binary": "/usr/bin/chromium-browser", "args": ["--headless", "--remote-debugging-host=127.0.0.1", "--remote-debugging-port=55859", "--user-data-dir=/tmp/tmpm1akox68", "--lang=en-US", "--no-default-browser-check", "--no-first-run", "--headless", "--window-size=1920,1080", "--start-maximized", "--no-sandbox", "--log-level=0"], "debuggerAddress": "127.0.0.1:55859"}}}
    [2022-02-21 03:29:20] urllib3.connectionpool DEBUG Starting new HTTP connection (1): localhost:56615
    [2022-02-21 03:29:21] urllib3.connectionpool DEBUG http://localhost:56615 "POST /session HTTP/1.1" 500 836
    [2022-02-21 03:29:21] selenium.webdriver.remote.remote_connection DEBUG Finished Request
    [2022-02-21 03:29:21] uc DEBUG closing webdriver
    [2022-02-21 03:29:21] uc DEBUG killing browser
    [2022-02-21 03:29:21] uc DEBUG successfully removed /tmp/tmpm1akox68
    Traceback (most recent call last):
      File "/project/test.py", line 123, in run
        self.startup()
      File "/project/test.py", line 46, in startup
        self.driver = uc.Chrome(chrome_options=opts, options=opts, version_main=95)
      File "/project/.env/lib/python3.9/site-packages/undetected_chromedriver/__init__.py", line 369, in __init__
        super(Chrome, self).__init__(
      File "/project/.env/lib/python3.9/site-packages/selenium/webdriver/chrome/webdriver.py", line 70, in __init__
        super(WebDriver, self).__init__(DesiredCapabilities.CHROME['browserName'], "goog",
      File "/project/.env/lib/python3.9/site-packages/selenium/webdriver/chromium/webdriver.py", line 93, in __init__
        RemoteWebDriver.__init__(
      File "/project/.env/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 268, in __init__
        self.start_session(capabilities, browser_profile)
      File "/project/.env/lib/python3.9/site-packages/undetected_chromedriver/__init__.py", line 552, in start_session
        super(selenium.webdriver.chrome.webdriver.WebDriver, self).start_session(
      File "/project/.env/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 359, in start_session
        response = self.execute(Command.NEW_SESSION, parameters)
      File "/project/.env/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 424, in execute
        self.error_handler.check_response(response)
      File "/project/.env/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py", line 247, in check_response
        raise exception_class(message, screen, stacktrace)
    selenium.common.exceptions.WebDriverException: Message: unknown error: cannot connect to chrome at 127.0.0.1:55859
    from session not created: This version of ChromeDriver only supports Chrome version 95
    Current browser version is 97.0.4692.71

Notice DEBUG statement says it's downloading `https://chromedriver.storage.googleapis.com/95.0.4638.69/chromedriver_linux64.zip`, which is the 95 version, yet the ChromeDriver thinks it's using version 97.0.4692.71.

Why is it downloading version 95 but using 97? I'm not explicitly specifying any executable paths.

**Comment by chrisspen** [comment]
The problem was there was a mismatch between the browser version UC uses and the version that's installed on my system.

I used this code to lookup the local version, and pass that to UC's main_version option:

    def get_local_chrome_version():
        logger.info('Finding local Chrome version.')
        text = subprocess.getoutput('chromium-browser --version')
        matches = re.findall(r'Chromium ([0-9\.]+)', text)
        if matches:
            version = int(matches[0].split('.')[0])
            logger.info('Chrome version %s detected.', version)
            return version
        logger.info('No Chrome version detected.')

**Comment by chrisspen** [comment]
Note, this no longer works. I've since upgraded my version of Chrome, selenium, and undetected-chromedriver, and now it's all broken again, even though the version numbers still match...ugh.

**Comment by chrisspen** [comment]
It looks like something may not be setting the remote debugger address. My debugging output is:

    [2022-05-19 21:19:14] selenium.webdriver.remote.remote_connection DEBUG POST http://localhost:35687/session {"capabilities": {"firstMatch": [{}], "alwaysMatch": {"browserName": "chrome", "pageLoadStrategy": "normal", "goog:chromeOptions": {"debuggerAddress": "127.0.0.1:36229", "extensions": [], "binary": "/usr/bin/google-chrome", "args": ["--start-maximized", "--user-data-dir=/home/chris/.config/google-chrome", "--profile-directory=Profile 1", "--remote-debugging-host=127.0.0.1", "--remote-debugging-port=36229", "--lang=en-US", "--no-default-browser-check", "--no-first-run", "--log-level=0"]}}}}
    [2022-05-19 21:19:14] urllib3.connectionpool DEBUG Starting new HTTP connection (1): localhost:35687

Notice the debugging port in the options is "36229",  but the final line says it's trying to open port 35687. Why is this?
