### ISSUE TITLE
Yet another multi-process error

### ISSUE THREAD

**Issue by PureSci** [ultrafunkamsterdam/undetected-chromedriver#518]
`Process Process-1:
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\undetected_chromedriver\dprocess.py", line 59, in _start_detached
    p = Popen([executable, *args], stdin=PIPE, stdout=PIPE, stderr=PIPE, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 966, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 1375, in _execute_child
    args = list2cmdline(args)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 561, in list2cmdline
    for arg in map(os.fsdecode, seq):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\os.py", line 822, in fsdecode
    filename = fspath(filename)  # Does type-checking of `filename`.
TypeError: expected str, bytes or os.PathLike object, not NoneType`

Getting this error with that simple lane of code.

`if __name__ == '__main__':
    import undetected_chromedriver as uc
    driver = uc.Chrome()
    driver.get('https://nowsecure.nl')`

**Comment by sebdelsol** [comment]
it seems your chrome executable is not found... have you tried to call [`find_chrome_executable()`](https://github.com/ultrafunkamsterdam/undetected-chromedriver/blob/a4cc4a8b72691a3f5462b6f23973727e2b03da9e/undetected_chromedriver/__init__.py#L621) to check whether it returns `None` ?

**Comment by ImperialCrise** [comment]
Hello i did this function and yes it returns None...

**Comment by sebdelsol** [comment]
Have you installed Chrome in its default directory ? could you check its actual path ?
You'll find the actual `find_chrome_executable()` code [here](https://github.com/ultrafunkamsterdam/undetected-chromedriver/blob/a4cc4a8b72691a3f5462b6f23973727e2b03da9e/undetected_chromedriver/__init__.py#L621).

Anyway one easy workaround is to add your chrome path in `os.environ["PATH"]` before instantiating a driver.
