### ISSUE TITLE
Can't make a sample code work

### ISSUE THREAD

**Issue by MathiAs2Pique** [ultrafunkamsterdam/undetected-chromedriver#519]
Hi there, I'm new here.
Being detected on some websites with Selenium "vanilla", I'm trying undetected-chromedriver to bypass their detections, but I can't even get the demo program to work.

My code :

```python
import undetected_chromedriver as uc
driver = uc.Chrome()
driver.get('https://nowsecure.nl')
```

The error : 
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Python310\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Python310\lib\multiprocessing\spawn.py", line 125, in _main
    prepare(preparation_data)
  File "C:\Python310\lib\multiprocessing\spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Python310\lib\multiprocessing\spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "C:\Python310\lib\runpy.py", line 269, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "C:\Python310\lib\runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "C:\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\Fichiers\Bureau\Bureau\Code\NikePourEdouard\test.py", line 2, in <module>
    driver = uc.Chrome()
  File "C:\Python310\lib\site-packages\undetected_chromedriver\__init__.py", line 356, in __init__
    self.browser_pid = start_detached(
  File "C:\Python310\lib\site-packages\undetected_chromedriver\dprocess.py", line 35, in start_detached
    ).start()
  File "C:\Python310\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "C:\Python310\lib\multiprocessing\context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Python310\lib\multiprocessing\context.py", line 327, in _Popen
    return Popen(process_obj)
  File "C:\Python310\lib\multiprocessing\popen_spawn_win32.py", line 45, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "C:\Python310\lib\multiprocessing\spawn.py", line 154, in get_preparation_data
    _check_not_importing_main()
  File "C:\Python310\lib\multiprocessing\spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
```

**Comment by JokersCat** [comment]
yeah got the same problem :(

**Comment by RobbyFrank** [comment]
@MathiAs2Pique  **Try this:**

`import undetected_chromedriver as uc

if __name__ == '__main__':
    driver = uc.Chrome()
    driver.get("https://google.com")`

**Comment by ToasterUwU** [comment]
@JokersCat @MathiAs2Pique 

what @RobbyFrank said works 100%, every second issue on this GitHub page is basically this error.

**Comment by ToasterUwU** [comment]
@ultrafunkamsterdam ready to close the issue

**Comment by andr0s** [comment]
@sebdelsol 

Well after reading this solution https://github.com/ultrafunkamsterdam/undetected-chromedriver/issues/561#issuecomment-1075363395

I must say that the docs really need to be improved/fixed.

We, as users of this library, are not supposed to understand how exactly it's written. Multiprocessing, threading, single thread or whatever. If examples of the code are not working then they aren't examples - they are useless, misleading and confusing.

If you think that's a negative feedback from me then this line "Python multiprocessing documentation is worth a read" is arrogant and ignorant ;) Instead of giving the solution, it just spreads that passive aggressive "RTFM" attitude.

With all that being said, I really appreciate time time you spent to create this lib and it really does its job and it's great! Thanks!

**Comment by sebdelsol** [comment]
Sure please create a pull request for that.

In this case _the solution is literally given in the error_, and if you want to learn why it happens then the best way is to actually _read the multiprocessing documentation_. I don't see how it's arrogant or ignorant to help people learn to be more self reliant. 

As a user of this **free** library you're supposed to take some time to understand what you're doing wrong instead of creating another duplicate of the same basic issue, _relying on other people free time_  just because you didn't bother to read a basic Python documentation...This sense of entitlement just confounds me.

**Comment by ToasterUwU** [comment]
I see both points. 

Its important to understand errors and be able to find solutions, if you rely on other people to fix your problems, you barely even deserve the title "Script Kiddy", it would more be a "CTRL+C CTR+V Goblin"

But i also think its important to make sure the library works properly.
Yes is free software, yes its not fair to demand anything for free, no a issue that is a problem to many people shouldnt be answered with "Read the multiprecessing docs". Instead it should be that someone makes a fix for it, and if thats not possible it should at least be explained in the example. An example code for trying it out should be correct, and not incorrect and throw errors. And tbh, most of these people making the issues on this github repo, wouldnt be here if the freeze support problem would be explained on a basic level in the example code.

**Comment by sebdelsol** [comment]
If you think a documentation should explain how to read a exception message and remind basic Python idioms then _feel free to create a pull request_.

**Comment by andr0s** [comment]
First of all, I didn’t say that someone specifically SHOULD go and fix it.
The docs need to be fixed, in my opinion, but I never told anyone
specifically to go and fix it.

I didn’t devaluate anyone’s efforts and time spent on this library. So
please try to avoid devaluating other developers by insulting them with
that “don’t deserve a script kiddy” - or your label yourself as a toxic
judgemental person, not less not more.

We all don’t owe anything to anyone. You guys created this library but it
doesn’t automatically mean other people have to comply with your
expectations - we are all free to leave comments and feedback here if it
doesn’t offend someone specifically. You, on the other hand, absolutely
don’t have to do anything we ask.

In my opinion it’s just inefficient to stumble upon duplicated issues and
see people complaining VS just fixing it once and forever. Just my opinion,
okay? No need to get offended about it haha :)

Don’t wanna see dupes, opinions and feedback? Well, just close the issues
:)

Again, our suggestions and feedback and expectations don’t mean you gotta
actually do what we want. And I never blamed you for not doing that.

**Comment by sebdelsol** [comment]
People that don't bother to read an exception message won't read the documentation either.

Windows lack of support for forking a process makes multiprocessing cumbersome, fortunately Google gives you hundreds of thousand solutions. 

So I'm very curious to find out what what would be a "once and forever fix" that would beat a 5 seconds Google search.

**Comment by ToasterUwU** [comment]
> @ToasterUWu, @andr0s
> 
> People that don't bother to read an exception message won't read the documentation either.
> 
> Windows lack of support for forking a process makes Python multiprocessing cumbersome on that system, fortunately Google gives you hundreds of thousands valid solutions that all show you how to protect your main entry point.
> 
> I'm at a loss to find a fix that would beat a 5 seconds Google search. Maybe both of you have some practical suggestions ?

Disclosing it in the example would still be a good idea. No matter if fix or not.
