### ISSUE TITLE
urllib.error.URLError: <urlopen error [WinError 10061]

### ISSUE THREAD

**Issue by LeftH0ok** [ultrafunkamsterdam/undetected-chromedriver#522]
OS Name:                   Microsoft Windows 10 Professional Edition
OS Version:                10.0.19042 N/A Build 19042
Python Version:          3.10.2
undetected_chromedriver version: 3.1.3
-----------------------------------------ERROR------------------------------------------------
Traceback (most recent call last):
  File "D:\Program Files\Python310\lib\urllib\request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "D:\Program Files\Python310\lib\http\client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "D:\Program Files\Python310\lib\http\client.py", line 1328, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "D:\Program Files\Python310\lib\http\client.py", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "D:\Program Files\Python310\lib\http\client.py", line 1037, in _send_output
    self.send(msg)
  File "D:\Program Files\Python310\lib\http\client.py", line 975, in send
    self.connect()
  File "D:\Program Files\Python310\lib\http\client.py", line 1447, in connect
    super().connect()
  File "D:\Program Files\Python310\lib\http\client.py", line 941, in connect
    self.sock = self._create_connection(
  File "D:\Program Files\Python310\lib\socket.py", line 845, in create_connection
    raise err
  File "D:\Program Files\Python310\lib\socket.py", line 833, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\admin\Desktop\stupid-xyz\main.py", line 2, in <module>
    driver = uc.Chrome()
  File "C:\Users\admin\Desktop\stupid-xyz\venv\lib\site-packages\undetected_chromedriver\__init__.py", line 208, in __init__
    patcher.auto()
  File "C:\Users\admin\Desktop\stupid-xyz\venv\lib\site-packages\undetected_chromedriver\patcher.py", line 118, in auto
    release = self.fetch_release_number()
  File "C:\Users\admin\Desktop\stupid-xyz\venv\lib\site-packages\undetected_chromedriver\patcher.py", line 140, in fetch_release_number
    return LooseVersion(urlopen(self.url_repo + path).read().decode())
  File "D:\Program Files\Python310\lib\urllib\request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "D:\Program Files\Python310\lib\urllib\request.py", line 519, in open
    response = self._open(req, data)
  File "D:\Program Files\Python310\lib\urllib\request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "D:\Program Files\Python310\lib\urllib\request.py", line 496, in _call_chain
    result = func(*args)
  File "D:\Program Files\Python310\lib\urllib\request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "D:\Program Files\Python310\lib\urllib\request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [WinError 10061] No connection could be made because the target machine actively refused it>

Process finished with exit code 1

**Comment by sebdelsol** [comment]
The patcher can't establish a connection with the [chromedriver storage server](https://chromedriver.storage.googleapis.com/) to download the chromedriver executable. Can you access it on your browser ? There might be something wrong with your Python environment.

**Comment by LeftH0ok** [comment]
Thank you, I reinstalled version 3.1.3, and it works fine already
