### ISSUE TITLE
Issue with multiprocessing(?)

### ISSUE THREAD

**Issue by bntr00t** [ultrafunkamsterdam/undetected-chromedriver#561]
C:\Program Files\Google\Chrome\Application\chrome.exe
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\bnt\AppData\Local\Programs\Python\Python39\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\bnt\AppData\Local\Programs\Python\Python39\lib\multiprocessing\spawn.py", line 125, in _main
    prepare(preparation_data)
  File "C:\Users\bnt\AppData\Local\Programs\Python\Python39\lib\multiprocessing\spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\bnt\AppData\Local\Programs\Python\Python39\lib\multiprocessing\spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "C:\Users\bnt\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 268, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "C:\Users\bnt\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "C:\Users\bnt\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\bnt\Documents\Documents\all2\all2\all2\1337Zip\uProxy Tool 2.1\demoSC\t1.py", line 4, in <module>
    driver = uc.Chrome()
  File "C:\Users\bnt\AppData\Local\Programs\Python\Python39\lib\site-packages\undetected_chromedriver\__init__.py", line 388, in __init__
    self.browser_pid = start_detached(
  File "C:\Users\bnt\AppData\Local\Programs\Python\Python39\lib\site-packages\undetected_chromedriver\dprocess.py", line 30, in start_detached
    multiprocessing.Process(
  File "C:\Users\bnt\AppData\Local\Programs\Python\Python39\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "C:\Users\bnt\AppData\Local\Programs\Python\Python39\lib\multiprocessing\context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\bnt\AppData\Local\Programs\Python\Python39\lib\multiprocessing\context.py", line 327, in _Popen
    return Popen(process_obj)
  File "C:\Users\bnt\AppData\Local\Programs\Python\Python39\lib\multiprocessing\popen_spawn_win32.py", line 45, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "C:\Users\bnt\AppData\Local\Programs\Python\Python39\lib\multiprocessing\spawn.py", line 154, in get_preparation_data
    _check_not_importing_main()
  File "C:\Users\bnt\AppData\Local\Programs\Python\Python39\lib\multiprocessing\spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                '''

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.

Code used
```        
import undetected_chromedriver.v2 as uc
a = uc.find_chrome_executable()
print(a)
driver = uc.Chrome()
driver.get('https://nowsecure.nl')
```

**Comment by sebdelsol** [comment]
**This is not a bug**, but people keep raising this as an issue when they don't understand how Python multiprocessing works _on Windows_.

Please protect the main entry point where you create a driver, this a [well known Python idiom](https://docs.python.org/3/library/multiprocessing.html#the-spawn-and-forkserver-start-methods):

```python3
import undetected_chromedriver as uc


# this code will be executed twice (main process & sub process)
print ("Python multiprocessing documentation is worth a read")

if __name__ == '__main__':
    # this code will be executed only once (main process)
    driver = uc.Chrome()
    driver.get("https://nowsecure.nl")
```
You'll see that the message is _printed twice_ !

This is not a bug but Python multiprocessing lib protecting you against recursive process spawning by raising an error.

**Comment by bntr00t** [comment]
oh, wow i've never known that, well makes sense now

thanks for the info, i will read through it :D

**Comment by aerobinsonIV** [comment]
Thank you so much, words are not enough to express my gratitude for giving simple example code

**Comment by RichardAtCT** [comment]
I have a question that hopefully someone can help with. I want to use UC in a package that I have created. Now my understanding is that if I make use of `if __name__ == '__main__':` it will never be run as I am not running the code directly. Is this correct? If so what is the best way to go about it?
Thanks!

**Comment by sebdelsol** [comment]
Everything will be re-imported again so you still need to protect your main entry point where you instantiate anything that'll end up creating the driver.
