### ISSUE TITLE
status code 127

### ISSUE THREAD

**Issue by defning** [ultrafunkamsterdam/undetected-chromedriver#571]
i am using Replit to run this code. i get status code 127 everytime i use undetected-chromedriver, chrome opens but the code gets stopped and give me an status code 127.
this is the error i got:
`Traceback (most recent call last):
  File "main.py", line 30, in on_message
    driver = uc.Chrome(options=chrome_options)
  File "/home/runner/web-bot/venv/lib/python3.8/site-packages/undetected_chromedriver/__init__.py", line 401, in __init__
    super(Chrome, self).__init__(
  File "/home/runner/web-bot/venv/lib/python3.8/site-packages/selenium/webdriver/chrome/webdriver.py", line 70, in __init__
    super(WebDriver, self).__init__(DesiredCapabilities.CHROME['browserName'], "goog",
  File "/home/runner/web-bot/venv/lib/python3.8/site-packages/selenium/webdriver/chromium/webdriver.py", line 90, in __init__
    self.service.start()
  File "/home/runner/web-bot/venv/lib/python3.8/site-packages/selenium/webdriver/common/service.py", line 98, in start
    self.assert_process_still_running()
  File "/home/runner/web-bot/venv/lib/python3.8/site-packages/selenium/webdriver/common/service.py", line 110, in assert_process_still_running
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: Service /home/runner/.local/share/undetected_chromedriver/50b2b46168d4b928_chromedriver unexpectedly exited. Status code was: 127`

**Comment by sebdelsol** [comment]
It means your chromedriver has crashed. Without any code or context it could be anything.

**Comment by sebdelsol** [comment]
It's a very likely a duplicate of #572 which has been resolved (this was not a bug btw).
Please check that your undetected-chromedriver package and your Chrome are both correctly updated.

**Comment by aasharck** [comment]
I also got this exact same error while running on replit. Here's the code - 
`import undetected_chromedriver as uc
from selenium.webdriver.chrome.options import Options

options = Options()
options.add_argument('--no-sandbox')
options.add_argument('--disable-dev-shm-usage')
options.add_argument("--incognito")
driver = uc.Chrome(options=options)

driver.get("https://google.com/")`

Any help would be appreciated! 😀

**Comment by PhilipNiedzwiadek** [comment]
Im having the exact same error running pretty much the exact same things as aasharck. I would love to hear if anyone has found a solution to this.

**Comment by heckedbyfurki** [comment]
Have you found it ?

**Comment by TurgutHarunArslan** [comment]
How can i change path of the driver to location of replit's chromedriver, cause idk where's the chrome driver in replit is

**Comment by Nothig00** [comment]
@PhilipNiedzwiadek @sebdelsol @heckedbyfurki 
Have u guys found solution for this error.

**Comment by heckedbyfurki** [comment]
> How can i change path of the driver to location of replit's chromedriver, cause idk where's the chrome driver in replit is

By running chormedriver --help on replits shell you can get full path.

**Comment by heckedbyfurki** [comment]
> @PhilipNiedzwiadek @sebdelsol @heckedbyfurki @aasharck Have u guys found solution for this error.

Read my comment above

**Comment by TurgutHarunArslan** [comment]
Okay thanks I'll try!

**Comment by TurgutHarunArslan** [comment]
@heckedbyfurki  Hello i get same error + my chromium is 108.0.5359.94
and my chrome driver is 108.0.5359.71   and i set this by 
![image](https://user-images.githubusercontent.com/83730616/221401781-5f5589cf-7337-4b06-a385-bbe58b019d2b.png)

**Comment by Nothig00** [comment]
@TurgutHarunArslan sir can u pls guide in steps how to solve this error.
Really sir I'm not get single step of improvement.

**Comment by heckedbyfurki** [comment]
> @heckedbyfurki Hello i get same error + my chromium is 108.0.5359.94 and my chrome driver is 108.0.5359.71 and i set this by ![image](https://user-images.githubusercontent.com/83730616/221401781-5f5589cf-7337-4b06-a385-bbe58b019d2b.png) how can i download same version of them?

It should be driver_executable_path, not browser_executable_path

**Comment by heckedbyfurki** [comment]
> @heckedbyfurki  sir can u pls guide in steps how to solve this error.
> Really sir I'm not get single step of improvement.

- Include chromedriver and chromium on nix packages 

-Initialize undetected chromedriver with driver_executable_path as replit's chromedriver path

-Enjoy?

**Comment by TurgutHarunArslan** [comment]
@heckedbyfurki  im now getting permission denied

**Comment by heckedbyfurki** [comment]
> @heckedbyfurki  im now getting permission denied

There's probably something else missing. Since you fixed error code 127 you can look that up on internet.

**Comment by Nothig00** [comment]
@heckedbyfurki can u do something like this https://replit.com/talk/learn/Python-Selenium-Tutorial-The-Basics/148030

It's really going to helpful for proper set without getting in any kind of error. And pulling hair.

**Comment by TurgutHarunArslan** [comment]
Normal selenium works man , uc doesnt

**Comment by Nothig00** [comment]
```
import undetected_chromedriver as uc
from selenium.webdriver.chrome.options import Options

options = Options()
options.add_argument('--no-sandbox')
options.add_argument('--disable-dev-shm-usage')
options.add_extension('Metamask.crx')
options.page_load_strategy = 'eager'
driver = uc.Chrome(options=options)

#driver.get("chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/home.html#onboarding/import-with-recovery-phrase")

driver.get("https://opensea.io")
print('finish')
```

Here my code.

I did all the things u guide to do but because of my skills I'm still getting same error.

Help me @heckedbyfurki bro

**Comment by Nothig00** [comment]
> > @heckedbyfurki  sir can u pls guide in steps how to solve this error.
> > Really sir I'm not get single step of improvement.
> 
> * Include chromedriver and chromium on nix packages
> * Initialize undetected chromedriver with driver_executable_path as replit's chromedriver path
> * Enjoy?

```
import undetected_chromedriver as uc
from selenium.webdriver.chrome.options import Options

options = Options()
options.add_argument('--no-sandbox')
options.add_argument('--disable-dev-shm-usage')
options.add_extension('Metamask.crx')
options.page_load_strategy = 'eager'
driver = uc.Chrome(options=options)

#driver.get("chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/home.html#onboarding/import-with-recovery-phrase")

driver.get("https://opensea.io")
print('finish')
```

Here my code.

I did all the things u guide to do but because of my skills I'm still getting same error.

**Comment by Nothig00** [comment]
> Normal selenium works man , uc doesnt

Your error got fixed?

**Comment by Nothig00** [comment]
Still stuck on same error

**Comment by TurgutHarunArslan** [comment]
> > @heckedbyfurki  sir can u pls guide in steps how to solve this error.
> > Really sir I'm not get single step of improvement.
> 
> * Include chromedriver and chromium on nix packages
> * Initialize undetected chromedriver with driver_executable_path as replit's chromedriver path
> * Enjoy?

hey bro sorry for pinging again, its giving permission error

**Comment by khoi1908vn** [comment]
if you got permission error when setting the driver_executable_path to /nix/store/.../chromedriver then try to give it permissions : `chmod 777 /nix/store/.../bin/chromedriver`

**Comment by Wellmare** [comment]
And how do I change the path if undetected chromedriver is used in another library? (https://github.com/terry3041/pyChatGPT)

**Comment by cheemzboi** [comment]
anybody found the fix i have tried everything but it just doesnt work

**Comment by realZyxxy** [comment]
I have solved this - see https://stackoverflow.com/questions/71201650/

**Comment by Jediweirdo** [comment]
For the people who don't want to read through all of the comments to fix this, here's a step by step guide that confirmed works:

1. Open up the replit shell and put in chromedriver --help. If you get prompted about the command not being installed, say yes. After it's done running, it should return something like this:

```
/nix/store/n4qcnqy0isnvxcpcgv6i2z9ql9wsxksw-chromedriver-114.0.5735.90
Usage: /nix/store/n4qcnqy0isnvxcpcgv6i2z9ql9wsxksw-chromedriver-114.0.5735.90/bin/chromedriver [OPTIONS]

Options
[insert a list of commands here]

```
Copy the directory labeled as "Usage" using ctrl+shift+c or via the right click menu (Replit copy/paste can be weird sometimes)

2. Any file in the nix directory needs permission in order to be accessed via a program. So, before you leave the shell, run `chmod 777 path/to/chromedriver`

3. Going back to your code, you need to add an argument when you initialize uc. Copy/paste the following into your code:
```
import undetected_chromedriver as uc
driver = uc.Chrome(headless=True,use_subprocess=False, driver_executable_path = "path/to/chromedriver")
```

**Comment by 34j** [comment]
> 2\. Any file in the nix directory needs permission in order to be accessed via a program. So, before you leave the shell, run `chmod 777 path/to/chromedriver`

This does not work on my end, it says `Read-only file system`

**Comment by VanshChandra06** [comment]
> 2. Any file in the nix directory needs permission in order to be accessed via a program. So, before you leave the shell, run `chmod 777 path/to/chromedriver`

its saying operation not permitted for me, what can i do?
