### ISSUE TITLE
Chrome can not be opened

### ISSUE THREAD

**Issue by YOTYTeaM** [ultrafunkamsterdam/undetected-chromedriver#572]
I get this error

```
patching driver executable C:\Users\YOTYTeaM\appdata\roaming\undetected_chromedriver\a1092ea028fa5cf8_chromedriver.exe
Exception in thread Thread-2:
Traceback (most recent call last):
  File "C:\Users\YOTYTeaM\AppData\Local\Programs\Python\Python39\lib\threading.py", line 954, in _bootstrap_inner
    self.run()
  File "C:\Users\YOTYTeaM\AppData\Local\Programs\Python\Python39\lib\threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "G:\..\Basic.py", line 38, in create
    self.driver = self.make_driver()
  File "G:\..\Chrome.py", line 47, in make_driver
    driver = Chrome(options=option, browser_executable_path=os.getcwd()+"\\Resources\\Drivers\\chromedriver.exe")
  File "C:\Users\YOTYTeaM\AppData\Local\Programs\Python\Python39\lib\site-packages\undetected_chromedriver\__init__.py", line 401, in __init__
    super(Chrome, self).__init__(
  File "C:\Users\YOTYTeaM\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 70, in __init__
    super(WebDriver, self).__init__(DesiredCapabilities.CHROME['browserName'], "goog",
  File "C:\Users\YOTYTeaM\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\chromium\webdriver.py", line 93, in __init__
    RemoteWebDriver.__init__(
  File "C:\Users\YOTYTeaM\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 269, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Users\YOTYTeaM\AppData\Local\Programs\Python\Python39\lib\site-packages\undetected_chromedriver\__init__.py", line 589, in start_session
    super(selenium.webdriver.chrome.webdriver.WebDriver, self).start_session(
  File "C:\Users\YOTYTeaM\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 360, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Users\YOTYTeaM\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 425, in execute
    self.error_handler.check_response(response)
  File "C:\Users\YOTYTeaM\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot connect to chrome at 127.0.0.1:5456
from chrome not reachable
Stacktrace:
Backtrace:
        Ordinal0 [0x009A7413+2389011]
        Ordinal0 [0x00939F61+1941345]
        Ordinal0 [0x0082C520+836896]
        Ordinal0 [0x008205AB+787883]
        Ordinal0 [0x0084C128+966952]
        Ordinal0 [0x00845D9B+941467]
        Ordinal0 [0x00845B66+940902]
        Ordinal0 [0x00878C80+1150080]
        Ordinal0 [0x008788DA+1149146]
        Ordinal0 [0x00873F66+1130342]
        Ordinal0 [0x0084E546+976198]
        Ordinal0 [0x0084F456+980054]
        GetHandleVerifier [0x00B59632+1727522]
        GetHandleVerifier [0x00C0BA4D+2457661]
        GetHandleVerifier [0x00A3EB81+569713]
        GetHandleVerifier [0x00A3DD76+566118]
        Ordinal0 [0x00940B2B+1968939]
        Ordinal0 [0x00945988+1989000]
        Ordinal0 [0x00945A75+1989237]
        Ordinal0 [0x0094ECB1+2026673]
        BaseThreadInitThunk [0x7691FA29+25]
        RtlGetAppContainerNamedObjectPath [0x77507A9E+286]
        RtlGetAppContainerNamedObjectPath [0x77507A6E+238]
```

**Comment by sebdelsol** [comment]
howdy, how are we're supposed to reproduce that ? what's your options ? Are you launching drivers in multi thread ? what's your OS ? have you updated Selenium and undetected-chromedriver ?

**Comment by varna9000** [comment]
Hi I have the same error. 
I'm just using the example code from the Readme. My path is `/usr/bin/chromedriver` and it's in the PATH.

**Comment by sebdelsol** [comment]
It doesn't help though : please show some code or at least the logs before the error. 
Btw which path do you mean ? `driver_executable_path `or `browser_executable_path` ?

**Comment by varna9000** [comment]
Ok, so there's the code and error from the REPL:

```
Python 3.7.3 (default, Jan 22 2021, 20:04:44)
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import undetected_chromedriver as uc
>>> driver = uc.Chrome()
^[[A^[[ATraceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/milen/nap/env/lib/python3.7/site-packages/undetected_chromedriver/__init__.py", line 408, in __init__
    keep_alive=keep_alive,
  File "/home/milen/nap/env/lib/python3.7/site-packages/selenium/webdriver/chrome/webdriver.py", line 73, in __init__
    service_log_path, service, keep_alive)
  File "/home/milen/nap/env/lib/python3.7/site-packages/selenium/webdriver/chromium/webdriver.py", line 99, in __init__
    options=options)
  File "/home/milen/nap/env/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 269, in __init__
    self.start_session(capabilities, browser_profile)
  File "/home/milen/nap/env/lib/python3.7/site-packages/undetected_chromedriver/__init__.py", line 590, in start_session
    capabilities, browser_profile
  File "/home/milen/nap/env/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 360, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/milen/nap/env/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 425, in execute
    self.error_handler.check_response(response)
  File "/home/milen/nap/env/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot connect to chrome at 127.0.0.1:33107
from chrome not reachable
Stacktrace:
#0 0x5596f95fead3 <unknown>
#1 0x5596f935e3ff <unknown>
#2 0x5596f934cab9 <unknown>
#3 0x5596f9384f69 <unknown>
#4 0x5596f937cee6 <unknown>
#5 0x5596f93b82ba <unknown>
#6 0x5596f93b24e3 <unknown>
#7 0x5596f9387d1a <unknown>
#8 0x5596f9388e75 <unknown>
#9 0x5596f962cefd <unknown>
#10 0x5596f964619b <unknown>
#11 0x5596f962ec65 <unknown>
#12 0x5596f9646ec8 <unknown>
#13 0x5596f9622360 <unknown>
#14 0x5596f9662a68 <unknown>
#15 0x5596f9662be8 <unknown>
#16 0x5596f967c7fd <unknown>
#17 0x7f59f16a5fa3 <unknown>
```

**Comment by sebdelsol** [comment]
* I actually meant the **undetected**_chromedriver version (current one is _3.1.5r4_), not the chromdriver's one. 
* Is your Chrome actually launched ? 
* Is your chrome the same version as your chromedriver ? undetected-chromedriver is supposed to download the [latest release](https://chromedriver.storage.googleapis.com/LATEST_RELEASE), how come you've got a version that's 1 year old ?
* The actual logs would probably be helpful `logging.basicConfig(level=logging.DEBUG)`

**Comment by varna9000** [comment]
- `undetected_chromedriver-3.1.5.post4.dist-info`
- No, Chrome is not launched. Should it be?
- Chromium Version 90.0.4430.212 (Developer Build) built on Debian 10.9, running on Debian 10.11 (64-bit)
- I have no idea. I pip installed undetected-chromedriver
- will try to log now.

**Comment by varna9000** [comment]
Here's the same code with logging:

```
Python 3.7.3 (default, Jan 22 2021, 20:04:44)
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import undetected_chromedriver as uc
>>> import logging
>>> logging.basicConfig(level=logging.DEBUG)
>>> driver = uc.Chrome()
DEBUG:undetected_chromedriver.patcher:getting release number from /LATEST_RELEASE
DEBUG:undetected_chromedriver.patcher:downloading from https://chromedriver.storage.googleapis.com/100.0.4896.60/chromedriver_linux64.zip
DEBUG:undetected_chromedriver.patcher:unzipping /tmp/tmp7r2xr2sb
INFO:undetected_chromedriver.patcher:patching driver executable /home/milen/.local/share/undetected_chromedriver/3ee16d33c206cfb6_chromedriver
DEBUG:selenium.webdriver.remote.remote_connection:POST http://localhost:47401/session {"capabilities": {"firstMatch": [{}], "alwaysMatch": {"browserName": "chrome", "pageLoadStrategy": "normal", "goog:chromeOptions": {"extensions": [], "binary": "/usr/bin/chromium", "args": ["--remote-debugging-host=127.0.0.1", "--remote-debugging-port=35373", "--user-data-dir=/tmp/tmpsi14ddi1", "--lang=bg-BG", "--no-default-browser-check", "--no-first-run", "--log-level=0"], "debuggerAddress": "127.0.0.1:35373"}}}, "desiredCapabilities": {"browserName": "chrome", "pageLoadStrategy": "normal", "goog:chromeOptions": {"extensions": [], "binary": "/usr/bin/chromium", "args": ["--remote-debugging-host=127.0.0.1", "--remote-debugging-port=35373", "--user-data-dir=/tmp/tmpsi14ddi1", "--lang=bg-BG", "--no-default-browser-check", "--no-first-run", "--log-level=0"], "debuggerAddress": "127.0.0.1:35373"}}}
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost:47401
DEBUG:urllib3.connectionpool:http://localhost:47401 "POST /session HTTP/1.1" 500 769
DEBUG:selenium.webdriver.remote.remote_connection:Finished Request
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/milen/nap/env/lib/python3.7/site-packages/undetected_chromedriver/__init__.py", line 408, in __init__
    keep_alive=keep_alive,
  File "/home/milen/nap/env/lib/python3.7/site-packages/selenium/webdriver/chrome/webdriver.py", line 73, in __init__
    service_log_path, service, keep_alive)
  File "/home/milen/nap/env/lib/python3.7/site-packages/selenium/webdriver/chromium/webdriver.py", line 99, in __init__
    options=options)
  File "/home/milen/nap/env/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 269, in __init__
    self.start_session(capabilities, browser_profile)
  File "/home/milen/nap/env/lib/python3.7/site-packages/undetected_chromedriver/__init__.py", line 590, in start_session
    capabilities, browser_profile
  File "/home/milen/nap/env/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 360, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/milen/nap/env/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 425, in execute
    self.error_handler.check_response(response)
  File "/home/milen/nap/env/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot connect to chrome at 127.0.0.1:35373
from chrome not reachable
Stacktrace:
#0 0x55b772617ad3 <unknown>
#1 0x55b7723773ff <unknown>
#2 0x55b772365ab9 <unknown>
#3 0x55b77239df69 <unknown>
#4 0x55b772395ee6 <unknown>
#5 0x55b7723d12ba <unknown>
#6 0x55b7723cb4e3 <unknown>
```

**Comment by sebdelsol** [comment]
Your Chrome and Chromedriver versions match (and I guess Selenium would have explicitly said so otherwise). 
Yes Chrome is spawned in a detached process by undetected-chromedriver, if it crashes Selenium throws this error because it can't connect to it.
Does the Chromium found by `undetected_chromedriver.find_chrome_executable()` actually works fine ?

**Comment by varna9000** [comment]
Yes, it seem so:

```
iport undetected_chromedriver
>>> undetected_chromedriver.find_chrome_executable()
'/usr/bin/chromium'
```

I don't think I have other Chromium versions.

**Comment by varna9000** [comment]
<img width="1169" alt="Screenshot 2022-04-08 at 16 57 16" src="https://user-images.githubusercontent.com/39020101/162450679-ccc8cf51-99b3-4237-9f74-6fb1b41bd784.png">

**Comment by sebdelsol** [comment]
Hence the error : chromedriver won't connect to a chrome that has a different version number. 
Please update your Chromium and it should work.
What's surprising is that Selenium didn't explicitly told so in its error...

**Comment by varna9000** [comment]
Ok Thank you. Is there a way to force undetected-chromdriver not to download the newest chrome or it defeats the purpose? Updating anything on Debian to the newest version is a nightmare.

**Comment by sebdelsol** [comment]
Yes you can 
* Either use the `version_main` argument : the asked version will be downloaded and patched so that its signature will change each time a chromedriver is spawned.
* Or use the `driver_executable_path` argument (please find the [documentation here](https://github.com/ultrafunkamsterdam/undetected-chromedriver/blob/b2e804e977c9cf3dd9c845474752cac142a72508/undetected_chromedriver/__init__.py#L142)) to force the use of the chromedriver already existing in this path. I would not recommend that since it'll be patched only once and you'll end up with a chromedriver that always has the same signature which might trigger some detection.

**Comment by varna9000** [comment]
I tried with `version_main=90` but get the same error, although undetected_chromedrive seems to be downloading the v.90 now. I'm really confused. Will try on another machine with up-to-date Chromium and revert.

```
>>> import logging
>>> logging.basicConfig(level=logging.DEBUG)
>>> driver = uc.Chrome(version_main=90)
DEBUG:undetected_chromedriver.patcher:getting release number from /LATEST_RELEASE_90
DEBUG:undetected_chromedriver.patcher:downloading from https://chromedriver.storage.googleapis.com/90.0.4430.24/chromedriver_linux64.zip
DEBUG:undetected_chromedriver.patcher:unzipping /tmp/tmp7rzrjxg0
INFO:undetected_chromedriver.patcher:patching driver executable /home/milen/.local/share/undetected_chromedriver/6255cd5679df8c48_chromedriver
DEBUG:selenium.webdriver.remote.remote_connection:POST http://localhost:55495/session {"capabilities": {"firstMatch": [{}], "alwaysMatch": {"browserName": "chrome", "pageLoadStrategy": "normal", "goog:chromeOptions": {"extensions": [], "binary": "/bin/chromium", "args": ["--remote-debugging-host=127.0.0.1", "--remote-debugging-port=32981", "--user-data-dir=/tmp/tmpvzlzd0rl", "--lang=bg-BG", "--no-default-browser-check", "--no-first-run", "--log-level=0"], "debuggerAddress": "127.0.0.1:32981"}}}, "desiredCapabilities": {"browserName": "chrome", "pageLoadStrategy": "normal", "goog:chromeOptions": {"extensions": [], "binary": "/bin/chromium", "args": ["--remote-debugging-host=127.0.0.1", "--remote-debugging-port=32981", "--user-data-dir=/tmp/tmpvzlzd0rl", "--lang=bg-BG", "--no-default-browser-check", "--no-first-run", "--log-level=0"], "debuggerAddress": "127.0.0.1:32981"}}}
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost:55495
DEBUG:urllib3.connectionpool:http://localhost:55495 "POST /session HTTP/1.1" 500 183
DEBUG:selenium.webdriver.remote.remote_connection:Finished Request
DEBUG:undetected_chromedriver.patcher:successfully unlinked /home/milen/.local/share/undetected_chromedriver/68429eee05baf5bc_chromedriver
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/milen/nap/env/lib/python3.7/site-packages/undetected_chromedriver/__init__.py", line 408, in __init__
    keep_alive=keep_alive,
  File "/home/milen/nap/env/lib/python3.7/site-packages/selenium/webdriver/chrome/webdriver.py", line 73, in __init__
    service_log_path, service, keep_alive)
  File "/home/milen/nap/env/lib/python3.7/site-packages/selenium/webdriver/chromium/webdriver.py", line 99, in __init__
    options=options)
  File "/home/milen/nap/env/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 269, in __init__
    self.start_session(capabilities, browser_profile)
  File "/home/milen/nap/env/lib/python3.7/site-packages/undetected_chromedriver/__init__.py", line 590, in start_session
    capabilities, browser_profile
  File "/home/milen/nap/env/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 360, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/milen/nap/env/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 425, in execute
    self.error_handler.check_response(response)
  File "/home/milen/nap/env/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot connect to chrome at 127.0.0.1:32981
from chrome not reachable
Stacktrace:
#0 0x55675d0c4e89 <unknown>
```

**Comment by varna9000** [comment]
Ok, so this is strange. I've been executing the above code via ssh on my remote machine and the errors occur. However, when I logged in through Remote Desktop on that same machine and executed the code from Xterm (in the GUI), I see that Chrome is being started  (window appears) and I can execute driver.get(url) without problem.

Is your library not meant to be run with headless browser?

**Comment by sebdelsol** [comment]
I’m not the author. It’s not meant to be run headless except if you want to be easily detected.
It seems that Chrome is not spawned or crashes before the chromedriver can connect…
