### ISSUE TITLE
cannot import in spyder IDE

### ISSUE THREAD

**Issue by lcendoya** [ultrafunkamsterdam/undetected-chromedriver#583]
Hi. I am having issues to import the library in spyder IDE. I searched everywhere but couldn't find the solution. I am able to run it in Jupyter so I have all the requiered libraries but it is annoying I cannot run it from the IDE. 

This is the error message I get:

import undetected_chromedriver.v2 as uc
Traceback (most recent call last):

  File "<ipython-input-70-f6a44cc49046>", line 1, in <module>
    import undetected_chromedriver.v2 as uc

  File "C:\Users\Administrator\anaconda3\lib\site-packages\undetected_chromedriver\__init__.py", line 61, in <module>
    class Chrome(selenium.webdriver.chrome.webdriver.WebDriver):

AttributeError: module 'selenium' has no attribute 'webdriver'

**Comment by QIN2DIM** [comment]
This is a basic python syntax question. You have defined a `selenium` variable yourself.

```python
import requests

requests = 1 # noqa

requests.get("https://github.com") # noqa
```
