### ISSUE TITLE
Can't load extensions in headless mode

### ISSUE THREAD

**Issue by Avnsx** [ultrafunkamsterdam/undetected-chromedriver#59]
Extension I was trying to add https://chrome.google.com/webstore/detail/domain-blocker/ggdcjplapccgoinblmidpkoocfafajfa which I used https://crx-downloader.com/ to download it.

My code works perfectly fine in headlessmode off, but when I turn it on I can't add / use an extension at all. Noticed this with lots of other extensions too, and I'm wondering why?

**Code:**
```python
def create_session(headless):
	import undetected_chromedriver as uc
	options = uc.ChromeOptions()
	options.headless = headless
	options.add_extension(r"C:\Users\..\Desktop\domain_blocker.crx")
	global driver
	driver = uc.Chrome(options=options)
create_session(True)
```

**Errors in:**
```python
Traceback (most recent call last):
  File "C:\Users\..\Desktop\project.py", line 158, in <module>
    create_session(True)
  File "C:\Users\..\Desktop\project.py", line 45, in create_session
    driver = uc.Chrome(options=options)
  File "C:\Program Files\Python38\lib\site-packages\undetected_chromedriver\__init__.py", line 51, in __new__
    instance.__init__(*args, **kwargs)
  File "C:\Program Files\Python38\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 76, in __init__
    RemoteWebDriver.__init__(
  File "C:\Program Files\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Program Files\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Program Files\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Program Files\Python38\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: failed to wait for extension background page to load: chrome-extension://ggdcjplapccgoinblmidpkoocfafajfa/_generated_background_page.html
from unknown error: page could not be found: chrome-extension://ggdcjplapccgoinblmidpkoocfafajfa/_generated_background_page.html```

**Comment by ultrafunkamsterdam** [comment]
Because afaik that is unsupported . And even if it was, I don't support them. I'm sorry
