### ISSUE TITLE
weird error?

### ISSUE THREAD

**Issue by git-avinash** [ultrafunkamsterdam/undetected-chromedriver#616]
`Process Process-1:
Traceback (most recent call last):
  File "C:\Users\USER\AppData\Local\Programs\Python\Python39-32\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "C:\Users\USER\AppData\Local\Programs\Python\Python39-32\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\USER\.virtualenvs\ad-clicker-idaRXG-1\lib\site-packages\undetected_chromedriver\dprocess.py", line 59, in _start_detached
    p = Popen([executable, *args], stdin=PIPE, stdout=PIPE, stderr=PIPE, **kwargs)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python39-32\lib\subprocess.py", line 951, in _init_
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\USER\AppData\Local\Programs\Python\Python39-32\lib\subprocess.py", line 1360, in _execute_child
    args = list2cmdline(args)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python39-32\lib\subprocess.py", line 565, in list2cmdline
    for arg in map(os.fsdecode, seq):
  File "C:\Users\USER\AppData\Local\Programs\Python\Python39-32\lib\os.py", line 822, in fsdecode
    filename = fspath(filename)  # Does type-checking of `filename`.
TypeError: expected str, bytes or os.PathLike object, not NoneType
[08:44][ERR]Traceback (most recent call last):
  File "c:\- linkedin\ad-clicker\run.py", line 175, in main
    driver = get_driver(proxy)
  File "c:\- linkedin\ad-clicker\src\browser\get_driver.py", line 120, in get_driver
    driver = webdriver.Chrome(options=options)
  File "C:\Users\USER\.virtualenvs\ad-clicker-idaRXG-1\lib\site-packages\undetected_chromedriver\_init.py", line 388, in __init_
    self.browser_pid = start_detached(
  File "C:\Users\USER\.virtualenvs\ad-clicker-idaRXG-1\lib\site-packages\undetected_chromedriver\dprocess.py", line 37, in start_detached
    pid = reader.recv()
  File "C:\Users\USER\AppData\Local\Programs\Python\Python39-32\lib\multiprocessing\connection.py", line 255, in recv
    buf = self._recv_bytes()
  File "C:\Users\USER\AppData\Local\Programs\Python\Python39-32\lib\multiprocessing\connection.py", line 310, in _recv_bytes
    waitres = _winapi.WaitForMultipleObjects(
KeyboardInterrupt`

**Comment by sebdelsol** [comment]
Your error message is barely readable, please format it.
```python
File "C:\Users\USER\AppData\Local\Programs\Python\Python39-32\lib\os.py", line 822, 
in fsdecode filename = fspath(filename) # Does type-checking of filename. 
TypeError: expected str, bytes or os.PathLike object, not NoneType
```
It means your Chrome executable hasn't been found, `find_chrome_executable()` returns `None`
```python
import undetected_chromedriver as uc
print(uc.find_chrome_executable())  # print nothing
```
So your Chrome is probably not installed in its standard path. Please use `browser_executable_path` argument to specify your browser executable path (check the docstring [here](https://github.com/ultrafunkamsterdam/undetected-chromedriver/blob/b2e804e977c9cf3dd9c845474752cac142a72508/undetected_chromedriver/__init__.py#L144))

**Comment by git-avinash** [comment]
I am reinstalling with default settings, still it fails to find

**Comment by sebdelsol** [comment]
* what does `uc.find_chrome_executable()` return ?
* what's the actual path of your Chrome executable on your system ?

**Comment by git-avinash** [comment]
It returns -> None

**Comment by sebdelsol** [comment]
What's the actual path of your Chrome executable on your system ?

**Comment by Tunay221** [comment]
Pls answer that

**Comment by git-avilabs** [comment]
Hi, we can consider this close, I'm no longer using the project as it never worked for me

**Comment by Tunay221** [comment]
Are you using the app on the server?

**Comment by git-avilabs** [comment]
if the server is headless then you would need to use xvfb along with selenium

**Comment by Tunay221** [comment]
xfvb nedir ?

**Comment by git-avilabs** [comment]
we can talk on discord: 
https://discord.gg/jv6K8rrX
