### ISSUE TITLE
I keep getting this error when i run this code

### ISSUE THREAD

**Issue by vitalisc** [ultrafunkamsterdam/undetected-chromedriver#628]
The code i run is this below 

import undetected_chromedriver as uc
driver = uc.Chrome()
driver.get('https://nowsecure.nl')

the above code used to run very well but this time it shows the error below
please i need some help

The error i get is below 

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "multiprocessing\spawn.py", line 116, in spawn_main
  File "multiprocessing\spawn.py", line 125, in _main
  File "multiprocessing\spawn.py", line 236, in prepare
  File "multiprocessing\spawn.py", line 287, in _fixup_main_from_path
  File "runpy.py", line 265, in run_path
  File "runpy.py", line 97, in _run_module_code
  File "runpy.py", line 87, in _run_code
  File "c:\users\vitalis\desktop\deezer pyqt\undetectable\undetectable.py", line 9, in <module>
    driver = uc.Chrome()
  File "C:\Users\vitalis\AppData\Local\Programs\Python\Python310\Lib\site-packages\undetected_chromedriver\__init__.py", line 388, in __init__
    self.browser_pid = start_detached(
  File "C:\Users\vitalis\AppData\Local\Programs\Python\Python310\Lib\site-packages\undetected_chromedriver\dprocess.py", line 30, in start_detached
    multiprocessing.Process(
  File "multiprocessing\process.py", line 121, in start
  File "multiprocessing\context.py", line 224, in _Popen
  File "multiprocessing\context.py", line 327, in _Popen
  File "multiprocessing\popen_spawn_win32.py", line 45, in __init__
  File "multiprocessing\spawn.py", line 154, in get_preparation_data
  File "multiprocessing\spawn.py", line 134, in _check_not_importing_main
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.

**Comment by sebdelsol** [comment]
This a duplicate of a duplicate of a duplicate... _ad infinitum_. 
Please check some of those :  #621 #570 #561 #519 #384.

BTW you already opened the same issue : #585
**_None of those "issues" are actual bugs._**
* Please check this well known [**Python idiom**](https://docs.python.org/3/library/multiprocessing.html#the-spawn-and-forkserver-start-methods).
* Please check [**this answer**](https://github.com/ultrafunkamsterdam/undetected-chromedriver/issues/621#issuecomment-1118610275) to understand what you're doing wrong.
* Please check [**this other answer**](https://github.com/ultrafunkamsterdam/undetected-chromedriver/issues/561#issuecomment-1075363395) and try by yourself why you need to wrap your code with an if-clause to protect it from executing multiple times (and probably be stuck in an infinite loop otherwise).
