### ISSUE TITLE
ModuleNotFoundError when working in debugging mode

### ISSUE THREAD

**Issue by lhaifenglhf** [ultrafunkamsterdam/undetected-chromedriver#633]
Hi, 

My script works well when being executed in command line but error happens when it is debugged (Eclipse Pydev) and importing undected_chromedriver.  The error looks like:

Traceback (most recent call last):
  File "C:\C2SEC\Bitbucket\dp\darkpost_crawler\darkpost_crawler\breachforums\seleniumBreached.py", line 19, in <module>
    import undetected_chromedriver as uc
  File "C:\Users\lhaif\AppData\Roaming\Python\Python37\site-packages\undetected_chromedriver\__init__.py", line 42, in <module>
    from .options import ChromeOptions
  File "C:\Users\lhaif\AppData\Roaming\Python\Python37\site-packages\undetected_chromedriver\options.py", line 8, in <module>
    from selenium.webdriver.chromium.options import ChromiumOptions as _ChromiumOptions
ModuleNotFoundError: No module named 'selenium.webdriver.chromium'

Any clues for resolving this?

**Comment by sebdelsol** [comment]
Undetected-chromedriver inherits a lot of stuff from Selenium.
If I remember correctly you have to [add all your external libraries to the Eclipse Pydev project](https://www.ibm.com/docs/en/qradar-common?topic=2-developing-apps-in-eclipse). 
Anyway it's very tedious, I'd rather use a modern Python IDE...
