### ISSUE TITLE
Runtime Error w/ Suggested Usage,Chrome doesn't work, it pops up a blank window and crashes immediately

### ISSUE THREAD

**Issue by makeukus** [ultrafunkamsterdam/undetected-chromedriver#635]
The code i run is this below:

import undetected_chromedriver.v2 as uc

if __name__ == '__main__':
    driver = uc.Chrome()
    driver.get("https://www.google.com/")

the above code used to run very well but this time it shows the error below
please i need some help
The error i get is below

Traceback (most recent call last):
  File "C:\Users\Administrator\PycharmProjects\youtube\main.py", line 5, in <module>
    driver = uc.Chrome()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\undetected_chromedriver\v2.py", line 309, in __init__
    super(Chrome, self).__init__(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 70, in __init__
    super(WebDriver, self).__init__(DesiredCapabilities.CHROME['browserName'], "goog",
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\chromium\webdriver.py", line 92, in __init__
    RemoteWebDriver.__init__(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 275, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\undetected_chromedriver\v2.py", line 600, in start_session
    super(Chrome, self).start_session(capabilities, browser_profile)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 365, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 430, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot connect to chrome at 127.0.0.1:64606
from chrome not reachable
Stacktrace:
Backtrace:
	Ordinal0 [0x006BB8F3+2406643]
	Ordinal0 [0x0064AF31+1945393]
	Ordinal0 [0x0053C610+837136]
	Ordinal0 [0x0053036B+787307]
	Ordinal0 [0x0055C268+967272]
	Ordinal0 [0x00555EBB+941755]
	Ordinal0 [0x00555C86+941190]
	Ordinal0 [0x00588EE0+1150688]
	Ordinal0 [0x00588B3A+1149754]
	Ordinal0 [0x00584096+1130646]
	Ordinal0 [0x0055E636+976438]
	Ordinal0 [0x0055F546+980294]
	GetHandleVerifier [0x00929612+2498066]
	GetHandleVerifier [0x0091C920+2445600]
	GetHandleVerifier [0x00754F2A+579370]
	GetHandleVerifier [0x00753D36+574774]
	Ordinal0 [0x00651C0B+1973259]
	Ordinal0 [0x00656688+1992328]
	Ordinal0 [0x00656775+1992565]
	Ordinal0 [0x0065F8D1+2029777]
	BaseThreadInitThunk [0x756CFA29+25]
	RtlGetAppContainerNamedObjectPath [0x77487A7E+286]
	RtlGetAppContainerNamedObjectPath [0x77487A4E+238]

Process finished with exit code 1

**Comment by makeukus** [comment]
Chrome crashed, First，python 310 with undetected_chromedriver3.06 version, seems to work fine. But when the web page is finished opening, after a certain amount of time, maybe 5 seconds. Chrome will automatically exit. So, I tried to upgrade the version of undetected_chromedriver to a higher version, but found that chrome did not work, and I restored the version of the undetected_chromedriver to 3.06, but to no avail, Chrome still crashed. The code editor I use is pycharm, I need your help, thank you very much
