### ISSUE TITLE
headed via pyvirtualdisplay/xvfb in docker?

### ISSUE THREAD

**Issue by DGaffney** [ultrafunkamsterdam/undetected-chromedriver#636]
Hello!

Tremendously in love with all the work happening here. Excellent to see, and so so grateful for everyone's contributions. I'm on 3.1.3, in a Docker env. I know headless doesn't work right now, but does a virtual mount work? I see a couple issues that sort of obliquely get at this, but here's the approach I was using:

```
>>> import undetected_chromedriver as uc
>>> from pyvirtualdisplay import Display
>>> display = Display(visible=0, size=(1680, 860))
>>> display.start()
<pyvirtualdisplay.display.Display object at 0x7f30596b7fd0>
>>> driver = uc.Chrome(headless=False)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/dist-packages/undetected_chromedriver/__init__.py", line 400, in __init__
    super(Chrome, self).__init__(
  File "/usr/local/lib/python3.9/dist-packages/selenium/webdriver/chrome/webdriver.py", line 70, in __init__
    super(WebDriver, self).__init__(DesiredCapabilities.CHROME['browserName'], "goog",
  File "/usr/local/lib/python3.9/dist-packages/selenium/webdriver/chromium/webdriver.py", line 93, in __init__
    RemoteWebDriver.__init__(
  File "/usr/local/lib/python3.9/dist-packages/selenium/webdriver/remote/webdriver.py", line 269, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python3.9/dist-packages/undetected_chromedriver/__init__.py", line 680, in start_session
    super(selenium.webdriver.chrome.webdriver.WebDriver, self).start_session(
  File "/usr/local/lib/python3.9/dist-packages/selenium/webdriver/remote/webdriver.py", line 360, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.9/dist-packages/selenium/webdriver/remote/webdriver.py", line 425, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.9/dist-packages/selenium/webdriver/remote/errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot connect to chrome at 127.0.0.1:33695
from chrome not reachable
Stacktrace:
#0 0x555fa6521533 <unknown>
#1 0x555fa628007f <unknown>
#2 0x555fa626e319 <unknown>
#3 0x555fa62a6989 <unknown>
#4 0x555fa629e8f6 <unknown>
#5 0x555fa62d9d0a <unknown>
#6 0x555fa62d3e33 <unknown>
#7 0x555fa62a971a <unknown>
#8 0x555fa62aa875 <unknown>
#9 0x555fa6565e1d <unknown>
#10 0x555fa6569751 <unknown>
#11 0x555fa655007e <unknown>
#12 0x555fa656a388 <unknown>
#13 0x555fa6544fe0 <unknown>
#14 0x555fa6586748 <unknown>
#15 0x555fa65868c8 <unknown>
#16 0x555fa65a070d <unknown>
#17 0x7f02cbd2dea7 <unknown>
```

Is there something else that I'm missing? Has anyone gotten a reproducible headed instance running in a virtual display?

**Comment by DGaffney** [comment]
An update to this ticket:

It doesn't really have anything to do with Docker per se - here's a series of install scripts and the associated python code required to replicate this issue on any Ubuntu 20.04 LTS server - am I just doing something wrong here?

```
apt-get update && apt-get install -y \
    python3 python3-pip \
    fonts-liberation libasound2 libatk-bridge2.0-0 \
    libnspr4 libnss3 lsb-release xdg-utils libxss1 libdbus-glib-1-2 libcups2 \
    libgtk-3-dev unzip \
    curl unzip wget dumb-init nano libgbm1 libre2-dev \
    xvfb \
    expect openvpn openvpn-systemd-resolved

pip3 install pyvirtualdisplay undetected-chromedriver

CHROMEDRIVER_VERSION=`curl -sS chromedriver.storage.googleapis.com/LATEST_RELEASE` && \
    wget https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip && \
    unzip chromedriver_linux64.zip -d /usr/bin && \
    chmod +x /usr/bin/chromedriver && \
    rm chromedriver_linux64.zip

CHROME_SETUP=google-chrome.deb && \
    wget -O $CHROME_SETUP "https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb" && \
    dpkg -i $CHROME_SETUP && \
    apt-get install -y -f && \
    rm $CHROME_SETUP
```

```
python3
import undetected_chromedriver as uc
from pyvirtualdisplay import Display
display = Display(visible=0, size=(1680, 860))
display.start()
driver = uc.Chrome(headless=True, version_main=102) #works
driver = uc.Chrome(headless=False, version_main=102) #doesn't work
```

And the error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/undetected_chromedriver/__init__.py", line 401, in __init__
    super(Chrome, self).__init__(
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/chrome/webdriver.py", line 70, in __init__
    super(WebDriver, self).__init__(DesiredCapabilities.CHROME['browserName'], "goog",
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/chromium/webdriver.py", line 92, in __init__
    RemoteWebDriver.__init__(
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/webdriver.py", line 275, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python3.8/dist-packages/undetected_chromedriver/__init__.py", line 589, in start_session
    super(selenium.webdriver.chrome.webdriver.WebDriver, self).start_session(
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/webdriver.py", line 365, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/webdriver.py", line 430, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot connect to chrome at 127.0.0.1:50615
from chrome not reachable
Stacktrace:
#0 0x559947579f33 <unknown>
#1 0x5599472c3faf <unknown>
#2 0x5599472b2209 <unknown>
#3 0x5599472eaa79 <unknown>
#4 0x5599472e2a06 <unknown>
#5 0x55994731dd3a <unknown>
#6 0x559947317e63 <unknown>
#7 0x5599472ed82a <unknown>
#8 0x5599472ee985 <unknown>
#9 0x5599475be4cd <unknown>
#10 0x5599475c25ec <unknown>
#11 0x5599475a871e <unknown>
#12 0x5599475c3238 <unknown>
#13 0x55994759d870 <unknown>
#14 0x5599475df608 <unknown>
#15 0x5599475df788 <unknown>
#16 0x5599475f9f1d <unknown>
#17 0x7f7d6d565609 <unknown>
```

**Comment by zunoffon** [comment]
```python
options.add_argument("--no-sandbox")
```
It's not recommended but adding this option could resolve your issue.

**Comment by DGaffney** [comment]
> ```python
> options.add_argument("--no-sandbox")
> ```
> 
> It's not recommended but adding this option could resolve your issue.

Works great! Thanks much, figured it was something basic. Closing as solved.

**Comment by teisseire117** [comment]
> ```python
> options.add_argument("--no-sandbox")
> ```
> 
> It's not recommended but adding this option could resolve your issue.

LOVE YOU, IT FIXED MY ISSUE TOO. I THOUGHT I WOULDN'T FIND.

**Comment by zax2002** [comment]
> ```python
> options.add_argument("--no-sandbox")
> ```
> 
> It's not recommended but adding this option could resolve your issue.

Thank you a lot ♥
