### ISSUE TITLE
fetch_release_number is failing

### ISSUE THREAD

**Issue by piusyikyu** [ultrafunkamsterdam/undetected-chromedriver#658]
Traceback (most recent call last):
  File "D:\Desktop\UC\main.py", line 5, in <module>
    driver = uc.Chrome()
  File "D:\ProgramData\.conda\envs\UC\lib\site-packages\undetected_chromedriver\__init__.py", line 233, in __init__
    patcher.auto()
  File "D:\ProgramData\.conda\envs\UC\lib\site-packages\undetected_chromedriver\patcher.py", line 127, in auto
    release = self.fetch_release_number()
  File "D:\ProgramData\.conda\envs\UC\lib\site-packages\undetected_chromedriver\patcher.py", line 148, in fetch_release_number
    return LooseVersion(urlopen(self.url_repo + path).read().decode()) <<<-------------------- [This line in patcher]
  File "D:\ProgramData\.conda\envs\UC\lib\urllib\request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "D:\ProgramData\.conda\envs\UC\lib\urllib\request.py", line 517, in open
    response = self._open(req, data)
  File "D:\ProgramData\.conda\envs\UC\lib\urllib\request.py", line 539, in _open
    return self._call_chain(self.handle_open, 'unknown',
  File "D:\ProgramData\.conda\envs\UC\lib\urllib\request.py", line 494, in _call_chain
    result = func(*args)
  File "D:\ProgramData\.conda\envs\UC\lib\urllib\request.py", line 1417, in unknown_open
    raise URLError('unknown url type: %s' % type)
urllib.error.URLError: <urlopen error unknown url type: https>

Process finished with exit code 1

**Comment by sebdelsol** [comment]
If that reproduces the same error: 
```python3
from urllib.request import urlopen, urlretrieve

url_repo = "https://chromedriver.storage.googleapis.com"
path = "/latest_release".upper()
print(urlopen(url_repo + path).read().decode())
```
Then you should reinstall undetected-chromedriver to have its dependencies reinstalled :
`pip install --upgrade --force-reinstall undetected-chromedriver`

**Comment by piusyikyu** [comment]
Tried that. It is giving the same error about urlopen.
`urllib.error.urlerror: <urlopen error unknown url type: https>`

should I just reinstall package?

**Comment by sebdelsol** [comment]
It's more like your Python installation is broken : Please [**check this**](https://stackoverflow.com/questions/28376506/urllib-https-request-urlopen-error-unknown-url-type-https).

**Comment by piusyikyu** [comment]
Sure. Thanks for your time :)
