### ISSUE TITLE
UC crashed immediately when using get

### ISSUE THREAD

**Issue by henzycuong1** [ultrafunkamsterdam/undetected-chromedriver#695]
this is traceback
```
Traceback (most recent call last):

  File "d:\selenium.py", line 45, in do_task
    driver.get(url)
  File "C:\Users\Four\AppData\Local\Programs\Python\Python39\lib\site-packages\undetected_chromedriver\__init__.py", line 533, in get
    if self._get_cdc_props():
  File "C:\Users\Four\AppData\Local\Programs\Python\Python39\lib\site-packages\undetected_chromedriver\__init__.py", line 505, in _get_cdc_props
    return self.execute_script(
  File "C:\Users\Four\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 884, in execute_script
    return self.execute(command, {
  File "C:\Users\Four\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 430, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Four\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: chrome not reachable
  (Session info: chrome=103.0.5060.53)
Stacktrace:
Backtrace:
        Ordinal0 [0x003D6463+2188387]
        Ordinal0 [0x0036E461+1762401]
        Ordinal0 [0x00283C40+801856]
        Ordinal0 [0x00278932+756018]
        Ordinal0 [0x00279168+758120]
        Ordinal0 [0x0027AA22+764450]
        Ordinal0 [0x00274379+738169]
        Ordinal0 [0x002850D0+807120]
        Ordinal0 [0x002DC402+1164290]
        Ordinal0 [0x002CC5F6+1099254]
        Ordinal0 [0x002A6BE0+945120]
        Ordinal0 [0x002A7AD6+948950]
        GetHandleVerifier [0x006771F2+2712546]
        GetHandleVerifier [0x0066886D+2652765]
        GetHandleVerifier [0x0046002A+520730]
        GetHandleVerifier [0x0045EE06+516086]
        Ordinal0 [0x0037468B+1787531]
        Ordinal0 [0x00378E88+1805960]
        Ordinal0 [0x00378F75+1806197]
        Ordinal0 [0x00381DF1+1842673]
        BaseThreadInitThunk [0x7637FA29+25]
        RtlGetAppContainerNamedObjectPath [0x77677A9E+286]
        RtlGetAppContainerNamedObjectPath [0x77677A6E+238]
```
Can someone tell me what happend ? How can I fix it

**Comment by realdronos** [comment]
Did you update chrome webdriver?
https://chromedriver.storage.googleapis.com/index.html may help, just get right version

**Comment by henzycuong1** [comment]
> Did you update chrome webdriver? https://chromedriver.storage.googleapis.com/index.html may help, just get right version

thank you, I'll try it

**Comment by henzycuong1** [comment]
how about this
```
 File "d:\selenium.py", line 41, in do_task
    driver.get(url)
File "C:\Users\Four\AppData\Local\Programs\Python\Python39\lib\site-packages\undetected_chromedriver\__init__.py", line 538, in get
    return super().get(url)
  File "C:\Users\Four\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 442, in get
    self.execute(Command.GET, {'url': url})
  File "C:\Users\Four\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 430, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Four\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot determine loading status
from unknown error: unexpected command response
  (Session info: chrome=103.0.5060.53)
Stacktrace:
Backtrace:
        Ordinal0 [0x00896463+2188387]
        Ordinal0 [0x0082E461+1762401]
        Ordinal0 [0x00743D78+802168]
        Ordinal0 [0x00737210+750096]
        Ordinal0 [0x0073675A+747354]
        Ordinal0 [0x00735D3F+744767]
        Ordinal0 [0x00734C28+740392]
        Ordinal0 [0x00735228+741928]
        Ordinal0 [0x0073EF2F+782127]
        Ordinal0 [0x00749FBB+827323]
        Ordinal0 [0x0074D310+840464]
        Ordinal0 [0x007354F6+742646]
        Ordinal0 [0x00749BF3+826355]
        Ordinal0 [0x0079CF6D+1167213]
        Ordinal0 [0x0078C5F6+1099254]
        Ordinal0 [0x00766BE0+945120]
        Ordinal0 [0x00767AD6+948950]
        GetHandleVerifier [0x00B371F2+2712546]
        GetHandleVerifier [0x00B2886D+2652765]
        GetHandleVerifier [0x0092002A+520730]
        GetHandleVerifier [0x0091EE06+516086]
        Ordinal0 [0x0083468B+1787531]
        Ordinal0 [0x00838E88+1805960]
        Ordinal0 [0x00838F75+1806197]
        Ordinal0 [0x00841DF1+1842673]
        BaseThreadInitThunk [0x7637FA29+25]
        RtlGetAppContainerNamedObjectPath [0x77677A9E+286]
        RtlGetAppContainerNamedObjectPath [0x77677A6E+238]
```

**Comment by sebdelsol** [comment]
This is a duplicate of #694, it's a Chrome v103 bug, there some temporary workaround though.

**Comment by henzycuong1** [comment]
> @henzycuong1 Please check #694, it's a Chrome v103 bug, there some temporary workaround though.

I got it, thank you so much
