### ISSUE TITLE
stuck in a infinite loop 

### ISSUE THREAD

**Issue by m-jishnu** [ultrafunkamsterdam/undetected-chromedriver#722]
when i run 
```

import undetected_chromedriver as uc
driver = uc.Chrome()
driver.get('https://nowsecure.nl')

```
i get 

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Python\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Python\lib\multiprocessing\spawn.py", line 125, in _main
    prepare(preparation_data)
  File "C:\Python\lib\multiprocessing\spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Python\lib\multiprocessing\spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "C:\Python\lib\runpy.py", line 268, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "C:\Python\lib\runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "C:\Python\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "f:\Code\projects\python_projects\App_Installer\test2.py", line 2, in <module>
    driver = uc.Chrome()
  File "F:\Code\projects\python_projects\App_Installer\venv\lib\site-packages\undetected_chromedriver\__init__.py", line 388, in __init__
    self.browser_pid = start_detached(
  File "F:\Code\projects\python_projects\App_Installer\venv\lib\site-packages\undetected_chromedriver\dprocess.py", line 30, in start_detached
    multiprocessing.Process(
  File "C:\Python\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "C:\Python\lib\multiprocessing\context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Python\lib\multiprocessing\context.py", line 327, in _Popen
    return Popen(process_obj)
  File "C:\Python\lib\multiprocessing\popen_spawn_win32.py", line 45, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "C:\Python\lib\multiprocessing\spawn.py", line 154, in get_preparation_data
    _check_not_importing_main()
  File "C:\Python\lib\multiprocessing\spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
```
the version 3.0.4 works fine but fails to pass the cloudflare test
i am using chrome ver 103

**Comment by xploader** [comment]
I get the same error

**Comment by timbeh** [comment]
Same error here on Windows 10, working perfectly on macOS though

**Comment by Maxanox** [comment]
Comme indiqué dans l'erreur il faut mettre votre code en dessous cette ligne :

```
import undetected_chromedriver as uc


if __name__ == '__main__':
    driver = uc.Chrome()
    driver.get('https://nowsecure.nl')
```

**Comment by m-jishnu** [comment]
> Comme indiqué dans l'erreur il faut mettre votre code en dessous cette ligne :
> 
> ```python
> import undetected_chromedriver as uc
> 
> 
> if __name__ == '__main__':
>     driver = uc.Chrome()
>     driver.get('https://nowsecure.nl')
> ```

doing it under if __name__ == '__main__':  seems to have solved the issue now it works fine
but is there anyway to do it without putting it under the if condition for scenarios where the if condition becomes false like calling it from another file @Maxanox 
btw thanks for the help!

**Comment by Maxanox** [comment]
So put the

if __name__ == '__main__':

At the origin, the first starting file.
