### ISSUE TITLE
cannot connect to chrome in Linux Ubuntu 22.04

### ISSUE THREAD

**Issue by kisoo** [ultrafunkamsterdam/undetected-chromedriver#729]
My Env is
  Ubuntu 22.04 Server Install (Non X Window)
  Google Chrome: 103.0.5060.114 (Latest version)
  Python: 3.10.4

  My Dsektop: windows 10
  X Server: vcxrv 64.1.20.14.0

Case 1. ssh connect with user A (wheel group)
   run my script  with Chrome Browser in GUI (X Window)   -->  works fine 

Case 2. ssh connect with user A (wheel group)
  run my script with headless mode  --> works fine

Case 3. ssh connect with user jenkins (jenkins group)
   run my script  with Chrome Browser in GUI (X Window)   -->  works fine 

_**Problem
Case 4. ssh connect with user jenkins (jenkins group)
  run my script with headless mode  --> connect error message**_

--- Error Message is
 Traceback (most recent call last):
  File "/opt/websystemcheck/dbinc-portal.py", line 574, in <module>
    driver = init_driver()
  File "/opt/websystemcheck/dbinc-portal.py", line 28, in init_driver
    driver = uc.Chrome(options=options)
  File "/usr/local/lib/python3.10/dist-packages/undetected_chromedriver/__init__.py", line 401, in __init__
    super(Chrome, self).__init__(
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/chrome/webdriver.py", line 69, in __init__
    super().__init__(DesiredCapabilities.CHROME['browserName'], "goog",
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/chromium/webdriver.py", line 92, in __init__
    super().__init__(
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/webdriver.py", line 277, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python3.10/dist-packages/undetected_chromedriver/__init__.py", line 589, in start_session
    super(selenium.webdriver.chrome.webdriver.WebDriver, self).start_session(
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/webdriver.py", line 370, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/webdriver.py", line 435, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot connect to chrome at 127.0.0.1:52731
from chrome not reachable
Stacktrace:
#0 0x560409d18b13 <unknown>
#1 0x560409b1f51f <unknown>
#2 0x560409b0eb59 <unknown>
#3 0x560409b4739f <unknown>
#4 0x560409b3f256 <unknown>
#5 0x560409b7a64a <unknown>
#6 0x560409b747a3 <unknown>
#7 0x560409b4a0ea <unknown>
#8 0x560409b4b225 <unknown>
#9 0x560409d602dd <unknown>
#10 0x560409d642c7 <unknown>
#11 0x560409d4a22e <unknown>
#12 0x560409d650a8 <unknown>
#13 0x560409d3ebc0 <unknown>
#14 0x560409d816c8 <unknown>
#15 0x560409d81848 <unknown>
#16 0x560409d9bc0d <unknown>
#17 0x7fb2b7aa4b43 <unknown>

**Comment by kisoo** [comment]
Case 5. ssh connect with user jenkins (add to wheel group)
run my script with headless mode --> works fine

**Comment by bibs2091** [comment]
I downgraded my chrome browser to match my webdriver and it solved the problem!
