### ISSUE TITLE
AttributeError: 'str' object has no attribute '_session'

### ISSUE THREAD

**Issue by Bits4Bux** [ultrafunkamsterdam/undetected-chromedriver#733]
Hello, I got this error:

Traceback (most recent call last):
  File "C:\Users\JustAnotherUser\Downloads\Bot\main\SoundCloud.py", line 16, in <module>
    driver = webdriver.Chrome("C:\\Users\\JustAnotherUser\\Downloads\\Bot\\main\\chromedriver.exe")
  File "C:\Users\JustAnotherUser\Downloads\Bot\main\undetected_chromedriver\__init__.py", line 248, in __init__
    options._session = self
AttributeError: 'str' object has no attribute '_session'

Process finished with exit code 1

Can anyone help?

**Comment by draftmanpenny** [comment]
have you tried `if __name__ == __main__: `

**Comment by jamesr657** [comment]
Having issues with this as well, "have you tried if __name__ == __main__:" Did not work for me. Please let me know if you figure out a fix :)

**Comment by Monir-Nassan** [comment]
I had the same error and i fixed it with by initializing the options 
options = webdriver.ChromeOptions()
driver = webdriver.Chrome(options=options)
