### ISSUE TITLE
Error when install ver 3.1.2++

### ISSUE THREAD

**Issue by ngolun669** [ultrafunkamsterdam/undetected-chromedriver#734]
```
Collecting undetected-chromedriver
  Using cached undetected-chromedriver-3.1.5.post4.tar.gz (55 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [29 lines of output]
      running egg_info
      creating C:\Users\Kang\AppData\Local\Temp\pip-pip-egg-info-t44ocgm4\undetected_chromedriver.egg-info
      writing C:\Users\Kang\AppData\Local\Temp\pip-pip-egg-info-t44ocgm4\undetected_chromedriver.egg-info\PKG-INFO
      c:\users\kang\appdata\local\programs\python\python37\lib\distutils\dist.py:274: UserWarning: Unknown distribution option: 'long_description_content_type'
        warnings.warn(msg)
      c:\users\kang\appdata\local\programs\python\python37\lib\site-packages\setuptools\dist.py:397: UserWarning: Normalizing '3.1.5r4' to '3.1.5.post4'
        normalized_version,
      Traceback (most recent call last):
        File "<string>", line 36, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\Kang\AppData\Local\Temp\pip-install-bd_gl6id\undetected-chromedriver_c8a9b8040c4e459ba666f5a84a6c1895\setup.py", line 61, in <module>
          "Programming Language :: Python :: 3.11",
        File "c:\users\kang\appdata\local\programs\python\python37\lib\site-packages\setuptools\__init__.py", line 129, in setup
          return distutils.core.setup(**attrs)
        File "c:\users\kang\appdata\local\programs\python\python37\lib\distutils\core.py", line 148, in setup
          dist.run_commands()
        File "c:\users\kang\appdata\local\programs\python\python37\lib\distutils\dist.py", line 966, in run_commands
          self.run_command(cmd)
        File "c:\users\kang\appdata\local\programs\python\python37\lib\distutils\dist.py", line 985, in run_command
          cmd_obj.run()
        File "c:\users\kang\appdata\local\programs\python\python37\lib\site-packages\setuptools\command\egg_info.py", line 271, in run
          writer(self, ep.name, os.path.join(self.egg_info, ep.name))
        File "c:\users\kang\appdata\local\programs\python\python37\lib\site-packages\setuptools\command\egg_info.py", line 604, in write_pkg_info
          metadata.write_pkg_info(cmd.egg_info)
        File "c:\users\kang\appdata\local\programs\python\python37\lib\distutils\dist.py", line 1117, in write_pkg_info
          self.write_pkg_file(pkg_info)
        File "c:\users\kang\appdata\local\programs\python\python37\lib\site-packages\setuptools\dist.py", line 63, in write_pkg_file
          file.write('Summary: %s\n' % self.get_description())
      TypeError: not all arguments converted during string formatting
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```
i got some error when install version 3.1.2++, someone help me. Thanks!

**Comment by ezklap** [comment]
Had the same issue, Update setuptools and pip see if it helps

python -m pip install --upgrade setuptools
pip install --upgrade pip

**Comment by ngolun669** [comment]
> Had the same issue, Update setuptools and pip see if it helps
> 
> python -m pip install --upgrade setuptools pip install --upgrade pip

thank u, it's work

**Comment by Chris-Lea** [comment]
> Had the same issue, Update setuptools and pip see if it helps
> 
> python -m pip install --upgrade setuptools pip install --upgrade pip

thanks, it works for me as well
