### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by bubublik** [ultrafunkamsterdam/undetected-chromedriver#738]
Mac OS, Python 3.10

Tryed:

```
import undetected_chromedriver as uc

driver = uc.Chrome(browser_executable_path="/opt/homebrew/bin/chromium")
driver.get("https://nowsecure.nl")
```
&

```
import undetected_chromedriver as uc

driver = uc.Chrome(")
driver.get("https://nowsecure.nl")
```

&

```
import undetected_chromedriver as uc

driver = uc.Chrome(browser_executable_path="/opt/homebrew/bin/chromium", driver_executable_path="/Users/bubublik/dev/project_dit/chromedriver",)
driver.get("https://nowsecure.nl")
```

I get an error all the time:
```

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 288, in run_path
    code, fname = _get_code_from_file(run_name, path_name)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 252, in _get_code_from_file
    with io.open_code(decoded_path) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/bubublik/dev/project_dir/<input>'
```

Please advise what the problem could be.

**Comment by bubublik** [comment]
Chrome: Version 103.0.5060.134 (Official Build)
ChromeDriver 103.0.5060.134 (8ec6fce403b3feb0869b0732eda8bd95011d333c-refs/branch-heads/5060@{#1262})
