### ISSUE TITLE
Chrome Driver initialization Error - Multiprocessing Error returned when ran from Docker

### ISSUE THREAD

**Issue by Sagaryal** [ultrafunkamsterdam/undetected-chromedriver#740]
The below code works fine when running locally using virtualenv. But when I dockerized it, an error is received. As I debugged it seems the error is from `driver = uc.Chrome(headless=True)`

Python Versions tried: 3.10, 3.8

```python
import json
from fastapi import FastAPI
import undetected_chromedriver.v2 as uc
from selenium.webdriver.common.by import By
from utils import Item

app = FastAPI()
driver = uc.Chrome(headless=True)

@app.post("/")
def root(item: Item):
    # known url using cloudflare's "under attack mode"
    driver.get(item.url)
    html = driver.find_element(By.TAG_NAME, 'html').text
    return json.loads(html)
```

Error:
```
Process Process-1:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.10/site-packages/undetected_chromedriver/dprocess.py", line 59, in _start_detached
    p = Popen([executable, *args], stdin=PIPE, stdout=PIPE, stderr=PIPE, **kwargs)
  File "/usr/local/lib/python3.10/subprocess.py", line 969, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/lib/python3.10/subprocess.py", line 1720, in _execute_child
    and os.path.dirname(executable)
  File "/usr/local/lib/python3.10/posixpath.py", line 152, in dirname
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

Dockerfile
```Dockerfile
FROM python:3.10

ENV PYTHONUNBUFFERED True

WORKDIR /app

COPY requirements.txt ./

RUN pip install -r requirements.txt

EXPOSE 8000

COPY . ./

CMD exec uvicorn main:app --host 0.0.0.0 --port 8000
```

**Comment by ultrafunkamsterdam** [comment]
you are trying to load plain html to json.

**Comment by Sagaryal** [comment]
> you are trying to load plain html to json.

@ultrafunkamsterdam  Sir please do once check the above Edited code again. It's not because of `plain html to json.` As you can see even plain return response is not working.

Furthermore, the `root()` function executes only when API is called. But Chrome initialization is done before and code is not even running.

As you can see error logs. `Before Chrome Initiasation ------>` is being printed but not `After Chrome Initiasation ------>` which means that Chrome is not being initialized.

Nevertheless, I have tried and edited the code and error response above for your doubt.

**Comment by pepi99** [comment]
Did you solve it ?
