### ISSUE TITLE
Error on process when browser is not installed in a system.

### ISSUE THREAD

**Issue by Kinuseka** [ultrafunkamsterdam/undetected-chromedriver#747]
This error occurs at another process thread when a browser is not found, causing the program to be stuck indefinetly without knowing it had crashed.

The error should be invoked in the main thread or reraised at the main thread for easier error handling;

```
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/fgg/.local/lib/python3.10/site-packages/undetected_chromedriver/dprocess.py", line 59, in _start_detached
    p = Popen([executable, *args], stdin=PIPE, stdout=PIPE, stderr=PIPE, **kwargs)
  File "/usr/lib/python3.10/subprocess.py", line 966, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1717, in _execute_child
    and os.path.dirname(executable)
  File "/usr/lib/python3.10/posixpath.py", line 152, in dirname
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

**Comment by nikunjdhamelia** [comment]
same issue, any solution?

**Comment by pscj** [comment]
same issue too
