### ISSUE TITLE
Unable to run after a few days

### ISSUE THREAD

**Issue by sengseng84** [ultrafunkamsterdam/undetected-chromedriver#756]
It was working fine. until today i got this error... Very strange... have no idea what broke it...

python3 testing.py
Traceback (most recent call last):
  File "app/testing.py", line 62, in <module>
    main()
  File "app/testing.py", line 21, in main
    driver = uc.Chrome()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/undetected_chromedriver/v2.py", line 169, in __init__
    patcher.auto()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/undetected_chromedriver/patcher.py", line 121, in auto
    self.unzip_package(self.fetch_package())
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/undetected_chromedriver/patcher.py", line 158, in fetch_package
    return urlretrieve(u)[0]
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 239, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 523, in open
    response = meth(req, response)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 632, in http_response
    response = self.parent.error(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 561, in error
    return self._call_chain(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden
Exception ignored in: <function Chrome.__del__ at 0x7fcbad9eab80>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/undetected_chromedriver/v2.py", line 647, in __del__
    self.quit()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/undetected_chromedriver/v2.py", line 604, in quit
    self.service.process.kill()
AttributeError: 'Chrome' object has no attribute 'service'

**Comment by sengseng84** [comment]
Nevermind. I found the issue. Gonna write the import statement within the main function.
