### ISSUE TITLE
SyntaxError: future feature annotations is not defined

### ISSUE THREAD

**Issue by damp11113** [ultrafunkamsterdam/undetected-chromedriver#761]
```
Traceback (most recent call last):
  File "C:/Users/Lenovo/PycharmProjects/pythonProject/test122.py", line 1, in <module>
    import undetected_chromedriver.v2 as uc
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python36\lib\site-packages\undetected_chromedriver\__init__.py", line 31, in <module>
    from . import v2
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python36\lib\site-packages\undetected_chromedriver\v2.py", line 4
    from __future__ import annotations
    ^
SyntaxError: future feature annotations is not defined
```

**Comment by sebdelsol** [comment]
you use a old version of this package, please upgrade it.
