### ISSUE TITLE
unknown error: cannot connect to chrome at 127.0.0.1:55059

### ISSUE THREAD

**Issue by teisseire117** [ultrafunkamsterdam/undetected-chromedriver#774]
Hello,

I made a program, it works my on window laptop, then I tried launching it on my Debian 10 (Buster) VPS, but it returns an error 
google-chrome version : `Google Chrome 104.0.5112.79`
chromedriver version : `ChromeDriver 104.0.5112.79 (3cf3e8c8a07d104b9e1260c910efb8f383285dc5-refs/branch-heads/5112@{#1307})`

: 
```
Traceback (most recent call last):
  File "nhentai_archiver.py", line 1, in <module>
    from utils import rate_limit_handler, try_resume, save_state, store_message, add_user
  File "/root/nhentai_archiver/utils.py", line 12, in <module>
    driver = uc.Chrome(use_subprocess=True)
  File "/usr/local/lib/python3.7/dist-packages/undetected_chromedriver/__init__.py", line 408, in __init__
    keep_alive=keep_alive,
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/chrome/webdriver.py", line 72, in __init__
    service_log_path, service, keep_alive)
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/chromium/webdriver.py", line 97, in __init__
    options=options)
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 276, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python3.7/dist-packages/undetected_chromedriver/__init__.py", line 590, in start_session
    capabilities, browser_profile
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 369, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 434, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 243, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot connect to chrome at 127.0.0.1:55059
from chrome not reachable
Stacktrace:
#0 0x5559849f4403 <unknown>
#1 0x5559847fa64b <unknown>
#2 0x5559847eac49 <unknown>
#3 0x5559848223b6 <unknown>
#4 0x555984819ddf <unknown>
#5 0x55598485583a <unknown>
#6 0x55598484f8f3 <unknown>
#7 0x5559848250d8 <unknown>
#8 0x555984826205 <unknown>
#9 0x555984a3be3d <unknown>
#10 0x555984a3edb6 <unknown>
#11 0x555984a2513e <unknown>
#12 0x555984a3f9b5 <unknown>
#13 0x555984a19970 <unknown>
#14 0x555984a5c228 <unknown>
#15 0x555984a5c3bf <unknown>
#16 0x555984a76abe <unknown>
#17 0x7f7cf61abfa3 <unknown>
```

I've searched on google solutions for this error message, however I don't know, either I don't understand them or they don't fit for Debian.

Could you provide me a list of commands I need to run, with a brief explanation of why/what ?

Thank you for your time

**Comment by teisseire117** [comment]
Fixed the issue.

I did two things, and I'm not entirely sure which one actually made it work, so I'll put both just in case : 

I did that first : https://stackoverflow.com/a/10399597

Then I added that to my program(before it was just `driver = uc.Chrome(use_subprocess=True)`): 
```
from selenium.webdriver.chrome.options import Options

chrome_options = Options()
chrome_options.add_argument("--headless")
driver = uc.Chrome(use_subprocess=True,executable_path="/usr/local/bin/chromedriver", options=chrome_options)
```
