### ISSUE TITLE
Not working on Replit

### ISSUE THREAD

**Issue by lengvietcuong** [ultrafunkamsterdam/undetected-chromedriver#786]
Hello, I'm trying to use this on Replit but it doesn't seem to work, while the normal selenium works just fine.
Here's the code:

import undetected_chromedriver as uc
driver = uc.Chrome()
driver.get('https://google.com')

I'm getting this error message:

Traceback (most recent call last):
  File "main.py", line 4, in <module>
    driver = uc.Chrome()
  File "/home/runner/fff/venv/lib/python3.8/site-packages/undetected_chromedriver/__init__.py", line 401, in __init__
    super(Chrome, self).__init__(
  File "/home/runner/fff/venv/lib/python3.8/site-packages/selenium/webdriver/chrome/webdriver.py", line 69, in __init__
    super().__init__(DesiredCapabilities.CHROME['browserName'], "goog",
  File "/home/runner/fff/venv/lib/python3.8/site-packages/selenium/webdriver/chromium/webdriver.py", line 89, in __init__
    self.service.start()
  File "/home/runner/fff/venv/lib/python3.8/site-packages/selenium/webdriver/common/service.py", line 98, in start
    self.assert_process_still_running()
  File "/home/runner/fff/venv/lib/python3.8/site-packages/selenium/webdriver/common/service.py", line 110, in assert_process_still_running
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: Service /home/runner/.local/share/undetected_chromedriver/be5abb7191dcb2e9_chromedriver unexpectedly exited. Status code was: 127

Please help me fix it, thanks so much!

**Comment by MohammadAmaan14** [comment]
Same issue

**Comment by evgcrvsed** [comment]
Same issue
