### ISSUE TITLE
TypeError: expected str, bytes or os.PathLike object, not NoneType

### ISSUE THREAD

**Issue by saif-byte** [ultrafunkamsterdam/undetected-chromedriver#787]
I am trying to run undetected chromedriver with the get started code but keep getting this error:
```
[Process Process-1:
Traceback (most recent call last):
  File "C:\Users\DC\AppData\Local\Programs\Python\Python39\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "C:\Users\DC\AppData\Local\Programs\Python\Python39\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\DC\AppData\Local\Programs\Python\Python39\lib\site-packages\undetected_chromedriver\dprocess.py", line 59, in _start_detached
    p = Popen([executable, *args], stdin=PIPE, stdout=PIPE, stderr=PIPE, **kwargs)
  File "C:\Users\DC\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 947, in __init__    
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\DC\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 1356, in _execute_child
    args = list2cmdline(args)
  File "C:\Users\DC\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 561, in list2cmdline 
   for arg in map(os.fsdecode, seq):
  File "C:\Users\DC\AppData\Local\Programs\Python\Python39\lib\os.py", line 822, in fsdecode
    filename = fspath(filename)  # Does type-checking of `filename`.
TypeError: expected str, bytes or os.PathLike object, not NoneType](url)
```

**Comment by RomanSaviuk** [comment]
Do you have chrome installed?

**Comment by saif-byte** [comment]
@RomanSaviuk yes I have chrome installed.

**Comment by tandaoli** [comment]
i have solve it ,i should install chrom in my linxu environment ,oh i get it
需要在云服务器中安装谷歌浏览器，困住我好久。。。

**Comment by kaliiiiiiiiii** [comment]
have a look at https://github.com/ultrafunkamsterdam/undetected-chromedriver/issues/497#issuecomment-1039864761
