### ISSUE TITLE
Message: Service /root/.local/share/undetected_chromedriver/ae9b10e548ec168c_chromedriver unexpectedly exited. Status code was: 255

### ISSUE THREAD

**Issue by pfremm** [ultrafunkamsterdam/undetected-chromedriver#790]
I was attempting to run undetected-chromedriver in a docker container on my m1 mac and received the following stack trace:

Traceback (most recent call last):
  File "//test2.py", line 9, in <module>
    driver = uc.Chrome(options=options, use_subprocess=True, headless=True)
  File "/usr/local/lib/python3.10/site-packages/undetected_chromedriver/__init__.py", line 401, in __init__
    super(Chrome, self).__init__(
  File "/usr/local/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py", line 69, in __init__
    super().__init__(DesiredCapabilities.CHROME['browserName'], "goog",
  File "/usr/local/lib/python3.10/site-packages/selenium/webdriver/chromium/webdriver.py", line 89, in __init__
    self.service.start()
  File "/usr/local/lib/python3.10/site-packages/selenium/webdriver/common/service.py", line 98, in start
    self.assert_process_still_running()
  File "/usr/local/lib/python3.10/site-packages/selenium/webdriver/common/service.py", line 110, in assert_process_still_running
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: Service /root/.local/share/undetected_chromedriver/ae9b10e548ec168c_chromedriver unexpectedly exited. Status code was: 255

Eventually determined this was caused by patcher.py only looking at platform and determining linux and not also importing platform and checking for aarch64 as processor architecture.
```
>>> platform.machine()
'aarch64'
```

I was able to install the driver within the debian container via
```
apt-get install -y chromium-driver
```

Then adjusted code as follows to specify chromedriver path:

```
driver = uc.Chrome(options=options, use_subprocess=True, headless=True, driver_executable_path="/usr/bin/chromedriver")
```

Would you accept a pull request to throw an exception if platform is linux and machine is aarch64 to indicate additional configuration and installs outside this package is required?

**Comment by AsheKR** [comment]
I faced the same problem. `chromedriver unexpectedly exited. Status code was: 255`
Is there a solution?

**Comment by pfremm** [comment]
Yes, the solution is above install chrome driver yourself and then set the driver executable path.

**Comment by ultrafunkamsterdam** [comment]
This seems like a bug in upstream :
https://github.com/SeleniumHQ/selenium/issues/11076

And regarding arm64, that is for mac, and this seems like a new driver as previously there were only 3 flavours. Will fix this. And running in a docker container on your mac / why?! And does the official not work? Don't reinvent the wheel

**Comment by pfremm** [comment]
It works fine with what I mention above.  The code doesn't check for cpu architecture just Linux which is causing the error.

**Comment by MaxDB01** [comment]
Oh my god. Finally! 
I was looking for this solution for hours. 

Thank you. Not all heros wear capes.
