### ISSUE TITLE
How can I use this with Node.js?

### ISSUE THREAD

**Issue by darksur** [ultrafunkamsterdam/undetected-chromedriver#821]
I use selenium with javascript and I have not found something like this yet, it would be great if it could be adapted to be used with Node.js

**Comment by tehaksbrid** [comment]
You can. You just need to tell the python driver to accept remote commands.

Python:
```
    import undetected_chromedriver as uc
    options = uc.ChromeOptions()
    options.add_experimental_option('w3c', False)
    driver = uc.Chrome(options=options, service_args=['--port=57133'], port=57133)
```

In NodeJS (TS):
```
  const {data: sessionData} = await axios(`${remote_url}/sessions`);
  const pySessionId:string = sessionData.value[0].id;

  // Create our request client & API executor
  const client = new HttpClient(remote_url);
  const executor = new Executor(client);
  const pySession = new selenium.Session(pySessionId, {});

  const {WebDriver} = selenium;
  const remoteDriver = new WebDriver(pySession, executor);
```

You can then control `remoteDriver` as normal selenium driver.

**Comment by Anticope12** [comment]
Hi @tehaksbrid ,
Thanks for sharing the above! Out of curiosity, I've seen a few issues here without a straightforward answer for a complicated request. 

Would the above work with that ?

https://github.com/ultrafunkamsterdam/undetected-chromedriver/issues/617#issuecomment-1204492565

**Comment by Anticope12** [comment]
Hi @tehaksbrid 
Thanks for sharing the above! Out of curiosity, I've seen a few issues here without a straightforward answer for a complicated request.

Would the above work with that ?

https://github.com/ultrafunkamsterdam/undetected-chromedriver/issues/617

**Comment by z7pz** [comment]
![image](https://user-images.githubusercontent.com/63007978/213907284-81a582fe-f34d-4a8b-ae88-98be7104af1e.png)
```$ py .\yourscript.py
C:\Python310\lib\site-packages\selenium\webdriver\chromium\options.py:139: UserWarning: Manipulating `w3c` setting can have unintended consequences.
  warnings.warn(UserWarning("Manipulating `w3c` setting can have unintended consequences."))
Traceback (most recent call last):
  File "C:\Users\Mr.Kasper\Documents\projects\probot_claim_v2\yourscript.py", line 6, in <module>
    driver = uc.Chrome(options=options, service_args=[
  File "C:\Python310\lib\site-packages\undetected_chromedriver\__init__.py", line 404, in __init__
    desired_capabilities = options.to_capabilities()
  File "C:\Python310\lib\site-packages\selenium\webdriver\chromium\options.py", line 175, in to_capabilities
    raise AttributeError(
AttributeError: setting w3c to False is not allowed, Please update to W3C Syntax: https://www.selenium.dev/blog/2022/legacy-protocol-support/```

**Comment by baptx** [comment]
@tehaksbrid When running the Python server, I get the error "selenium.common.exceptions.SessionNotCreatedException: Message: session not created: Missing or invalid capabilities". Any idea why?
