### ISSUE TITLE
undetected_chromedriver The run reports an error in the linux，please help me！！

### ISSUE THREAD

**Issue by tandaoli** [ultrafunkamsterdam/undetected-chromedriver#822]
- 
        print('开始初始化')
        options = uc.ChromeOptions()
        # 无头模式
        options.headless = True
        self.driver = uc.Chrome(suppress_welcome=False, options=options,use_subprocess=True)
        self.driver.get('https://www.douyin.com')
        print('初始化完成')

- Traceback (most recent call last):
  File "2.py", line 113, in <module>
    ua1 = un_chrome()
  File "2.py", line 14, in __init__
    self.driver = uc.Chrome(suppress_welcome=False, options=options,use_subprocess=True)
  File "/www/server/python_manager/versions/3.7.12/lib/python3.7/site-packages/undetected_chromedriver/__init__.py", line 397, in __init__
    close_fds=IS_POSIX,
  File "/www/server/python_manager/versions/3.7.12/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/www/server/python_manager/versions/3.7.12/lib/python3.7/subprocess.py", line 1465, in _execute_child
    executable = os.fsencode(executable)
  File "/www/server/python_manager/versions/3.7.12/lib/python3.7/os.py", line 814, in fsencode
    filename = fspath(filename)  # Does type-checking of `filename`.
TypeError: expected str, bytes or os.PathLike object, not NoneType

**Comment by tandaoli** [comment]
i can run it in windows environment
but i can‘t run it in Linux environment
it mass me!!

**Comment by tandaoli** [comment]
i have solve it ,i should install chrom in my linxu environment ,oh i get it
需要在云服务器中安装谷歌浏览器，困住我好久。。。

**Comment by wazoooo** [comment]
Yes, make sure you install chrome first. Close issue please.

**Comment by Liu-Angelo** [comment]
File "/usr/local/bin/python310/lib/python3.10/site-packages/revChatGPT/ChatGPT.py", line 401, in get_cf_cookies
    driver = uc.Chrome(
  File "/usr/local/bin/python310/lib/python3.10/site-packages/undetected_chromedriver/__init__.py", line 246, in __init__
    patcher.auto()
  File "/usr/local/bin/python310/lib/python3.10/site-packages/undetected_chromedriver/patcher.py", line 130, in auto
    release = self.fetch_release_number()
  File "/usr/local/bin/python310/lib/python3.10/site-packages/undetected_chromedriver/patcher.py", line 151, in fetch_release_number
    return LooseVersion(urlopen(self.url_repo + path).read().decode())
  File "/usr/local/bin/python310/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/bin/python310/lib/python3.10/urllib/request.py", line 519, in open
    response = self._open(req, data)
  File "/usr/local/bin/python310/lib/python3.10/urllib/request.py", line 541, in _open
    return self._call_chain(self.handle_open, 'unknown',
  File "/usr/local/bin/python310/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/usr/local/bin/python310/lib/python3.10/urllib/request.py", line 1419, in unknown_open
    raise URLError('unknown url type: %s' % type)
urllib.error.URLError: <urlopen error unknown url type: https>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/langstonliu/chatgpt_main.py", line 9, in <module>
    chatbot = Chatbot(config, conversation_id=None, parent_id=None)
  File "/usr/local/bin/python310/lib/python3.10/site-packages/revChatGPT/ChatGPT.py", line 77, in __init__
    self.get_cf_cookies()
  File "/usr/local/bin/python310/lib/python3.10/site-packages/revChatGPT/ChatGPT.py", line 416, in get_cf_cookies
    driver.quit()
UnboundLocalError: local variable 'driver' referenced before assignment
