### ISSUE TITLE
Close webdriver

### ISSUE THREAD

**Issue by Krato** [ultrafunkamsterdam/undetected-chromedriver#83]
Hello. First need to say thanks for your project.

After using your webdriver with `uc.install()` I have some problems when close method is used.

I tried with `close` and `quit` but no way. 

Here is the traceback if helps:

```
Traceback (most recent call last):
  File "/home/eric/WebDriver/Driver.py", line 127, in close
    self.driver.quit()
  File "/home/eric/.local/lib/python3.8/site-packages/selenium/webdriver/chrome/webdriver.py", line 158, in quit
    self.service.stop()
  File "/home/eric/.local/lib/python3.8/site-packages/selenium/webdriver/common/service.py", line 151, in stop
    self.send_remote_shutdown_command()
  File "/home/eric/.local/lib/python3.8/site-packages/selenium/webdriver/common/service.py", line 127, in send_remote_shutdown_command
    url_request.urlopen("%s/shutdown" % self.service_url)
  File "/usr/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/usr/lib/python3.8/urllib/request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 1346, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/lib/python3.8/urllib/request.py", line 1321, in do_open
    r = h.getresponse()
  File "/usr/lib/python3.8/http/client.py", line 1322, in getresponse
    response.begin()
  File "/usr/lib/python3.8/http/client.py", line 303, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.8/http/client.py", line 272, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without respons
```

**Comment by ultrafunkamsterdam** [comment]
why would you close it? it will close automatically on exit.
anyhow. in the recent update the close method is overwritten and so you need to either use 'quit()' or just exit your program.

**Comment by Krato** [comment]
@ultrafunkamsterdam I want to close it cause I make some operations after use the browser. So I don't want to have it in memory. But perfect with `quit()` method. 

Thanks! 😄

**Comment by ngolun669** [comment]
quit() function is not working
