### ISSUE TITLE
Error with: Pyinstaller + Undetected-chromedriver: compiles but doesn't open.

### ISSUE THREAD

**Issue by AlexPaiva** [ultrafunkamsterdam/undetected-chromedriver#831]
Just importing uc normally and starting it normally, 3 lines of code.
Via command line it works perfectly.

Via pyinstaller it gives the following error:
"Failed to execute script 'main' due to unhandled exception: No module named 'setuptools._distutils'"
Traceback (most recent call last):
  File "main.py", line 27, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "undetected_chromedriver\__init__.py", line 43, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "undetected_chromedriver\patcher.py", line 13, in <module>
  File "_distutils_hack\__init__.py", line 88, in create_module
  File "importlib\__init__.py", line 126, in import_module
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "setuptools\__init__.py", line 10, in <module>
  File "_distutils_hack\__init__.py", line 88, in create_module
  File "importlib\__init__.py", line 126, in import_module
ModuleNotFoundError: No module named 'setuptools._distutils'

BUT if I manually import the package via hiddenimports on the spec file of the .exe, I get:
"Failed to execute script 'main' due to unhandled exception: cannot import name 'log' from 'setuptools._distutils' (C:\User\AA\AppData\Local\Temp\_MEI78002\setuptools\_distutils....." (... because it custs off the screen)
Traceback (most recent call last):
  File "main.py", line 27, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "undetected_chromedriver\__init__.py", line 43, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "undetected_chromedriver\patcher.py", line 13, in <module>
  File "_distutils_hack\__init__.py", line 88, in create_module
  File "importlib\__init__.py", line 126, in import_module
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "setuptools\__init__.py", line 10, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "distutils\core.py", line 16, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "distutils\dist.py", line 19, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "distutils\util.py", line 15, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "distutils\spawn.py", line 15, in <module>
ImportError: cannot import name 'log' from 'setuptools._distutils' (C:\Users\AA\AppData\Local\Temp\_MEI78002\setuptools\_distutils\__init__.pyc)

No idea on how to fix this, I tried tweaking it, changing the imports, adding a service, adding manual executable path, nothing...

**Comment by Fakesum** [comment]
Duplicate of #501
