### ISSUE TITLE
undetected_chromedriver requires newer chromedriver - version than automatically provided

### ISSUE THREAD

**Issue by AndreasLuckert** [ultrafunkamsterdam/undetected-chromedriver#868]
This post is based on [my post on StackOverFlow](https://stackoverflow.com/questions/74279326/undetected-chromedriver-requires-newer-chromedriver-version-than-automatically) as I realized I should probably ask it here:

Before instantiating a new [undetected-chromedriver][1] - instance, I ensure that the latest [ChromeDriver version][2] is installed via the [python-chromedriver-autoinstaller][3] library as mentioned in [this post][4]:

    import chromedriver_autoinstaller
    chromedriver_autoinstaller.install()
    
    'C:\\Users\\username\\project_path\\lib\\site-packages\\chromedriver_autoinstaller\\106\\chromedriver.exe'

As can be seen, it automatically installs version **106**, but in the error message (caused by the intent to instantiate the undetected Chrome Driver via `UndetectedChromeDriver.Chrome(options=self._browser_options)`), it states I need the next version **107**:

> selenium.common.exceptions.WebDriverException: Message: unknown error:
> cannot connect to chrome at 127.0.0.1:... from session not created:
> This version of ChromeDriver only supports Chrome version **107** Current
> browser version is **106**.0.5249.119

Another conventional way of automatically installing the required chromedriver did not work either:

    from selenium.webdriver.chrome.service import Service as ChromeService
    from webdriver_manager.chrome import ChromeDriverManager
    import undetected_chromedriver as UndetectedChromeDriver
    
    return UndetectedChromeDriver.Chrome(
    	options=self._browser_options,
    	service=ChromeService(ChromeDriverManager().install()))

I need to deploy this remotely, so there should be a way to automatically get and install the required ChromeDriver - version.

The full error message with traceback is as follows:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\username\project_path\lib\site-packages\undetected_chromedriver\__init__.py", line 103, in __init__
        def __init__(
      File "C:\Users\username\project_path\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 35, in __init__
        def __init__(self, executable_path=DEFAULT_EXECUTABLE_PATH, port=DEFAULT_PORT,
      File "C:\Users\username\project_path\lib\site-packages\selenium\webdriver\chromium\webdriver.py", line 37, in __init__
        def __init__(self, browser_name, vendor_prefix,
      File "C:\Users\username\project_path\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 195, in __init__
        def __init__(self, command_executor='http://127.0.0.1:4444',
      File "C:\Users\username\project_path\lib\site-packages\undetected_chromedriver\__init__.py", line 599, in start_session
        def start_session(self, capabilities=None, browser_profile=None):
      File "C:\Users\username\project_path\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 346, in start_session
        def start_session(self, capabilities: dict, browser_profile=None) -> None:
      File "C:\Users\username\project_path\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 408, in execute
        def execute(self, driver_command: str, params: dict = None) -> dict:
      File "C:\Users\username\project_path\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 102, in check_response
        def check_response(self, response: Dict[str, Any]) -> None:
    
    selenium.common.exceptions.WebDriverException: Message: unknown error: cannot connect to chrome at 127.0.0.1:...
    from session not created: This version of ChromeDriver only supports Chrome version 107
    Current browser version is 106.0.5249.119
    
    Stacktrace:
    
    Backtrace:
    	Ordinal0 [0x00FEACD3+2075859]
    	Ordinal0 [0x00F7EE61+1633889]
    	Ordinal0 [0x00E7B7BD+571325]
    	Ordinal0 [0x00E9DFCD+712653]
    	Ordinal0 [0x00E96D24+683300]
    	Ordinal0 [0x00E96B01+682753]
    	Ordinal0 [0x00ECDBD3+908243]
    	Ordinal0 [0x00ECD6AA+906922]
    	Ordinal0 [0x00EC7136+880950]
    	Ordinal0 [0x00E9FEFD+720637]
    	Ordinal0 [0x00EA0F3F+724799]
    	GetHandleVerifier [0x0129EED2+2769538]
    	GetHandleVerifier [0x01290D95+2711877]
    	GetHandleVerifier [0x0107A03A+521194]
    	GetHandleVerifier [0x01078DA0+516432]
    	Ordinal0 [0x00F8682C+1665068]
    	Ordinal0 [0x00F8B128+1683752]
    	Ordinal0 [0x00F8B215+1683989]
    	Ordinal0 [0x00F96484+1729668]
    	BaseThreadInitThunk [0x774CFA29+25]
    	RtlGetAppContainerNamedObjectPath [0x779E7BBE+286]
    	RtlGetAppContainerNamedObjectPath [0x779E7B8E+238]

**EDIT** (more info about Chrome Version):

    C:\Users\username>REG QUERY HKEY_CURRENT_USER\Software\Google\Chrome\BLBeacon /v Version
    
    HKEY_CURRENT_USER\Software\Google\Chrome\BLBeacon
        Version    REG_SZ    106.0.5249.119

  [1]: https://github.com/ultrafunkamsterdam/undetected-chromedriver
  [2]: https://chromedriver.chromium.org/downloads
  [3]: https://github.com/yeongbin-jo/python-chromedriver-autoinstaller
  [4]: https://stackoverflow.com/a/72123590/12298276

**Comment by AndreasLuckert** [comment]
Thanks for the hint, by hard-coding `106` it works:

```
            chromedriver_autoinstaller.install()
            return UndetectedChromeDriver.Chrome(options=self._browser_options,
                                                 version_main=106)
```

However, this is just a workaround.
I would rather have a long-term sustainable solution where the automatically installed chromedriver matches the expected version of the UndetectedChromeDriver.

E.g. what would happen if a new version 108 is released? Then UndetectedChromeDriver might expected 108, chromedriver_autoinstaller installs 107, I still have 106 hard-coded and everything fails again.

**Comment by MattWaller** [comment]
My [PR](https://github.com/ultrafunkamsterdam/undetected-chromedriver/pull/823) should solve this issue, but hasn't been reviewed or approved.

**Comment by m3ali** [comment]
I solved this issue by following this steps:
1- Install Webdriver Manager for Python: pip install webdriver-manager
2- In my code:

from webdriver_manager.core.os_manager import OperationSystemManager,ChromeType        
br_ver = OperationSystemManager().get_browser_version_from_os(ChromeType.GOOGLE)   
version_main=int(br_ver.split('.')[0]) 
options = uc.ChromeOptions()      
driver = uc.Chrome(options=options,version_main=version_main) 

Unfortunately, undetected_chromedriver has no way to get the current version of chrome browser, So I installed webdriver-manager to get this information

**Comment by m3ali** [comment]
You can use version_main argument as follows:

    import undetected_chromedriver as uc
    driver = uc.Chrome(version_main=116)

see https://github.com/ultrafunkamsterdam/undetected-chromedriver/issues/572

But if the your browser is updated you should change the 
version_main to the new chrome version
So I am using this method to get the current chrome version and pass it as the version_main value:

 1. Install Webdriver Manager for Python: pip install webdriver-manager
 2. Use this code:

    import undetected_chromedriver as uc
    from webdriver_manager.core.os_manager import OperationSystemManager,ChromeType        
    br_ver = OperationSystemManager().get_browser_version_from_os(ChromeType.GOOGLE)   
    version_main=int(br_ver.split('.')[0]) 
    options = uc.ChromeOptions()          
    driver = uc.Chrome(version_main=version_main)

**Comment by enganese** [comment]
> You can pass `version_main` argument with your current driver version to your webdriver.
> 
> `driver = uc.Chrome(options=options, version_main=106)`

Thanks, helped!

**Comment by Louis24** [comment]
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: cannot connect to chrome at 127.0.0.1:64276
from chrome not reachable
Stacktrace:
	GetHandleVerifier [0x009EFD53+23747]
	(No symbol) [0x00977D54]
	(No symbol) [0x0084BCCD]
	(No symbol) [0x008407AC]
	(No symbol) [0x008806F6]
	(No symbol) [0x0087720F]
	(No symbol) [0x00877057]
	(No symbol) [0x008BB3C1]
	(No symbol) [0x008BAB9A]
	(No symbol) [0x008B1B96]
	(No symbol) [0x00883F3C]
	(No symbol) [0x00884EBD]
	GetHandleVerifier [0x00CCAC73+3017699]
	GetHandleVerifier [0x00CDB93B+3086507]
	GetHandleVerifier [0x00CD40F2+3055714]
	GetHandleVerifier [0x00A85AF0+637536]
	(No symbol) [0x00980A5D]
	(No symbol) [0x0097DA28]
	(No symbol) [0x0097DBC5]
	(No symbol) [0x009707F0]
	BaseThreadInitThunk [0x76D27BA9+25]
	RtlInitializeExceptionChain [0x779CC0CB+107]
	RtlClearBits [0x779CC04F+191]


I got the same issue
