### ISSUE TITLE
Undetected_chromedriver not working when compiled to .exe

### ISSUE THREAD

**Issue by kojakeugenio** [ultrafunkamsterdam/undetected-chromedriver#873]
I tried to compiled the gmail login script I made using undetected_chromedriver library but when I compiled it with pyinstaller it doesnt work. It just opened the terminal and not printing anything then it throws this error. It's working when I ran it on VSCode.

```
Traceback (most recent call last):
  File "gmailLogin.py", line 33, in <module>
  File "gmailLogin.py", line 18, in gmailLogin
  File "undetected_chromedriver\__init__.py", line 240, in __init__
  File "undetected_chromedriver\patcher.py", line 130, in auto
  File "undetected_chromedriver\patcher.py", line 185, in unzip_package
OSError: [WinError 145] The directory is not empty: 'C:\\Users\\Kojak Eugenio\\appdata\\roaming\\undetected_chromedriver\\c5d13d71af0288a8'
[9804] Failed to execute script 'gmailLogin' due to unhandled exception!
```

here's the full code i compiled to .exe

```
# import selenium as webdriver
import undetected_chromedriver as uc
from selenium.webdriver.common.by import By
# from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support import expected_conditions as EC
from time import sleep

def gmailLogin():
    userN = "myuser@gmail.com"
    passW = "mypass"
    driver = uc.Chrome()
    driver.get("https://www.gmail.com")
    sleep(2)
    inputUser = driver.find_element(By.XPATH, "//input[@id='identifierId']").send_keys(userN)
    sleep(2)
    inputUser = driver.find_element(By.XPATH, "//input[@id='identifierId']").send_keys(Keys.ENTER)
    sleep(2)
    inputUser = driver.find_element(By.XPATH, '//input[@type="password"]').send_keys(passW)
    sleep(2)
    inputUser = driver.find_element(By.XPATH, '//input[@type="password"]').send_keys(Keys.ENTER)

    sleep(15)
    driver.close()
    
if __name__ == "__main__":
    gmailLogin()
```

 I noticed that it keeps generating these files here while the .exe is open. Its not stopping generating these files. 

[Image](https://i.stack.imgur.com/fbZ45.jpg)

**Comment by liladhen** [comment]
Try this:

_from multiprocessing import freeze_support

if __name__ == "__main__":
    freeze_support()
    gmailLogin()_
