### ISSUE TITLE
Driver patching gets stuck in Docker container

### ISSUE THREAD

**Issue by PhilK-7** [ultrafunkamsterdam/undetected-chromedriver#878]
I'm executing a Python script inside a Docker container. So far, everything worked for me locally.

The call `uc.Chrome()` by default triggers the patcher that downloads the executable to a local path.

Now, in the container, I instead get the following stack trace:

```
2022-11-08 15:14:44,487 [INFO] patching driver executable /home/airflow/.local/share/undetected_chromedriver/chromedriver
Process Process-1:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/undetected_chromedriver/dprocess.py", line 59, in _start_detached
    p = Popen([executable, *args], stdin=PIPE, stdout=PIPE, stderr=PIPE, **kwargs)
  File "/usr/local/lib/python3.10/subprocess.py", line 966, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/lib/python3.10/subprocess.py", line 1717, in _execute_child
    and os.path.dirname(executable)
  File "/usr/local/lib/python3.10/posixpath.py", line 152, in dirname
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

The program gets stuck at this point.

**Comment by emanodame** [comment]
How docker

**Comment by axiangcoding** [comment]
Same issue. how we install chromedriver locally?

**Comment by Arsh1219** [comment]
same issue, any solution?

**Comment by axiangcoding** [comment]
I found a way that works for me
Dockerfile
```
FROM python:3.11-alpine
WORKDIR /app
RUN apk update && apk upgrade
RUN apk add chromium chromium-chromedriver unzip curl

COPY requirements.txt ./
RUN pip install -r requirements.txt

COPY main.py ./
ENTRYPOINT ["python", "-u", "main.py"]
```

inside `main.py`
```
options = uc.ChromeOptions()
options.add_argument("--disable-gpu")
options.add_argument('--no-sandbox')
# comment driver_executable_path when you test in local
driver = uc.Chrome(version_main=111, options=options, headless=True,
                   driver_executable_path="/usr/bin/chromedriver")
```

**Comment by grayskripko** [comment]
has relation to https://github.com/ultrafunkamsterdam/undetected-chromedriver/issues/747
