### ISSUE TITLE
Problem with executing on Ubuntu 18.04.5 LTS

### ISSUE THREAD

**Issue by sirgoogleadmin** [ultrafunkamsterdam/undetected-chromedriver#88]
Hi Guys,
I tried to execute the following code:

import undetected_chromedriver as uc
driver = uc.Chrome()
driver.get('https://distilnetworks.com')

But i am always getting the same error, i googled and googled but nothing helped me.
Error:

Traceback (most recent call last):
  File "chrome.py", line 2, in <module>
    driver = uc.Chrome()
  File "/usr/local/lib/python3.6/dist-packages/undetected_chromedriver/__init__.py", line 53, in __new__
    instance.__init__(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/chrome/webdriver.py", line 73, in __init__
    self.service.start()
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/common/service.py", line 98, in start
    self.assert_process_still_running()
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/common/service.py", line 111, in assert_process_still_running
    % (self.path, return_code)
selenium.common.exceptions.WebDriverException: Message: Service ./chromedriver unexpectedly exited. Status code was: 127

I hope someone can help me, keep up the good work!

**Comment by ultrafunkamsterdam** [comment]
my best guess.. google chrome is not included, you need to make sure it's installed (in a common, preferable default location).

**Comment by HMaker** [comment]
in bash `127` exit code means command not found, so I think chrome has not found too
