### ISSUE TITLE
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot connect to chrome at 127.0.0.1:41601 from session not created: This version of ChromeDriver only supports Chrome version 107 Current browser version is 109.0.5410.0

### ISSUE THREAD

**Issue by ghost** [ultrafunkamsterdam/undetected-chromedriver#885]
Traceback (most recent call last):
  File "/home/xor7/browser.py", line 2, in <module>
    driver = uc.Chrome()
  File "/home/xor7/.local/lib/python3.10/site-packages/undetected_chromedriver/__init__.py", line 409, in __init__
    super(Chrome, self).__init__(
  File "/home/xor7/.local/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py", line 81, in __init__
    super().__init__(
  File "/home/xor7/.local/lib/python3.10/site-packages/selenium/webdriver/chromium/webdriver.py", line 106, in __init__
    super().__init__(
  File "/home/xor7/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 288, in __init__
    self.start_session(capabilities, browser_profile)
  File "/home/xor7/.local/lib/python3.10/site-packages/undetected_chromedriver/__init__.py", line 602, in start_session
    super(selenium.webdriver.chrome.webdriver.WebDriver, self).start_session(
  File "/home/xor7/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 381, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/xor7/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 444, in execute
    self.error_handler.check_response(response)
  File "/home/xor7/.local/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py", line 249, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot connect to chrome at 127.0.0.1:41601
from session not created: This version of ChromeDriver only supports Chrome version 107
Current browser version is 109.0.5410.0
Stacktrace:
#0 0x55aaabd6a463 <unknown>
#1 0x55aaabb2e8d8 <unknown>
#2 0x55aaabb5b3c6 <unknown>
#3 0x55aaabb5182f <unknown>
#4 0x55aaabb95802 <unknown>
#5 0x55aaabb952af <unknown>
#6 0x55aaabb8d443 <unknown>
#7 0x55aaabb5e3c5 <unknown>
#8 0x55aaabb5f531 <unknown>
#9 0x55aaabdbcdce <unknown>
#10 0x55aaabdc0192 <unknown>
#11 0x55aaabda193e <unknown>
#12 0x55aaabdc1103 <unknown>
#13 0x55aaabd94d85 <unknown>
#14 0x55aaabde20a8 <unknown>
#15 0x55aaabde2239 <unknown>
#16 0x55aaabdfd492 <unknown>
#17 0x7f33e848cded start_thread

**Comment by andriuy000** [comment]
if you use profile path?
