### ISSUE TITLE
Speedup driver shutdown

### ISSUE THREAD

**Issue by nuclear-bean** [ultrafunkamsterdam/undetected-chromedriver#890]
After calling driver.quit() the script still hangs for a while. I did some digging and it seems multiple retries are sent for DELETE /session/uuid request. 

script to reproduce:

```
import logging
from time import sleep

import undetected_chromedriver as uc

if __name__ == '__main__':
    log = logging.getLogger('pds')
    logging.basicConfig(
        format='%(asctime)s %(levelname)-8s %(message)s',
        level=logging.DEBUG,
        datefmt='%Y-%m-%d %H:%M:%S')

    driver = uc.Chrome()
    driver.get(url='https://www.example.org/')
    sleep(1)
    driver.quit()
```

and the interesting thing in the output is:
```
2022-11-13 21:08:49 DEBUG    DELETE http://localhost:51106/session/24d486186cecee5100e8d4e158a2cbd6 {}
2022-11-13 21:08:49 DEBUG    Resetting dropped connection: localhost
2022-11-13 21:08:53 DEBUG    Incremented Retry for (url='/session/24d486186cecee5100e8d4e158a2cbd6'): Retry(total=2, connect=None, read=None, redirect=None, status=None)
2022-11-13 21:08:53 WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001A0E74180D0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/24d486186cecee5100e8d4e158a2cbd6
2022-11-13 21:08:53 DEBUG    Starting new HTTP connection (2): localhost:51106
2022-11-13 21:08:57 DEBUG    Incremented Retry for (url='/session/24d486186cecee5100e8d4e158a2cbd6'): Retry(total=1, connect=None, read=None, redirect=None, status=None)
2022-11-13 21:08:57 WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001A0E4DF64C0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/24d486186cecee5100e8d4e158a2cbd6
2022-11-13 21:08:57 DEBUG    Starting new HTTP connection (3): localhost:51106
2022-11-13 21:09:01 DEBUG    Incremented Retry for (url='/session/24d486186cecee5100e8d4e158a2cbd6'): Retry(total=0, connect=None, read=None, redirect=None, status=None)
2022-11-13 21:09:01 WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001A0E7263D60>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/24d486186cecee5100e8d4e158a2cbd6
2022-11-13 21:09:01 DEBUG    Starting new HTTP connection (4): localhost:51106
```

seems that delete request is executed 3 more times before it gives up. Can be fixed / modified to decrease shutdown time.

**Comment by mayflowerr** [comment]
I wrote about a way to override the __del__ method:
```python
class Chrome(uc.Chrome):

    def __del__(self):
        self.quit()
```
This solves the problem with reconnect attempts, but it still tries to delete temporary folders that are already gone, and this again takes some time. 
```
DEBUG:seleniumwire.storage:Cleaning up C:\Users\user\AppData\Local\Temp\.seleniumwire\storage-3688490b-3f00-49c2-9659-6d6cee83d9c7
```
When more than 100 chrome drivers are created for different profiles, closing them takes quite a long time. 
Any ideas on how to speed up this process?

**Comment by mayflowerr** [comment]
I already wrote a way to solve the problem with reconnects to an already closed browser by overriding the __del__ of the method:
```python
class Chrome(uc.Chrome):

    def __del__(self):
        self.quit()
```
But after that, the browser still takes some time to close, and when there are a lot of browser windows, this becomes a problem.
I began to search, and found that when removing the chrome Service, it sends a shutdown command to the browser [at this line](https://github.com/SeleniumHQ/selenium/blob/0231def8c8d07582f983930407ed0aa5522d1143/py/selenium/webdriver/common/service.py#L154). If you comment out this line, all browsers and the program close almost instantly. But I'm not sure it's safe to do so. Will there be any processes left in memory? Do you have any thoughts?

**Comment by ggnetoo** [comment]
Same here. Got this log when I call the .quit() and the process that used the UC ends.

Logs:
Exception ignored in: <function Chrome.__del__ at 0x000001B4A662C720>
Traceback (most recent call last):
  File "C:\Users\Mano\AppData\Local\Programs\Python\Python311\Lib\site-packages\undetected_chromedriver\__init__.py", line 788, in __del__
    self.quit()
  File "C:\Users\Mano\AppData\Local\Programs\Python\Python311\Lib\site-packages\undetected_chromedriver\__init__.py", line 743, in quit   
    time.sleep(0.1)
OSError: [WinError 6] Identificador inválido
