### ISSUE TITLE
how to connect proxy to undetected driver

### ISSUE THREAD

**Issue by ahmedabdelhamedz** [ultrafunkamsterdam/undetected-chromedriver#899]
`import time
import seleniumwire.undetected_chromedriver as uc

if name == "main":
chrome_options = uc.ChromeOptions()
# here your chrome options

seleniumwire_options = {
    "proxy": {
        "https": "https://user:pass@ip:port"
    }
}

driver = uc.Chrome(
    options=chrome_options, seleniumwire_options=seleniumwire_options
)
driver.get("https://api.myip.com/")
time.sleep(10)`
i found this error code

C:\Users\pcpc\PycharmProjects\untitled\venv\Scripts\python.exe C:/Users/pcpc/PycharmProjects/untitled/script.py
Traceback (most recent call last):
File "C:\Users\pcpc\PycharmProjects\untitled\script.py", line 8, in
from seleniumwire import webdriver
File "C:\Users\pcpc\PycharmProjects\untitled\venv\lib\site-packages\seleniumwire\webdriver.py", line 28, in
from seleniumwire import backend, utils
File "C:\Users\pcpc\PycharmProjects\untitled\venv\lib\site-packages\seleniumwire\backend.py", line 4, in
from seleniumwire.server import MitmProxy
File "C:\Users\pcpc\PycharmProjects\untitled\venv\lib\site-packages\seleniumwire\server.py", line 5, in
from seleniumwire.handler import InterceptRequestHandler
File "C:\Users\pcpc\PycharmProjects\untitled\venv\lib\site-packages\seleniumwire\handler.py", line 5, in
from seleniumwire import har
File "C:\Users\pcpc\PycharmProjects\untitled\venv\lib\site-packages\seleniumwire\har.py", line 12, in
from seleniumwire.thirdparty.mitmproxy.http import HTTPFlow
File "C:\Users\pcpc\PycharmProjects\untitled\venv\lib\site-packages\seleniumwire\thirdparty\mitmproxy\http.py", line 7, in
from seleniumwire.thirdparty.mitmproxy.net import http
File "C:\Users\pcpc\PycharmProjects\untitled\venv\lib\site-packages\seleniumwire\thirdparty\mitmproxy\net\http_init_.py", line 1, in
from seleniumwire.thirdparty.mitmproxy.net.http import http1, http2, multipart, status_codes
File "C:\Users\pcpc\PycharmProjects\untitled\venv\lib\site-packages\seleniumwire\thirdparty\mitmproxy\net\http\http1_init_.py", line 2, in
from .read import (connection_close, expected_http_body_size, read_body, read_request, read_request_head,
File "C:\Users\pcpc\PycharmProjects\untitled\venv\lib\site-packages\seleniumwire\thirdparty\mitmproxy\net\http\http1\read.py", line 7, in
from seleniumwire.thirdparty.mitmproxy.net.http import (headers, request,
File "C:\Users\pcpc\PycharmProjects\untitled\venv\lib\site-packages\seleniumwire\thirdparty\mitmproxy\net\http\request.py", line 8, in
from seleniumwire.thirdparty.mitmproxy.net.http import cookies, message, multipart
File "C:\Users\pcpc\PycharmProjects\untitled\venv\lib\site-packages\seleniumwire\thirdparty\mitmproxy\net\http\message.py", line 6, in
from seleniumwire.thirdparty.mitmproxy.net.http import encoding
File "C:\Users\pcpc\PycharmProjects\untitled\venv\lib\site-packages\seleniumwire\thirdparty\mitmproxy\net\http\encoding.py", line 12, in
import brotli
File "C:\Users\pcpc\PycharmProjects\untitled\venv\lib\site-packages\brotli.py", line 8, in
import _brotli
ImportError: DLL load failed while importing _brotli: The specified module could not be found.

Process finished with exit code 1

please can you explain to me how to fix this error ? @brandfocus @brandfocus @sebdelsol @thomas-milburn @ultrafunkamsterdam @MattWaller

**Comment by MattWaller** [comment]
Not an expert for selenium-wire, but it looks like your protocol on your proxy could be wrong. Should it not be http://user:pass@ip:port not https?

**Comment by ahmedabdelhamedz** [comment]
thanks i fix it by download microsoft c++ last version
