### ISSUE TITLE
Browser crashes and closes when using proxy

### ISSUE THREAD

**Issue by kSalih54** [ultrafunkamsterdam/undetected-chromedriver#901]
My driver options:       
 ```
        myoptions = uc.ChromeOptions()
        myoptions.add_argument(f'--proxy-server=http://'+ str(proxy))
        myoptions.add_argument('--lang=tr')
        myoptions.add_argument('--disable-popup-blocking')

        driver = uc.Chrome(use_subprocess=True, options=myoptions)
```
gives this error: **ERR_TUNNEL_CONNECTION_FAILED**
`selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_TUNNEL_CONNECTION_FAILED`

`Traceback (most recent call last):
  File "c:\Users\kSalih\Desktop\ADV Blog\CookieVar.py", line 162, in <module>
    driver.get(lines[0])
  File "C:\Users\kSalih\AppData\Local\Programs\Python\Python311\Lib\site-packages\undetected_chromedriver\__init__.py", line 543, in get
    return super().get(url)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\kSalih\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 441, in get
    self.execute(Command.GET, {'url': url})
  File "C:\Users\kSalih\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 429, in execute
    self.error_handler.check_response(response)
  File "C:\Users\kSalih\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 243, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_TUNNEL_CONNECTION_FAILED
  (Session info: chrome=107.0.5304.107)
Stacktrace:
Backtrace:
        Ordinal0 [0x009EACD3+2075859]
        Ordinal0 [0x0097EE61+1633889]
        Ordinal0 [0x0087B7BD+571325]
        Ordinal0 [0x00877CD2+556242]
        Ordinal0 [0x0086EC5D+519261]
        Ordinal0 [0x0086FAEC+522988]
        Ordinal0 [0x0086EF27+519975]
        Ordinal0 [0x0086E2EB+516843]
        Ordinal0 [0x0086E231+516657]
        Ordinal0 [0x0086D0A3+512163]
        Ordinal0 [0x0086D5AD+513453]
        Ordinal0 [0x0087D0CE+577742]
        Ordinal0 [0x008DBC7D+965757]
        Ordinal0 [0x008C731C+881436]
        Ordinal0 [0x008DB56A+963946]
        Ordinal0 [0x008C7136+880950]
        Ordinal0 [0x0089FEFD+720637]
        Ordinal0 [0x008A0F3F+724799]
        GetHandleVerifier [0x00C9EED2+2769538]
        GetHandleVerifier [0x00C90D95+2711877]
        GetHandleVerifier [0x00A7A03A+521194]
        GetHandleVerifier [0x00A78DA0+516432]
        Ordinal0 [0x0098682C+1665068]
        Ordinal0 [0x0098B128+1683752]
        Ordinal0 [0x0098B215+1683989]
        Ordinal0 [0x00996484+1729668]
        BaseThreadInitThunk [0x7749FEF9+25]
        RtlGetAppContainerNamedObjectPath [0x77E57BBE+286]
        RtlGetAppContainerNamedObjectPath [0x77E57B8E+238]

Exception ignored in: <function Chrome.__del__ at 0x0000019DEA21B600>
Traceback (most recent call last):
  File "C:\Users\kSalih\AppData\Local\Programs\Python\Python311\Lib\site-packages\undetected_chromedriver\__init__.py", line 657, in __del__
  File "C:\Users\kSalih\AppData\Local\Programs\Python\Python311\Lib\site-packages\undetected_chromedriver\__init__.py", line 645, in quit
OSError: [WinError 6] İşleyici geçersiz
Exception ignored in: <function Patcher.__del__ at 0x0000019DEA1B87C0>
Traceback (most recent call last):
  File "C:\Users\kSalih\AppData\Local\Programs\Python\Python311\Lib\site-packages\undetected_chromedriver\patcher.py", line 273, in __del__
OSError: [WinError 6] İşleyici geçersiz`

**Comment by LexxLuey** [comment]
wow. no comment on this?
