### ISSUE TITLE
Runtime error

### ISSUE THREAD

**Issue by jab2727** [ultrafunkamsterdam/undetected-chromedriver#905]
**Key issue:**
I can't get undetected-chromedriver to run. Is this project compatible with my system?

**System:**
Mac OS 10.15.7
Python 3.8.2
Chrome: 107.0.5304.62
Webdriver: 107.0.5304.62

**Full error message:**

> Traceback (most recent call last):
>     File "<string>", line 1, in <module>
>     File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/multiprocessing/spawn.py", line 116, in spawn_main
>       exitcode = _main(fd, parent_sentinel)
>     File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/multiprocessing/spawn.py", line 125, in _main
>       prepare(preparation_data)
>     File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/multiprocessing/spawn.py", line 236, in prepare
>       _fixup_main_from_path(data['init_main_from_path'])
>     File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
>       main_content = runpy.run_path(main_path,
>     File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/runpy.py", line 263, in run_path
>       return _run_module_code(code, init_globals, run_name,
>     File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/runpy.py", line 96, in _run_module_code
>       _run_code(code, mod_globals, init_globals,
>     File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/runpy.py", line 86, in _run_code
>       exec(code, run_globals)
>     File "/Users/AZC4063/Desktop/pythonProject/TCG_Player_Complete_v1.py", line 24, in <module>
>       driver = uc.Chrome()
>     File "/Users/AZC4063/Desktop/pythonProject/venv/lib/python3.8/site-packages/undetected_chromedriver/__init__.py", line 396, in __init__
>       self.browser_pid = start_detached(
>     File "/Users/AZC4063/Desktop/pythonProject/venv/lib/python3.8/site-packages/undetected_chromedriver/dprocess.py", line 30, in start_detached
>       multiprocessing.Process(
>     File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/multiprocessing/process.py", line 121, in start
>       self._popen = self._Popen(self)
>     File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/multiprocessing/context.py", line 224, in _Popen
>       return _default_context.get_context().Process._Popen(process_obj)
>     File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/multiprocessing/context.py", line 283, in _Popen
>       return Popen(process_obj)
>     File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 32, in __init__
>       super().__init__(process_obj)
>     File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
>       self._launch(process_obj)
>     File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 42, in _launch
>       prep_data = spawn.get_preparation_data(process_obj._name)
>     File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/multiprocessing/spawn.py", line 154, in get_preparation_data
>       _check_not_importing_main()
>     File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/multiprocessing/spawn.py", line 134, in _check_not_importing_main
>       raise RuntimeError('''
>     RuntimeError: 
>         An attempt has been made to start a new process before the
>         current process has finished its bootstrapping phase.
> 
>         This probably means that you are not using fork to start your
>         child processes and you have forgotten to use the proper idiom
>         in the main module:
> 
>             if __name__ == '__main__':
>                 freeze_support()
>                 ...
> 
>         The "freeze_support()" line can be omitted if the program
>         is not going to be frozen to produce an executable.

**Comment by Jaewan-Yun** [comment]
You can use this extension to bypass hCaptcha/reCAPTCHA/FunCAPTCHA/AWS WAF.
https://chrome.google.com/webstore/detail/nopecha-captcha-solver/dknlfmjaanfblgfdfebhijalfmhmjjjo

Source:
https://github.com/NopeCHA/NopeCHA

`
options = uc.ChromeOptions()
options.add_argument("--load-extension=/home/PATH/TO/NOPECHA")
driver = uc.Chrome(options=options)
`

**Comment by Martinzz** [comment]
+1

**Comment by 404b** [comment]
**noCaptchaAi has free plan (6K req/month) you can use**

Chrome Extension
https://github.com/noCaptchaAi/chrome-extension


**Selenium Packages** 

https://github.com/Hammad69275/NoCaptchaSolver
https://github.com/claudiofepereira/nocaptchaai-selenium


`npm install nocaptchasolver`

```
const {HCaptchaSolver} = require("nocaptchasolver")

const config = {
    apiKey,
    userAgent,
    siteKey,
    siteURL,
    enableLogger,
    loggerFunction,
    delay // in milliseconds (default is 7000ms)
}

const Solver = new HCaptchaSolver(config)


```
