### ISSUE TITLE
Chromedriver exception

### ISSUE THREAD

**Issue by FedorSomov** [ultrafunkamsterdam/undetected-chromedriver#930]
My Code:

```
import undetected_chromedriver as uc

driver = uc.Chrome(use_subprocess=True)
driver.get("https://nowsecure.nl")
driver.save_screenshot('screenie.png')

driver.close()
driver.quit()
```

first: nowsecure.nl - detect
![screenie](https://user-images.githubusercontent.com/116040971/205001474-6ebb13b6-17f9-4c3a-8f9d-fcf4712783a4.png)
second: 

```
Exception ignored in: <function Chrome.__del__ at 0x0000023AF063DF80>
Traceback (most recent call last):
  File "C:\Users\ItSMe\PycharmProjects\Ozonparser\venv\Lib\site-packages\undetected_chromedriver\__init__.py", line 769, in __del__
  File "C:\Users\ItSMe\PycharmProjects\Ozonparser\venv\Lib\site-packages\undetected_chromedriver\__init__.py", line 758, in quit
OSError: [WinError 6] Неверный дескриптор

Process finished with exit code 0
```

What am I doing wrong?
Python 3.11.0
PyCharm - last
Undetected chromedriver 3.1.6
Hands are not quite straight, but I try

**Comment by timbeh** [comment]
Hey, did you find a solution for this?

**Comment by krishpuri** [comment]
Would be interested in a solution as well
