### ISSUE TITLE
10054错误是怎么解决呢

### ISSUE THREAD

**Issue by shadow6336** [ultrafunkamsterdam/undetected-chromedriver#933]
run:
from urllib.request import urlopen

url_repo = "https://chromedriver.storage.googleapis.com"
path = "/latest_release".upper()
print(urlopen(url_repo + path).read().decode())

then:
D:\software\Python1\python.exe C:/Users/xtccw/PycharmProjects/pythonProject/testt1.py
Traceback (most recent call last):
  File "D:\software\Python1\lib\urllib\request.py", line 1350, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "D:\software\Python1\lib\http\client.py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "D:\software\Python1\lib\http\client.py", line 1301, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "D:\software\Python1\lib\http\client.py", line 1250, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "D:\software\Python1\lib\http\client.py", line 1010, in _send_output
    self.send(msg)
  File "D:\software\Python1\lib\http\client.py", line 950, in send
    self.connect()
  File "D:\software\Python1\lib\http\client.py", line 1424, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "D:\software\Python1\lib\ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "D:\software\Python1\lib\ssl.py", line 1040, in _create
    self.do_handshake()
  File "D:\software\Python1\lib\ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/xtccw/PycharmProjects/pythonProject/testt1.py", line 5, in <module>
    print(urlopen(url_repo + path).read().decode())
  File "D:\software\Python1\lib\urllib\request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "D:\software\Python1\lib\urllib\request.py", line 525, in open
    response = self._open(req, data)
  File "D:\software\Python1\lib\urllib\request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "D:\software\Python1\lib\urllib\request.py", line 502, in _call_chain
    result = func(*args)
  File "D:\software\Python1\lib\urllib\request.py", line 1393, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "D:\software\Python1\lib\urllib\request.py", line 1353, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [WinError 10054] 远程主机强迫关闭了一个现有的连接。>

Process finished with exit code 1

**Comment by shadow6336** [comment]
> 我现在也遇到了这个问题[悲] Saddly,I have the same error now

我使用了其他的开源，这个是谷歌那个驱动包访问不到，下载不了。你可以参考下：https://github.com/wz-wong/ez-webdriver

**Comment by QIN2DIM** [comment]
你们是认真的吗，在这里问这种问题😃
