### ISSUE TITLE
driver.quit() and/or driver.close() causing urllib3 and logging Warnings/Erros

### ISSUE THREAD

**Issue by ggnetoo** [ultrafunkamsterdam/undetected-chromedriver#972]
Don't know how, but if I use either `driver.close()` or `driver.quit()`, it causes urllib3 WARNINGS and ALL my logging goes to the terminal (stdout) instead going only to the streamfile.

My code is something like this:
```
logger = logging.getLogger("TEST")
logger.setLevel(logging.INFO)
handler = TimedRotatingFileHandler("TEST.log", when="midnight", interval=1, encoding='utf-8')
handler.suffix = "%Y-%m-%d"
logger.addHandler(handler)

def run_test():
    logger.info("START")
    try:
        chrome_options = webdriver.ChromeOptions()
        chrome_options.add_argument('--headless')
        chrome_options.add_argument('--no-sandbox')
        chrome_options.add_argument("--disable-extensions")
        chrome_options.add_argument('--disable-application-cache')
        chrome_options.add_argument("--disable-setuid-sandbox")
        chrome_options.add_argument("--disable-dev-shm-usage")
        chrome_options.add_argument('--disable-gpu')
        chrome_options.add_argument("--start-maximized")

        driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()), options=chrome_options)

        driver.delete_all_cookies()

        driver.get("https://anysite")

    except Exception as e:
        print("Exception", e)
    finally:
        try:
            driver.close()
        except Exception as e:
            print("close", e)
        try:
            driver.quit()
        except Exception as e:
            print("quit", e)

    # more code
    logger.info("FINISH")

def start():
    run_test()
    logger.info("FINISH START")
```

It only happens when I close / quit the driver. Otherwise, the logging keeps writing to the file I designed to.

Some logs:
```
WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: localhost
WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: localhost
WARNING:urllib3.connectionpool:Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000123FE4B5188>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente')': /session/26ce881f83f3183033dde36a660d9261/se/log
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000123FE497788>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente')': /session/26ce881f83f3183033dde36a660d9261/se/log

Then my info logs goes wrongly to the terminal:
INFO:TEST:[Thread-13][04/01/2023 20:10:36.332082] - Some Info
INFO:TEST:[Thread-13][04/01/2023 20:10:36.336100] - Some Info
INFO:TEST:[Thread-13][04/01/2023 20:10:36.336100] - Some Info
INFO:TEST:[Thread-13][04/01/2023 20:10:36.336100] - Some Info
```

Don't know if is the URLLIB3 WARNING who's causing this logging.info to go to terminal/stdout or something else. All I know is that if I use quit/close, this logging -> stdout error happens.

**Comment by ggnetoo** [comment]
Got a few more logs using:
```
logging.getLogger().setLevel(10)
logger = logging.getLogger('undetected_chromedriver')
logger.setLevel(10)
logger.addHandler(logging.FileHandler(os.path.join("logs", "chrome.log")))
```

Logs:

```
====== WebDriver manager ======
Current google-chrome version is 108.0.5359
Get LATEST chromedriver version for 108.0.5359 google-chrome
Driver [C:\Users\Mano\.wdm\drivers\chromedriver\win32\108.0.5359.71\chromedriver.exe] found in cache
--- Logging error ---
Traceback (most recent call last):
  File "C:\Users\Mano\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connection.py", line 175, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "C:\Users\Mano\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\util\connection.py", line 96, in create_connection
    raise err
  File "C:\Users\Mano\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\util\connection.py", line 86, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Mano\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connectionpool.py", line 706, in urlopen
    chunked=chunked,
  File "C:\Users\Mano\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connectionpool.py", line 394, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "C:\Users\Mano\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connection.py", line 239, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "C:\Users\Mano\AppData\Local\Programs\Python\Python37\lib\http\client.py", line 1252, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Users\Mano\AppData\Local\Programs\Python\Python37\lib\http\client.py", line 1298, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Users\Mano\AppData\Local\Programs\Python\Python37\lib\http\client.py", line 1247, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\Mano\AppData\Local\Programs\Python\Python37\lib\http\client.py", line 1026, in _send_output
    self.send(msg)
  File "C:\Users\Mano\AppData\Local\Programs\Python\Python37\lib\http\client.py", line 966, in send
    self.connect()
  File "C:\Users\Mano\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connection.py", line 205, in connect
    conn = self._new_conn()
  File "C:\Users\Mano\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connection.py", line 187, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x0000017E66A69BC8>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Mano\AppData\Local\Programs\Python\Python37\lib\site-packages\undetected_chromedriver\reactor.py", line 74, in listen
    log_entries = self.driver.get_log("performance")
  File "C:\Users\Mano\AppData\Local\Programs\Python\Python37\lib\site-packages\undetected_chromedriver\__init__.py", line 474, in newfunc
    return original(*args, **kwargs)
  File "C:\Users\Mano\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1166, in get_log
    return self.execute(Command.GET_LOG, {'type': log_type})['value']
  File "C:\Users\Mano\AppData\Local\Programs\Python\Python37\lib\site-packages\undetected_chromedriver\__init__.py", line 474, in newfunc
    return original(*args, **kwargs)
  File "C:\Users\Mano\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 427, in execute
    response = self.command_executor.execute(driver_command, params)
  File "C:\Users\Mano\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\remote_connection.py", line 344, in execute
    return self._request(command_info[0], url, body=data)
  File "C:\Users\Mano\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\remote_connection.py", line 366, in _request
    response = self._conn.request(method, url, body=body, headers=headers)
  File "C:\Users\Mano\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\request.py", line 79, in request
    method, url, fields=fields, headers=headers, **urlopen_kw
  File "C:\Users\Mano\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\request.py", line 170, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "C:\Users\Mano\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\poolmanager.py", line 375, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "C:\Users\Mano\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connectionpool.py", line 796, in urlopen
    **response_kw
  File "C:\Users\Mano\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connectionpool.py", line 796, in urlopen
    **response_kw
  File "C:\Users\Mano\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connectionpool.py", line 796, in urlopen
    **response_kw
  File "C:\Users\Mano\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connectionpool.py", line 756, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "C:\Users\Mano\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\util\retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=53283): Max retries exceeded with url: /session/c7bc55019c45a7490090bfe99aac1212/se/log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000017E66A69BC8>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Mano\AppData\Local\Programs\Python\Python37\lib\logging\__init__.py", line 1025, in emit
    msg = self.format(record)
  File "C:\Users\Mano\AppData\Local\Programs\Python\Python37\lib\logging\__init__.py", line 869, in format
    return fmt.format(record)
  File "C:\Users\Mano\AppData\Local\Programs\Python\Python37\lib\logging\__init__.py", line 608, in format
    record.message = record.getMessage()
  File "C:\Users\Mano\AppData\Local\Programs\Python\Python37\lib\logging\__init__.py", line 369, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "C:\Users\Mano\AppData\Local\Programs\Python\Python37\lib\threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "C:\Users\Mano\AppData\Local\Programs\Python\Python37\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "C:\Users\Mano\AppData\Local\Programs\Python\Python37\lib\site-packages\undetected_chromedriver\reactor.py", line 49, in run
    self.loop.run_until_complete(self.listen())
  File "C:\Users\Mano\AppData\Local\Programs\Python\Python37\lib\asyncio\base_events.py", line 570, in run_until_complete
    self.run_forever()
  File "C:\Users\Mano\AppData\Local\Programs\Python\Python37\lib\asyncio\base_events.py", line 538, in run_forever
    self._run_once()
  File "C:\Users\Mano\AppData\Local\Programs\Python\Python37\lib\asyncio\base_events.py", line 1782, in _run_once
    handle._run()
  File "C:\Users\Mano\AppData\Local\Programs\Python\Python37\lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\Mano\AppData\Local\Programs\Python\Python37\lib\site-packages\undetected_chromedriver\reactor.py", line 102, in listen
    logging.debug("exception ignored :", e)
Message: 'exception ignored :'
Arguments: (MaxRetryError("HTTPConnectionPool(host='localhost', port=53283): Max retries exceeded with url: /session/c7bc55019c45a7490090bfe99aac1212/se/log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000017E66A69BC8>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))"),)
```

**Comment by ultrafunkamsterdam** [comment]
Don't exit, it will close implicitly at exit. 
and leave those out, it defeats the purpose:

       chrome_options.add_argument('--headless')
        chrome_options.add_argument('--no-sandbox')
        chrome_options.add_argument("--disable-extensions")
        chrome_options.add_argument('--disable-application-cache')
        chrome_options.add_argument("--disable-setuid-sandbox")
        chrome_options.add_argument("--disable-dev-shm-usage")
        chrome_options.add_argument('--disable-gpu')
        chrome_options.add_argument("--start-maximized")

**Comment by ggnetoo** [comment]
> Don't exit, it will close implicitly at exit. and leave those out, it defeats the purpose:
> 
> ```
>    chrome_options.add_argument('--headless')
>     chrome_options.add_argument('--no-sandbox')
>     chrome_options.add_argument("--disable-extensions")
>     chrome_options.add_argument('--disable-application-cache')
>     chrome_options.add_argument("--disable-setuid-sandbox")
>     chrome_options.add_argument("--disable-dev-shm-usage")
>     chrome_options.add_argument('--disable-gpu')
>     chrome_options.add_argument("--start-maximized")
> ```

The background processes / webdriver lasts. The RAM and CPU consuption grows as long as keep my code running and call the drive again.

Can you give me a code example where I can avoid this? BTW, I need to keep the headless too. I'm running it in a linux arm64 eviroment too.

**Comment by whhsw** [comment]
> Apparently solved by commenting this line:
> 
> ![image](https://user-images.githubusercontent.com/64275214/210877936-281f68a5-5f7f-4041-9880-e6c07240a2b3.png)

thanks, this works like a charm
